-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE locales_points_of_interest SET icon_name_loc5='獅王之傲旅店' WHERE entry=1; /* icon_name: Lion\'s Pride Inn */
UPDATE locales_points_of_interest SET icon_name_loc5='札爾迪瑪·維夫希爾特' WHERE entry=2; /* icon_name: Zaldimar Wefhellt */
UPDATE locales_points_of_interest SET icon_name_loc5='維爾海姆修士' WHERE entry=3; /* icon_name: Brother Wilhelm */
UPDATE locales_points_of_interest SET icon_name_loc5='女牧師潔塞塔' WHERE entry=4; /* icon_name: Priestess Josetta */
UPDATE locales_points_of_interest SET icon_name_loc5='科瑞恩·塞爾留斯' WHERE entry=5; /* icon_name: Keryn Sylvius */
UPDATE locales_points_of_interest SET icon_name_loc5='瑪克西米利安·克洛文' WHERE entry=6; /* icon_name: Maximillian Crowe */
UPDATE locales_points_of_interest SET icon_name_loc5='里瑞亞·杜拉克' WHERE entry=7; /* icon_name: Lyria Du Lac */
UPDATE locales_points_of_interest SET icon_name_loc5='鍊金師瑪洛瑞' WHERE entry=8; /* icon_name: Alchemist Mallory */
UPDATE locales_points_of_interest SET icon_name_loc5='鐵匠阿古斯' WHERE entry=9; /* icon_name: Smith Argus */
UPDATE locales_points_of_interest SET icon_name_loc5='廚師湯瑪斯' WHERE entry=10; /* icon_name: Tomas */
UPDATE locales_points_of_interest SET icon_name_loc5='蜜雪兒·貝利' WHERE entry=11; /* icon_name: Michelle Belle */
UPDATE locales_points_of_interest SET icon_name_loc5='李·布朗' WHERE entry=12; /* icon_name: Lee Brown */
UPDATE locales_points_of_interest SET icon_name_loc5='艾德勒·費歐德' WHERE entry=14; /* icon_name: Adele Fielder */
UPDATE locales_points_of_interest SET icon_name_loc5='海倫尼·派特斯金納' WHERE entry=15; /* icon_name: Helene Peltskinner */
UPDATE locales_points_of_interest SET icon_name_loc5='艾爾丁' WHERE entry=16; /* icon_name: Eldrin */
UPDATE locales_points_of_interest SET icon_name_loc5='旅店老闆艾瑪' WHERE entry=17; /* icon_name: Erma */
UPDATE locales_points_of_interest SET icon_name_loc5='暴風城拍賣場' WHERE entry=18; /* icon_name: Stormwind Auction House */
UPDATE locales_points_of_interest SET icon_name_loc5='鑲金玫瑰' WHERE entry=22; /* icon_name: The Gilded Rose */
UPDATE locales_points_of_interest SET icon_name_loc5='暴風城訪客中心' WHERE entry=24; /* icon_name: Stormwind Visitor\'s Center */
UPDATE locales_points_of_interest SET icon_name_loc5='耶諾瓦·石盾' WHERE entry=26; /* icon_name: Jenova Stoneshield */
UPDATE locales_points_of_interest SET icon_name_loc5='吳平' WHERE entry=27; /* icon_name: Woo Ping */
UPDATE locales_points_of_interest SET icon_name_loc5='勇士大廳' WHERE entry=28; /* icon_name: Champions\' Hall */
UPDATE locales_points_of_interest SET icon_name_loc5='花園' WHERE entry=32; /* icon_name: The Park */
UPDATE locales_points_of_interest SET icon_name_loc5='巫師聖所' WHERE entry=34; /* icon_name: Wizard\'s Sanctum */
UPDATE locales_points_of_interest SET icon_name_loc5='聖光大教堂' WHERE entry=35; /* icon_name: Cathedral Of Light */
UPDATE locales_points_of_interest SET icon_name_loc5='已宰的羔羊' WHERE entry=38; /* icon_name: The Slaughtered Lamb */
UPDATE locales_points_of_interest SET icon_name_loc5='鍊金材料店' WHERE entry=40; /* icon_name: Alchemy Needs */
UPDATE locales_points_of_interest SET icon_name_loc5='瑟魯姆·深爐' WHERE entry=41; /* icon_name: Therum Deepforge */
UPDATE locales_points_of_interest SET icon_name_loc5='豬和哨聲旅店' WHERE entry=42; /* icon_name: Pig and Whistle Tavern */
UPDATE locales_points_of_interest SET icon_name_loc5='魯坎·考迪爾' WHERE entry=43; /* icon_name: Lucan Cordell */
UPDATE locales_points_of_interest SET icon_name_loc5='利廉姆·火軸' WHERE entry=44; /* icon_name: Lilliam Sparkspindle */
UPDATE locales_points_of_interest SET icon_name_loc5='珊娜·弗勒' WHERE entry=45; /* icon_name: Shaina Fuller */
UPDATE locales_points_of_interest SET icon_name_loc5='阿諾德·利蘭' WHERE entry=46; /* icon_name: Arnold Leland */
UPDATE locales_points_of_interest SET icon_name_loc5='護體皮甲' WHERE entry=47; /* icon_name: The Protective Hide */
UPDATE locales_points_of_interest SET icon_name_loc5='吉爾曼·石手' WHERE entry=48; /* icon_name: Gelman Stonehand */
UPDATE locales_points_of_interest SET icon_name_loc5='鄧肯布料店' WHERE entry=49; /* icon_name: Duncan\'s Textiles */
UPDATE locales_points_of_interest SET icon_name_loc5='鐵爐堡拍賣場' WHERE entry=50; /* icon_name: Ironforge Auction house */
UPDATE locales_points_of_interest SET icon_name_loc5='礦道地鐵' WHERE entry=52; /* icon_name: Deeprun Tram */
UPDATE locales_points_of_interest SET icon_name_loc5='鐵爐堡訪客中心' WHERE entry=54; /* icon_name: Ironforge Visitor\'s Center */
UPDATE locales_points_of_interest SET icon_name_loc5='烏布雷克·火拳' WHERE entry=57; /* icon_name: Ulbrek Firehand */
UPDATE locales_points_of_interest SET icon_name_loc5='武器大廳' WHERE entry=61; /* icon_name: Hall of Arms */
UPDATE locales_points_of_interest SET icon_name_loc5='秘法大廳' WHERE entry=62; /* icon_name: Hall of Mysteries */
UPDATE locales_points_of_interest SET icon_name_loc5='漿泡的藥水飲料店' WHERE entry=66; /* icon_name: Berryfizz\'s Potions and Mixed Drinks */
UPDATE locales_points_of_interest SET icon_name_loc5='大鍛爐' WHERE entry=67; /* icon_name: The Great Forge */
UPDATE locales_points_of_interest SET icon_name_loc5='銅壺鐵罐' WHERE entry=68; /* icon_name: The Bronze Kettle */
UPDATE locales_points_of_interest SET icon_name_loc5='草鬚魔法用品店' WHERE entry=69; /* icon_name: Thistlefuzz Arcanery */
UPDATE locales_points_of_interest SET icon_name_loc5='鐵爐堡治療師協會' WHERE entry=70; /* icon_name: Ironforge Physician */
UPDATE locales_points_of_interest SET icon_name_loc5='旅行漁具店' WHERE entry=71; /* icon_name: Traveling Fisherman */
UPDATE locales_points_of_interest SET icon_name_loc5='皮甲用品店' WHERE entry=73; /* icon_name: Finespindle\'s Leather Goods */
UPDATE locales_points_of_interest SET icon_name_loc5='石眉布衣店' WHERE entry=75; /* icon_name: Stonebrow\'s Clothier */
UPDATE locales_points_of_interest SET icon_name_loc5='雷酒釀酒廠' WHERE entry=76; /* icon_name: Thunderbrew Distillery */
UPDATE locales_points_of_interest SET icon_name_loc5='謝爾比·石火' WHERE entry=77; /* icon_name: Shelby Stoneflint */
UPDATE locales_points_of_interest SET icon_name_loc5='格瑞夫' WHERE entry=78; /* icon_name: Grif Wildheart */
UPDATE locales_points_of_interest SET icon_name_loc5='瑪濟斯·石衣' WHERE entry=79; /* icon_name: Magis Sparkmantle */
UPDATE locales_points_of_interest SET icon_name_loc5='阿札爾·戰錘' WHERE entry=80; /* icon_name: Azar Stronghammer */
UPDATE locales_points_of_interest SET icon_name_loc5='馬克薩恩·安沃爾' WHERE entry=81; /* icon_name: Maxan Anvol */
UPDATE locales_points_of_interest SET icon_name_loc5='霍格拉爾·巴坎' WHERE entry=82; /* icon_name: Hogral Bakkan */
UPDATE locales_points_of_interest SET icon_name_loc5='吉姆瑞茲·影輪' WHERE entry=83; /* icon_name: Gimrizz Shadowcog */
UPDATE locales_points_of_interest SET icon_name_loc5='格蘭尼斯·快斧' WHERE entry=84; /* icon_name: Granis Swiftaxe */
UPDATE locales_points_of_interest SET icon_name_loc5='托格努斯·燧火' WHERE entry=85; /* icon_name: Tognus Flintfire */
UPDATE locales_points_of_interest SET icon_name_loc5='格雷姆羅克·匹斯諾爾' WHERE entry=86; /* icon_name: Gremlock Pilsnor */
UPDATE locales_points_of_interest SET icon_name_loc5='薩姆諾·普爾' WHERE entry=87; /* icon_name: Thamner Pol */
UPDATE locales_points_of_interest SET icon_name_loc5='帕克斯頓·岡特爾' WHERE entry=88; /* icon_name: Paxton Ganter */
UPDATE locales_points_of_interest SET icon_name_loc5='達納蘇斯拍賣場' WHERE entry=89; /* icon_name: Darnassus Auction House */
UPDATE locales_points_of_interest SET icon_name_loc5='阿拉辛' WHERE entry=95; /* icon_name: Alassin */
UPDATE locales_points_of_interest SET icon_name_loc5='伊琳尼雅·月火' WHERE entry=96; /* icon_name: Ilyenia Moonfire */
UPDATE locales_points_of_interest SET icon_name_loc5='戰士區' WHERE entry=101; /* icon_name: Warrior\'s Terrace */
UPDATE locales_points_of_interest SET icon_name_loc5='瑟里亞迪' WHERE entry=112; /* icon_name: Seriadne */
UPDATE locales_points_of_interest SET icon_name_loc5='卡爾' WHERE entry=113; /* icon_name: Kal */
UPDATE locales_points_of_interest SET icon_name_loc5='達札拉' WHERE entry=114; /* icon_name: Dazalar */
UPDATE locales_points_of_interest SET icon_name_loc5='勞爾娜·晨光' WHERE entry=115; /* icon_name: Laurna Morninglight */
UPDATE locales_points_of_interest SET icon_name_loc5='詹諾克·柔歌' WHERE entry=116; /* icon_name: Jannok Breezesong */
UPDATE locales_points_of_interest SET icon_name_loc5='凱拉·風刃' WHERE entry=117; /* icon_name: Kyra Windblade */
UPDATE locales_points_of_interest SET icon_name_loc5='塞恩德拉·細語者' WHERE entry=118; /* icon_name: Cyndra Kindwhisper */
UPDATE locales_points_of_interest SET icon_name_loc5='札瑞恩' WHERE entry=119; /* icon_name: Zarrin */
UPDATE locales_points_of_interest SET icon_name_loc5='奧蘭納·鴉眼' WHERE entry=120; /* icon_name: Alanna Raveneye */
UPDATE locales_points_of_interest SET icon_name_loc5='拜恩希' WHERE entry=121; /* icon_name: Byancie */
UPDATE locales_points_of_interest SET icon_name_loc5='瑪洛尼·刃葉' WHERE entry=122; /* icon_name: Malorne Bladeleaf */
UPDATE locales_points_of_interest SET icon_name_loc5='納迪婭·織髮' WHERE entry=123; /* icon_name: Nadyia Maneweaver */
UPDATE locales_points_of_interest SET icon_name_loc5='拉德納爾·織髮' WHERE entry=124; /* icon_name: Radnaal Maneweaver */
UPDATE locales_points_of_interest SET icon_name_loc5='納迪婭·織髮' WHERE entry=125; /* icon_name: Nadyia Maneweaver */
UPDATE locales_points_of_interest SET icon_name_loc5='奧格瑪銀行' WHERE entry=176; /* icon_name: Bank of Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc5='部落大使館' WHERE entry=178; /* icon_name: Horde Embassy */
UPDATE locales_points_of_interest SET icon_name_loc5='奧格瑪拍賣場' WHERE entry=181; /* icon_name: Orgrimmar Auction House */
UPDATE locales_points_of_interest SET icon_name_loc5='克蘇卡' WHERE entry=185; /* icon_name: Xon\'cha */
UPDATE locales_points_of_interest SET icon_name_loc5='傳說大廳' WHERE entry=186; /* icon_name: Hall of Legends */
UPDATE locales_points_of_interest SET icon_name_loc5='克魯恩' WHERE entry=238; /* icon_name: Krunn */
UPDATE locales_points_of_interest SET icon_name_loc5='米什基' WHERE entry=239; /* icon_name: Mishiki */
UPDATE locales_points_of_interest SET icon_name_loc5='勞迪克' WHERE entry=240; /* icon_name: Lau\'Tiki */
UPDATE locales_points_of_interest SET icon_name_loc5='拉烏克' WHERE entry=241; /* icon_name: Rawrk */
UPDATE locales_points_of_interest SET icon_name_loc5='穆德拉克' WHERE entry=242; /* icon_name: Mukdrak */
UPDATE locales_points_of_interest SET icon_name_loc5='杜克' WHERE entry=243; /* icon_name: Dwukk */
UPDATE locales_points_of_interest SET icon_name_loc5='米奧贊' WHERE entry=244; /* icon_name: Miao\'zan */
UPDATE locales_points_of_interest SET icon_name_loc5='塔紹爾·鋸痕' WHERE entry=245; /* icon_name: Tarshaw Jaggedscar */
UPDATE locales_points_of_interest SET icon_name_loc5='杜格魯·血怒' WHERE entry=246; /* icon_name: Dhugru Gorelust */
UPDATE locales_points_of_interest SET icon_name_loc5='斯瓦特' WHERE entry=247; /* icon_name: Swart */
UPDATE locales_points_of_interest SET icon_name_loc5='卡普拉克' WHERE entry=248; /* icon_name: Kaplak */
UPDATE locales_points_of_interest SET icon_name_loc5='泰金' WHERE entry=249; /* icon_name: Tai\'jin */
UPDATE locales_points_of_interest SET icon_name_loc5='安蘇瓦' WHERE entry=250; /* icon_name: Un\'Thuwa */
UPDATE locales_points_of_interest SET icon_name_loc5='索塔爾' WHERE entry=251; /* icon_name: Thotar */
UPDATE locales_points_of_interest SET icon_name_loc5='蘇亞米' WHERE entry=252; /* icon_name: Shoja\'my */
UPDATE locales_points_of_interest SET icon_name_loc5='鍊金房' WHERE entry=266; /* icon_name: The Apothecarium */
UPDATE locales_points_of_interest SET icon_name_loc5='塞薩·曦升勇士' WHERE entry=271; /* icon_name: Champion Cyssa Dawnrose */
UPDATE locales_points_of_interest SET icon_name_loc5='阿基巴德' WHERE entry=274; /* icon_name: Archibald */
UPDATE locales_points_of_interest SET icon_name_loc5='安雅·瑪爾雷' WHERE entry=275; /* icon_name: Anya Maulray */
UPDATE locales_points_of_interest SET icon_name_loc5='幽暗城拍賣場' WHERE entry=284; /* icon_name: Undercity Auction House */
UPDATE locales_points_of_interest SET icon_name_loc5='博文·布里斯博埃斯' WHERE entry=285; /* icon_name: Bowen Brisboise */
UPDATE locales_points_of_interest SET icon_name_loc5='蘭德·洛巴爾特' WHERE entry=286; /* icon_name: Rand Rhobart */
UPDATE locales_points_of_interest SET icon_name_loc5='舍倫尼·洛巴爾特' WHERE entry=287; /* icon_name: Shelene Rhobart */
UPDATE locales_points_of_interest SET icon_name_loc5='法魯薩' WHERE entry=288; /* icon_name: Faruza */
UPDATE locales_points_of_interest SET icon_name_loc5='克萊德·凱雷恩' WHERE entry=289; /* icon_name: Clyde Kellen */
UPDATE locales_points_of_interest SET icon_name_loc5='妮拉' WHERE entry=290; /* icon_name: Nurse Neela */
UPDATE locales_points_of_interest SET icon_name_loc5='范斯·安德格魯姆' WHERE entry=291; /* icon_name: Vance Undergloom */
UPDATE locales_points_of_interest SET icon_name_loc5='卡羅萊·大茴香' WHERE entry=292; /* icon_name: Carolai Anise */
UPDATE locales_points_of_interest SET icon_name_loc5='奧斯蒂爾·德·蒙' WHERE entry=293; /* icon_name: Austil de Mon */
UPDATE locales_points_of_interest SET icon_name_loc5='魯伯特·鮑什' WHERE entry=294; /* icon_name: Rupert Boch */
UPDATE locales_points_of_interest SET icon_name_loc5='馬里恩·考爾' WHERE entry=295; /* icon_name: Marion Call */
UPDATE locales_points_of_interest SET icon_name_loc5='莫加努斯' WHERE entry=296; /* icon_name: Morganus */
UPDATE locales_points_of_interest SET icon_name_loc5='黑暗教士貝里爾' WHERE entry=297; /* icon_name: Dark Cleric Beryl */
UPDATE locales_points_of_interest SET icon_name_loc5='凱恩·火歌' WHERE entry=298; /* icon_name: Cain Firesong */
UPDATE locales_points_of_interest SET icon_name_loc5='恐懼之末旅店' WHERE entry=299; /* icon_name: Gallows\' End Tavern */
UPDATE locales_points_of_interest SET icon_name_loc5='雷霆崖防具店' WHERE entry=301; /* icon_name: Thunder Bluff Armorers */
UPDATE locales_points_of_interest SET icon_name_loc5='莫蘭塔' WHERE entry=302; /* icon_name: Mooranta */
UPDATE locales_points_of_interest SET icon_name_loc5='石蹄地質學會' WHERE entry=303; /* icon_name: Stonehoof Geology */
UPDATE locales_points_of_interest SET icon_name_loc5='雷霆崖防具店' WHERE entry=304; /* icon_name: Thunder Bluff Armorers */
UPDATE locales_points_of_interest SET icon_name_loc5='綠色草藥' WHERE entry=306; /* icon_name: Holistic Herbalism */
UPDATE locales_points_of_interest SET icon_name_loc5='山頂漁具店' WHERE entry=307; /* icon_name: Mountaintop Bait & Tackle */
UPDATE locales_points_of_interest SET icon_name_loc5='精神治療' WHERE entry=308; /* icon_name: Spiritual Healing */
UPDATE locales_points_of_interest SET icon_name_loc5='晨行者附魔商店' WHERE entry=309; /* icon_name: Dawnstrider Enchanters */
UPDATE locales_points_of_interest SET icon_name_loc5='阿絲卡的廚房' WHERE entry=310; /* icon_name: Aska\'s Kitchen */
UPDATE locales_points_of_interest SET icon_name_loc5='卡恩鐵匠鋪' WHERE entry=311; /* icon_name: Karn\'s Smithy */
UPDATE locales_points_of_interest SET icon_name_loc5='貝娜的鍊金店' WHERE entry=312; /* icon_name: Bena\'s Alchemy */
UPDATE locales_points_of_interest SET icon_name_loc5='獵人大廳' WHERE entry=313; /* icon_name: Hunter\'s Hall */
UPDATE locales_points_of_interest SET icon_name_loc5='靈魂大廳' WHERE entry=314; /* icon_name: Hall of Spirits */
UPDATE locales_points_of_interest SET icon_name_loc5='預見之池' WHERE entry=315; /* icon_name: Pools of Vision */
UPDATE locales_points_of_interest SET icon_name_loc5='長者大廳' WHERE entry=316; /* icon_name: Hall of Elders */
UPDATE locales_points_of_interest SET icon_name_loc5='布爾魯格' WHERE entry=318; /* icon_name: Bulrug */
UPDATE locales_points_of_interest SET icon_name_loc5='安塞瓦' WHERE entry=319; /* icon_name: Ansekhwa */
UPDATE locales_points_of_interest SET icon_name_loc5='雷霆崖諮詢處' WHERE entry=323; /* icon_name: Thunder Bluff Civic Information */
UPDATE locales_points_of_interest SET icon_name_loc5='雷霆崖銀行' WHERE entry=325; /* icon_name: Thunder Bluff Bank */
UPDATE locales_points_of_interest SET icon_name_loc5='姚恩·深刺' WHERE entry=326; /* icon_name: Yonn Deepcut */
UPDATE locales_points_of_interest SET icon_name_loc5='查爾·硬皮' WHERE entry=327; /* icon_name: Chaw Stronghide */
UPDATE locales_points_of_interest SET icon_name_loc5='尤薩恩·靜水' WHERE entry=329; /* icon_name: Uthan Stillwater */
UPDATE locales_points_of_interest SET icon_name_loc5='維爾拉·幼蹄' WHERE entry=330; /* icon_name: Vira Younghoof */
UPDATE locales_points_of_interest SET icon_name_loc5='派爾·沉默行者' WHERE entry=331; /* icon_name: Pyall Silentstride */
UPDATE locales_points_of_interest SET icon_name_loc5='克朗·石蹄' WHERE entry=332; /* icon_name: Krang Stonehoof */
UPDATE locales_points_of_interest SET icon_name_loc5='納姆·逐星' WHERE entry=334; /* icon_name: Narm Skychaser */
UPDATE locales_points_of_interest SET icon_name_loc5='雅文·刺鬃' WHERE entry=335; /* icon_name: Yaw Sharpmane */
UPDATE locales_points_of_interest SET icon_name_loc5='潔妮亞·符文圖騰' WHERE entry=336; /* icon_name: Gennia Runetotem */
UPDATE locales_points_of_interest SET icon_name_loc5='希克瓦' WHERE entry=337; /* icon_name: Seikwa */
UPDATE locales_points_of_interest SET icon_name_loc5='亞爾·錘石' WHERE entry=339; /* icon_name: Yarr Hammerstone */
UPDATE locales_points_of_interest SET icon_name_loc5='草藥師博米洛伊' WHERE entry=363; /* icon_name: Herbalist Pomeroy */
UPDATE locales_points_of_interest SET icon_name_loc5='月神殿' WHERE entry=364; /* icon_name: Temple of the Moon */
UPDATE locales_points_of_interest SET icon_name_loc5='賓斯匹德器具店' WHERE entry=419; /* icon_name: Springspindle\'s Gadgets */
UPDATE locales_points_of_interest SET icon_name_loc5='暗木小屋' WHERE entry=421; /* icon_name: Darkbriar Lodge */
UPDATE locales_points_of_interest SET icon_name_loc5='靈魂小屋' WHERE entry=422; /* icon_name: Spirit Lodge */
UPDATE locales_points_of_interest SET icon_name_loc5='索爾的要塞' WHERE entry=423; /* icon_name: Thrall\'s Fortress */
UPDATE locales_points_of_interest SET icon_name_loc5='迅影兄弟會' WHERE entry=424; /* icon_name: Shadowswift Brotherhood */
UPDATE locales_points_of_interest SET icon_name_loc5='暗火營地' WHERE entry=425; /* icon_name: Darkfire Enclave */
UPDATE locales_points_of_interest SET icon_name_loc5='勇者大廳' WHERE entry=426; /* icon_name: Hall of the Brave */
UPDATE locales_points_of_interest SET icon_name_loc5='耶爾瑪克鍊金術與藥劑店' WHERE entry=427; /* icon_name: Yelmak\'s Alchemy and Potions */
UPDATE locales_points_of_interest SET icon_name_loc5='燃燒的鐵砧' WHERE entry=428; /* icon_name: The Burning Anvil */
UPDATE locales_points_of_interest SET icon_name_loc5='博斯坦的火坑' WHERE entry=429; /* icon_name: Borstan\'s Firepit */
UPDATE locales_points_of_interest SET icon_name_loc5='古丹的符文工藝店' WHERE entry=430; /* icon_name: Godan\'s Runeworks */
UPDATE locales_points_of_interest SET icon_name_loc5='諾格機械店' WHERE entry=431; /* icon_name: Nogg\'s Machine Shop */
UPDATE locales_points_of_interest SET icon_name_loc5='適者生存' WHERE entry=432; /* icon_name: Survival of the Fittest */
UPDATE locales_points_of_interest SET icon_name_loc5='魯瑪克漁具店' WHERE entry=433; /* icon_name: Lumak\'s Fishing */
UPDATE locales_points_of_interest SET icon_name_loc5='加迪植物園' WHERE entry=434; /* icon_name: Jandi\'s Arboretum */
UPDATE locales_points_of_interest SET icon_name_loc5='紅石谷礦業工會' WHERE entry=435; /* icon_name: Red Canyon Mining */
UPDATE locales_points_of_interest SET icon_name_loc5='科多獸皮工店' WHERE entry=436; /* icon_name: Kodohide Leatherworkers */
UPDATE locales_points_of_interest SET icon_name_loc5='瑪加爾布品店' WHERE entry=437; /* icon_name: Magar\'s Cloth Goods */

SET NAMES 'latin1';
