-- File generated by Mangos Online Translation Editor (MOTE) v0.8
SET NAMES 'utf8';
UPDATE gossip_texts SET content_loc5='伊斯奇歐說你會有某本書...' WHERE entry=-3000105; /* content: Ezekiel said that you might have a certain book... */
UPDATE gossip_texts SET content_loc5='讓溫德索爾元帥知道我準備好了。' WHERE entry=-3000106; /* content: Let Marshal Windsor know that I am ready. */
UPDATE gossip_texts SET content_loc5='我準備好了，我的軍隊也整裝待命。讓我們結束這次化妝舞會吧!' WHERE entry=-3000107; /* content: I am ready, as are my forces. Let us end this masquerade! */
UPDATE gossip_texts SET content_loc5='請留步，先生。' WHERE entry=-3000108; /* content: I need a moment of your time, sir. */
UPDATE gossip_texts SET content_loc5='我準備好了，歐朗諾克。讓我們毀了賽洛庫並解放那些元素吧!' WHERE entry=-3000109; /* content: I am ready, Oronok. Let us destroy Cyrukh and free the elements! */
UPDATE gossip_texts SET content_loc5='轉動鑰匙，啟動了機器。' WHERE entry=-3000111; /* content: Turn the key to start the machine. */
UPDATE gossip_texts SET content_loc5='請打開庭院的大門。' WHERE entry=-3033000; /* content: Please unlock the courtyard door. */
UPDATE gossip_texts SET content_loc5='活動開始了!' WHERE entry=-3043000; /* content: Let the event begin! */
UPDATE gossip_texts SET content_loc5='我準備好了。' WHERE entry=-3090000; /* content: I am ready to begin. */
UPDATE gossip_texts SET content_loc5='你自由了，杜格哈爾!快出去!' WHERE entry=-3230000; /* content: You\'re free, Dughal! Get out of here! */
UPDATE gossip_texts SET content_loc5='出去吧，托比亞斯，你自由了!' WHERE entry=-3230001; /* content: Get out of here, Tobias, you\'re free! */
UPDATE gossip_texts SET content_loc5='為什麼你跟羅克諾特不去找個二人天地呢...' WHERE entry=-3230003; /* content: Why don\'t you and Rocknot go find somewhere private... */
UPDATE gossip_texts SET content_loc5='告訴我更多的資訊。' WHERE entry=-3409000; /* content: Tell me more. */
UPDATE gossip_texts SET content_loc5='你還想說什麼?' WHERE entry=-3409001; /* content: What else do you have to say? */
UPDATE gossip_texts SET content_loc5='我從不犯錯。' WHERE entry=-3469000; /* content: I\'ve made no mistakes. */
UPDATE gossip_texts SET content_loc5='你已經失去理智，奈法利斯。你在說什麼啞謎。' WHERE entry=-3469001; /* content: You have lost your mind, Nefarius. You speak in riddles. */
UPDATE gossip_texts SET content_loc5='請繼續。' WHERE entry=-3469002; /* content: Please do. */
UPDATE gossip_texts SET content_loc5='我做不到，瓦拉斯塔茲!一定有什麼辦法可以治療你!' WHERE entry=-3469003; /* content: I cannot, Vaelastrasz! Surely something can be done to heal you! */
UPDATE gossip_texts SET content_loc5='瓦拉斯塔茲，不!!!' WHERE entry=-3469004; /* content: Vaelastrasz, no!!! */
UPDATE gossip_texts SET content_loc5='動手吧!' WHERE entry=-3509000; /* content: Let\'s find out. */
UPDATE gossip_texts SET content_loc5='讓我們看看你有什麼。' WHERE entry=-3509001; /* content: Let\'s see what you have. */

SET NAMES 'latin1';
