-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE locales_points_of_interest SET icon_name_loc9='Zaldimar Wefhellt' WHERE entry=2; /* icon_name: Zaldimar Wefhellt */
UPDATE locales_points_of_interest SET icon_name_loc9='La Rosa Dorata' WHERE entry=22; /* icon_name: The Gilded Rose */
UPDATE locales_points_of_interest SET icon_name_loc9='Centro Visitatori di Stormwind' WHERE entry=24; /* icon_name: Stormwind Visitor\'s Center */
UPDATE locales_points_of_interest SET icon_name_loc9='Champions\' Hall' WHERE entry=28; /* icon_name: Champions\' Hall */
UPDATE locales_points_of_interest SET icon_name_loc9='Il Parco' WHERE entry=32; /* icon_name: The Park */
UPDATE locales_points_of_interest SET icon_name_loc9='L\'Agnello Macellato' WHERE entry=38; /* icon_name: The Slaughtered Lamb */
UPDATE locales_points_of_interest SET icon_name_loc9='Esigenze Alchemiche' WHERE entry=40; /* icon_name: Alchemy Needs */
UPDATE locales_points_of_interest SET icon_name_loc9='Taverna del Maiale e del Fischietto' WHERE entry=42; /* icon_name: Pig and Whistle Tavern */
UPDATE locales_points_of_interest SET icon_name_loc9='La Pelle Protettiva' WHERE entry=47; /* icon_name: The Protective Hide */
UPDATE locales_points_of_interest SET icon_name_loc9='Tessili di Duncan' WHERE entry=49; /* icon_name: Duncan\'s Textiles */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Ironforge' WHERE entry=50; /* icon_name: Ironforge Auction house */
UPDATE locales_points_of_interest SET icon_name_loc9='Deeprun Tram' WHERE entry=52; /* icon_name: Deeprun Tram */
UPDATE locales_points_of_interest SET icon_name_loc9='Centro Visite di Ironforge' WHERE entry=54; /* icon_name: Ironforge Visitor\'s Center */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala delle Armi' WHERE entry=61; /* icon_name: Hall of Arms */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Misteri' WHERE entry=62; /* icon_name: Hall of Mysteries */
UPDATE locales_points_of_interest SET icon_name_loc9='Pozioni e Bevande Varie di Berryfizz' WHERE entry=66; /* icon_name: Berryfizz\'s Potions and Mixed Drinks */
UPDATE locales_points_of_interest SET icon_name_loc9='The Great Forge' WHERE entry=67; /* icon_name: The Great Forge */
UPDATE locales_points_of_interest SET icon_name_loc9='Il Ramino di Bronzo' WHERE entry=68; /* icon_name: The Bronze Kettle */
UPDATE locales_points_of_interest SET icon_name_loc9='Beni Arcani di Thistlefuzz' WHERE entry=69; /* icon_name: Thistlefuzz Arcanery */
UPDATE locales_points_of_interest SET icon_name_loc9='Medico di Ironforge' WHERE entry=70; /* icon_name: Ironforge Physician */
UPDATE locales_points_of_interest SET icon_name_loc9='Pescatore Itinerante' WHERE entry=71; /* icon_name: Traveling Fisherman */
UPDATE locales_points_of_interest SET icon_name_loc9='Merci di Pelle di Finespindle' WHERE entry=73; /* icon_name: Finespindle\'s Leather Goods */
UPDATE locales_points_of_interest SET icon_name_loc9='Vestiario di Stonebrow' WHERE entry=75; /* icon_name: Stonebrow\'s Clothier */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Darnassus' WHERE entry=89; /* icon_name: Darnassus Auction House */
UPDATE locales_points_of_interest SET icon_name_loc9='Banca di Orgrimmar' WHERE entry=176; /* icon_name: Bank of Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc9='Ambasciata dell\'Orda' WHERE entry=178; /* icon_name: Horde Embassy */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Orgrimmar' WHERE entry=181; /* icon_name: Orgrimmar Auction House */
UPDATE locales_points_of_interest SET icon_name_loc9='Hall of Legends' WHERE entry=186; /* icon_name: Hall of Legends */
UPDATE locales_points_of_interest SET icon_name_loc9='The Apothecarium' WHERE entry=266; /* icon_name: The Apothecarium */
UPDATE locales_points_of_interest SET icon_name_loc9='Armatori di Thunder Bluff' WHERE entry=301; /* icon_name: Thunder Bluff Armorers */
UPDATE locales_points_of_interest SET icon_name_loc9='Geologia Stonehoof' WHERE entry=303; /* icon_name: Stonehoof Geology */
UPDATE locales_points_of_interest SET icon_name_loc9='Armatori di Thunder Bluff' WHERE entry=304; /* icon_name: Thunder Bluff Armorers */
UPDATE locales_points_of_interest SET icon_name_loc9='Erbalismo Holistic' WHERE entry=306; /* icon_name: Holistic Herbalism */
UPDATE locales_points_of_interest SET icon_name_loc9='Esca & Attrezzatura da Pesca Mountaintop' WHERE entry=307; /* icon_name: Mountaintop Bait & Tackle */
UPDATE locales_points_of_interest SET icon_name_loc9='Cure Spirituali' WHERE entry=308; /* icon_name: Spiritual Healing */
UPDATE locales_points_of_interest SET icon_name_loc9='Incantatori Dawnstrider' WHERE entry=309; /* icon_name: Dawnstrider Enchanters */
UPDATE locales_points_of_interest SET icon_name_loc9='Cucina di Aska' WHERE entry=310; /* icon_name: Aska\'s Kitchen */
UPDATE locales_points_of_interest SET icon_name_loc9='Fucina di Karn' WHERE entry=311; /* icon_name: Karn\'s Smithy */
UPDATE locales_points_of_interest SET icon_name_loc9='Alchimia di Bena' WHERE entry=312; /* icon_name: Bena\'s Alchemy */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Cacciatori' WHERE entry=313; /* icon_name: Hunter\'s Hall */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala degli Spiriti' WHERE entry=314; /* icon_name: Hall of Spirits */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala degli Anziani' WHERE entry=316; /* icon_name: Hall of Elders */
UPDATE locales_points_of_interest SET icon_name_loc9='Informazioni Civiche di Thunder Bluff' WHERE entry=323; /* icon_name: Thunder Bluff Civic Information */
UPDATE locales_points_of_interest SET icon_name_loc9='Banca di Thunder Bluff' WHERE entry=325; /* icon_name: Thunder Bluff Bank */
UPDATE locales_points_of_interest SET icon_name_loc9='Gadget di Springspindle' WHERE entry=419; /* icon_name: Springspindle\'s Gadgets */
UPDATE locales_points_of_interest SET icon_name_loc9='Padiglione Darkbriar' WHERE entry=421; /* icon_name: Darkbriar Lodge */
UPDATE locales_points_of_interest SET icon_name_loc9='Padiglione dello Spirito' WHERE entry=422; /* icon_name: Spirit Lodge */
UPDATE locales_points_of_interest SET icon_name_loc9='Fortezza di Thrall' WHERE entry=423; /* icon_name: Thrall\'s Fortress */
UPDATE locales_points_of_interest SET icon_name_loc9='Fratellanza Shadowswift' WHERE entry=424; /* icon_name: Shadowswift Brotherhood */
UPDATE locales_points_of_interest SET icon_name_loc9='Enclave di Darkfire' WHERE entry=425; /* icon_name: Darkfire Enclave */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Coraggiosi' WHERE entry=426; /* icon_name: Hall of the Brave */
UPDATE locales_points_of_interest SET icon_name_loc9='Alchemi e Pozioni di Yelmak' WHERE entry=427; /* icon_name: Yelmak\'s Alchemy and Potions */
UPDATE locales_points_of_interest SET icon_name_loc9='L\'Incudine Bruciante' WHERE entry=428; /* icon_name: The Burning Anvil */
UPDATE locales_points_of_interest SET icon_name_loc9='Pozza del Fuoco di Borstan' WHERE entry=429; /* icon_name: Borstan\'s Firepit */
UPDATE locales_points_of_interest SET icon_name_loc9='Lavori Runici di Godan' WHERE entry=430; /* icon_name: Godan\'s Runeworks */
UPDATE locales_points_of_interest SET icon_name_loc9='Officina di Nogg' WHERE entry=431; /* icon_name: Nogg\'s Machine Shop */
UPDATE locales_points_of_interest SET icon_name_loc9='Sopravvivenza dei Più Adatti' WHERE entry=432; /* icon_name: Survival of the Fittest */
UPDATE locales_points_of_interest SET icon_name_loc9='Pesca di Lumak' WHERE entry=433; /* icon_name: Lumak\'s Fishing */
UPDATE locales_points_of_interest SET icon_name_loc9='Arboreto di Jandi' WHERE entry=434; /* icon_name: Jandi\'s Arboretum */
UPDATE locales_points_of_interest SET icon_name_loc9='Estrazioni del Canyon Rosso' WHERE entry=435; /* icon_name: Red Canyon Mining */
UPDATE locales_points_of_interest SET icon_name_loc9='Conciatori Kodohide' WHERE entry=436; /* icon_name: Kodohide Leatherworkers */
UPDATE locales_points_of_interest SET icon_name_loc9='Beni Tessili di Magar' WHERE entry=437; /* icon_name: Magar\'s Cloth Goods */

SET NAMES 'latin1';
