-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE creature_ai_texts SET content_loc9='Siamo ancora qui?' WHERE entry=-429; /* content: Are we there yet? */
UPDATE creature_ai_texts SET content_loc9='Guardie!' WHERE entry=-549; /* content: Guards! */

SET NAMES 'latin1';
