-- File generated by Mangos Online Translation Editor (MOTE) v0.8
SET NAMES 'utf8';
UPDATE mangos_string SET content_loc9='   Casuale' WHERE entry=528; /* content: Random */
UPDATE mangos_string SET content_loc9='   Punto del Tragitto' WHERE entry=529; /* content: Waypoint */
UPDATE mangos_string SET content_loc9='   Disorientato' WHERE entry=531; /* content: Confused */
UPDATE mangos_string SET content_loc9='   Punto Volo' WHERE entry=537; /* content: Taxi flight */
UPDATE mangos_string SET content_loc9='Fabbro' WHERE entry=653; /* content: blacksmith */
UPDATE mangos_string SET content_loc9='Miniera' WHERE entry=656; /* content: mine */
UPDATE mangos_string SET content_loc9='Mastro di Gilda' WHERE entry=811; /* content: Guild Master */

SET NAMES 'latin1';
