-- File generated by Mangos Online Translation Editor (MOTE) v2.00
SET NAMES 'utf8';
UPDATE db_script_string SET content_loc9='Ho bisogno di consultare Noram e Horatio.' WHERE entry=2000000021;
UPDATE db_script_string SET content_loc9='Hmm ...' WHERE entry=2000000092;
UPDATE db_script_string SET content_loc9='Avevi ragione di venire. La mia saggezza sarà tua.' WHERE entry=2000000109;
UPDATE db_script_string SET content_loc9='ROARRRRR !!' WHERE entry=2000000161;
UPDATE db_script_string SET content_loc9='Una bella presa è così! Tu porti onore al ragazzo dell\'Orda, Ti ringraziamo! ' WHERE entry=2000000192;
UPDATE db_script_string SET content_loc9='Perire qui. <La tua mente si riempie di visioni di caos e distruzione.>' WHERE entry=2000000353;
UPDATE db_script_string SET content_loc9='Una storia ... Hmmmm ... Lasciatemi esaminare questo per un momento.' WHERE entry=2000000523;
UPDATE db_script_string SET content_loc9='Sì?' WHERE entry=2000000792;
UPDATE db_script_string SET content_loc9='Davvero?' WHERE entry=2000005124;
UPDATE db_script_string SET content_loc9='Davvero?' WHERE entry=2000005127;
UPDATE db_script_string SET content_loc9='Davvero?' WHERE entry=2000005131;
UPDATE db_script_string SET content_loc9='Scavare troppo in profondità nel tuo passato potrebbe portare una brusca fine al tuo futuro.' WHERE entry=2000005308;
UPDATE db_script_string SET content_loc9='DIE ?! Fai piangere Pusillin!' WHERE entry=2000005463;

SET NAMES 'latin1';
