-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE locales_item SET name_loc9='Furia di Martin' WHERE entry=17; -- name: Martin Fury
UPDATE locales_item SET name_loc9='Spada Corta Logora' WHERE entry=25; -- name: Worn Shortsword
UPDATE locales_item SET name_loc9='Berga Piegata' WHERE entry=35; -- name: Bent Staff
UPDATE locales_item SET name_loc9='Mazza Logora' WHERE entry=36; -- name: Worn Mace
UPDATE locales_item SET name_loc9='Ascia Logora' WHERE entry=37; -- name: Worn Axe
UPDATE locales_item SET name_loc9='Camicia da Recluta' WHERE entry=38; -- name: Recruit\'s Shirt
UPDATE locales_item SET name_loc9='Pantaloni da Recluta' WHERE entry=39; -- name: Recruit\'s Pants
UPDATE locales_item SET name_loc9='Stivali da Recluta' WHERE entry=40; -- name: Recruit\'s Boots
UPDATE locales_item SET name_loc9='Stivali da Scudiero' WHERE entry=43; -- name: Squire\'s Boots
UPDATE locales_item SET name_loc9='Pantaloni da Scudiero' WHERE entry=44; -- name: Squire\'s Pants
UPDATE locales_item SET name_loc9='Camicia da Scudiero' WHERE entry=45; -- name: Squire\'s Shirt
UPDATE locales_item SET name_loc9='Scarpe da Fante' WHERE entry=47; -- name: Footpad\'s Shoes
UPDATE locales_item SET name_loc9='Pantaloni da Fante' WHERE entry=48; -- name: Footpad\'s Pants
UPDATE locales_item SET name_loc9='Camicia da Fante' WHERE entry=49; -- name: Footpad\'s Shirt
UPDATE locales_item SET name_loc9='Stivali da Neofita' WHERE entry=51; -- name: Neophyte\'s Boots
UPDATE locales_item SET name_loc9='Pantaloni da Neofita' WHERE entry=52; -- name: Neophyte\'s Pants
UPDATE locales_item SET name_loc9='Camicia da Neofita' WHERE entry=53; -- name: Neophyte\'s Shirt
UPDATE locales_item SET name_loc9='Stivali da Apprendista' WHERE entry=55; -- name: Apprentice\'s Boots
UPDATE locales_item SET name_loc9='Tunica da Apprendista' WHERE entry=56; -- name: Apprentice\'s Robe
UPDATE locales_item SET name_loc9='Tunica da Accolito' WHERE entry=57; -- name: Acolyte\'s Robe
UPDATE locales_item SET name_loc9='Scarpe da Accolito' WHERE entry=59; -- name: Acolyte\'s Shoes
UPDATE locales_item SET name_loc9='Tunica Spessa' WHERE entry=60; -- name: Layered Tunic
UPDATE locales_item SET name_loc9='Pantaloni di Cuoio Nanici' WHERE entry=61; -- name: Dwarven Leather Pants
UPDATE locales_item SET name_loc9='Braghe di Stoffa Nanica' WHERE entry=79; -- name: Dwarven Cloth Britches
UPDATE locales_item SET name_loc9='Scarpe soffici di Pelliccia' WHERE entry=80; -- name: Soft Fur-lined Shoes
UPDATE locales_item SET name_loc9='Abito Sporco di Cuoio' WHERE entry=85; -- name: Dirty Leather Vest
UPDATE locales_item SET name_loc9='Carne Essiccata' WHERE entry=117; -- name: Tough Jerky
UPDATE locales_item SET name_loc9='Pozione di Cura Minore' WHERE entry=118; -- name: Minor Healing Potion
UPDATE locales_item SET name_loc9='Pantaloni da Malvivente' WHERE entry=120; -- name: Thug Pants
UPDATE locales_item SET name_loc9='Stivali da Malvivente' WHERE entry=121; -- name: Thug Boots
UPDATE locales_item SET name_loc9='Camicia da Bracconiere' WHERE entry=127; -- name: Trapper\'s Shirt
UPDATE locales_item SET name_loc9='Stivali rigidi da Bracconiere' WHERE entry=129; -- name: Rugged Trapper\'s Boots
UPDATE locales_item SET name_loc9='Pantaloni del Rissaiolo' WHERE entry=139; -- name: Brawler\'s Pants
UPDATE locales_item SET name_loc9='Stivali del Rissaiolo' WHERE entry=140; -- name: Brawler\'s Boots
UPDATE locales_item SET name_loc9='Pantaloni Rigidi del Bracconiere' WHERE entry=147; -- name: Rugged Trapper\'s Pants
UPDATE locales_item SET name_loc9='Camicia rigida del Bracconiere' WHERE entry=148; -- name: Rugged Trapper\'s Shirt
UPDATE locales_item SET name_loc9='Kilt Primitivo' WHERE entry=153; -- name: Primitive Kilt
UPDATE locales_item SET name_loc9='Mantello Primitivo' WHERE entry=154; -- name: Primitive Mantle
UPDATE locales_item SET name_loc9='Acqua Fresca Rinfrascante' WHERE entry=159; -- name: Refreshing Spring Water
UPDATE locales_item SET name_loc9='Testa di Garrick' WHERE entry=182; -- name: Garrick\'s Head
UPDATE locales_item SET name_loc9='Tuono Di Martin' WHERE entry=192; -- name: Martin Thunder
UPDATE locales_item SET name_loc9='Veste di Stoffa Lacera' WHERE entry=193; -- name: Tattered Cloth Vest
UPDATE locales_item SET name_loc9='Pantaloni di Stoffa Laceri' WHERE entry=194; -- name: Tattered Cloth Pants
UPDATE locales_item SET name_loc9='Stivali di Stoffa laceri' WHERE entry=195; -- name: Tattered Cloth Boots
UPDATE locales_item SET name_loc9='Veste di stoffa Spessa' WHERE entry=200; -- name: Thick Cloth Vest
UPDATE locales_item SET name_loc9='Pantaloni di stoffa Spessi' WHERE entry=201; -- name: Thick Cloth Pants
UPDATE locales_item SET name_loc9='Scarpe di stoffa Spesse' WHERE entry=202; -- name: Thick Cloth Shoes
UPDATE locales_item SET name_loc9='Guanti di stoffa Spessi' WHERE entry=203; -- name: Thick Cloth Gloves
UPDATE locales_item SET name_loc9='Pantaloni sporchi di Cuoio' WHERE entry=209; -- name: Dirty Leather Pants
UPDATE locales_item SET name_loc9='Stivali sporchi di Cuoio' WHERE entry=210; -- name: Dirty Leather Boots
UPDATE locales_item SET name_loc9='Armatura di Cuoio Trattata' WHERE entry=236; -- name: Cured Leather Armor
UPDATE locales_item SET name_loc9='Pantaloni di Cuoio Trattati' WHERE entry=237; -- name: Cured Leather Pants
UPDATE locales_item SET name_loc9='Stivali di Cuoio Trattati' WHERE entry=238; -- name: Cured Leather Boots
UPDATE locales_item SET name_loc9='Guanti di Cuoio Trattati' WHERE entry=239; -- name: Cured Leather Gloves
UPDATE locales_item SET name_loc9='Veste Magliascaglie' WHERE entry=285; -- name: Scalemail Vest
UPDATE locales_item SET name_loc9='Pantaloni Magliascaglie' WHERE entry=286; -- name: Scalemail Pants
UPDATE locales_item SET name_loc9='Stivali Magliascaglie' WHERE entry=287; -- name: Scalemail Boots
UPDATE locales_item SET name_loc9='Dalaran Secco' WHERE entry=414; -- name: Dalaran Sharp
UPDATE locales_item SET name_loc9='Formaggio Nanesco' WHERE entry=422; -- name: Dwarven Mild
UPDATE locales_item SET name_loc9='Scaglie Dure' WHERE entry=537; -- name: Dull Frenzy Scale
UPDATE locales_item SET name_loc9='Piume Arruffate' WHERE entry=555; -- name: Rough Vulture Feathers
UPDATE locales_item SET name_loc9='Becco da Poiana' WHERE entry=556; -- name: Buzzard Beak
UPDATE locales_item SET name_loc9='Destino' WHERE entry=647; -- name: Destiny
UPDATE locales_item SET name_loc9='Braccialetti da miliziano' WHERE entry=710; -- name: Bracers of the People\'s Militia
UPDATE locales_item SET name_loc9='Guanti Laceri di Stoffa' WHERE entry=711; -- name: Tattered Cloth Gloves
UPDATE locales_item SET name_loc9='Guanti di Cuoio Sporchi' WHERE entry=714; -- name: Dirty Leather Gloves
UPDATE locales_item SET name_loc9='Guanti Magliascaglie' WHERE entry=718; -- name: Scalemail Gloves
UPDATE locales_item SET name_loc9='Guanti da Maneggiatore di Conigli' WHERE entry=719; -- name: Rabbit Handler Gloves
UPDATE locales_item SET name_loc9='Guanti da Picchiatore' WHERE entry=720; -- name: Brawler Gloves
UPDATE locales_item SET name_loc9='Fegato di Goretusk' WHERE entry=723; -- name: Goretusk Liver
UPDATE locales_item SET name_loc9='Torta di Fegato di Goretusk' WHERE entry=724; -- name: Goretusk Liver Pie
UPDATE locales_item SET name_loc9='Zampa di Gnoll' WHERE entry=725; -- name: Gnoll Paw
UPDATE locales_item SET name_loc9='Spada Corta Dentellata' WHERE entry=727; -- name: Notched Shortsword
UPDATE locales_item SET name_loc9='Ricetta: Stufato di Westfall' WHERE entry=728; -- name: Recipe: Westfall Stew -- description: Teaches you how to cook Westfall Stew.
UPDATE locales_item SET name_loc9='Carne fibrosa di Avvoltoio' WHERE entry=729; -- name: Stringy Vulture Meat
UPDATE locales_item SET name_loc9='Occhio di Murloc' WHERE entry=730; -- name: Murloc Eye
UPDATE locales_item SET name_loc9='Muso del Goretusk' WHERE entry=731; -- name: Goretusk Snout
UPDATE locales_item SET name_loc9='Ocra' WHERE entry=732; -- name: Okra
UPDATE locales_item SET name_loc9='Sufato di Westfall' WHERE entry=733; -- name: Westfall Stew
UPDATE locales_item SET name_loc9='Medaglione Rolf e Malakai' WHERE entry=735; -- name: Rolf and Malakai\'s Medallions
UPDATE locales_item SET name_loc9='Santa Acqua fresca' WHERE entry=737; -- name: Holy Spring Water
UPDATE locales_item SET name_loc9='Sacco di Orzo' WHERE entry=738; -- name: Sack of Barley
UPDATE locales_item SET name_loc9='Sacco di Mais' WHERE entry=739; -- name: Sack of Corn
UPDATE locales_item SET name_loc9='Sacco di Segale' WHERE entry=740; -- name: Sack of Rye

SET NAMES 'latin1';
