-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE locales_points_of_interest SET icon_name_loc9='Locanda del Fiero Leone' WHERE entry=1; /* icon_name: Lion\'s Pride Inn */
UPDATE locales_points_of_interest SET icon_name_loc9='Zaldimar Wefhellt' WHERE entry=2; /* icon_name: Zaldimar Wefhellt */
UPDATE locales_points_of_interest SET icon_name_loc9='Fratello Wilhelm' WHERE entry=3; /* icon_name: Brother Wilhelm */
UPDATE locales_points_of_interest SET icon_name_loc9='Alchimista Mallory' WHERE entry=8; /* icon_name: Alchemist Mallory */
UPDATE locales_points_of_interest SET icon_name_loc9='Smith Argus' WHERE entry=9; /* icon_name: Smith Argus */
UPDATE locales_points_of_interest SET icon_name_loc9='Tomas' WHERE entry=10; /* icon_name: Tomas */
UPDATE locales_points_of_interest SET icon_name_loc9='Adele Fielder' WHERE entry=14; /* icon_name: Adele Fielder */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Roccavento' WHERE entry=18; /* icon_name: Stormwind Auction House */
UPDATE locales_points_of_interest SET icon_name_loc9='La Rosa Dorata' WHERE entry=22; /* icon_name: The Gilded Rose */
UPDATE locales_points_of_interest SET icon_name_loc9='Centro Visitatori di Stormwind' WHERE entry=24; /* icon_name: Stormwind Visitor\'s Center */
UPDATE locales_points_of_interest SET icon_name_loc9='Woo Ping' WHERE entry=27; /* icon_name: Woo Ping */
UPDATE locales_points_of_interest SET icon_name_loc9='Champions\' Hall' WHERE entry=28; /* icon_name: Champions\' Hall */
UPDATE locales_points_of_interest SET icon_name_loc9='Mastro di Guerra di Stormwind' WHERE entry=29; /* icon_name: Battlemasters Stormwind */
UPDATE locales_points_of_interest SET icon_name_loc9='Il Parco' WHERE entry=32; /* icon_name: The Park */
UPDATE locales_points_of_interest SET icon_name_loc9='Santuario del Mago' WHERE entry=34; /* icon_name: Wizard\'s Sanctum */
UPDATE locales_points_of_interest SET icon_name_loc9='Cathedral Of Light' WHERE entry=35; /* icon_name: Cathedral Of Light */
UPDATE locales_points_of_interest SET icon_name_loc9='L\'Agnello Macellato' WHERE entry=38; /* icon_name: The Slaughtered Lamb */
UPDATE locales_points_of_interest SET icon_name_loc9='Esigenze Alchemiche' WHERE entry=40; /* icon_name: Alchemy Needs */
UPDATE locales_points_of_interest SET icon_name_loc9='Therum Deepforge' WHERE entry=41; /* icon_name: Therum Deepforge */
UPDATE locales_points_of_interest SET icon_name_loc9='Taverna del Maiale e del Fischietto' WHERE entry=42; /* icon_name: Pig and Whistle Tavern */
UPDATE locales_points_of_interest SET icon_name_loc9='Arnold Leland' WHERE entry=46; /* icon_name: Arnold Leland */
UPDATE locales_points_of_interest SET icon_name_loc9='La Pelle Protettiva' WHERE entry=47; /* icon_name: The Protective Hide */
UPDATE locales_points_of_interest SET icon_name_loc9='Tessili di Duncan' WHERE entry=49; /* icon_name: Duncan\'s Textiles */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Ironforge' WHERE entry=50; /* icon_name: Ironforge Auction house */
UPDATE locales_points_of_interest SET icon_name_loc9='Deeprun Tram' WHERE entry=52; /* icon_name: Deeprun Tram */
UPDATE locales_points_of_interest SET icon_name_loc9='Centro Visite di Ironforge' WHERE entry=54; /* icon_name: Ironforge Visitor\'s Center */
UPDATE locales_points_of_interest SET icon_name_loc9='Ulbrek Firehand' WHERE entry=57; /* icon_name: Ulbrek Firehand */
UPDATE locales_points_of_interest SET icon_name_loc9='Bixi e Buliwyf' WHERE entry=58; /* icon_name: Bixi and Buliwyf */
UPDATE locales_points_of_interest SET icon_name_loc9='Mastro di Guerra di Ironforge' WHERE entry=59; /* icon_name: Battlemasters Ironforge */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala delle Armi' WHERE entry=61; /* icon_name: Hall of Arms */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Misteri' WHERE entry=62; /* icon_name: Hall of Mysteries */
UPDATE locales_points_of_interest SET icon_name_loc9='Pozioni e Bevande Varie di Berryfizz' WHERE entry=66; /* icon_name: Berryfizz\'s Potions and Mixed Drinks */
UPDATE locales_points_of_interest SET icon_name_loc9='The Great Forge' WHERE entry=67; /* icon_name: The Great Forge */
UPDATE locales_points_of_interest SET icon_name_loc9='Il Ramino di Bronzo' WHERE entry=68; /* icon_name: The Bronze Kettle */
UPDATE locales_points_of_interest SET icon_name_loc9='Beni Arcani di Thistlefuzz' WHERE entry=69; /* icon_name: Thistlefuzz Arcanery */
UPDATE locales_points_of_interest SET icon_name_loc9='Medico di Ironforge' WHERE entry=70; /* icon_name: Ironforge Physician */
UPDATE locales_points_of_interest SET icon_name_loc9='Pescatore Itinerante' WHERE entry=71; /* icon_name: Traveling Fisherman */
UPDATE locales_points_of_interest SET icon_name_loc9='Merci di Pelle di Finespindle' WHERE entry=73; /* icon_name: Finespindle\'s Leather Goods */
UPDATE locales_points_of_interest SET icon_name_loc9='Vestiario di Stonebrow' WHERE entry=75; /* icon_name: Stonebrow\'s Clothier */
UPDATE locales_points_of_interest SET icon_name_loc9='Distilleria Birratuono' WHERE entry=76; /* icon_name: Thunderbrew Distillery */
UPDATE locales_points_of_interest SET icon_name_loc9='Shelby Stoneflint' WHERE entry=77; /* icon_name: Shelby Stoneflint */
UPDATE locales_points_of_interest SET icon_name_loc9='Azar Stronghammer' WHERE entry=80; /* icon_name: Azar Stronghammer */
UPDATE locales_points_of_interest SET icon_name_loc9='Tognus Flintfire' WHERE entry=85; /* icon_name: Tognus Flintfire */
UPDATE locales_points_of_interest SET icon_name_loc9='Paxton Ganter' WHERE entry=88; /* icon_name: Paxton Ganter */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Darnassus' WHERE entry=89; /* icon_name: Darnassus Auction House */
UPDATE locales_points_of_interest SET icon_name_loc9='Alassin' WHERE entry=95; /* icon_name: Alassin */
UPDATE locales_points_of_interest SET icon_name_loc9='Mastro di Guerra di Darnassus' WHERE entry=97; /* icon_name: Battlemasters Darnassus */
UPDATE locales_points_of_interest SET icon_name_loc9='Terrazza dei Guerrieri' WHERE entry=101; /* icon_name: Warrior\'s Terrace */
UPDATE locales_points_of_interest SET icon_name_loc9='Seriadne' WHERE entry=112; /* icon_name: Seriadne */
UPDATE locales_points_of_interest SET icon_name_loc9='Cyndra Kindwhisper' WHERE entry=118; /* icon_name: Cyndra Kindwhisper */
UPDATE locales_points_of_interest SET icon_name_loc9='Zarrin' WHERE entry=119; /* icon_name: Zarrin */
UPDATE locales_points_of_interest SET icon_name_loc9='Alanna Raveneye' WHERE entry=120; /* icon_name: Alanna Raveneye */
UPDATE locales_points_of_interest SET icon_name_loc9='Byancie' WHERE entry=121; /* icon_name: Byancie */
UPDATE locales_points_of_interest SET icon_name_loc9='Banca di Orgrimmar' WHERE entry=176; /* icon_name: Bank of Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc9='Ambasciata dell\'Orda' WHERE entry=178; /* icon_name: Horde Embassy */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Orgrimmar' WHERE entry=181; /* icon_name: Orgrimmar Auction House */
UPDATE locales_points_of_interest SET icon_name_loc9='Sayoc & Hanashi' WHERE entry=184; /* icon_name: Sayoc & Hanashi */
UPDATE locales_points_of_interest SET icon_name_loc9='Xon\'cha' WHERE entry=185; /* icon_name: Xon\'cha */
UPDATE locales_points_of_interest SET icon_name_loc9='Hall of Legends' WHERE entry=186; /* icon_name: Hall of Legends */
UPDATE locales_points_of_interest SET icon_name_loc9='Mastro di Guerra di Orgrimmar' WHERE entry=187; /* icon_name: Battlemasters Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc9='Rawrk' WHERE entry=241; /* icon_name: Rawrk */
UPDATE locales_points_of_interest SET icon_name_loc9='Tai\'jin' WHERE entry=249; /* icon_name: Tai\'jin */
UPDATE locales_points_of_interest SET icon_name_loc9='Un\'Thuwa' WHERE entry=250; /* icon_name: Un\'Thuwa */
UPDATE locales_points_of_interest SET icon_name_loc9='Thotar' WHERE entry=251; /* icon_name: Thotar */
UPDATE locales_points_of_interest SET icon_name_loc9='Shoja\'my' WHERE entry=252; /* icon_name: Shoja\'my */
UPDATE locales_points_of_interest SET icon_name_loc9='The Apothecarium' WHERE entry=266; /* icon_name: The Apothecarium */
UPDATE locales_points_of_interest SET icon_name_loc9='Campione Cyssa Dawnrose' WHERE entry=271; /* icon_name: Champion Cyssa Dawnrose */
UPDATE locales_points_of_interest SET icon_name_loc9='Archibald' WHERE entry=274; /* icon_name: Archibald */
UPDATE locales_points_of_interest SET icon_name_loc9='Anya Maulray' WHERE entry=275; /* icon_name: Anya Maulray */
UPDATE locales_points_of_interest SET icon_name_loc9='Mastro di Guerra di Undercity' WHERE entry=280; /* icon_name: Battlemasters Undercity */
UPDATE locales_points_of_interest SET icon_name_loc9='Casa d\'Aste di Sepulcra' WHERE entry=284; /* icon_name: Undercity Auction House */
UPDATE locales_points_of_interest SET icon_name_loc9='Bowen Brisboise' WHERE entry=285; /* icon_name: Bowen Brisboise */
UPDATE locales_points_of_interest SET icon_name_loc9='Rand Rhobart' WHERE entry=286; /* icon_name: Rand Rhobart */
UPDATE locales_points_of_interest SET icon_name_loc9='Shelene Rhobart' WHERE entry=287; /* icon_name: Shelene Rhobart */
UPDATE locales_points_of_interest SET icon_name_loc9='Clyde Kellen' WHERE entry=289; /* icon_name: Clyde Kellen */
UPDATE locales_points_of_interest SET icon_name_loc9='Vance Undergloom' WHERE entry=291; /* icon_name: Vance Undergloom */
UPDATE locales_points_of_interest SET icon_name_loc9='Carolai Anise' WHERE entry=292; /* icon_name: Carolai Anise */
UPDATE locales_points_of_interest SET icon_name_loc9='Austil de Mon' WHERE entry=293; /* icon_name: Austil de Mon */
UPDATE locales_points_of_interest SET icon_name_loc9='Rupert Boch' WHERE entry=294; /* icon_name: Rupert Boch */
UPDATE locales_points_of_interest SET icon_name_loc9='Cain Firesong' WHERE entry=298; /* icon_name: Cain Firesong */
UPDATE locales_points_of_interest SET icon_name_loc9='Taverna dell\'Impiccato' WHERE entry=299; /* icon_name: Gallows\' End Tavern */
UPDATE locales_points_of_interest SET icon_name_loc9='Armatori di Thunder Bluff' WHERE entry=301; /* icon_name: Thunder Bluff Armorers */
UPDATE locales_points_of_interest SET icon_name_loc9='Geologia Stonehoof' WHERE entry=303; /* icon_name: Stonehoof Geology */
UPDATE locales_points_of_interest SET icon_name_loc9='Armatori di Thunder Bluff' WHERE entry=304; /* icon_name: Thunder Bluff Armorers */
UPDATE locales_points_of_interest SET icon_name_loc9='Erbalismo Holistic' WHERE entry=306; /* icon_name: Holistic Herbalism */
UPDATE locales_points_of_interest SET icon_name_loc9='Esca & Attrezzatura da Pesca Mountaintop' WHERE entry=307; /* icon_name: Mountaintop Bait & Tackle */
UPDATE locales_points_of_interest SET icon_name_loc9='Cure Spirituali' WHERE entry=308; /* icon_name: Spiritual Healing */
UPDATE locales_points_of_interest SET icon_name_loc9='Incantatori Dawnstrider' WHERE entry=309; /* icon_name: Dawnstrider Enchanters */
UPDATE locales_points_of_interest SET icon_name_loc9='Cucina di Aska' WHERE entry=310; /* icon_name: Aska\'s Kitchen */
UPDATE locales_points_of_interest SET icon_name_loc9='Fucina di Karn' WHERE entry=311; /* icon_name: Karn\'s Smithy */
UPDATE locales_points_of_interest SET icon_name_loc9='Alchimia di Bena' WHERE entry=312; /* icon_name: Bena\'s Alchemy */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Cacciatori' WHERE entry=313; /* icon_name: Hunter\'s Hall */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala degli Spiriti' WHERE entry=314; /* icon_name: Hall of Spirits */
UPDATE locales_points_of_interest SET icon_name_loc9='Pozze delle Visioni' WHERE entry=315; /* icon_name: Pools of Vision */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala degli Anziani' WHERE entry=316; /* icon_name: Hall of Elders */
UPDATE locales_points_of_interest SET icon_name_loc9='Mastro di Guerra di Thunder Bluff' WHERE entry=317; /* icon_name: Battlemasters Thunder Bluff */
UPDATE locales_points_of_interest SET icon_name_loc9='Bulrug' WHERE entry=318; /* icon_name: Bulrug */
UPDATE locales_points_of_interest SET icon_name_loc9='Ansekhwa' WHERE entry=319; /* icon_name: Ansekhwa */
UPDATE locales_points_of_interest SET icon_name_loc9='Informazioni Civiche di Thunder Bluff' WHERE entry=323; /* icon_name: Thunder Bluff Civic Information */
UPDATE locales_points_of_interest SET icon_name_loc9='Banca di Thunder Bluff' WHERE entry=325; /* icon_name: Thunder Bluff Bank */
UPDATE locales_points_of_interest SET icon_name_loc9='Yonn Deepcut' WHERE entry=326; /* icon_name: Yonn Deepcut */
UPDATE locales_points_of_interest SET icon_name_loc9='Chaw Stronghide' WHERE entry=327; /* icon_name: Chaw Stronghide */
UPDATE locales_points_of_interest SET icon_name_loc9='Vira Younghoof' WHERE entry=330; /* icon_name: Vira Younghoof */
UPDATE locales_points_of_interest SET icon_name_loc9='Yaw Sharpmane' WHERE entry=335; /* icon_name: Yaw Sharpmane */
UPDATE locales_points_of_interest SET icon_name_loc9='Seikwa' WHERE entry=337; /* icon_name: Seikwa */
UPDATE locales_points_of_interest SET icon_name_loc9='Locanda di Bloodhoof Village' WHERE entry=338; /* icon_name: Bloodhoof Village Inn */
UPDATE locales_points_of_interest SET icon_name_loc9='Yarr Hammerstone' WHERE entry=339; /* icon_name: Yarr Hammerstone */
UPDATE locales_points_of_interest SET icon_name_loc9='Tempio della Luna' WHERE entry=364; /* icon_name: Temple of the Moon */
UPDATE locales_points_of_interest SET icon_name_loc9='Gadget di Springspindle' WHERE entry=419; /* icon_name: Springspindle\'s Gadgets */
UPDATE locales_points_of_interest SET icon_name_loc9='Padiglione Darkbriar' WHERE entry=421; /* icon_name: Darkbriar Lodge */
UPDATE locales_points_of_interest SET icon_name_loc9='Padiglione dello Spirito' WHERE entry=422; /* icon_name: Spirit Lodge */
UPDATE locales_points_of_interest SET icon_name_loc9='Fortezza di Thrall' WHERE entry=423; /* icon_name: Thrall\'s Fortress */
UPDATE locales_points_of_interest SET icon_name_loc9='Fratellanza Shadowswift' WHERE entry=424; /* icon_name: Shadowswift Brotherhood */
UPDATE locales_points_of_interest SET icon_name_loc9='Enclave di Darkfire' WHERE entry=425; /* icon_name: Darkfire Enclave */
UPDATE locales_points_of_interest SET icon_name_loc9='Sala dei Coraggiosi' WHERE entry=426; /* icon_name: Hall of the Brave */
UPDATE locales_points_of_interest SET icon_name_loc9='Alchemi e Pozioni di Yelmak' WHERE entry=427; /* icon_name: Yelmak\'s Alchemy and Potions */
UPDATE locales_points_of_interest SET icon_name_loc9='L\'Incudine Bruciante' WHERE entry=428; /* icon_name: The Burning Anvil */
UPDATE locales_points_of_interest SET icon_name_loc9='Pozza del Fuoco di Borstan' WHERE entry=429; /* icon_name: Borstan\'s Firepit */
UPDATE locales_points_of_interest SET icon_name_loc9='Lavori Runici di Godan' WHERE entry=430; /* icon_name: Godan\'s Runeworks */
UPDATE locales_points_of_interest SET icon_name_loc9='Officina di Nogg' WHERE entry=431; /* icon_name: Nogg\'s Machine Shop */
UPDATE locales_points_of_interest SET icon_name_loc9='Sopravvivenza dei Più Adatti' WHERE entry=432; /* icon_name: Survival of the Fittest */
UPDATE locales_points_of_interest SET icon_name_loc9='Pesca di Lumak' WHERE entry=433; /* icon_name: Lumak\'s Fishing */
UPDATE locales_points_of_interest SET icon_name_loc9='Arboreto di Jandi' WHERE entry=434; /* icon_name: Jandi\'s Arboretum */
UPDATE locales_points_of_interest SET icon_name_loc9='Estrazioni del Canyon Rosso' WHERE entry=435; /* icon_name: Red Canyon Mining */
UPDATE locales_points_of_interest SET icon_name_loc9='Conciatori Kodohide' WHERE entry=436; /* icon_name: Kodohide Leatherworkers */
UPDATE locales_points_of_interest SET icon_name_loc9='Beni Tessili di Magar' WHERE entry=437; /* icon_name: Magar\'s Cloth Goods */

SET NAMES 'latin1';
