-- File generated by Mangos Online Translation Editor (MOTE) v0.8
SET NAMES 'utf8';
UPDATE mangos_string SET content_loc7='UNUSED' WHERE entry=235; /* content: UNUSED */
UPDATE mangos_string SET content_loc7='UNUSED' WHERE entry=242; /* content: UNUSED */
UPDATE mangos_string SET content_loc7='UNUSED' WHERE entry=243; /* content: UNUSED */
UPDATE mangos_string SET content_loc7='UNUSED' WHERE entry=244; /* content: UNUSED */
UPDATE mangos_string SET content_loc7='UNUSED' WHERE entry=245; /* content: UNUSED */
UPDATE mangos_string SET content_loc7='UNUSED' WHERE entry=251; /* content: UNUSED */
UPDATE mangos_string SET content_loc7='Horda' WHERE entry=458; /* content: horde */
UPDATE mangos_string SET content_loc7='¡La Alianza gana!' WHERE entry=600; /* content: The Alliance wins! */
UPDATE mangos_string SET content_loc7='¡La Horda gana!' WHERE entry=601; /* content: The Horde wins! */
UPDATE mangos_string SET content_loc7='La batalla por la Garganta Grito de Guerra comenzará en 1 minuto.' WHERE entry=602; /* content: The battle for Warsong Gulch begins in 1 minute. */
UPDATE mangos_string SET content_loc7='¡$n ha capturado la bandera de la Horda!' WHERE entry=605; /* content: $n captured the Horde flag! */
UPDATE mangos_string SET content_loc7='¡$n ha capturado la bandera de la Alianza!' WHERE entry=606; /* content: $n captured the Alliance flag! */
UPDATE mangos_string SET content_loc7='¡$n ha dejado caer la bandera de la Horda!' WHERE entry=607; /* content: The Horde flag was dropped by $n! */
UPDATE mangos_string SET content_loc7='¡$n ha dejado caer la bandera de la Alianza!' WHERE entry=608; /* content: The Alliance Flag was dropped by $n! */
UPDATE mangos_string SET content_loc7='¡$n ha devuelto la bandera de la Alianza a su base!' WHERE entry=609; /* content: The Alliance Flag was returned to its base by $n! */
UPDATE mangos_string SET content_loc7='¡$n ha devuelto la bandera de la Horda a su base!' WHERE entry=610; /* content: The Horde flag was returned to its base by $n! */
UPDATE mangos_string SET content_loc7='¡$n ha tomado la bandera de la Horda!' WHERE entry=611; /* content: The Horde flag was picked up by $n! */
UPDATE mangos_string SET content_loc7='¡$n ha tomado la bandera de la Alianza!' WHERE entry=612; /* content: The Alliance Flag was picked up by $n! */
UPDATE mangos_string SET content_loc7='Las banderas están colocadas en sus bases.' WHERE entry=613; /* content: The flags are now placed at their bases. */
UPDATE mangos_string SET content_loc7='Ahora la bandera de la Alianza está situada en la base.' WHERE entry=614; /* content: The Alliance flag is now placed at its base. */
UPDATE mangos_string SET content_loc7='Ahora la bandera de la Horda está situada en la base.' WHERE entry=615; /* content: The Horde flag is now placed at its base. */
UPDATE mangos_string SET content_loc7='Horda' WHERE entry=651; /* content: horde */
UPDATE mangos_string SET content_loc7='Herrería' WHERE entry=653; /* content: blacksmith */
UPDATE mangos_string SET content_loc7='¡La Alianza ha reunido $1776W recursos y está cerca de la victoria!' WHERE entry=664; /* content: The Alliance has gathered $1776W resources, and is near victory! */
UPDATE mangos_string SET content_loc7='¡La Horda ha reunido $1777W recursos y está cerca de la victoria!' WHERE entry=665; /* content: The Horde has gathered $1777W resources, and is near victory! */
UPDATE mangos_string SET content_loc7='1 minuto para que dé comienzo la batalla por el Valle de Alterac.' WHERE entry=784; /* content: 1 minute until the battle for Alterac Valley begins. */
UPDATE mangos_string SET content_loc7='¡La batalla por el Valle de Alterac ha comenzado!' WHERE entry=786; /* content: The battle for Alterac Valley has begun! */
UPDATE mangos_string SET content_loc7='¡El equipo de la Alianza se está quedando sin refuerzos!' WHERE entry=787; /* content: The Alliance Team is running out of reinforcements! */
UPDATE mangos_string SET content_loc7='¡El equipo de la Horda se está quedando sin refuerzos!' WHERE entry=788; /* content: The Horde Team is running out of reinforcements! */
UPDATE mangos_string SET content_loc7='¡El general Lobo Gélido ha muerto!' WHERE entry=789; /* content: The Frostwolf General is Dead! */
UPDATE mangos_string SET content_loc7='¡El general Pico Tormenta ha muerto!' WHERE entry=790; /* content: The Stormpike General is Dead! */
UPDATE mangos_string SET content_loc7='Maestro de hermandad' WHERE entry=811; /* content: Guild Master */
UPDATE mangos_string SET content_loc7='Naranja' WHERE entry=1188; /* content: Orange */
UPDATE mangos_string SET content_loc7='|cffffff00¡La Horda se ha hecho con el control de la Torre del Paso Norte!|r' WHERE entry=1600; /* content: |cffffff00Northpass Tower has been taken by the Horde!|r */
UPDATE mangos_string SET content_loc7='|cffffff00¡La Alianza se ha hecho con el control de la Torre del Paso Norte!|r' WHERE entry=1601; /* content: |cffffff00Northpass Tower has been taken by the Alliance!|r */
UPDATE mangos_string SET content_loc7='|cffffff00¡La Horda se ha hecho con el control de la Torre de la Corona!|r' WHERE entry=1602; /* content: |cffffff00Crown Guard Tower has been taken by the Horde!|r */
UPDATE mangos_string SET content_loc7='|cffffff00¡La Alianza se ha hecho con el control de la Torre de la Corona!|r' WHERE entry=1603; /* content: |cffffff00Crown Guard Tower has been taken by the Alliance!|r */
UPDATE mangos_string SET content_loc7='|cffffff00¡La Horda se ha hecho con el control de la Torre de la Muralla del Este!|r' WHERE entry=1604; /* content: |cffffff00Eastwall Tower has been taken by the Horde!|r */
UPDATE mangos_string SET content_loc7='|cffffff00¡La Alianza se ha hecho con el control de la Torre de la Muralla del Este!|r' WHERE entry=1605; /* content: |cffffff00Eastwall Tower has been taken by the Alliance!|r */
UPDATE mangos_string SET content_loc7='|cffffff00¡La Horda se ha hecho con el control de la Torre del Bosque de la Peste!|r' WHERE entry=1606; /* content: |cffffff00The Plaguewood Tower has been taken by the Horde!|r */
UPDATE mangos_string SET content_loc7='|cffffff00¡La Alianza se ha hecho con el control de la Torre del Bosque de la Peste!|r' WHERE entry=1607; /* content: |cffffff00The Plaguewood Tower has been taken by the Alliance!|r */

SET NAMES 'latin1';
