-- File generated by Mangos Online Translation Editor (MOTE) v2.10
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc3`='Cat Figurine Trap' WHERE `word_id` = 117014; -- locales_gameobject - name : entry=12653
UPDATE `trans_words` SET `content_loc3`='Fire With Boiling Water' WHERE `word_id` = 114910; -- locales_gameobject - name : entry=103773
UPDATE `trans_words` SET `content_loc3`='Locked Cage' WHERE `word_id` = 115510; -- locales_gameobject - name : entry=175786
UPDATE `trans_words` SET `content_loc3`='Bowel with Boobles' WHERE `word_id` = 115556; -- locales_gameobject - name : entry=176157
UPDATE `trans_words` SET `content_loc3`='Mysterious Wailing Caverns Chest' WHERE `word_id` = 116598; -- locales_gameobject - name : entry=180055
UPDATE `trans_words` SET `content_loc3`='Wickerman Guardian Ember' WHERE `word_id` = 117017; -- locales_gameobject - name : entry=180574
UPDATE `trans_words` SET `content_loc3`='Arena Spoils' WHERE `word_id` = 116413; -- locales_gameobject - name : entry=181074
UPDATE `trans_words` SET `content_loc3`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184507
UPDATE `trans_words` SET `content_loc3`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184508
UPDATE `trans_words` SET `content_loc3`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184509
UPDATE `trans_words` SET `content_loc3`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184511
UPDATE `trans_words` SET `content_loc3`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184512
UPDATE `trans_words` SET `content_loc3`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184513
UPDATE `trans_words` SET `content_loc3`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184514
UPDATE `trans_words` SET `content_loc3`='Wooden Board' WHERE `word_id` = 116718; -- locales_gameobject - name : entry=184515
UPDATE `trans_words` SET `content_loc3`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184563
UPDATE `trans_words` SET `content_loc3`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184564
UPDATE `trans_words` SET `content_loc3`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184579
UPDATE `trans_words` SET `content_loc3`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184580
UPDATE `trans_words` SET `content_loc3`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184581
UPDATE `trans_words` SET `content_loc3`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184582
UPDATE `trans_words` SET `content_loc3`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184583
UPDATE `trans_words` SET `content_loc3`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184584
UPDATE `trans_words` SET `content_loc3`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184585
UPDATE `trans_words` SET `content_loc3`='Aura Trap Purple Tall' WHERE `word_id` = 116809; -- locales_gameobject - name : entry=185564
UPDATE `trans_words` SET `content_loc3`='Aura Trap Purple Tall' WHERE `word_id` = 116809; -- locales_gameobject - name : entry=185578
UPDATE `trans_words` SET `content_loc3`='Aura Trap Purple Tall' WHERE `word_id` = 116809; -- locales_gameobject - name : entry=185579
UPDATE `trans_words` SET `content_loc3`='Shopping Centre' WHERE `word_id` = 116893; -- locales_gameobject - name : entry=200001
UPDATE `trans_words` SET `content_loc3`='Teleport-Stone to Hyjal' WHERE `word_id` = 116922; -- locales_gameobject - name : entry=211050

SET NAMES 'latin1';
