-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE locales_creature SET subname_loc3='Enraged Form' WHERE entry=2454; -- subname: Enraged Form
UPDATE locales_creature SET subname_loc3='Crocilisk Trainer' WHERE entry=2876; -- subname: Crocilisk Trainer
UPDATE locales_creature SET subname_loc3='Night Elf Druid' WHERE entry=4253; -- subname: Night Elf Druid
UPDATE locales_creature SET subname_loc3='Tauren Druid' WHERE entry=4261; -- subname: Tauren Druid
UPDATE locales_creature SET subname_loc3='Night Elf Druid' WHERE entry=4408; -- subname: Night Elf Druid
UPDATE locales_creature SET subname_loc3='Tauren Druid' WHERE entry=4410; -- subname: Tauren Druid
UPDATE locales_creature SET subname_loc3='Night Elf Druid' WHERE entry=6571; -- subname: Night Elf Druid
UPDATE locales_creature SET subname_loc3='Tauren Druid' WHERE entry=6572; -- subname: Tauren Druid
UPDATE locales_creature SET subname_loc3='Male' WHERE entry=7503; -- subname: Male
UPDATE locales_creature SET subname_loc3='Female' WHERE entry=7504; -- subname: Female
UPDATE locales_creature SET subname_loc3='Spell Visual' WHERE entry=10579; -- subname: Spell Visual
UPDATE locales_creature SET subname_loc3='Orc Female' WHERE entry=10784; -- subname: Orc Female
UPDATE locales_creature SET subname_loc3='Tauren Male' WHERE entry=10785; -- subname: Tauren Male
UPDATE locales_creature SET subname_loc3='Tauren Female' WHERE entry=10786; -- subname: Tauren Female
UPDATE locales_creature SET subname_loc3='Troll Male' WHERE entry=10787; -- subname: Troll Male
UPDATE locales_creature SET subname_loc3='Troll Female' WHERE entry=10788; -- subname: Troll Female
UPDATE locales_creature SET subname_loc3='Undead Male' WHERE entry=10789; -- subname: Undead Male
UPDATE locales_creature SET subname_loc3='Undead Female' WHERE entry=10790; -- subname: Undead Female
UPDATE locales_creature SET subname_loc3='Dwarf Male' WHERE entry=10791; -- subname: Dwarf Male
UPDATE locales_creature SET subname_loc3='Dwarf Female' WHERE entry=10792; -- subname: Dwarf Female
UPDATE locales_creature SET subname_loc3='Gnome Male' WHERE entry=10793; -- subname: Gnome Male
UPDATE locales_creature SET subname_loc3='Gnome Female' WHERE entry=10794; -- subname: Gnome Female
UPDATE locales_creature SET subname_loc3='Human Male' WHERE entry=10795; -- subname: Human Male
UPDATE locales_creature SET subname_loc3='Human Female' WHERE entry=10796; -- subname: Human Female
UPDATE locales_creature SET subname_loc3='Night Elf Male' WHERE entry=10797; -- subname: Night Elf Male
UPDATE locales_creature SET subname_loc3='(Night Elf Female)' WHERE entry=10798; -- subname: (Night Elf Female)
UPDATE locales_creature SET subname_loc3='The Head of The Black Flight' WHERE entry=11583; -- subname: The Head of The Black Flight
UPDATE locales_creature SET subname_loc3='Ghost Visual' WHERE entry=12861; -- subname: Ghost Visual
UPDATE locales_creature SET subname_loc3='DO NOT DELETE' WHERE entry=12999; -- subname: DO NOT DELETE
UPDATE locales_creature SET subname_loc3='DO NOT DELETE' WHERE entry=14501; -- subname: DO NOT DELETE
UPDATE locales_creature SET subname_loc3='Night Elf Druid' WHERE entry=15313; -- subname: Night Elf Druid
UPDATE locales_creature SET subname_loc3='Tauren Druid' WHERE entry=15314; -- subname: Tauren Druid
UPDATE locales_creature SET subname_loc3='DO NOT DELETE' WHERE entry=15384; -- subname: DO NOT DELETE
UPDATE locales_creature SET subname_loc3='Mount Visual' WHERE entry=15778; -- subname: Mount Visual
UPDATE locales_creature SET name_loc3='Vicious Gladiator\'s Gavel',subname_loc3='Exotic Reagent Merchant' WHERE entry=16015; -- name: Vicious Gladiator\'s Gavel -- subname: Exotic Reagent Merchant
UPDATE locales_creature SET subname_loc3='Ghost/Ghoul spawner' WHERE entry=16306; -- subname: Ghost/Ghoul spawner
UPDATE locales_creature SET subname_loc3='Ghost/Skeleton spawner' WHERE entry=16336; -- subname: Ghost/Skeleton spawner
UPDATE locales_creature SET subname_loc3='Ghoul/Skeleton spawner' WHERE entry=16338; -- subname: Ghoul/Skeleton spawner
UPDATE locales_creature SET subname_loc3='finder' WHERE entry=16356; -- subname: finder
UPDATE locales_creature SET subname_loc3='Ammunition Vendor' WHERE entry=17598; -- subname: Ammunition Vendor

SET NAMES 'latin1';
