-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE locales_points_of_interest SET icon_name_loc3='Stormwind Locksmith' WHERE entry=25; /* icon_name: Stormwind Locksmith */
UPDATE locales_points_of_interest SET icon_name_loc3='Ironforge Shaman Trainer' WHERE entry=65; /* icon_name: Ironforge Shaman Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Orgrimmar Eastern Zeppelin Tower' WHERE entry=182; /* icon_name: Orgrimmar Eastern Zeppelin Tower */
UPDATE locales_points_of_interest SET icon_name_loc3='Orgrimmar Western Zeppelin Tower' WHERE entry=183; /* icon_name: Orgrimmar Western Zeppelin Tower */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Auctioneer' WHERE entry=190; /* icon_name: Exodar, Auctioneer */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, bank' WHERE entry=191; /* icon_name: Exodar, bank */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Hippogryph Master' WHERE entry=192; /* icon_name: Exodar, Hippogryph Master */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Guild Master' WHERE entry=193; /* icon_name: Exodar, Guild Master */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Inn' WHERE entry=194; /* icon_name: Exodar, Inn */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Mailbox' WHERE entry=195; /* icon_name: Exodar, Mailbox */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Stable Master' WHERE entry=196; /* icon_name: Exodar, Stable Master */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Weapon Master' WHERE entry=197; /* icon_name: Exodar, Weapon Master */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Druid Trainer' WHERE entry=198; /* icon_name: Exodar, Druid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Hunter Trainers' WHERE entry=199; /* icon_name: Exodar, Hunter Trainers */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Mage Trainers' WHERE entry=200; /* icon_name: Exodar, Mage Trainers */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Paladin Trainers' WHERE entry=201; /* icon_name: Exodar, Paladin Trainers */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Priest Trainers' WHERE entry=202; /* icon_name: Exodar, Priest Trainers */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Shaman Trainer' WHERE entry=203; /* icon_name: Exodar, Shaman Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Warrior Trainers' WHERE entry=204; /* icon_name: Exodar, Warrior Trainers */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Alchemist Trainers' WHERE entry=205; /* icon_name: Exodar, Alchemist Trainers */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Blacksmithing Trainers' WHERE entry=206; /* icon_name: Exodar, Blacksmithing Trainers */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Enchanters' WHERE entry=207; /* icon_name: Exodar, Enchanters */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Engineering' WHERE entry=208; /* icon_name: Exodar, Engineering */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, First Aid Trainer' WHERE entry=209; /* icon_name: Exodar, First Aid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Fishing Trainer' WHERE entry=210; /* icon_name: Exodar, Fishing Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Herbalist Trainer' WHERE entry=211; /* icon_name: Exodar, Herbalist Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Jewelcrafters' WHERE entry=213; /* icon_name: Exodar, Jewelcrafters */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Leatherworking' WHERE entry=214; /* icon_name: Exodar, Leatherworking */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Mining Trainers' WHERE entry=215; /* icon_name: Exodar, Mining Trainers */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Skinning Trainer' WHERE entry=216; /* icon_name: Exodar, Skinning Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Tailors' WHERE entry=217; /* icon_name: Exodar, Tailors */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Cook' WHERE entry=218; /* icon_name: Exodar, Cook */
UPDATE locales_points_of_interest SET icon_name_loc3='Azure Watch, Innkeeper' WHERE entry=219; /* icon_name: Azure Watch, Innkeeper */
UPDATE locales_points_of_interest SET icon_name_loc3='Azure Watch, Stable Master' WHERE entry=220; /* icon_name: Azure Watch, Stable Master */
UPDATE locales_points_of_interest SET icon_name_loc3='Azure Watch, Hunter Trainer' WHERE entry=221; /* icon_name: Azure Watch, Hunter Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Azure Watch, Mage Trainer' WHERE entry=222; /* icon_name: Azure Watch, Mage Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Azure Watch, Paladin Trainer' WHERE entry=223; /* icon_name: Azure Watch, Paladin Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Azure Watch, Priest Trainer' WHERE entry=224; /* icon_name: Azure Watch, Priest Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Azure Watch, Shaman Trainer' WHERE entry=225; /* icon_name: Azure Watch, Shaman Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Azure Watch, Warrior Trainer' WHERE entry=226; /* icon_name: Azure Watch, Warrior Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Azure Watch, Alchemist' WHERE entry=227; /* icon_name: Azure Watch, Alchemist */
UPDATE locales_points_of_interest SET icon_name_loc3='Odesyus\' Landing, Blacksmith' WHERE entry=228; /* icon_name: Odesyus\' Landing, Blacksmith */
UPDATE locales_points_of_interest SET icon_name_loc3='Odesyus\' Landing, Cook' WHERE entry=229; /* icon_name: Odesyus\' Landing, Cook */
UPDATE locales_points_of_interest SET icon_name_loc3='Azure Watch, Engineering Trainer' WHERE entry=230; /* icon_name: Azure Watch, Engineering Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Azure Watch, First Aid Trainer' WHERE entry=231; /* icon_name: Azure Watch, First Aid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Ammen Ford, Fisherwoman' WHERE entry=232; /* icon_name: Ammen Ford, Fisherwoman */
UPDATE locales_points_of_interest SET icon_name_loc3='Azure Watch, Herbalist' WHERE entry=233; /* icon_name: Azure Watch, Herbalist */
UPDATE locales_points_of_interest SET icon_name_loc3='Stillpine Hold, Leatherworker' WHERE entry=234; /* icon_name: Stillpine Hold, Leatherworker */
UPDATE locales_points_of_interest SET icon_name_loc3='Azure Watch, Mining Trainer' WHERE entry=235; /* icon_name: Azure Watch, Mining Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Stillpine Hold, Skinner' WHERE entry=236; /* icon_name: Stillpine Hold, Skinner */
UPDATE locales_points_of_interest SET icon_name_loc3='Odesyus\' Landing, Tailor' WHERE entry=237; /* icon_name: Odesyus\' Landing, Tailor */
UPDATE locales_points_of_interest SET icon_name_loc3='Undercity Locksmith' WHERE entry=277; /* icon_name: Undercity Locksmith */
UPDATE locales_points_of_interest SET icon_name_loc3='Thunder Bluff Zeppelin' WHERE entry=300; /* icon_name: Thunder Bluff Zeppelin */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath Cantina' WHERE entry=340; /* icon_name: Shattrath Cantina */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath Taxi' WHERE entry=341; /* icon_name: Shattrath Taxi */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath Alchemist' WHERE entry=342; /* icon_name: Shattrath Alchemist */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath Armor/Weapon Crafter' WHERE entry=343; /* icon_name: Shattrath Armor/Weapon Crafter */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath Cook' WHERE entry=344; /* icon_name: Shattrath Cook */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath Enchanters' WHERE entry=345; /* icon_name: Shattrath Enchanters */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath First Aid' WHERE entry=346; /* icon_name: Shattrath First Aid */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath Jewelcrafter' WHERE entry=347; /* icon_name: Shattrath Jewelcrafter */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath Leatherworker' WHERE entry=348; /* icon_name: Shattrath Leatherworker */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath Skinner' WHERE entry=349; /* icon_name: Shattrath Skinner */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath Mana Loom' WHERE entry=350; /* icon_name: Shattrath Mana Loom */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath Alchemy Lab' WHERE entry=351; /* icon_name: Shattrath Alchemy Lab */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath Bank Aldor' WHERE entry=352; /* icon_name: Shattrath Bank Aldor */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath Bank Scryer' WHERE entry=353; /* icon_name: Shattrath Bank Scryer */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath Inn Aldor' WHERE entry=354; /* icon_name: Shattrath Inn Aldor */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath Inn Scryer' WHERE entry=355; /* icon_name: Shattrath Inn Scryer */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath Stable Aldor' WHERE entry=356; /* icon_name: Shattrath Stable Aldor */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath Stable Scryer' WHERE entry=357; /* icon_name: Shattrath Stable Scryer */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath Battlemasters Alliance' WHERE entry=358; /* icon_name: Shattrath Battlemasters Alliance */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath Battlemasters Horde' WHERE entry=359; /* icon_name: Shattrath Battlemasters Horde */
UPDATE locales_points_of_interest SET icon_name_loc3='Shattrath Arena Battlemasters' WHERE entry=360; /* icon_name: Shattrath Arena Battlemasters */
UPDATE locales_points_of_interest SET icon_name_loc3='Aldor Gem Vendor' WHERE entry=361; /* icon_name: Aldor Gem Vendor */
UPDATE locales_points_of_interest SET icon_name_loc3='Scryer Gem Vendor' WHERE entry=362; /* icon_name: Scryer Gem Vendor */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Auction House' WHERE entry=367; /* icon_name: Silvermoon City, Auction House */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Auction House' WHERE entry=368; /* icon_name: Silvermoon City, Auction House */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Bank' WHERE entry=369; /* icon_name: Silvermoon City, Bank */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Bank' WHERE entry=370; /* icon_name: Silvermoon City, Bank */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Flight Master' WHERE entry=371; /* icon_name: Silvermoon City, Flight Master */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Guild House' WHERE entry=372; /* icon_name: Silvermoon City, Guild House */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Inn' WHERE entry=373; /* icon_name: Silvermoon City, Inn */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Inn' WHERE entry=374; /* icon_name: Silvermoon City, Inn */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Mailbox' WHERE entry=375; /* icon_name: Silvermoon City, Mailbox */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Stable Master' WHERE entry=376; /* icon_name: Silvermoon City, Stable Master */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Weapon Master' WHERE entry=377; /* icon_name: Silvermoon City, Weapon Master */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Battlemasters' WHERE entry=378; /* icon_name: Silvermoon City, Battlemasters */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Druid Trainer' WHERE entry=379; /* icon_name: Silvermoon City, Druid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Hunter Trainer' WHERE entry=380; /* icon_name: Silvermoon City, Hunter Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Mage Trainer' WHERE entry=381; /* icon_name: Silvermoon City, Mage Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Paladin Trainer' WHERE entry=382; /* icon_name: Silvermoon City, Paladin Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Priest Trainer' WHERE entry=383; /* icon_name: Silvermoon City, Priest Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Rogue Trainer' WHERE entry=384; /* icon_name: Silvermoon City, Rogue Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Warlock Trainers' WHERE entry=385; /* icon_name: Silvermoon City, Warlock Trainers */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Alchemy' WHERE entry=386; /* icon_name: Silvermoon City, Alchemy */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Blacksmithing' WHERE entry=387; /* icon_name: Silvermoon City, Blacksmithing */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Cooking' WHERE entry=388; /* icon_name: Silvermoon City, Cooking */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Enchanting' WHERE entry=389; /* icon_name: Silvermoon City, Enchanting */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Engineering' WHERE entry=390; /* icon_name: Silvermoon City, Engineering */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, First Aid' WHERE entry=391; /* icon_name: Silvermoon City, First Aid */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Fishing' WHERE entry=392; /* icon_name: Silvermoon City, Fishing */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Herbalism' WHERE entry=393; /* icon_name: Silvermoon City, Herbalism */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Jewelcrafting' WHERE entry=395; /* icon_name: Silvermoon City, Jewelcrafting */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Leatherworking' WHERE entry=396; /* icon_name: Silvermoon City, Leatherworking */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Mining' WHERE entry=397; /* icon_name: Silvermoon City, Mining */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Skinning' WHERE entry=398; /* icon_name: Silvermoon City, Skinning */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Tailoring' WHERE entry=399; /* icon_name: Silvermoon City, Tailoring */
UPDATE locales_points_of_interest SET icon_name_loc3='Silvermoon City, Mana Loom' WHERE entry=400; /* icon_name: Silvermoon City, Mana Loom */
UPDATE locales_points_of_interest SET icon_name_loc3='Falconwing Square, Innkeeper' WHERE entry=401; /* icon_name: Falconwing Square, Innkeeper */
UPDATE locales_points_of_interest SET icon_name_loc3='Falconwing Square, Stable Master' WHERE entry=402; /* icon_name: Falconwing Square, Stable Master */
UPDATE locales_points_of_interest SET icon_name_loc3='Falconwing Square, Hunter Trainer' WHERE entry=403; /* icon_name: Falconwing Square, Hunter Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Falconwing Square, Mage Trainer' WHERE entry=404; /* icon_name: Falconwing Square, Mage Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Falconwing Square, Priest Trainer' WHERE entry=406; /* icon_name: Falconwing Square, Priest Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Falconwing Square, Rogue Trainer' WHERE entry=407; /* icon_name: Falconwing Square, Rogue Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Falconwing Square, Warlock Trainer' WHERE entry=408; /* icon_name: Falconwing Square, Warlock Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Saltheril\'s Haven, Alchemist' WHERE entry=409; /* icon_name: Saltheril\'s Haven, Alchemist */
UPDATE locales_points_of_interest SET icon_name_loc3='Farstrider Retreat, Blacksmith' WHERE entry=410; /* icon_name: Farstrider Retreat, Blacksmith */
UPDATE locales_points_of_interest SET icon_name_loc3='Falconwing Square, Cook' WHERE entry=411; /* icon_name: Falconwing Square, Cook */
UPDATE locales_points_of_interest SET icon_name_loc3='Saltheril\'s Haven, Enchanter' WHERE entry=412; /* icon_name: Saltheril\'s Haven, Enchanter */
UPDATE locales_points_of_interest SET icon_name_loc3='Falconwing Square, First Aid Trainer' WHERE entry=413; /* icon_name: Falconwing Square, First Aid Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Saltheril\'s Haven, Herbalist' WHERE entry=414; /* icon_name: Saltheril\'s Haven, Herbalist */
UPDATE locales_points_of_interest SET icon_name_loc3='Falconwing Square, Jewelcrafter' WHERE entry=415; /* icon_name: Falconwing Square, Jewelcrafter */
UPDATE locales_points_of_interest SET icon_name_loc3='Eversong Woods, Leatherworker' WHERE entry=416; /* icon_name: Eversong Woods, Leatherworker */
UPDATE locales_points_of_interest SET icon_name_loc3='Eversong Woods, Skinner' WHERE entry=417; /* icon_name: Eversong Woods, Skinner */
UPDATE locales_points_of_interest SET icon_name_loc3='Darnassus Mage Trainer' WHERE entry=438; /* icon_name: Darnassus Mage Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Darnassus Paladin Trainer' WHERE entry=439; /* icon_name: Darnassus Paladin Trainer */
UPDATE locales_points_of_interest SET icon_name_loc3='Exodar, Battlemasters' WHERE entry=441; /* icon_name: Exodar, Battlemasters */
UPDATE locales_points_of_interest SET icon_name_loc3='Arena Battlemaster Exodar' WHERE entry=442; /* icon_name: Arena Battlemaster Exodar */

SET NAMES 'latin1';
