-- File generated by Mangos Online Translation Editor (MOTE) v2.10
SET NAMES 'utf8';
UPDATE `trans_words`SET `content_loc3`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text3_0 : entry=10734
UPDATE `trans_words`SET `content_loc3`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text5_0 : entry=10734
UPDATE `trans_words`SET `content_loc3`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text7_0 : entry=10734
UPDATE `trans_words`SET `content_loc3`='All I ever wanted to do was study.' WHERE `word_id`=197115; -- locales_npc_text - Text1_0 : entry=11458
UPDATE `trans_words`SET `content_loc3`='Weve located the mark, commander. Ya-six and i have been seperated. Requesting backup.' WHERE `word_id`=196931; -- locales_npc_text - Text0_1 : entry=20551
UPDATE `trans_words`SET `content_loc3`='Weve located the mark, commander. Ya-six and i have been seperated. Requesting backup.' WHERE `word_id`=196932; -- locales_npc_text - Text1_0 : entry=20551
UPDATE `trans_words`SET `content_loc3`='Arxes! Send help! Im pinned down in the mines, I...Im not sure where iam exactly but i had the presence of mind to drop tracers on the gro8und behind me' WHERE `word_id`=196933; -- locales_npc_text - Text1_1 : entry=20551
UPDATE `trans_words`SET `content_loc3`='Copy that, Araxes. Backup is on the way. Hold your position. I repeat, Hold your Position' WHERE `word_id`=196936; -- locales_npc_text - Text0_1 : entry=20564
UPDATE `trans_words`SET `content_loc3`='Copy that, Araxes. Backup is on the way. Hold your position. I repeat, Hold your Position' WHERE `word_id`=196937; -- locales_npc_text - Text1_0 : entry=20564

SET NAMES 'latin1';
