-- File generated by Mangos Online Translation Editor (MOTE) v0.10
SET NAMES 'utf8';
UPDATE creature_ai_texts SET content_loc6='Parece que esos idiotas de la Abadía nos han enviado carne fresca.' WHERE entry=-1; /* content: I see those fools at the Abbey sent some fresh meat for us. */
UPDATE creature_ai_texts SET content_loc6='La hermandad no tolerará tus actos.' WHERE entry=-2; /* content: The Brotherhood will not tolerate your actions. */
UPDATE creature_ai_texts SET content_loc6='Ah, una oportunidad para usar esta hoja recién afilada.' WHERE entry=-3; /* content: Ah, a chance to use this freshly sharpened blade. */
UPDATE creature_ai_texts SET content_loc6='¡Siente el poder de la hermandad!' WHERE entry=-4; /* content: Feel the power of the Brotherhood! */
UPDATE creature_ai_texts SET content_loc6='Más huesos para roer...' WHERE entry=-5; /* content: More bones to gnaw on... */
UPDATE creature_ai_texts SET content_loc6='Grrr... ¡Carne fresca!' WHERE entry=-6; /* content: Grrrr... fresh meat! */
UPDATE creature_ai_texts SET content_loc6='¡Tú no llevarte vela!' WHERE entry=-7; /* content: You no take candle! */
UPDATE creature_ai_texts SET content_loc6='¡Yujuuuuuu! ¡Yo correr!' WHERE entry=-8; /* content: Yiieeeee! Me run! */
UPDATE creature_ai_texts SET content_loc6='¡VanCleef paga mucho por vuestras cabezas!' WHERE entry=-22; /* content: VanCleef pay big for you heads! */
UPDATE creature_ai_texts SET content_loc6='¡Este no es sitio para ti! ¡Ancestros, alzaos contra los intrusos!' WHERE entry=-28; /* content: You do not belong here!  Ancients, rise against these intruders! */
UPDATE creature_ai_texts SET content_loc6='Partículas de sangre de %s se esparcen en el aire.' WHERE entry=-30; /* content: %s blood sprays into the air! */
UPDATE creature_ai_texts SET content_loc6='%s recibe salpicaduras de sangre y se pone radiante de felicidad.' WHERE entry=-31; /* content: %s is splashed by the blood and becomes irradiated! */
UPDATE creature_ai_texts SET content_loc6='¡Justicia eléctrica!' WHERE entry=-32; /* content: Electric justice! */
UPDATE creature_ai_texts SET content_loc6='¡Alerta! ¡Alerta! ¡Alerta intruso! ¡Alerta intruso!' WHERE entry=-33; /* content: Warning! Warning! Intruder alert! Intruder alert! */
UPDATE creature_ai_texts SET content_loc6='Es hora de unirte a nosotros, $c.' WHERE entry=-42; /* content: Time to join us, $c. */
UPDATE creature_ai_texts SET content_loc6='¡%s se enfurece!' WHERE entry=-46; /* content: %s becomes enraged! */
UPDATE creature_ai_texts SET content_loc6='¡%s intenta huir despavorida!' WHERE entry=-47; /* content: %s attempts to run away in fear! */
UPDATE creature_ai_texts SET content_loc6='Tan oscuro...' WHERE entry=-73; /* content: So dark... */
UPDATE creature_ai_texts SET content_loc6='¡Aaaaahhh! Casi consigue escapar.' WHERE entry=-74; /* content: Aaaaahhh! So close to escaping. */
UPDATE creature_ai_texts SET content_loc6='¡Nunca despertarás al soñador!' WHERE entry=-99; /* content: You will never wake the dreamer! */
UPDATE creature_ai_texts SET content_loc6='%s emite un grito agudo en señal de socorro.' WHERE entry=-100; /* content: %s lets out a high pitched screech, calling for help! */
UPDATE creature_ai_texts SET content_loc6='¡Por los Faucedraco!' WHERE entry=-101; /* content: For the Dragonmaw! */
UPDATE creature_ai_texts SET content_loc6='¡Larga vida a los Faucedraco! ¡Muere, insignificante $r!' WHERE entry=-102; /* content: Long live the Dragonmaw! Die you worthless $r! */
UPDATE creature_ai_texts SET content_loc6='Cerebros...' WHERE entry=-103; /* content: Brains... */
UPDATE creature_ai_texts SET content_loc6='¡Tus huesos se romperán bajo mi bota, $r!' WHERE entry=-105; /* content: Your bones will break under my boot, $r! */
UPDATE creature_ai_texts SET content_loc6='¡%s entra en frenesí!' WHERE entry=-106; /* content: %s goes into a frenzy! */
UPDATE creature_ai_texts SET content_loc6='Cachorros insolentes. ¡Yo os enseñaré a no entrometeros!' WHERE entry=-133; /* content: Troublesome whelps. I\'ll teach you to interfere! */
UPDATE creature_ai_texts SET content_loc6='¡Malditos extranjeros, pagaréis por invadir nuestras tierras!' WHERE entry=-135; /* content: You outsiders will pay for encroaching on our land! */
UPDATE creature_ai_texts SET content_loc6='¡Aah! ¡Mi poder es quien manda aquí!' WHERE entry=-136; /* content: Bah! My power rules here! */
UPDATE creature_ai_texts SET content_loc6='¡Resurgiré, mortales! ¡Incendius me hará resurgir de las cenizas!' WHERE entry=-137; /* content: I will be reborn, mortals! Incendius shall raise me from these ashes! */
UPDATE creature_ai_texts SET content_loc6='¡Los Defias vencerán! ¡Ningún aventurero enclenque nos detendrá!' WHERE entry=-143; /* content: The Defias shall succeed! No meek adventurer will stop us! */
UPDATE creature_ai_texts SET content_loc6='$gUn:Una; $r... viviente será pronto un muerto como yo.' WHERE entry=-161; /* content: A living $r... soon to be a dead like me. */
UPDATE creature_ai_texts SET content_loc6='Mmm... Adoro la deliciosa cerveza de Costasur.' WHERE entry=-162; /* content: Mmm... I love my delicious Southshore stout. */
UPDATE creature_ai_texts SET content_loc6='¡Acabad con ellos hermanos! ¡Por la Plaga!' WHERE entry=-163; /* content: Slay them, my brethren! For the Scourge! */
UPDATE creature_ai_texts SET content_loc6='¡Esclavizaremos a los jabaespines!' WHERE entry=-164; /* content: We will enslave the quilboar! */
UPDATE creature_ai_texts SET content_loc6='¡Nos extenderemos por esta tierra yerma!' WHERE entry=-165; /* content: We will spread across this barren land! */
UPDATE creature_ai_texts SET content_loc6='¡Pronto, la Plaga dominará el mundo!' WHERE entry=-166; /* content: Soon, the Scourge will rule the world! */
UPDATE creature_ai_texts SET content_loc6='¡¡¡Matar!!!' WHERE entry=-167; /* content: KILL!!! */
UPDATE creature_ai_texts SET content_loc6='¿Quién se atreve a molestarme? ¡Muere, $n!' WHERE entry=-168; /* content: Who dares disturb me?  Die $N! */
UPDATE creature_ai_texts SET content_loc6='¡Nadie osa desafiar a la Hermandad!' WHERE entry=-169; /* content: None may challenge the Brotherhood! */
UPDATE creature_ai_texts SET content_loc6='¡Y quédate ahí!' WHERE entry=-170; /* content: And stay down! */
UPDATE creature_ai_texts SET content_loc6='¡Perritos falderos, todos vosotros!' WHERE entry=-171; /* content: Lapdogs, all of you! */
UPDATE creature_ai_texts SET content_loc6='¡Ignorantes! ¡Nuestra causa es justa!' WHERE entry=-172; /* content: Fools! Our cause is righteous! */
UPDATE creature_ai_texts SET content_loc6='¡La Hermandad se impondrá!' WHERE entry=-173; /* content: The Brotherhood shall prevail! */
UPDATE creature_ai_texts SET content_loc6='¡Argh! ¡Me estáis haciendo enfadar!' WHERE entry=-176; /* content: D\'ah! Now you\'re making me angry! */
UPDATE creature_ai_texts SET content_loc6='¡Me voy a hacer una chaqueta con tu pellejo! ¿Los cigarrillos? Tendrás que pasar por encima de mi cadáver... eh... ¡¡¡¡RAWR!!!!' WHERE entry=-177; /* content: I\'m going to wear your skin as a smoking jacket! The stogies? You\'ll have to pry them from my cold dead... er... RAWR!!!! */
UPDATE creature_ai_texts SET content_loc6='¿¿¿¿Buscabas algo???? ¡Nunca serán tuyos!' WHERE entry=-178; /* content: Looking for these???? You\'ll never have em! */
UPDATE creature_ai_texts SET content_loc6='Confiesa y te dejaremos en libertad.' WHERE entry=-185; /* content: Confess and we shall set you free. */
UPDATE creature_ai_texts SET content_loc6='¡Los vivos están aquí!' WHERE entry=-186; /* content: The living are here! */
UPDATE creature_ai_texts SET content_loc6='$gUn:Una; trogg repugnante donde $glos:las; haya. ¡Muere!' WHERE entry=-188; /* content: A foul trogg if ever I saw one.  Die! */
UPDATE creature_ai_texts SET content_loc6='Esta enfermedad nubla mi vista, pero sé que tienes que ser un trogg. ¡Muere, $ginvasor apestoso:invasora apestosa;!' WHERE entry=-189; /* content: This sickness clouds my vision, but I know you must be a trogg.  Die foul invader! */
UPDATE creature_ai_texts SET content_loc6='Ningún gnomo se quedará atrás.' WHERE entry=-190; /* content: No gnome will be left behind. */
UPDATE creature_ai_texts SET content_loc6='Los troggs... no dejan de venir. ¡Muere, trogg! ¡Muere!' WHERE entry=-191; /* content: The troggs...they never stop coming.  Die trogg!  Die! */
UPDATE creature_ai_texts SET content_loc6='Puede hacer mucho calor en las Tierras Inhóspitas. Pero al menos es un calor seco.' WHERE entry=-192; /* content: It can get really hot here in the Badlands. But at least it\'s a dry heat. */
UPDATE creature_ai_texts SET content_loc6='Comprobando aparatitos... Comprobando chismes... Comprobando timbres...' WHERE entry=-193; /* content: Gizmos... check. Doothingies... check. Wizzers... check. */
UPDATE creature_ai_texts SET content_loc6='Un día seré un niño de verdad.' WHERE entry=-194; /* content: One day I\'ll be a real boy. */
UPDATE creature_ai_texts SET content_loc6='Brr... clic... fiuu...' WHERE entry=-195; /* content: Brzt... click... whir... */
UPDATE creature_ai_texts SET content_loc6='Esto es peligroso, maestro. Pero ayudaré a montar la guardia aquí.' WHERE entry=-196; /* content: It is dangerous here, master. But I shall help stand guard. */
UPDATE creature_ai_texts SET content_loc6='Podemos hacerlo mejor, con mayor fuerza y más rápido. Disponemos de la tecnología. Tenemos la magia.' WHERE entry=-197; /* content: We can make it better, stronger, faster. We have the technology. We have the magic. */
UPDATE creature_ai_texts SET content_loc6='¡No deberíais estar aquí! ¡Matadlos!' WHERE entry=-198; /* content: You should not be here! Slay them! */
UPDATE creature_ai_texts SET content_loc6='Serás presa fácil, $c.' WHERE entry=-200; /* content: You will be easy prey, $c. */
UPDATE creature_ai_texts SET content_loc6='Mis garras destrozarán tu raquítico cuerpo, $r.' WHERE entry=-201; /* content: My talons will shred your puny body, $r. */
UPDATE creature_ai_texts SET content_loc6='Tu cabeza será un excelente trofeo, $r.' WHERE entry=-202; /* content: A fine trophy your head will make, $r. */
UPDATE creature_ai_texts SET content_loc6='¡¡¡NO!!! ¡Saca de la cesta, mete en la cesta, siempre estamos igual!' WHERE entry=-203; /* content: NO!!!  It puts the tannin in the basket, or it gets the mallet again! */
UPDATE creature_ai_texts SET content_loc6='¡Pan recién horneado a la venta!' WHERE entry=-204; /* content: Fresh bread for sale! */
UPDATE creature_ai_texts SET content_loc6='¡Vendo pan recién horneado!' WHERE entry=-205; /* content: Freshly baked bread for sale! */
UPDATE creature_ai_texts SET content_loc6='Una ayuda para este pobre hombre...' WHERE entry=-207; /* content: Help a poor bloke out? */
UPDATE creature_ai_texts SET content_loc6='¡Te enviaré al más allá, $c!' WHERE entry=-210; /* content: I\'ll deliver you, weak $c, to the afterlife! */
UPDATE creature_ai_texts SET content_loc6='¡Muere en nombre de Edwin VanCleef!' WHERE entry=-211; /* content: Die in the name of Edwin van Cleef! */
UPDATE creature_ai_texts SET content_loc6='¡MACHACAR!' WHERE entry=-213; /* content: Crush! */
UPDATE creature_ai_texts SET content_loc6='¡MATAR!' WHERE entry=-214; /* content: KILL! */
UPDATE creature_ai_texts SET content_loc6='¡DESTRUIR!' WHERE entry=-215; /* content: Destroy! */
UPDATE creature_ai_texts SET content_loc6='¡Voy a convertirte en mojo!' WHERE entry=-228; /* content: I gonna make you into mojo! */
UPDATE creature_ai_texts SET content_loc6='Mataros será fácil.' WHERE entry=-229; /* content: Killing you be easy. */
UPDATE creature_ai_texts SET content_loc6='¡Pronto eh\'taréis mueh\'tos!' WHERE entry=-230; /* content: You be dead soon! */
UPDATE creature_ai_texts SET content_loc6='¡Te daré un tajo!' WHERE entry=-231; /* content: I\'ll cut you! */
UPDATE creature_ai_texts SET content_loc6='La hermandad no tolerará insectos.' WHERE entry=-232; /* content: The Brotherhood will not be hampered by insects. */
UPDATE creature_ai_texts SET content_loc6='Has mejorado algo desde la última vez. Pero todavía tiene una estructura ósea muy endeble. Cuando invoques uno de estos estarás en el buen camino.' WHERE entry=-311; /* content: This one is slightly better than the last. However, it still suffers from the same flimsy bone structure as the others. When you summon one of these, you are on the right path. */
UPDATE creature_ai_texts SET content_loc6='¡Que las arenas te consuman!' WHERE entry=-320; /* content: Sands consume you! */
UPDATE creature_ai_texts SET content_loc6='¡Es hora de machacar!' WHERE entry=-324; /* content: Time to bash! */
UPDATE creature_ai_texts SET content_loc6='¡%s emerge de un salto de las tinieblas!' WHERE entry=-341; /* content: %s jumps out of the shadows! */
UPDATE creature_ai_texts SET content_loc6='%s pide a más de sus aliados que salgan de las sombras.' WHERE entry=-342; /* content: %s calls more of his allies out of the shadows. */
UPDATE creature_ai_texts SET content_loc6='%s gruñe en dirección tuya, antes de olfatearte con calma.' WHERE entry=-343; /* content: %s growls in your direction before taking time to sniff you. */
UPDATE creature_ai_texts SET content_loc6='¡%s comienza a invocar refuerzos!' WHERE entry=-346; /* content: %s begins to summon in reinforcements! */
UPDATE creature_ai_texts SET content_loc6='¡Yo no huir de $c como tú!' WHERE entry=-353; /* content: Me no run from $c like you! */
UPDATE creature_ai_texts SET content_loc6='¡Yupi! ¡Yo matar!' WHERE entry=-354; /* content: Yip! Me kill! */
UPDATE creature_ai_texts SET content_loc6='¡$gEl único:La única; $r $gbueno:buena; es $gun:una; $r $gmuerto:muerta;!' WHERE entry=-355; /* content: The only good $r is a dead $r! */
UPDATE creature_ai_texts SET content_loc6='¡$C, mequetrefe! ¡No estás a la altura de la tribu de los Rompecantos!' WHERE entry=-356; /* content: Weak $c! You are no match for the Stonesplinter Tribe! */
UPDATE creature_ai_texts SET content_loc6='¡Siente el poder de los enanos Hierro Negro!' WHERE entry=-357; /* content: Feel the power of the Dark Iron Dwarves! */
UPDATE creature_ai_texts SET content_loc6='¡Os aplastaré!' WHERE entry=-359; /* content: I will crush you! */
UPDATE creature_ai_texts SET content_loc6='¡Yo machacar! ¡Tú morir!' WHERE entry=-360; /* content: Me smash! You die! */
UPDATE creature_ai_texts SET content_loc6='¡¡Raaar!! ¡Yo machacar a $r!' WHERE entry=-361; /* content: Raaar!!! Me smash $r! */
UPDATE creature_ai_texts SET content_loc6='¡El rey Magni Barbabronce es un tonto y un charlatán!' WHERE entry=-362; /* content: King Magni Bronzebeard is a fool and a charlatan! */
UPDATE creature_ai_texts SET content_loc6='¡Ji, ji, ji! ¡Os venís conmigo!' WHERE entry=-364; /* content: Wahehe! I\'m taking you down with me! */
UPDATE creature_ai_texts SET content_loc6='¡Me aburre tanta estupidez! ¡Prepárate para morir!' WHERE entry=-365; /* content: I tire of this nonsense! Prepare to die! */
UPDATE creature_ai_texts SET content_loc6='¿Eh? ¿Qué ej eso?' WHERE entry=-367; /* content: Huh? What dat? */
UPDATE creature_ai_texts SET content_loc6='¡$gEse:Esa; $r está pa comérselo!' WHERE entry=-368; /* content: Dat $r look gud to eat! */
UPDATE creature_ai_texts SET content_loc6='¡Al ataque!' WHERE entry=-369; /* content: Bash it! */
UPDATE creature_ai_texts SET content_loc6='¿$gUn:Una; $c $gllamado:llamada; $n? ¡Serás un suculento desayuno!' WHERE entry=-370; /* content: A $c called $N? You\'ll make a fine breakfast! */
UPDATE creature_ai_texts SET content_loc6='¡Muere en nombre de Ragnaros!' WHERE entry=-373; /* content: Die in the name of Ragnaros! */
UPDATE creature_ai_texts SET content_loc6='¡Los ojos de %s brillan como rubíes al tiempo que enciende la dinamita y empieza a reír malévolamente!' WHERE entry=-375; /* content: %s\'s eyes glow red as he lights his dynamite and begins to cackle madly! */
UPDATE creature_ai_texts SET content_loc6='%s parece mucho más tranquilo, ahora que se ha comido los restos de $n.' WHERE entry=-405; /* content: %s seems much calmer now that it has eaten the remains of $N. */
UPDATE creature_ai_texts SET content_loc6='No contraríes nunca a un Hierro Negro, $c.' WHERE entry=-406; /* content: Never cross a Dark Iron, $c. */
UPDATE creature_ai_texts SET content_loc6='¡Derramaré tu sangre, $c!' WHERE entry=-407; /* content: I shall spill your blood, $c! */
UPDATE creature_ai_texts SET content_loc6='¿Alguien necesita un descanso? ¡Mala suerte! ¡Al trabajo, patanes!' WHERE entry=-408; /* content: Anyone want to take a break?  Well too bad!  Get to work you oafs! */
UPDATE creature_ai_texts SET content_loc6='¡Llevar esas piezas hacia el barco!' WHERE entry=-409; /* content: Get those parts moving down to the ship! */
UPDATE creature_ai_texts SET content_loc6='Ummm, este más bien podría servir como carillón. Tomad nota, clase... Esto NO es lo que queréis invocar en el fragor de la batalla.' WHERE entry=-410; /* content: Hmmm, this one looks like something that would be better off as a windchime. Take notes class... This is NOT what you want to summon in the heat of battle. */
UPDATE creature_ai_texts SET content_loc6='Te prometo que el martes te pago lo que me des hoy para una hamburguesa.' WHERE entry=-411; /* content: I will gladly pay you Tuesday for a hamburger today. */
UPDATE creature_ai_texts SET content_loc6='Todo es culpa del maldito ejército de la Alianza... Tenían que construir sus torres justo detrás de mi granja.' WHERE entry=-413; /* content: It\'s all their fault, stupid Alliance army. Just had to build their towers right behind my farm. */
UPDATE creature_ai_texts SET content_loc6='Si el Capitán se entera, será mi fin.' WHERE entry=-414; /* content: If the Captain finds out, it\'ll be the end of me. */
UPDATE creature_ai_texts SET content_loc6='Alguien tuvo que ayudarles.' WHERE entry=-415; /* content: They must have had someone helping them. */
UPDATE creature_ai_texts SET content_loc6='De repente, estaban en todas partes.' WHERE entry=-416; /* content: All of a sudden they were everywhere. */
UPDATE creature_ai_texts SET content_loc6='Creo que estoy empezando a dejar surcos en las losas.' WHERE entry=-423; /* content: Think I\'m starting to wear a rut in the paving stones. */
UPDATE creature_ai_texts SET content_loc6='¡Ay, mi pobre y arrugado trasero! Yo soy la única que acarrea agua por aquí.' WHERE entry=-424; /* content: Jack and Jill my wrinkled patoot! I do all the water luggin\' \'round here. */
UPDATE creature_ai_texts SET content_loc6='Como si yo no tuviera cosas mejores que hacer a mi edad que llevar cubos de agua de un lado a otro.' WHERE entry=-427; /* content: As if I don\'t have better things to do in my old age than carry buckets of water. */
UPDATE creature_ai_texts SET content_loc6='¿Hemos llegado ya?' WHERE entry=-429; /* content: Are we there yet? */
UPDATE creature_ai_texts SET content_loc6='Me duelen los pies.' WHERE entry=-430; /* content: My feet hurt. */
UPDATE creature_ai_texts SET content_loc6='¿Por qué siempre vamos por el mismo camino?' WHERE entry=-432; /* content: Why do we always go the same way? */
UPDATE creature_ai_texts SET content_loc6='¿Adónde vamos?' WHERE entry=-433; /* content: Where we goin\'? */
UPDATE creature_ai_texts SET content_loc6='Quiero ver la Torre de los Magos.' WHERE entry=-434; /* content: I wanna see the Mage Tower. */
UPDATE creature_ai_texts SET content_loc6='Esto es un ejemplo de lo que no invocar. Mira, es frágil y delicado. Un buen golpe de maza y sus huesos se esparcirían hechos pedazos.' WHERE entry=-435; /* content: Now this is an example of what not to summon. Look, it\'s frail and brittle. One good whack from a mace will send bone shards flying. */
UPDATE creature_ai_texts SET content_loc6='¡Nos han traicionado!' WHERE entry=-438; /* content: We are betrayed! */
UPDATE creature_ai_texts SET content_loc6='%s suelta un grito agudo.' WHERE entry=-448; /* content: %s lets out a shrill cry. */
UPDATE creature_ai_texts SET content_loc6='¿Quién se cree $geste:esta; $r para jugar con el pasado? ¡Que la leyenda de Stalvan vaya a la tumba contigo!' WHERE entry=-449; /* content: Who is this mere $r that meddles with that which is past?  May the legend of Stalvan die along with you! */
UPDATE creature_ai_texts SET content_loc6='¡No remuevas asuntos del pasado, $n!' WHERE entry=-450; /* content: Toil not in matters of the past, $N! */
UPDATE creature_ai_texts SET content_loc6='¿Por qué no han venido los guardias de Ventormenta?' WHERE entry=-451; /* content: Why haven\'t the Stormwind guards come? */
UPDATE creature_ai_texts SET content_loc6='La luz parece habernos abandonado.' WHERE entry=-452; /* content: The light appears to have forsaken us. */
UPDATE creature_ai_texts SET content_loc6='Las noticias de Ventormenta no presagian nada bueno...' WHERE entry=-453; /* content: The news from Stormwind does not bode well. . . . */
UPDATE creature_ai_texts SET content_loc6='Nuestras eternas discusiones no nos llevarán a ninguna parte. Tenemos que actuar.' WHERE entry=-454; /* content: Constant bickering will get us nowhere.  We need to take action. */
UPDATE creature_ai_texts SET content_loc6='Me temo que algo tenebroso va a ocurrir.' WHERE entry=-456; /* content: I fear something dark is coming. */
UPDATE creature_ai_texts SET content_loc6='Nuestra causa es ignorada más allá de los gruesos muros de piedra de Ventormenta.' WHERE entry=-457; /* content: Our cause falls on deaf ears beyond the thick, stone walls of Stormwind. */
UPDATE creature_ai_texts SET content_loc6='La gente de Villa Oscura espera más del Consejo. No podemos dejar que padezcan esta Peste nefasta que nos asola.' WHERE entry=-458; /* content: The people of Darkshire expect more from the Council.  We cannot let them suffer from this unholy wrath which plagues us. */
UPDATE creature_ai_texts SET content_loc6='Los no-muertos se arrastran por toda esta tierra. ¿Dónde está el ejército de Ventormenta?' WHERE entry=-459; /* content: Undead are crawling all over the land.  Where is the Stormwind Army? */
UPDATE creature_ai_texts SET content_loc6='Un momento... tú no eres mi marido. Pero seguro que te ha enviado. Y tú... ¡estás para comerte!' WHERE entry=-460; /* content: Wait...you are not my husband.  But he must have sent you.  And you...look..delicious! */
UPDATE creature_ai_texts SET content_loc6='¿Aber? ¿Eres tú...? Oh... ¡qué hambre tengo, Aber! ¡¡TENGO MUCHA HAMBRE!!' WHERE entry=-461; /* content: Aber?  Is that you...?  Oh...I\'m so hungry, Aber!  SO HUNGRY!! */
UPDATE creature_ai_texts SET content_loc6='El Consejo del Bosque del Ocaso debe tomar medidas. El mal flota en el aire.' WHERE entry=-462; /* content: The Council of Duskwood must take action.  Evil lingers in the air. */
UPDATE creature_ai_texts SET content_loc6='Nunca detendrás a los Renegados, $r. La Dama Oscura te hará sufrir.' WHERE entry=-469; /* content: You will never stop the Forsaken, $r. The Dark Lady shall make you suffer. */
UPDATE creature_ai_texts SET content_loc6='¡Tienes mi palabra de que daré un uso a tu cadáver después de que te mate, $r!' WHERE entry=-470; /* content: You have my word that I shall find a use for your body after I\'ve killed you, $r. */
UPDATE creature_ai_texts SET content_loc6='%s comienza a resquebrajarse y a partirse en dos...' WHERE entry=-471; /* content: %s begins to crack and break apart. */
UPDATE creature_ai_texts SET content_loc6='La fuerza de %s mengua mientras la roca empieza a partirse.' WHERE entry=-472; /* content: %s\'s strength dwindles as chunks of rock break off. */
UPDATE creature_ai_texts SET content_loc6='%s se reduce a escombros, pero continúa luchando.' WHERE entry=-473; /* content: %s is reduced to rubble, but still continues to fight. */
UPDATE creature_ai_texts SET content_loc6='La espalda me está matando.' WHERE entry=-490; /* content: My back is killing me. */
UPDATE creature_ai_texts SET content_loc6='Si cayera, coge mi bolsa y asegúrate de que llega a manos de la Alta General.' WHERE entry=-491; /* content: If I should fall, take my pouch. Make certain that it gets to the High General. */
UPDATE creature_ai_texts SET content_loc6='Siento que se acerca el peligro.' WHERE entry=-492; /* content: I sense danger up ahead. */
UPDATE creature_ai_texts SET content_loc6='Mis garras destrozarán tu raquítico cuerpo, $r.' WHERE entry=-494; /* content: My talons will shred your puny body, $r. */
UPDATE creature_ai_texts SET content_loc6='¿Supongo que traes buenas noticias?' WHERE entry=-502; /* content: I presume you come with good news? */
UPDATE creature_ai_texts SET content_loc6='Todo va según lo planeado, Lord Falconcrest. Te aseguro que solo es cuestión de tiempo.' WHERE entry=-503; /* content: Things are going as planned, Lord Falconcrest. I assure you, it is only a matter of time. */
UPDATE creature_ai_texts SET content_loc6='%s comienza a invocar a un tejedor de tinieblas Puño Negro.' WHERE entry=-523; /* content: %s begins to summon in a Blackhand Dreadweaver! */
UPDATE creature_ai_texts SET content_loc6='%s comienza a invocar a un veterano Puño Negro.' WHERE entry=-524; /* content: %s begins to summon in a Blackhand Veteran! */
UPDATE creature_ai_texts SET content_loc6='%s invoca a un tejedor de tinieblas Puño Negro para que le ayude.' WHERE entry=-525; /* content: %s summons a Blackhand Dreadweaver to his aid! */
UPDATE creature_ai_texts SET content_loc6='%s invoca a un veterano Puño Negro para que le ayude.' WHERE entry=-526; /* content: %s summons a Blackhand Veteran to his aid! */
UPDATE creature_ai_texts SET content_loc6='¡El Magno os machacará!' WHERE entry=-527; /* content: The Great One will smash you! */
UPDATE creature_ai_texts SET content_loc6='¡Muere! ¡No vas a liberar a Myzrael!' WHERE entry=-528; /* content: Die!  You will not free Myzrael! */
UPDATE creature_ai_texts SET content_loc6='Manteneos firmes, hermanos. ¡Y no os preocupéis! ¡El tamaño nos favorece!' WHERE entry=-529; /* content: Stand firm, brothers.  And don\'t worry!  Size is on our side! */
UPDATE creature_ai_texts SET content_loc6='¡No! ¡Dejadnos! ¡No podemos fracasar en nuestra tarea!' WHERE entry=-530; /* content: No!  Leave us!  We must not fail our task! */
UPDATE creature_ai_texts SET content_loc6='¡Toma! ¡Los Mostacho Seco vencerán!' WHERE entry=-531; /* content: Take that!  The Drywhiskers will prevail! */
UPDATE creature_ai_texts SET content_loc6='¡Basta! $C idiota, no dejaremos que invoques a la criatura Myzrael!' WHERE entry=-532; /* content: Stop!  Foolish $c, we cannot let you summon the creature Myzrael! */
UPDATE creature_ai_texts SET content_loc6='Escaneando formas de vida... objetivo no encontrado.' WHERE entry=-545; /* content: Scanning life forms....target not found */
UPDATE creature_ai_texts SET content_loc6='Objetivo perdido... retomando patrones de búsqueda Delta.' WHERE entry=-546; /* content: Target lost....resuming search patterns Delta */
UPDATE creature_ai_texts SET content_loc6='Detectadas formas de vida desconocidas... evaluando...' WHERE entry=-547; /* content: Unknown life forms detected....assessing... */
UPDATE creature_ai_texts SET content_loc6='¡Guardias!' WHERE entry=-549; /* content: Guards! */
UPDATE creature_ai_texts SET content_loc6='¡%s monta en cólera tras ver a su amigo caer en batalla!' WHERE entry=-550; /* content: %s goes into a rage after seeing a friend fall in battle! */
UPDATE creature_ai_texts SET content_loc6='¡%s pide ayuda!' WHERE entry=-551; /* content: %s calls for help! */
UPDATE creature_ai_texts SET content_loc6='¿Quién osa perturbar la santidad de Eldre\'Thalas? ¡Enfrentaos a mí, cobardes!' WHERE entry=-553; /* content: Who dares disrupt the sanctity of Eldre\'Thalas? Face me, cowards! */
UPDATE creature_ai_texts SET content_loc6='Al fin mi alma podrá descansar... Oh, mi amado Cerellean...' WHERE entry=-554; /* content: Finally, my soul may rest... Oh, dearest Cerellean... */
UPDATE creature_ai_texts SET content_loc6='¡Por las barbas de Thaurissan! ¡Matadlos!' WHERE entry=-576; /* content: By Thaurissan\'s beard! Slay them! */
UPDATE creature_ai_texts SET content_loc6='¡Yo Grimlok, rey!' WHERE entry=-577; /* content: Me Grimlok, king! */
UPDATE creature_ai_texts SET content_loc6='¡Muere! ¡Muere!' WHERE entry=-578; /* content: Die! Die! */
UPDATE creature_ai_texts SET content_loc6='¡MORID, MORTALES!' WHERE entry=-580; /* content: DIE, MORTALS! */
UPDATE creature_ai_texts SET content_loc6='Bijou sabe dónde están los tesoros.' WHERE entry=-582; /* content: Bijou knows where treasures are hidden. */
UPDATE creature_ai_texts SET content_loc6='¡¡¡KRUAAAAC!!! *tose* *tose* ¡Tengo que dejar de fumar!' WHERE entry=-583; /* content: SQUAWK!! *cough* *cough* I need to quit smoking! */
UPDATE creature_ai_texts SET content_loc6='¡Pregunta a Kibler acerca del tesoro! ¡KRUAAAAC!' WHERE entry=-584; /* content: Ask Kibler about the treasure! SQUAWK! */
UPDATE creature_ai_texts SET content_loc6='Opus quiere un poco de Oro Cuergo... con gusano.' WHERE entry=-586; /* content: Opus wants some Cuergo\'s Gold... with worm. */
UPDATE creature_ai_texts SET content_loc6='Kibler está siendo investigado por G.E.T.A.' WHERE entry=-587; /* content: Kibler is being investigated by G.E.T.A. */
UPDATE creature_ai_texts SET content_loc6='¡%s deja salir un gruñido profundo que alerta a los aliados cercanos y se enfurece!' WHERE entry=-648; /* content: %s lets out a deep roar, alerting nearby allies and becoming enraged! */
UPDATE creature_ai_texts SET content_loc6='%s entra en un frenesí alcohólico.' WHERE entry=-649; /* content: %s goes into a drunken rage! */
UPDATE creature_ai_texts SET content_loc6='Cuando me topé con las piedras de Suntara en la excavación de Limugre, el poder de Ragnaros me poseyó. Fue Ragnaros quien me dio un propósito.' WHERE entry=-660; /* content: When I stumbled upon the Suntara stones at the Grimesilt Digsite, the power of Ragnaros surged through my being. It was Ragnaros that gave me a purpose. */
UPDATE creature_ai_texts SET content_loc6='Gracias a la voluntad de Ragnaros construimos a Obsidion. Obsidion destruirá a los orcos Roca Negra de la cumbre de Roca Negra, uniéndonos con nuestros hermanos en las profundidades ardientes.' WHERE entry=-661; /* content: It was the will of Ragnaros that Obsidion be built. Obsidion will destroy the Blackrock orcs of Blackrock Spire, uniting us with our bretheren in the fiery depths. */
UPDATE creature_ai_texts SET content_loc6='Y finalmente, fue Ragnaros quien me nombró cuando renací como acólito de fuego: Lathoric... Lathoric el Negro.' WHERE entry=-662; /* content: And ultimately, it was Ragnaros that named me when I was reborn as an acolyte of fire: Lathoric... Lathoric the Black. */
UPDATE creature_ai_texts SET content_loc6='Has terminado tu tarea. ¡Prepárate para morir!' WHERE entry=-664; /* content: Your task is complete. Prepare to meet your doom. */
UPDATE creature_ai_texts SET content_loc6='Escuchad con atención, porque el señor de Roca Negra os destruirá si no estáis preparados.' WHERE entry=-667; /* content: Listen carefully, for the lord of Blackrock will surely destroy you, should you not be prepared. */
UPDATE creature_ai_texts SET content_loc6='%s se astilla.' WHERE entry=-694; /* content: %s chips and splinters! */
UPDATE creature_ai_texts SET content_loc6='¡Nadie puede robar los secretos de los Creadores!' WHERE entry=-695; /* content: None may steal the secrets of the Makers! */
UPDATE creature_ai_texts SET content_loc6='¡Que las arenas del desierto se eleven y apaguen la luz del sol!' WHERE entry=-698; /* content: Sands of the desert, rise and block out the sun! */
UPDATE creature_ai_texts SET content_loc6='Estáis acabados.' WHERE entry=-699; /* content: You are terminated. */
UPDATE creature_ai_texts SET content_loc6='%s ruega para que lo liberen de tanto sufrimiento.' WHERE entry=-704; /* content: %s begs to be put out of his misery. */
UPDATE creature_ai_texts SET content_loc6='%s gruñe.' WHERE entry=-705; /* content: %s groans. */
UPDATE creature_ai_texts SET content_loc6='%s llora lastimosamente.' WHERE entry=-706; /* content: %s weeps pitifully. */
UPDATE creature_ai_texts SET content_loc6='Ha llegado el almuerzo, mis bellos niños. ¡Hacedlos añicos!' WHERE entry=-710; /* content: Lunch has arrived, my beautiful children. Tear them to pieces! */
UPDATE creature_ai_texts SET content_loc6='¡Álzate y defiende a tu maestro!' WHERE entry=-711; /* content: Rise and defend your master! */
UPDATE creature_ai_texts SET content_loc6='Los hijos de Sul protegerán a su maestro. ¡Álzate otra vez, Sul\'lithuz!' WHERE entry=-712; /* content: The children of Sul will protect their master. Rise once more Sul\'lithuz! */
UPDATE creature_ai_texts SET content_loc6='¡Ilifar, tu maestro te llama!' WHERE entry=-713; /* content: Ilifar, your master calls! */
UPDATE creature_ai_texts SET content_loc6='¡Que las llamas del caos te devoren!' WHERE entry=-714; /* content: Let the flames of chaos engulf you! */
UPDATE creature_ai_texts SET content_loc6='¡Enfrentaos a mi campeón, mortales!' WHERE entry=-715; /* content: Face my champion, mortals! */
UPDATE creature_ai_texts SET content_loc6='Preparaos por una eternidad de angustia y tortura... la venganza será mía...' WHERE entry=-716; /* content: Prepare yourselves for an eternity of anguish and torture - vengeance shall be mine... */
UPDATE creature_ai_texts SET content_loc6='¡ABANDONA ESTE LUGAR!' WHERE entry=-764; /* content: Leave this place! */
UPDATE creature_ai_texts SET content_loc6='%s coge su mazo y empieza a balancearlo salvajemente.' WHERE entry=-797; /* content: %s puts his club away and begins swinging wildly! */
UPDATE creature_ai_texts SET content_loc6='¡%s comienza a responder a todos los ataques!' WHERE entry=-807; /* content: %s begins to retaliate all attacks against him! */
UPDATE creature_ai_texts SET content_loc6='¡Nadie pasar por mí y amenazar $gal rey:a la reina;! ¡Agh, toma!' WHERE entry=-808; /* content: No one get past me and threaten da king!  Ungh, take it!! */
UPDATE creature_ai_texts SET content_loc6='¡Ayúdame a aplastar a estos impresentables!' WHERE entry=-809; /* content: Help me crush these punys! */
UPDATE creature_ai_texts SET content_loc6='¡Marchaos! ¡No despertéis al soñador!' WHERE entry=-819; /* content: Turn back! Do not wake the dreamer! */
UPDATE creature_ai_texts SET content_loc6='¡Ahí viene el Cazador de Almas!' WHERE entry=-822; /* content: The Soulflayer comes! */
UPDATE creature_ai_texts SET content_loc6='¡Uníos a nosotros!' WHERE entry=-823; /* content: Join us! */
UPDATE creature_ai_texts SET content_loc6='¡Hakkar volverá a la vida!' WHERE entry=-824; /* content: Hakkar shall live again! */
UPDATE creature_ai_texts SET content_loc6='¡No podemos permitir que el mal entre en este mundo! ¡Venid, hijos míos!' WHERE entry=-825; /* content: This evil cannot be allowed to enter this world!  Come my children! */
UPDATE creature_ai_texts SET content_loc6='¡Eres un mosquitajo para los Maderiza! ¡Muere!' WHERE entry=-826; /* content: You are a little gnat to the Foulweald!  Die! */
UPDATE creature_ai_texts SET content_loc6='¡No! ¡No puedes ser más fuerte que los Maderiza! ¡¡No!!' WHERE entry=-827; /* content: No!  You cannot be stronger than the Foulweald!  No!! */
UPDATE creature_ai_texts SET content_loc6='¡%s carga!' WHERE entry=-829; /* content: %s charges! */
UPDATE creature_ai_texts SET content_loc6='¡Apuesto a que hay más agentes de la Hermandad! ¡Nunca recuperaréis Alterac... o Costasur!' WHERE entry=-924; /* content: More agents of the Syndicate I\'ll wager! You\'ll never take back Alterac... Or Southshore! */
UPDATE creature_ai_texts SET content_loc6='Este huerto está ahora tan yermo y triste como mi caparazón en descomposición. En otros tiempos, estos árboles estaban cargados de frutos, pero ahora solo hay podredumbre.' WHERE entry=-925; /* content: This orchard is now as barren and lifeless as my rotting shell. Once these trees bloomed with fruit but now there is only rot. */
UPDATE creature_ai_texts SET content_loc6='Dediqué toda mi vida a cuidar de estos árboles. Podándolos y cuidándolos... preparándolos para que me hiciesen compañía en mi muerte.' WHERE entry=-926; /* content: I spent my whole life caring for these trees. Pruning and nurturing them... only fitting that they have joined me in death. */
UPDATE creature_ai_texts SET content_loc6='¡Intrusos! ¡Atacad a los intrusos!' WHERE entry=-927; /* content: Intruders! Attack the intruders! */
UPDATE creature_ai_texts SET content_loc6='¡Costasur lo pagará con sangre!' WHERE entry=-928; /* content: Southshore shall pay in blood! */
UPDATE creature_ai_texts SET content_loc6='¡Estoy en pie otra vez!' WHERE entry=-929; /* content: I have risen! */
UPDATE creature_ai_texts SET content_loc6='¡La venganza será mía al fin!' WHERE entry=-930; /* content: Revenge shall be mine at last! */
UPDATE creature_ai_texts SET content_loc6='Los no-muertos se darán un festín con tu alma, $n.' WHERE entry=-931; /* content: The undead shall feast on your soul, $N. */
UPDATE creature_ai_texts SET content_loc6='¡Socorro! ¡Socorro! ¡Hay asesinos en las colinas! ¡Coged las armas! ¡Coged las armas!' WHERE entry=-932; /* content: Help me! Help! Assassins in the hills! To arms! To arms! */
UPDATE creature_ai_texts SET content_loc6='¡Guardias, a vuestros puestos! Seguro que otra vez vienen a por el magistrado. ¡Hay que protegerlo! ¡Podrían venir desde cualquier dirección!' WHERE entry=-933; /* content: Guards to your posts! They must be after the Magistrate again. He must be protected! They could come from any direction! */
UPDATE creature_ai_texts SET content_loc6='Asesinos... salvad al... Magistraaa...' WHERE entry=-935; /* content: Assassins... save... th... Magistraaa... */
UPDATE creature_ai_texts SET content_loc6='¡Ladrones! ¡Pillos! ¡Tunantes! ¡Venid, devolvedme mis almohadas gigantescas!' WHERE entry=-974; /* content: Thieves! Scallywags! Rapscallions! Come face me gigantic pillas! */
UPDATE creature_ai_texts SET content_loc6='¿Hay alguien ahí? Tirion, viejo amigo, ¿eres tú? ¿Has venido a salvarnos?' WHERE entry=-982; /* content: Is someone there? Tirion my old friend, is that you? Have you come to save us? */
UPDATE creature_ai_texts SET content_loc6='¡Cómo te atreves! ¡Ahora enfréntate a mi ira!' WHERE entry=-983; /* content: You dare! Now feel my wrath! */
UPDATE creature_ai_texts SET content_loc6='¡¿Quién se atreve a..?! ¡Te destruiré!' WHERE entry=-984; /* content: Who dares?! I will destroy you! */
UPDATE creature_ai_texts SET content_loc6='¡Mamaíta!' WHERE entry=-990; /* content: Mommy! */
UPDATE creature_ai_texts SET content_loc6='¡Edición limitada! Rana crujiente solo aquí, en la Feria de la Luna Negra.' WHERE entry=-1027; /* content: For a limited time only, Crunchy Frog available exclusively here at the Darkmoon Faire. */
UPDATE creature_ai_texts SET content_loc6='¡La Cruzada Escarlata azotará al perverso y expulsará al demonio de estas tierras!' WHERE entry=-1028; /* content: The Scarlet Crusade shall smite the wicked and drive evil from these lands! */
UPDATE creature_ai_texts SET content_loc6='Tú llevas la peste de la Plaga. Prepárate para entrar en El Vacío Abisal.' WHERE entry=-1029; /* content: You carry the taint of the scourge.  Prepare to enter the twisting nether. */
UPDATE creature_ai_texts SET content_loc6='¡Se acabarán las atrocidades de los no-muertos!' WHERE entry=-1031; /* content: These undead atrocities will be destroyed! */
UPDATE creature_ai_texts SET content_loc6='¡Hay que limpiar estas tierras!' WHERE entry=-1032; /* content: These lands shall be cleansed! */
UPDATE creature_ai_texts SET content_loc6='¡El desierto es mío!' WHERE entry=-1035; /* content: This desert be mine! */
UPDATE creature_ai_texts SET content_loc6='¡El reino de Furiarena es invencible!' WHERE entry=-1036; /* content: The Sandfury reign supreme! */
UPDATE creature_ai_texts SET content_loc6='¡Siente la furia de las arenas!' WHERE entry=-1037; /* content: Feel the fury of the sands! */
UPDATE creature_ai_texts SET content_loc6='¡Muere, forastero!' WHERE entry=-1038; /* content: Die, outlander! */
UPDATE creature_ai_texts SET content_loc6='¡Que comiencen las ejecuciones!' WHERE entry=-1039; /* content: Let the executions begin! */
UPDATE creature_ai_texts SET content_loc6='¡Se ha hecho justicia!' WHERE entry=-1040; /* content: Justice is done! */
UPDATE creature_ai_texts SET content_loc6='¡Decid al celador que esta prisión es nuestra ahora!' WHERE entry=-1041; /* content: Tell the Warden this prison is ours now! */
UPDATE creature_ai_texts SET content_loc6='¡Aplastaré vuestros cráneos con mi bota!' WHERE entry=-1042; /* content: I\'ll crush your skull beneath my boot! */
UPDATE creature_ai_texts SET content_loc6='¡Muerte a los hombres del celador!' WHERE entry=-1043; /* content: Death to the Warden\'s men! */
UPDATE creature_ai_texts SET content_loc6='¡Carne fresca!' WHERE entry=-1044; /* content: Fresh meat! */
UPDATE creature_ai_texts SET content_loc6='¡Más chicos de los recados del celador!' WHERE entry=-1045; /* content: More of the Warden\'s errand boys! */
UPDATE creature_ai_texts SET content_loc6='¡Cómo osas entrar en mi sagrario!' WHERE entry=-1047; /* content: How dare you enter my sanctum! */
UPDATE creature_ai_texts SET content_loc6='%s se derrumba pero el arruinado cuerpo vuelve a alzarse.' WHERE entry=-1054; /* content: %s collapses but the broken body rises again! */
UPDATE creature_ai_texts SET content_loc6='¡El correo no se toca!' WHERE entry=-1055; /* content: No tampering with the mail! */
UPDATE creature_ai_texts SET content_loc6='¡Ese es nuestro tesoro, pelele!' WHERE entry=-1056; /* content: That\'s our treasure, you lubber! */
UPDATE creature_ai_texts SET content_loc6='¡Eh! ¡Apártate de nuestro tesoro!' WHERE entry=-1057; /* content: Hey!  Get away from our treasure! */
UPDATE creature_ai_texts SET content_loc6='¡Mata a $n!' WHERE entry=-1119; /* content: Kill $N! */
UPDATE creature_ai_texts SET content_loc6='¡Por Kalimdor!' WHERE entry=-1133; /* content: For Kalimdor! */
UPDATE creature_ai_texts SET content_loc6='¡Nadie puede medirse con los Señores Serpiente!' WHERE entry=-1135; /* content: None can stand against the serpent lords! */
UPDATE creature_ai_texts SET content_loc6='Ven, $n. Mira lo que trae la Pesadilla...' WHERE entry=-1139; /* content: Come, $n. See what the Nightmare brings... */
UPDATE creature_ai_texts SET content_loc6='¡Nadie podrá detener a la Pesadilla!' WHERE entry=-1140; /* content: The Nightmare cannot be stopped! */
UPDATE creature_ai_texts SET content_loc6='%s pone fin al último resquicio de vida de $n y se traga su alma.' WHERE entry=-1141; /* content: %s squeezes the last bit of life out of $n and swallows their soul. */
UPDATE creature_ai_texts SET content_loc6='Os lo habéis buscado.' WHERE entry=-1148; /* content: You asked for it. */
UPDATE creature_ai_texts SET content_loc6='¡Siente el acero, chucho!' WHERE entry=-1156; /* content: Taste blade, mongrel! */
UPDATE creature_ai_texts SET content_loc6='Como si no tuviéramos bastantes problemas, ¡vas tú y creas más!' WHERE entry=-1158; /* content: As if we don\'t have enough problems, you go and create more! */
UPDATE creature_ai_texts SET content_loc6='¿Eso es lo mejor que sabes hacer?' WHERE entry=-1159; /* content: Is that the best you can do? */
UPDATE creature_ai_texts SET content_loc6='¡El emperador Thaurissan no desea ser perturbado! ¡Regresad ahora o enfrentaos a vuestro fin, débiles mortales!' WHERE entry=-1194; /* content: Emperor Thaurissan does not wish to be disturbed! Turn back now or face your doom, weak mortals! */
UPDATE creature_ai_texts SET content_loc6='¡Prepárate para recibir un machaque de Gassol!' WHERE entry=-1195; /* content: Prepare to be Malowned! */
UPDATE creature_ai_texts SET content_loc6='¡TIMMY!' WHERE entry=-1197; /* content: TIMMY! */
UPDATE creature_ai_texts SET content_loc6='¡Cuéntamelo... cuéntamelo todo!' WHERE entry=-1198; /* content: Tell me... tell me everything! */
UPDATE creature_ai_texts SET content_loc6='¡Sucios secretos!' WHERE entry=-1199; /* content: Naughty secrets! */
UPDATE creature_ai_texts SET content_loc6='¡Te arrancaré los secretos de la carne!' WHERE entry=-1200; /* content: I\'ll rip the secrets from your flesh! */
UPDATE creature_ai_texts SET content_loc6='¡Que el dolor te purgue!' WHERE entry=-1201; /* content: Purged by pain! */
UPDATE creature_ai_texts SET content_loc6='Ansiamos vengarnos.' WHERE entry=-1202; /* content: We hunger for vengeance. */
UPDATE creature_ai_texts SET content_loc6='¡Soltad a los sabuesos!' WHERE entry=-1205; /* content: Release the hounds! */
UPDATE creature_ai_texts SET content_loc6='FUISTE MUY DIVERTIDO LA ÚLTIMA VEZ... ¡SAL!' WHERE entry=-1212; /* content: YOU WERE SUCH GOOD SPORT THE LAST TIME...COME OUT! */
UPDATE creature_ai_texts SET content_loc6='¡A mí, mis vasallos!' WHERE entry=-1222; /* content: To me, my servants! */
UPDATE creature_ai_texts SET content_loc6='¡Yo soy la mano del Rey Exánime!' WHERE entry=-1224; /* content: I am the hand of the Lich King! */
UPDATE creature_ai_texts SET content_loc6='¡Oh, ahora vas y me enfadas! ¡Es hora de ver la verdadera fuerza de la Roca de las Mareas!' WHERE entry=-1226; /* content: Oh now you\'ve gone and angered me! Time to see the true force of the Stone of Tides! */
UPDATE creature_ai_texts SET content_loc6='El poder de la Luz es grandioso y misericordioso.' WHERE entry=-1296; /* content: The power of the light is truly great and merciful. */
UPDATE creature_ai_texts SET content_loc6='Podremos volver a estar juntos, amor mío...' WHERE entry=-1297; /* content: We shall be reunited once more, my love... */
UPDATE creature_ai_texts SET content_loc6='$gForastero:forastera;, encuentra al príncipe caído, Menethil, y pon fin a su reinado de terror.' WHERE entry=-1299; /* content: Stranger, find the fallen Prince Menethil and end his reign of terror. */
UPDATE creature_ai_texts SET content_loc6='Si consigo sobrevivir, la única ambición de mi vida será destruir a Arthas...' WHERE entry=-1300; /* content: Should I live through this, I shall make it my life\'s sole ambition to destroy Arthas... */
UPDATE creature_ai_texts SET content_loc6='No lo conseguiré... Vete... Sigue sin mí...' WHERE entry=-1301; /* content: I won\'t make it... go... go on without me... */
UPDATE creature_ai_texts SET content_loc6='¡Que la muerte me lleve! No puedo seguir adelante. Ya no me queda nada...' WHERE entry=-1302; /* content: Death take me! I cannot go on! I have nothing left... */
UPDATE creature_ai_texts SET content_loc6='La luz condena a todo aquel que alberga el mal. ¡Ahora morirás!' WHERE entry=-1305; /* content: The light condemns all who harbor evil.  Now you will die! */
UPDATE creature_ai_texts SET content_loc6='Tú llevas la peste de la Plaga. Prepárate para entrar en El Vacío Abisal.' WHERE entry=-1306; /* content: You carry the taint of the scourge.  Prepare to enter the twisting nether. */
UPDATE creature_ai_texts SET content_loc6='No tienes escapatoria. La Cruzada destruirá a todo aquel que lleve la peste de la Plaga.' WHERE entry=-1307; /* content: There is no escape for you.  The Crusade shall destroy all who carry the scourge\'s taint. */
UPDATE creature_ai_texts SET content_loc6='¡La Cruzada Escarlata azotará al perverso y expulsará al demonio de estas tierras!' WHERE entry=-1308; /* content: The Scarlet Crusade shall smite the wicked and drive evil from these lands! */
UPDATE creature_ai_texts SET content_loc6='¡$gBienvenido:Bienvenida; al país de los sabores!' WHERE entry=-1310; /* content: Welcome to flavor country! */
UPDATE creature_ai_texts SET content_loc6='No puedo creer que papá no me deje conservar a tu hermana.' WHERE entry=-1312; /* content: I can\'t believe dad won\'t let me keep your sister. */
UPDATE creature_ai_texts SET content_loc6='¿Alguien puede darle un hogar a mi adorable gatito?' WHERE entry=-1313; /* content: Can anyone give my adorable, extra little kitty a home? */
UPDATE creature_ai_texts SET content_loc6='¿Pero qué quiere decir "alérgico"? ¿Y qué tiene que ver eso con mis gatitos?' WHERE entry=-1314; /* content: What does allergic mean anyway? And what does it have to do with either of my kitties? */
UPDATE creature_ai_texts SET content_loc6='¿Alguien podría proporcionar un buen hogar a mi gatito?' WHERE entry=-1315; /* content: Will someone please give my little kitten a good home? */
UPDATE creature_ai_texts SET content_loc6='No te preocupes, te encontraré un buen hogar.' WHERE entry=-1316; /* content: Don\'t worry, I\'ll find a good home for ya. */
UPDATE creature_ai_texts SET content_loc6='%s se divide en otros dos Príncipes de Lava.' WHERE entry=-1320; /* content: %s splits into two new Lava Spawns! */
UPDATE creature_ai_texts SET content_loc6='Si estás aquí, significa que ya puedes empezar a estudiar la invocación de cohortes demoníacas para hacer lo que te plazca. Empezaremos por las criaturas más humildes que podrás invocar y continuaremos a partir de ahí. Comencemos.' WHERE entry=-1411; /* content: If you\'re here, then it means you are prepared to begin the study of summoning demonic cohorts to do your bidding. We will start with the lowliest creatures you will be able to call and continue from there. Let us begin. */
UPDATE creature_ai_texts SET content_loc6='La criatura más fácil de invocar para ti es el diablillo. A estas alturas, ya deberías ser capaz de crear al esbirro, pero por razones de complejidad, empezaré por él.' WHERE entry=-1412; /* content: The easiest creature for you to summon is the imp. You should already be able to bring forth this minion but for completeness\' sake I will start with him. */
UPDATE creature_ai_texts SET content_loc6='Esta pequeña bestia hedionda es el diablillo. Es pequeño y débil, lo que lo convierte en un ser prácticamente inútil como escudo de carne y hueso y su capacidad de destrucción es realmente mediocre. Esta criatura resulta más útil como apoyo de un grupo más grande.' WHERE entry=-1413; /* content: This foul little beast is the imp. It is small and weak, making it almost useless as a meatshield, and its damage output is mediocre at best. This creature is best used for support of a larger group. */
UPDATE creature_ai_texts SET content_loc6='Este ente demoníaco se conoce como abisario. Si fuerza y resistencia son importantes, resultando ideal para la defensa. Envíalo al frente para atacar a tu enemigo y luego úsalo como escudo mientras utilizas tus encantamientos y habilidades para extinguir la vida de tu oponente.' WHERE entry=-1415; /* content: This demonic entity is known as the Voidwalker. Its strength and endurance are significant, making it ideal for defense. Send it to attack your enemy, then use it as a shield while you use your spells and abilities to drain away your opponent\'s life. */
UPDATE creature_ai_texts SET content_loc6='Merece la pena contemplarlo, por si no lo has visto antes. Se trata de una criatura realmente impresionante dentro como fuera del campo de batalla. Ahora, echemos un vistazo a lo que estoy seguro que todos vosotros, alumnos varones, habéis estado esperando. El súcubo.' WHERE entry=-1416; /* content: If you\'ve never seen one, it is a sight to behold. A very impressive creature both on and off the field of battle. Next, let us take a look at what I am sure all you male students have been waiting for. The succubus. */
UPDATE creature_ai_texts SET content_loc6='Muy bien. Además de la distracción evidente que un esbirro como este supondrá para vuestros enemigos masculinos, ella también tiene una capacidad de destrucción impresionante. No obstante, su frágil resistencia la hace casi inservible como escudo.' WHERE entry=-1417; /* content: All right now. Aside from the obvious distractions a minion like this will provide against your more masculine foes, she is also capable of dealing out impressive amounts of damage. However, her fragile endurance makes her almost useless as a shield. */
UPDATE creature_ai_texts SET content_loc6='Estudiad mucho y quizás algún día podréis invocar a vuestro propio esbirro, pero ahora pasaremos a estudiar al manáfago.' WHERE entry=-1418; /* content: Study hard and you might one day be able to summon one on your own, but for now it\'s time to move on to the felhunter. */
UPDATE creature_ai_texts SET content_loc6='Lo que tenéis delante es un manáfago. Entre los talentos naturales de esta criatura está la capacidad de neutralizar encantamientos y otras habilidades, convirtiéndola en un ser inigualable a la hora de enfrentarse a un oponente con poderes mágicos.' WHERE entry=-1419; /* content: What you see before you is a felhunter. This creature\'s natural talents include spell lock and other abilities which make it unequalled when facing a magically attuned opponent. */
UPDATE creature_ai_texts SET content_loc6='A la hora de enfrentarse a cualquier taumaturgo, esta bestia salvaje será vuestro mejor amigo. Veamos ahora algo ligeramente distinto. La siguiente criatura os ayudará en vuestros viajes y hará más agradables vuestros viajes futuros. Vamos a echar un vistazo a un corcel vil.' WHERE entry=-1420; /* content: When facing a spellcaster of any kind, this feral beast will be your best friend. Now, let us take a look at something a bit different. This next creature will aid your travels and make your future journeys much easier. Let\'s take a look at a felsteed. */
UPDATE creature_ai_texts SET content_loc6='Aquí lo tenéis. Nuestra lección sobre las invocaciones ha llegado a su fin. En breve iniciaremos otra clase, así que si queréis poneros al día, os podéis quedar por aquí.' WHERE entry=-1422; /* content: There you have it. Our lesson on summoning has come to an end. A new class will begin shortly, so if you wish to brush up, feel free to stay around. */

SET NAMES 'latin1';
