-- File generated by Mangos Online Translation Editor (MOTE) v2.00
SET NAMES 'utf8';
UPDATE locales_creature SET name_loc8='Waypoint',subname_loc8='GM Visual' WHERE entry=1;
UPDATE locales_creature SET name_loc8='Spawnpoint',subname_loc8='GM Visual' WHERE entry=2;
UPDATE locales_creature SET subname_loc8='Enraged Form' WHERE entry=2454;
UPDATE locales_creature SET subname_loc8='PH MODEL WIP' WHERE entry=2694;
UPDATE locales_creature SET subname_loc8='Female' WHERE entry=7504;
UPDATE locales_creature SET subname_loc8='Spell Visual' WHERE entry=10579;
UPDATE locales_creature SET subname_loc8='(Night Elf Female)' WHERE entry=10798;
UPDATE locales_creature SET subname_loc8='The Head of The Black Flight' WHERE entry=11583;
UPDATE locales_creature SET subname_loc8='Ghost Visual' WHERE entry=12861;
UPDATE locales_creature SET subname_loc8='Mount Visual' WHERE entry=15778;
UPDATE locales_creature SET subname_loc8='Ghost/Ghoul spawner' WHERE entry=16306;
UPDATE locales_creature SET subname_loc8='Ghost/Skeleton spawner' WHERE entry=16336;
UPDATE locales_creature SET subname_loc8='Ghoul/Skeleton spawner' WHERE entry=16338;
UPDATE locales_creature SET subname_loc8='finder' WHERE entry=16356;

SET NAMES 'latin1';
