-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE creature_ai_texts SET content_loc8='%s is splashed by the blood and becomes irradiated!' WHERE entry=-31; -- content: %s is splashed by the blood and becomes irradiated!
UPDATE creature_ai_texts SET content_loc8='So dark...' WHERE entry=-73; -- content: So dark...
UPDATE creature_ai_texts SET content_loc8='Aaaaahhh! So close to escaping.' WHERE entry=-74; -- content: Aaaaahhh! So close to escaping.
UPDATE creature_ai_texts SET content_loc8='Get it while it\'s hot!' WHERE entry=-142; -- content: Get it while it\'s hot!
UPDATE creature_ai_texts SET content_loc8='The Defias shall succeed! No meek adventurer will stop us!' WHERE entry=-143; -- content: The Defias shall succeed! No meek adventurer will stop us!
UPDATE creature_ai_texts SET content_loc8='What? How dare you!' WHERE entry=-144; -- content: What? How dare you!
UPDATE creature_ai_texts SET content_loc8='[Kalimag] Ma reth bromo zoln kilagrin dra ma zoern tu ko fraht ko kadrom Ma krin drinor zoln drinor Ma krin kan aasrugel korsul' WHERE entry=-148; -- content: [Kalimag] Ma reth bromo zoln kilagrin dra ma zoern tu ko fraht ko kadrom Ma krin drinor zoln drinor Ma krin kan aasrugel korsul
UPDATE creature_ai_texts SET content_loc8='The Brotherhood shall prevail!' WHERE entry=-173; -- content: The Brotherhood shall prevail!
UPDATE creature_ai_texts SET content_loc8='We\'re under attack! Avast ya swabs! Repel the invaders!' WHERE entry=-174; -- content: We\'re under attack! Avast ya swabs! Repel the invaders!
UPDATE creature_ai_texts SET content_loc8='You land lovers are tougher then I thought! I will need to improvise' WHERE entry=-175; -- content: You land lovers are tougher then I thought! I will need to improvise
UPDATE creature_ai_texts SET content_loc8='D\'ah! Now you\'re making me angry!' WHERE entry=-176; -- content: D\'ah! Now you\'re making me angry!
UPDATE creature_ai_texts SET content_loc8='Aaaahhhhhh!' WHERE entry=-212; -- content: Aaaahhhhhh!
UPDATE creature_ai_texts SET content_loc8='Sands consume you!' WHERE entry=-320; -- content: Sands consume you!
UPDATE creature_ai_texts SET content_loc8='%s growls in your direction before taking time to sniff you.' WHERE entry=-343; -- content: %s growls in your direction before taking time to sniff you.
UPDATE creature_ai_texts SET content_loc8='%s faces southeast and whimpers before looking back at you. ' WHERE entry=-344; -- content: %s faces southeast and whimpers before looking back at you.
UPDATE creature_ai_texts SET content_loc8='%s\'s death cry has stirred the nearby silithid hive.' WHERE entry=-345; -- content: %s\'s death cry has stirred the nearby silithid hive.
UPDATE creature_ai_texts SET content_loc8='Think I\'m starting to wear a rut in the paving stones.' WHERE entry=-423; -- content: Think I\'m starting to wear a rut in the paving stones.
UPDATE creature_ai_texts SET content_loc8='Jack and Jill my wrinkled patoot! I do all the water luggin\' \'round here.' WHERE entry=-424; -- content: Jack and Jill my wrinkled patoot! I do all the water luggin\' \'round here.
UPDATE creature_ai_texts SET content_loc8='Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya.' WHERE entry=-425; -- content: Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya.
UPDATE creature_ai_texts SET content_loc8='Where\'s the water Emma? Get the water Emma? If\'n it weren\'t fer me that lot wouldn\'t know what water looks like.' WHERE entry=-426; -- content: Where\'s the water Emma? Get the water Emma? If\'n it weren\'t fer me that lot wouldn\'t know what water looks like.
UPDATE creature_ai_texts SET content_loc8='As if I don\'t have better things to do in my old age than carry buckets of water.' WHERE entry=-427; -- content: As if I don\'t have better things to do in my old age than carry buckets of water.
UPDATE creature_ai_texts SET content_loc8='O\'ourse I\'m talking to myself. Only way to get a decent conversation in this city.' WHERE entry=-428; -- content: O\'ourse I\'m talking to myself. Only way to get a decent conversation in this city.
UPDATE creature_ai_texts SET content_loc8='%s lets out a deep roar, alerting nearby allies and becoming enraged!' WHERE entry=-648; -- content: %s lets out a deep roar, alerting nearby allies and becoming enraged!
UPDATE creature_ai_texts SET content_loc8='%s goes into a drunken rage!' WHERE entry=-649; -- content: %s goes into a drunken rage!
UPDATE creature_ai_texts SET content_loc8='Fools. I knew that if I played upon my brother\'s feeble emotions, he would send \'rescuers.\'' WHERE entry=-658; -- content: Fools. I knew that if I played upon my brother\'s feeble emotions, he would send \'rescuers.\'
UPDATE creature_ai_texts SET content_loc8='How easy it was to manipulate you into recovering the last Suntara stone from those imbeciles of the Twilight\'s Hammer..' WHERE entry=-659; -- content: How easy it was to manipulate you into recovering the last Suntara stone from those imbeciles of the Twilight\'s Hammer..
UPDATE creature_ai_texts SET content_loc8='When I stumbled upon the Suntara stones at the Grimesilt Digsite, the power of Ragnaros surged through my being. It was Ragnaros that gave me a purpose.' WHERE entry=-660; -- content: When I stumbled upon the Suntara stones at the Grimesilt Digsite, the power of Ragnaros surged through my being. It was Ragnaros that gave me a purpose.
UPDATE creature_ai_texts SET content_loc8='It was the will of Ragnaros that Obsidion be built. Obsidion will destroy the Blackrock orcs of Blackrock Spire, uniting us with our bretheren in the fiery depths.' WHERE entry=-661; -- content: It was the will of Ragnaros that Obsidion be built. Obsidion will destroy the Blackrock orcs of Blackrock Spire, uniting us with our bretheren in the fiery depths.
UPDATE creature_ai_texts SET content_loc8='And ultimately, it was Ragnaros that named me when I was reborn as an acolyte of fire: Lathoric... Lathoric the Black.' WHERE entry=-662; -- content: And ultimately, it was Ragnaros that named me when I was reborn as an acolyte of fire: Lathoric... Lathoric the Black.
UPDATE creature_ai_texts SET content_loc8='%s\'s laughter trails off..' WHERE entry=-663; -- content: %s\'s laughter trails off..
UPDATE creature_ai_texts SET content_loc8='Your task is complete. Prepare to meet your doom.' WHERE entry=-664; -- content: Your task is complete. Prepare to meet your doom.
UPDATE creature_ai_texts SET content_loc8='Obsidion, Rise and Serve your Master!' WHERE entry=-665; -- content: Obsidion, Rise and Serve your Master!
UPDATE creature_ai_texts SET content_loc8='At last: one among you is worthy of my knowledge. Worry not: I have probed your thoughts, no harm will come to you.' WHERE entry=-666; -- content: At last: one among you is worthy of my knowledge. Worry not: I have probed your thoughts, no harm will come to you.
UPDATE creature_ai_texts SET content_loc8='Listen carefully, for the lord of Blackrock will surely destroy you, should you not be prepared.' WHERE entry=-667; -- content: Listen carefully, for the lord of Blackrock will surely destroy you, should you not be prepared.
UPDATE creature_ai_texts SET content_loc8='%s chips and splinters!' WHERE entry=-694; -- content: %s chips and splinters!
UPDATE creature_ai_texts SET content_loc8='Sands of the desert, rise and block out the sun!' WHERE entry=-698; -- content: Sands of the desert, rise and block out the sun!
UPDATE creature_ai_texts SET content_loc8='You are terminated.' WHERE entry=-699; -- content: You are terminated.
UPDATE creature_ai_texts SET content_loc8='I have... failed.' WHERE entry=-700; -- content: I have... failed.
UPDATE creature_ai_texts SET content_loc8='%s puts his club away and begins swinging wildly!' WHERE entry=-797; -- content: %s puts his club away and begins swinging wildly!
UPDATE creature_ai_texts SET content_loc8='%s begins to retaliate all attacks against him!' WHERE entry=-807; -- content: %s begins to retaliate all attacks against him!
UPDATE creature_ai_texts SET content_loc8='This evil cannot be allowed to enter this world!  Come my children!' WHERE entry=-825; -- content: This evil cannot be allowed to enter this world!  Come my children!
UPDATE creature_ai_texts SET content_loc8='%s attacks Karang\'s Banner!' WHERE entry=-828; -- content: %s attacks Karang\'s Banner!
UPDATE creature_ai_texts SET content_loc8='%s charges!' WHERE entry=-829; -- content: %s charges!
UPDATE creature_ai_texts SET content_loc8='More agents of the Syndicate I\'ll wager! You\'ll never take back Alterac... Or Southshore!' WHERE entry=-924; -- content: More agents of the Syndicate I\'ll wager! You\'ll never take back Alterac... Or Southshore!
UPDATE creature_ai_texts SET content_loc8='This orchard is now as barren and lifeless as my rotting shell. Once these trees bloomed with fruit but now there is only rot.' WHERE entry=-925; -- content: This orchard is now as barren and lifeless as my rotting shell. Once these trees bloomed with fruit but now there is only rot.
UPDATE creature_ai_texts SET content_loc8='I spent my whole life caring for these trees. Pruning and nurturing them... only fitting that they have joined me in death.' WHERE entry=-926; -- content: I spent my whole life caring for these trees. Pruning and nurturing them... only fitting that they have joined me in death.
UPDATE creature_ai_texts SET content_loc8='Intruders! Attack the intruders!' WHERE entry=-927; -- content: Intruders! Attack the intruders!
UPDATE creature_ai_texts SET content_loc8='Southshore shall pay in blood!' WHERE entry=-928; -- content: Southshore shall pay in blood!
UPDATE creature_ai_texts SET content_loc8='I have risen!' WHERE entry=-929; -- content: I have risen!
UPDATE creature_ai_texts SET content_loc8='Revenge shall be mine at last!' WHERE entry=-930; -- content: Revenge shall be mine at last!
UPDATE creature_ai_texts SET content_loc8='The undead shall feast on your soul, $N.' WHERE entry=-931; -- content: The undead shall feast on your soul, $N.
UPDATE creature_ai_texts SET content_loc8='Help me! Help! Assassins in the hills! To arms! To arms!' WHERE entry=-932; -- content: Help me! Help! Assassins in the hills! To arms! To arms!
UPDATE creature_ai_texts SET content_loc8='Guards to your posts! They must be after the Magistrate again. He must be protected! They could come from any direction!' WHERE entry=-933; -- content: Guards to your posts! They must be after the Magistrate again. He must be protected! They could come from any direction!
UPDATE creature_ai_texts SET content_loc8='%s grabs the back of his neck and his eyes go wide.' WHERE entry=-934; -- content: %s grabs the back of his neck and his eyes go wide.
UPDATE creature_ai_texts SET content_loc8='Assassins... save... th... Magistraaa...' WHERE entry=-935; -- content: Assassins... save... th... Magistraaa...
UPDATE creature_ai_texts SET content_loc8='Thieves! Scallywags! Rapscallions! Come face me gigantic pillas!' WHERE entry=-974; -- content: Thieves! Scallywags! Rapscallions! Come face me gigantic pillas!
UPDATE creature_ai_texts SET content_loc8='Are They all.... Dead?' WHERE entry=-981; -- content: Are They all.... Dead?
UPDATE creature_ai_texts SET content_loc8='Is someone there? Tirion my old friend, is that you? Have you come to save us?' WHERE entry=-982; -- content: Is someone there? Tirion my old friend, is that you? Have you come to save us?
UPDATE creature_ai_texts SET content_loc8='You dare! Now feel my wrath!' WHERE entry=-983; -- content: You dare! Now feel my wrath!
UPDATE creature_ai_texts SET content_loc8='Who dares?! I will destroy you!' WHERE entry=-984; -- content: Who dares?! I will destroy you!
UPDATE creature_ai_texts SET content_loc8='Mistress!! They seek to destroy your work!' WHERE entry=-985; -- content: Mistress!! They seek to destroy your work!
UPDATE creature_ai_texts SET content_loc8='This will teach you to lay off the herb, $r.' WHERE entry=-1019; -- content: This will teach you to lay off the herb, $r.
UPDATE creature_ai_texts SET content_loc8='The Scarlet Crusade shall not fail in it\'s mission!' WHERE entry=-1030; -- content: The Scarlet Crusade shall not fail in it\'s mission!
UPDATE creature_ai_texts SET content_loc8='These undead atrocities will be destroyed!' WHERE entry=-1031; -- content: These undead atrocities will be destroyed!
UPDATE creature_ai_texts SET content_loc8='These lands shall be cleansed!' WHERE entry=-1032; -- content: These lands shall be cleansed!
UPDATE creature_ai_texts SET content_loc8='The Agamand Mills is held by the Scourge, $c. Join us!' WHERE entry=-1034; -- content: The Agamand Mills is held by the Scourge, $c. Join us!
UPDATE creature_ai_texts SET content_loc8='Tell the Warden this prison is ours now!' WHERE entry=-1041; -- content: Tell the Warden this prison is ours now!
UPDATE creature_ai_texts SET content_loc8='I\'ll crush your skull beneath my boot!' WHERE entry=-1042; -- content: I\'ll crush your skull beneath my boot!
UPDATE creature_ai_texts SET content_loc8='Death to the Warden\'s men!' WHERE entry=-1043; -- content: Death to the Warden\'s men!
UPDATE creature_ai_texts SET content_loc8='Fresh meat!' WHERE entry=-1044; -- content: Fresh meat!
UPDATE creature_ai_texts SET content_loc8='More of the Warden\'s errand boys!' WHERE entry=-1045; -- content: More of the Warden\'s errand boys!
UPDATE creature_ai_texts SET content_loc8='How dare you enter my sanctum!' WHERE entry=-1047; -- content: How dare you enter my sanctum!
UPDATE creature_ai_texts SET content_loc8='You are in the presence of a god!' WHERE entry=-1048; -- content: You are in the presence of a god!
UPDATE creature_ai_texts SET content_loc8='%s seems to no longer be able to cast spells...' WHERE entry=-1058; -- content: %s seems to no longer be able to cast spells...
UPDATE creature_ai_texts SET content_loc8='Kill $N!' WHERE entry=-1119; -- content: Kill $N!
UPDATE creature_ai_texts SET content_loc8='For Kalimdor!' WHERE entry=-1133; -- content: For Kalimdor!
UPDATE creature_ai_texts SET content_loc8='Endudi Rifa!' WHERE entry=-1134; -- content: Endudi Rifa!
UPDATE creature_ai_texts SET content_loc8='Anudora!' WHERE entry=-1136; -- content: Anudora!
UPDATE creature_ai_texts SET content_loc8='WHO IS BOTHERING ME?' WHERE entry=-1137; -- content: WHO IS BOTHERING ME?
UPDATE creature_ai_texts SET content_loc8='Ahh, a new chew toy for my dogs!' WHERE entry=-1138; -- content: Ahh, a new chew toy for my dogs!
UPDATE creature_ai_texts SET content_loc8='Come, $n. See what the Nightmare brings...' WHERE entry=-1139; -- content: Come, $n. See what the Nightmare brings...
UPDATE creature_ai_texts SET content_loc8='The Nightmare cannot be stopped!' WHERE entry=-1140; -- content: The Nightmare cannot be stopped!
UPDATE creature_ai_texts SET content_loc8='%s squeezes the last bit of life out of $n and swallows their soul.' WHERE entry=-1141; -- content: %s squeezes the last bit of life out of $n and swallows their soul.
UPDATE creature_ai_texts SET content_loc8='I crush weaklings like you every day! Bring it on!' WHERE entry=-1142; -- content: I crush weaklings like you every day! Bring it on!
UPDATE creature_ai_texts SET content_loc8='You will not harm Emperor Thaurissan!' WHERE entry=-1143; -- content: You will not harm Emperor Thaurissan!
UPDATE creature_ai_texts SET content_loc8='Curse you! One day, vengeance will be mine!' WHERE entry=-1145; -- content: Curse you! One day, vengeance will be mine!
UPDATE creature_ai_texts SET content_loc8='Ach! Thank you so much I\'m free! Finally!' WHERE entry=-1146; -- content: Ach! Thank you so much I\'m free! Finally!
UPDATE creature_ai_texts SET content_loc8='%s \'s death cry has stirred the nearby silithid hive' WHERE entry=-1147; -- content: %s \'s death cry has stirred the nearby silithid hive
UPDATE creature_ai_texts SET content_loc8='You asked for it.' WHERE entry=-1148; -- content: You asked for it.
UPDATE creature_ai_texts SET content_loc8='I hate resorting to violence!' WHERE entry=-1149; -- content: I hate resorting to violence!
UPDATE creature_ai_texts SET content_loc8='Your time has come!' WHERE entry=-1150; -- content: Your time has come!
UPDATE creature_ai_texts SET content_loc8='Lok\'Narosh!' WHERE entry=-1151; -- content: Lok\'Narosh!
UPDATE creature_ai_texts SET content_loc8='For Doomhammer!' WHERE entry=-1152; -- content: For Doomhammer!
UPDATE creature_ai_texts SET content_loc8='You make big mistake, mon.' WHERE entry=-1153; -- content: You make big mistake, mon.
UPDATE creature_ai_texts SET content_loc8='Here come the voodoo!' WHERE entry=-1154; -- content: Here come the voodoo!
UPDATE creature_ai_texts SET content_loc8='For the Darkspear tribe!' WHERE entry=-1155; -- content: For the Darkspear tribe!
UPDATE creature_ai_texts SET content_loc8='Taste blade, mongrel!' WHERE entry=-1156; -- content: Taste blade, mongrel!
UPDATE creature_ai_texts SET content_loc8='Please tell me that you didn\'t just do what I think you just did. Please tell me that I\'m not going to have to hurt you...' WHERE entry=-1157; -- content: Please tell me that you didn\'t just do what I think you just did. Please tell me that I\'m not going to have to hurt you...
UPDATE creature_ai_texts SET content_loc8='As if we don\'t have enough problems, you go and create more!' WHERE entry=-1158; -- content: As if we don\'t have enough problems, you go and create more!
UPDATE creature_ai_texts SET content_loc8='Is that the best you can do?' WHERE entry=-1159; -- content: Is that the best you can do?
UPDATE creature_ai_texts SET content_loc8='Ah ken see very well through this haze, but I\'d know tha\' smell anywhere! Die ye foul ogre!' WHERE entry=-1160; -- content: Ah ken see very well through this haze, but I\'d know tha\' smell anywhere! Die ye foul ogre!
UPDATE creature_ai_texts SET content_loc8='Ooooooooh... $B To the plaguelands went old Duggan, ta\' send them Scourge back inta\' th\' groun\'. $B Where th\' scent of death is on th\' wind and everythin\' is mostly brown. $B An\' when he did arrive there, what\'d his dwarf eyes see? $B A hundred crates of barley there ta\' be makin\' inta\' mead! $B But tha\' mead was cursed with th\' plague o\' death, and now old Duggan, too. $B An\' surrounded by the Lich King\'s beasts, what could old Duggan do? $B But though I feel the plague within, my hopes \'ave not yet sunk. $B If\'n I\'m gonna be Scourge anyway, I might as well be drunk!' WHERE entry=-1161; -- content: Ooooooooh... $B To the plaguelands went old Duggan, ta\' send them Scourge back inta\' th\' groun\'. $B Where th\' scent of death is on th\' wind and everythin\' is mostly brown. $B An\' when he did arrive there, what\'d his dwarf eyes see? $B A hundred crates of barley there ta\' be makin\' inta\' mead! $B But tha\' mead was cursed with th\' plague o\' death, and now old Duggan, too. $B An\' surrounded by the Lich King\'s beasts, what could old Duggan do? $B But though I feel the plague within, my hopes \'ave not yet sunk. $B If\'n I\'m gonna be Scourge anyway, I might as well be drunk!
UPDATE creature_ai_texts SET content_loc8='I\'ll rip the secrets from your flesh!' WHERE entry=-1200; -- content: I\'ll rip the secrets from your flesh!
UPDATE creature_ai_texts SET content_loc8='SMOTTS, I HAVE YOUR LITTLE BELT....COME GET IT!' WHERE entry=-1206; -- content: SMOTTS, I HAVE YOUR LITTLE BELT....COME GET IT!
UPDATE creature_ai_texts SET content_loc8='SMOTTS! HEY, SMOTTS! COME OUT AND PLAY!' WHERE entry=-1207; -- content: SMOTTS! HEY, SMOTTS! COME OUT AND PLAY!
UPDATE creature_ai_texts SET content_loc8='DON\'T LET THIS STATUE BE MY ONLY COMPANY, COME OUT AND PLAY!' WHERE entry=-1208; -- content: DON\'T LET THIS STATUE BE MY ONLY COMPANY, COME OUT AND PLAY!
UPDATE creature_ai_texts SET content_loc8='COME OUT TO JANEIRO\'S POINT. I\'M WAITING FOR YOU, SMOTTS...' WHERE entry=-1209; -- content: COME OUT TO JANEIRO\'S POINT. I\'M WAITING FOR YOU, SMOTTS...
UPDATE creature_ai_texts SET content_loc8='I PROMISE I WON\'T KILL YOUR CREW THIS TIME. HAH! BUT MY BROTHER MIGHT EAT THEM!' WHERE entry=-1210; -- content: I PROMISE I WON\'T KILL YOUR CREW THIS TIME. HAH! BUT MY BROTHER MIGHT EAT THEM!
UPDATE creature_ai_texts SET content_loc8='HAVE YOU RUN OUT OF SHIPS TO SEND? WHERE IS YOUR COURAGE?' WHERE entry=-1211; -- content: HAVE YOU RUN OUT OF SHIPS TO SEND? WHERE IS YOUR COURAGE?
UPDATE creature_ai_texts SET content_loc8='YOU WERE SUCH GOOD SPORT THE LAST TIME...COME OUT!' WHERE entry=-1212; -- content: YOU WERE SUCH GOOD SPORT THE LAST TIME...COME OUT!
UPDATE creature_ai_texts SET content_loc8='I HAVE YOUR LITTLE BELT TIED AROUND MY FINGER, SMOTTS. DON\'T YOU WANT IT BACK?' WHERE entry=-1213; -- content: I HAVE YOUR LITTLE BELT TIED AROUND MY FINGER, SMOTTS. DON\'T YOU WANT IT BACK?
UPDATE creature_ai_texts SET content_loc8='Oh now you\'ve gone and angered me! Time to see the true force of the Stone of Tides!' WHERE entry=-1226; -- content: Oh now you\'ve gone and angered me! Time to see the true force of the Stone of Tides!
UPDATE creature_ai_texts SET content_loc8='Foolish mortal, you serve me now!' WHERE entry=-1295; -- content: Foolish mortal, you serve me now!
UPDATE creature_ai_texts SET content_loc8='The power of the light is truly great and merciful.' WHERE entry=-1296; -- content: The power of the light is truly great and merciful.
UPDATE creature_ai_texts SET content_loc8='We shall be reunited once more, my love...' WHERE entry=-1297; -- content: We shall be reunited once more, my love...
UPDATE creature_ai_texts SET content_loc8='At last, it ends...' WHERE entry=-1298; -- content: At last, it ends...
UPDATE creature_ai_texts SET content_loc8='Stranger, find the fallen Prince Menethil and end his reign of terror.' WHERE entry=-1299; -- content: Stranger, find the fallen Prince Menethil and end his reign of terror.
UPDATE creature_ai_texts SET content_loc8='Should I live through this, I shall make it my life\'s sole ambition to destroy Arthas...' WHERE entry=-1300; -- content: Should I live through this, I shall make it my life\'s sole ambition to destroy Arthas...
UPDATE creature_ai_texts SET content_loc8='I won\'t make it... go... go on without me...' WHERE entry=-1301; -- content: I won\'t make it... go... go on without me...
UPDATE creature_ai_texts SET content_loc8='Death take me! I cannot go on! I have nothing left...' WHERE entry=-1302; -- content: Death take me! I cannot go on! I have nothing left...
UPDATE creature_ai_texts SET content_loc8='Will someone please give my little kitten a good home?' WHERE entry=-1315; -- content: Will someone please give my little kitten a good home?
UPDATE creature_ai_texts SET content_loc8='Silithid Creeper lays an egg!' WHERE entry=-1317; -- content: Silithid Creeper lays an egg!
UPDATE creature_ai_texts SET content_loc8='Silithid Creeper Egg begins to crack and open...' WHERE entry=-1318; -- content: Silithid Creeper Egg begins to crack and open...
UPDATE creature_ai_texts SET content_loc8='Silithid Creeper Egg splits open!' WHERE entry=-1319; -- content: Silithid Creeper Egg splits open!
UPDATE creature_ai_texts SET content_loc8='%s splits into two new Lava Spawns!' WHERE entry=-1320; -- content: %s splits into two new Lava Spawns!
UPDATE creature_ai_texts SET content_loc8='Now that you have had a chance to study imp, let us move on the next minion you will be able to summon, the voidwalker.' WHERE entry=-1414; -- content: Now that you have had a chance to study imp, let us move on the next minion you will be able to summon, the voidwalker.

SET NAMES 'latin1';
