-- File generated by Mangos Online Translation Editor (MOTE) v2.0
SET NAMES 'utf8';
UPDATE trans_words SET content_loc2='Hunter Lodge' WHERE word_id = 127173;
UPDATE trans_words SET content_loc2='Stonefire Tavern' WHERE word_id = 127180;
UPDATE trans_words SET content_loc2='Battlemasters Ironforge' WHERE word_id = 127183;
UPDATE trans_words SET content_loc2='Ironforge Rogue Trainer' WHERE word_id = 127184;
UPDATE trans_words SET content_loc2='Ironforge Warlock Trainer' WHERE word_id = 127185;
UPDATE trans_words SET content_loc2='Darnassus Inn' WHERE word_id = 127191;
UPDATE trans_words SET content_loc2='Battlemasters Darnassus' WHERE word_id = 127193;
UPDATE trans_words SET content_loc2='Darnassus Tailor' WHERE word_id = 127205;
UPDATE trans_words SET content_loc2='Dolanaar Inn' WHERE word_id = 127206;
UPDATE trans_words SET content_loc2='Orgrimmar Inn' WHERE word_id = 127208;
UPDATE trans_words SET content_loc2='Sayoc & Hanashi' WHERE word_id = 127211;
UPDATE trans_words SET content_loc2='Battlemasters Orgrimmar' WHERE word_id = 127212;
UPDATE trans_words SET content_loc2='Razor Hill Inn' WHERE word_id = 127213;
UPDATE trans_words SET content_loc2='Undercity Skinning Trainer' WHERE word_id = 127215;
UPDATE trans_words SET content_loc2='Undercity Leatherworking Trainer' WHERE word_id = 127217;
UPDATE trans_words SET content_loc2='Undercity Engineering Trainer' WHERE word_id = 127221;
UPDATE trans_words SET content_loc2='Undercity Cooking Trainer' WHERE word_id = 127223;
UPDATE trans_words SET content_loc2='Undercity Rogue Trainers' WHERE word_id = 127227;
UPDATE trans_words SET content_loc2='Undercity Zeppelin' WHERE word_id = 127230;
UPDATE trans_words SET content_loc2='Undercity Inn' WHERE word_id = 127232;
UPDATE trans_words SET content_loc2='Battlemasters Thunder Bluff' WHERE word_id = 127240;
UPDATE trans_words SET content_loc2='Thunder Bluff Inn' WHERE word_id = 127243;
UPDATE trans_words SET content_loc2='Wind Rider Roost' WHERE word_id = 127244;
UPDATE trans_words SET content_loc2='Bloodhoof Village Inn' WHERE word_id = 127245;
UPDATE trans_words SET content_loc2='Saltheril\'s Haven, Tailor' WHERE word_id = 127247;

SET NAMES 'latin1';
