-- File generated by Mangos Online Translation Editor (MOTE) v2.10
SET NAMES 'utf8';
UPDATE `trans_words`SET `content_loc2`='"If you need robbers, head to the Old Town. It is in the northeast of Stormwind."' WHERE `word_id`=276845; -- locales_npc_text - Text2_1 : entry=900
UPDATE `trans_words`SET `content_loc2`='No better place to learn First Aid than under the watchful eye of Shaina Fuller at the Cathedral of Light. $B$BTo get there, just look for the yellow rooftops, or the towering spire of the Cathedral itself which you can see from almost anywhere in the city.' WHERE `word_id`=192143; -- locales_npc_text - Text1_0 : entry=923
UPDATE `trans_words`SET `content_loc2`='Well, if it isn\'t a young, bristling $C, no doubt drawn here by talk of my exploits in fields of battle!$B$BNo time for stories now, for there are great, important deeds that need doing!  So if you\'re looking for glory, then luck shines on you today...' WHERE `word_id`=197875; -- locales_npc_text - Text0_1 : entry=1244
UPDATE `trans_words`SET `content_loc2`='That wee wizardly lass, Bink, over in the Hall of Mysteries would probably be able to help ye out with any magical needs you have.$B$BThe Hall of Mysteries is just north of the gates of Ironforge.' WHERE `word_id`=192646; -- locales_npc_text - Text0_1 : entry=2771
UPDATE `trans_words`SET `content_loc2`='Well well!  You\'ve come to the right place to learn Mining, $Gboyo : girlie;!  Geofram Bouldertoe himself resides at the Deepmountain Mining Guild. Ye couldn\'t ask for a better instructor than him.' WHERE `word_id`=192678; -- locales_npc_text - Text1_0 : entry=2804
UPDATE `trans_words`SET `content_loc2`='Look for the Zeppelin Landing Tower outside of the city to the southeast.' WHERE `word_id`=192794; -- locales_npc_text - Text1_0 : entry=3173
UPDATE `trans_words`SET `content_loc2`='Hey there, friend. My name\'s Remy. I\'m from Redridge to the east, and came here looking for business, looking for business. You got any...got any??' WHERE `word_id`=197874; -- locales_npc_text - Text0_1 : entry=6157
UPDATE `trans_words`SET `content_loc2`='"Many entered this sanctuary, but few left it."' WHERE `word_id`=278038; -- locales_npc_text - Text2_1 : entry=6911
UPDATE `trans_words`SET `content_loc2`='The Silverwing Sentinels can use all the help they can get in their fight against the Warsong Outriders. $N, go to Stormwind Keep and speak with Elfarran if you wish to assist them.' WHERE `word_id`=194638; -- locales_npc_text - Text1_0 : entry=7501
UPDATE `trans_words`SET `content_loc2`='There is one that I know of here in Thunder Bluff that can aid you in your journey to Alterac Valley. On the Hunter Rise look for Taim Ragetotem. May you find what you are looking for $N.' WHERE `word_id`=194644; -- locales_npc_text - Text1_0 : entry=7505
UPDATE `trans_words`SET `content_loc2`='Missing US text.' WHERE `word_id`=196442; -- locales_npc_text - Text0_1 : entry=7775
UPDATE `trans_words`SET `content_loc2`='Elder Hammershout can be found within the walls of Stormwind.' WHERE `word_id`=196431; -- locales_npc_text - Text0_1 : entry=8174
UPDATE `trans_words`SET `content_loc2`='Elder Starweave can be found at the coastal village of Auberdine in Darkshore.' WHERE `word_id`=196427; -- locales_npc_text - Text0_1 : entry=8179
UPDATE `trans_words`SET `content_loc2`='Elder Moonwarden is observing the Crossroads in the Barrens.' WHERE `word_id`=196801; -- locales_npc_text - Text0_1 : entry=8187
UPDATE `trans_words`SET `content_loc2`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text3_0 : entry=10734
UPDATE `trans_words`SET `content_loc2`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text5_0 : entry=10734
UPDATE `trans_words`SET `content_loc2`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text7_0 : entry=10734
UPDATE `trans_words`SET `content_loc2`='All I ever wanted to do was study.' WHERE `word_id`=197115; -- locales_npc_text - Text1_0 : entry=11458
UPDATE `trans_words`SET `content_loc2`='Missing US text' WHERE `word_id`=195146; -- locales_npc_text - Text3_0 : entry=13064
UPDATE `trans_words`SET `content_loc2`='While my brother, Drazial, focuses his analysis on the more physical nature of the beasts of the blasted lands, I tend to focus on the more cerebral and spiritual aspects of the wildlife.$B$BIt is true that the beasts exhibit extremely unusual strength, agility, and stamina, but some of them also possess great intelligence and regenerative abilities, untied to their physical being.$B$BPerhaps you would be interested in helping advance my research, $R?' WHERE `word_id`=276826; -- locales_npc_text - Text0_1 : entry=16007
UPDATE `trans_words`SET `content_loc2`='Things can get a little stuffy here in Nethergarde. Sometimes a dwarf just needs a brew to take her mind off her duty for a bit.' WHERE `word_id`=196190; -- locales_npc_text - Text0_1 : entry=16219
UPDATE `trans_words`SET `content_loc2`='Hey there, cutie! Mind rubbing some lotion on my exposed areas?' WHERE `word_id`=196163; -- locales_npc_text - Text0_1 : entry=16644
UPDATE `trans_words`SET `content_loc2`='Weary of one of your demonic charges? Hoping for one with a more pleasing name?$B$BFor a price, I can assist you in the obliteration of a current minion so that you may summon an entirely new one...' WHERE `word_id`=196121; -- locales_npc_text - Text0_1 : entry=17816
UPDATE `trans_words`SET `content_loc2`='Iam Here, Commander' WHERE `word_id`=196931; -- locales_npc_text - Text0_1 : entry=20551
UPDATE `trans_words`SET `content_loc2`='Weve located the mark, commander. Ya-six and i have been seperated. Requesting backup.' WHERE `word_id`=196932; -- locales_npc_text - Text1_0 : entry=20551
UPDATE `trans_words`SET `content_loc2`='Arxes! Send help! Im pinned down in the mines, I...Im not sure where iam exactly but i had the presence of mind to drop tracers on the gro8und behind me' WHERE `word_id`=196933; -- locales_npc_text - Text1_1 : entry=20551
UPDATE `trans_words`SET `content_loc2`='Copy, Status report, Soldier.' WHERE `word_id`=196936; -- locales_npc_text - Text0_1 : entry=20564
UPDATE `trans_words`SET `content_loc2`='Copy that, Araxes. Backup is on the way. Hold your position. I repeat, Hold your Position' WHERE `word_id`=196937; -- locales_npc_text - Text1_0 : entry=20564
UPDATE `trans_words`SET `content_loc2`='Greetings $N' WHERE `word_id`=192036; -- locales_npc_text - Text0_1 : entry=60004

SET NAMES 'latin1';
