-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE trans_words SET content_loc4='[PH] SD3 unknown text' WHERE word_id = 127695;
UPDATE trans_words SET content_loc4='You challenged us and we have come. Where is this master you speak of?' WHERE word_id = 127680;

SET NAMES 'latin1';
