-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE locales_creature SET subname_loc4='Enraged Form' WHERE entry=2454; /* name: Skeletal Fiend */ /* subname: Enraged Form */
UPDATE locales_creature SET subname_loc4='PH MODEL WIP' WHERE entry=2694; /* name: Highvale Ranger */ /* subname: PH MODEL WIP */
UPDATE locales_creature SET subname_loc4='Crocilisk Trainer' WHERE entry=2876; /* name: Grunenstur Balindom */ /* subname: Crocilisk Trainer */
UPDATE locales_creature SET subname_loc4='Male' WHERE entry=7503; /* name: Curse of the Eye */ /* subname: Male */
UPDATE locales_creature SET subname_loc4='Female' WHERE entry=7504; /* name: Curse of the Eye */ /* subname: Female */
UPDATE locales_creature SET subname_loc4='Spell Visual' WHERE entry=10579; /* name: Kirtonos the Herald */ /* subname: Spell Visual */
UPDATE locales_creature SET subname_loc4='Orc Female' WHERE entry=10784; /* name: Orb of Deception */ /* subname: Orc Female */
UPDATE locales_creature SET subname_loc4='Tauren Male' WHERE entry=10785; /* name: Orb of Deception */ /* subname: Tauren Male */
UPDATE locales_creature SET subname_loc4='Tauren Female' WHERE entry=10786; /* name: Orb of Deception */ /* subname: Tauren Female */
UPDATE locales_creature SET subname_loc4='Troll Male' WHERE entry=10787; /* name: Orb of Deception */ /* subname: Troll Male */
UPDATE locales_creature SET subname_loc4='Troll Female' WHERE entry=10788; /* name: Orb of Deception */ /* subname: Troll Female */
UPDATE locales_creature SET subname_loc4='Undead Male' WHERE entry=10789; /* name: Orb of Deception */ /* subname: Undead Male */
UPDATE locales_creature SET subname_loc4='Undead Female' WHERE entry=10790; /* name: Orb of Deception */ /* subname: Undead Female */
UPDATE locales_creature SET subname_loc4='Dwarf Male' WHERE entry=10791; /* name: Orb of Deception */ /* subname: Dwarf Male */
UPDATE locales_creature SET subname_loc4='Dwarf Female' WHERE entry=10792; /* name: Orb of Deception */ /* subname: Dwarf Female */
UPDATE locales_creature SET subname_loc4='Gnome Male' WHERE entry=10793; /* name: Orb of Deception */ /* subname: Gnome Male */
UPDATE locales_creature SET subname_loc4='Gnome Female' WHERE entry=10794; /* name: Orb of Deception */ /* subname: Gnome Female */
UPDATE locales_creature SET subname_loc4='Human Male' WHERE entry=10795; /* name: Orb of Deception */ /* subname: Human Male */
UPDATE locales_creature SET subname_loc4='Human Female' WHERE entry=10796; /* name: Orb of Deception */ /* subname: Human Female */
UPDATE locales_creature SET subname_loc4='Night Elf Male' WHERE entry=10797; /* name: Orb of Deception */ /* subname: Night Elf Male */
UPDATE locales_creature SET subname_loc4='(Night Elf Female)' WHERE entry=10798; /* name: Orb of Deception */ /* subname: (Night Elf Female) */
UPDATE locales_creature SET subname_loc4='The Head of The Black Flight' WHERE entry=11583; /* name: Nefarian */ /* subname: The Head of The Black Flight */
UPDATE locales_creature SET subname_loc4='Mount Visual' WHERE entry=15778; /* name: Mouth Tentacle */ /* subname: Mount Visual */
UPDATE locales_creature SET subname_loc4='Ghost/Ghoul spawner' WHERE entry=16306; /* name: Scourge Invasion Minion */ /* subname: Ghost/Ghoul spawner */
UPDATE locales_creature SET subname_loc4='Ghost/Skeleton spawner' WHERE entry=16336; /* name: Scourge Invasion Minion */ /* subname: Ghost/Skeleton spawner */
UPDATE locales_creature SET subname_loc4='Ghoul/Skeleton spawner' WHERE entry=16338; /* name: Scourge Invasion Minion */ /* subname: Ghoul/Skeleton spawner */
UPDATE locales_creature SET subname_loc4='finder' WHERE entry=16356; /* name: Scourge Invasion Minion */ /* subname: finder */
UPDATE locales_creature SET subname_loc4='Ammunition Vendor' WHERE entry=17598; /* name: Renn\'az */ /* subname: Ammunition Vendor */

SET NAMES 'latin1';
