-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE locales_item SET description_loc4='Also serves as a mining pick.' WHERE entry=756; /* description: Also serves as a mining pick. */
UPDATE locales_item SET description_loc4='Also serves as a mining pick.' WHERE entry=778; /* description: Also serves as a mining pick. */
UPDATE locales_item SET description_loc4='Also serves as a mining pick.' WHERE entry=1819; /* description: Also serves as a mining pick. */
UPDATE locales_item SET description_loc4='Also serves as a mining pick.' WHERE entry=1893; /* description: Also serves as a mining pick. */
UPDATE locales_item SET description_loc4='Also serves as a mining pick.' WHERE entry=1959; /* description: Also serves as a mining pick. */
UPDATE locales_item SET description_loc4='Engraved with the words \'For years of service: -EVC.\'' WHERE entry=2239; /* description: Engraved with the words \'For years of service: -EVC.\' */
UPDATE locales_item SET description_loc4='Can also serve as any lesser runed enchanting rod.' WHERE entry=6339; /* description: Can also serve as any lesser runed enchanting rod. */
UPDATE locales_item SET description_loc4='Teaches Inner Fire (Rank 2).' WHERE entry=8964; /* description: Teaches Inner Fire (Rank 2). */
UPDATE locales_item SET description_loc4='Also serves as a mining pick.' WHERE entry=9465; /* description: Also serves as a mining pick. */
UPDATE locales_item SET description_loc4='Can also serve as any lesser runed enchanting rod.' WHERE entry=11130; /* description: Can also serve as any lesser runed enchanting rod. */
UPDATE locales_item SET description_loc4='Can also serve as any lesser runed enchanting rod.' WHERE entry=11145; /* description: Can also serve as any lesser runed enchanting rod. */
UPDATE locales_item SET description_loc4='Teaches you how to permanently enchant a bracer to give +3 defense rating.' WHERE entry=11163; /* description: Teaches you how to permanently enchant a bracer to give +3 defense rating. */
UPDATE locales_item SET description_loc4='Teaches you how to permanently enchant a bracer to give +5 Defense Rating.' WHERE entry=11223; /* description: Teaches you how to permanently enchant a bracer to give +5 Defense Rating. */
UPDATE locales_item SET description_loc4='Property of Finkle Einhorn, Grandmaster Adventurer' WHERE entry=12709; /* description: Property of Finkle Einhorn, Grandmaster Adventurer */
UPDATE locales_item SET description_loc4='Teaches you how to make Thorium Shells.' WHERE entry=16051; /* description: Teaches you how to make Thorium Shells. */
UPDATE locales_item SET description_loc4='Can also serve as any lesser runed enchanting rod.' WHERE entry=16207; /* description: Can also serve as any lesser runed enchanting rod. */
UPDATE locales_item SET description_loc4='Property of Finkle Einhorn, Grandmaster Adventurer' WHERE entry=18803; /* description: Property of Finkle Einhorn, Grandmaster Adventurer */
UPDATE locales_item SET description_loc4='Also serves as a skinning knife.' WHERE entry=19901; /* description: Also serves as a skinning knife. */
UPDATE locales_item SET description_loc4='Only ONE May Rise... (and consequently, only ONE may loot this head)' WHERE entry=20383; /* description: Only ONE May Rise... (and consequently, only ONE may loot this head) */
UPDATE locales_item SET description_loc4='Also serves as a mining pick.' WHERE entry=20723; /* description: Also serves as a mining pick. */
UPDATE locales_item SET description_loc4='Teaches you how to permanently enchant a cloak to increase stealth.' WHERE entry=20734; /* description: Teaches you how to permanently enchant a cloak to increase stealth. */
UPDATE locales_item SET description_loc4='Teaches you how to permanently enchant a cloak to give 12 dodge rating.' WHERE entry=20736; /* description: Teaches you how to permanently enchant a cloak to give 12 dodge rating. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=22345; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=22395; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=22396; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=23005; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=23199; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=23200; /* description: Counts as an Air, Earth, Fire, and Water totem. */

SET NAMES 'latin1';
