-- File generated by Mangos Online Translation Editor (MOTE) v0.8
SET NAMES 'utf8';
UPDATE locales_page_text SET text_loc4='<HTML>
<BODY>
<IMG src="Interface\Pictures\9330_Gammerita_sepia_256"/>
</BODY>
</HTML>' WHERE entry=1171; /* text: <HTML>
<BODY>
<IMG src="Interface\Pictures\9330_Gammerita_sepia_256"/>
</BODY>
</HTML> */
UPDATE locales_page_text SET text_loc4='<HTML> <BODY> <IMG src="Interface\Pictures\9330_Gammerita_sepia_256"/> </BODY> </HTML>' WHERE entry=1190; /* text: <HTML> <BODY> <IMG src="Interface\Pictures\9330_Gammerita_sepia_256"/> </BODY> </HTML> */
UPDATE locales_page_text SET text_loc4='<HTML>
<BODY>
<IMG src="Interface\Pictures\Linken_sepia_256px"/>
</BODY>
</HTML>' WHERE entry=1371; /* text: <HTML>
<BODY>
<IMG src="Interface\Pictures\Linken_sepia_256px"/>
</BODY>
</HTML> */
UPDATE locales_page_text SET text_loc4='<HTML> <BODY> <IMG src="Interface\Pictures\Linken_sepia_256px"/> </BODY> </HTML>' WHERE entry=1391; /* text: <HTML> <BODY> <IMG src="Interface\Pictures\Linken_sepia_256px"/> </BODY> </HTML> */
UPDATE locales_page_text SET text_loc4='<HTML>
<BODY>
<IMG src="Interface\Pictures\11733_blackrock_256"/>
</BODY>
</HTML>
' WHERE entry=1635; /* text: <HTML>
<BODY>
<IMG src="Interface\Pictures\11733_blackrock_256"/>
</BODY>
</HTML> */
UPDATE locales_page_text SET text_loc4='<HTML>
<BODY>
<IMG src="Interface\Pictures\11733_blasted_256"/>
</BODY>
</HTML>
' WHERE entry=1636; /* text: <HTML>
<BODY>
<IMG src="Interface\Pictures\11733_blasted_256"/>
</BODY>
</HTML> */
UPDATE locales_page_text SET text_loc4='<HTML>
<BODY>
<IMG src="Interface\Pictures\11733_ungoro_256"/>
</BODY>
</HTML>
' WHERE entry=1637; /* text: <HTML>
<BODY>
<IMG src="Interface\Pictures\11733_ungoro_256"/>
</BODY>
</HTML> */
UPDATE locales_page_text SET text_loc4='<HTML>
<BODY>
<IMG src="Interface\Pictures\11733_nightdragon_256"/>
</BODY>
</HTML>

' WHERE entry=1638; /* text: <HTML>
<BODY>
<IMG src="Interface\Pictures\11733_nightdragon_256"/>
</BODY>
</HTML> */
UPDATE locales_page_text SET text_loc4='<HTML>
<BODY>
<IMG src="Interface\Pictures\11733_blackrock_256"/>
</BODY>
</HTML>' WHERE entry=1639; /* text: <HTML>
<BODY>
<IMG src="Interface\Pictures\11733_blackrock_256"/>
</BODY>
</HTML> */
UPDATE locales_page_text SET text_loc4='<HTML>
<BODY>
<IMG src="Interface\Pictures\11733_bldbank_256"/>
</BODY>
</HTML>' WHERE entry=1640; /* text: <HTML>
<BODY>
<IMG src="Interface\Pictures\11733_bldbank_256"/>
</BODY>
</HTML> */
UPDATE locales_page_text SET text_loc4='<HTML>
<BODY>
<IMG src="Interface\Pictures\11733_ungoro_256"/>
</BODY>
</HTML>' WHERE entry=1641; /* text: <HTML>
<BODY>
<IMG src="Interface\Pictures\11733_ungoro_256"/>
</BODY>
</HTML> */
UPDATE locales_page_text SET text_loc4='<HTML> <BODY> <IMG src="Interface\Pictures\11733_blackrock_256"/> </BODY> </HTML>' WHERE entry=1642; /* text: <HTML> <BODY> <IMG src="Interface\Pictures\11733_blackrock_256"/> </BODY> </HTML> */
UPDATE locales_page_text SET text_loc4='<HTML> <BODY> <IMG src="Interface\Pictures\11733_blasted_256"/> </BODY> </HTML>' WHERE entry=1643; /* text: <HTML> <BODY> <IMG src="Interface\Pictures\11733_blasted_256"/> </BODY> </HTML> */
UPDATE locales_page_text SET text_loc4='<HTML> <BODY> <IMG src="Interface\Pictures\11733_ungoro_256"/> </BODY> </HTML>' WHERE entry=1644; /* text: <HTML> <BODY> <IMG src="Interface\Pictures\11733_ungoro_256"/> </BODY> </HTML> */
UPDATE locales_page_text SET text_loc4='<HTML> <BODY> <IMG src="Interface\Pictures\11733_blackrock_256"/> </BODY> </HTML>' WHERE entry=1645; /* text: <HTML> <BODY> <IMG src="Interface\Pictures\11733_blackrock_256"/> </BODY> </HTML> */
UPDATE locales_page_text SET text_loc4='<HTML> <BODY> <IMG src="Interface\Pictures\11733_bldbank_256"/> </BODY> </HTML>' WHERE entry=1646; /* text: <HTML> <BODY> <IMG src="Interface\Pictures\11733_bldbank_256"/> </BODY> </HTML> */
UPDATE locales_page_text SET text_loc4='<HTML> <BODY> <IMG src="Interface\Pictures\11733_blasted_256"/> </BODY> </HTML>' WHERE entry=1647; /* text: <HTML> <BODY> <IMG src="Interface\Pictures\11733_blasted_256"/> </BODY> </HTML> */
UPDATE locales_page_text SET text_loc4='<HTML> <BODY> <IMG src="Interface\Pictures\11733_ungoro_256"/> </BODY> </HTML>' WHERE entry=1648; /* text: <HTML> <BODY> <IMG src="Interface\Pictures\11733_ungoro_256"/> </BODY> </HTML> */
UPDATE locales_page_text SET text_loc4='<HTML> <BODY> <IMG src="Interface\Pictures\11733_blackrock_256"/> </BODY> </HTML> ' WHERE entry=1649; /* text: <HTML> <BODY> <IMG src="Interface\Pictures\11733_blackrock_256"/> </BODY> </HTML> */
UPDATE locales_page_text SET text_loc4='<HTML> <BODY> <IMG src="Interface\Pictures\11733_bldbank_256"/> </BODY> </HTML> ' WHERE entry=1650; /* text: <HTML> <BODY> <IMG src="Interface\Pictures\11733_bldbank_256"/> </BODY> </HTML> */
UPDATE locales_page_text SET text_loc4='<HTML> <BODY> <IMG src="Interface\Pictures\11733_whipper_256"/> </BODY> </HTML> ' WHERE entry=1651; /* text: <HTML> <BODY> <IMG src="Interface\Pictures\11733_whipper_256"/> </BODY> </HTML> */
UPDATE locales_page_text SET text_loc4='<HTML>
<BODY>
<IMG src="Interface\Pictures\11733_ungoro_256"/>
</BODY>
</HTML>' WHERE entry=1652; /* text: <HTML>
<BODY>
<IMG src="Interface\Pictures\11733_ungoro_256"/>
</BODY>
</HTML> */
UPDATE locales_page_text SET text_loc4='<HTML> <BODY> <IMG src="Interface\Pictures\11733_ungoro_256"/> </BODY> </HTML> ' WHERE entry=1690; /* text: <HTML> <BODY> <IMG src="Interface\Pictures\11733_ungoro_256"/> </BODY> </HTML> */
UPDATE locales_page_text SET text_loc4='<HTML>
<BODY>
<IMG src="Interface\Pictures\14679_Tirion_256"/>
</BODY>
</HTML>
' WHERE entry=2351; /* text: <HTML>
<BODY>
<IMG src="Interface\Pictures\14679_Tirion_256"/>
</BODY>
</HTML> */
UPDATE locales_page_text SET text_loc4='<HTML> <BODY> <IMG src="Interface\Pictures\14679_Tirion_256"/> </BODY> </HTML> ' WHERE entry=2370; /* text: <HTML> <BODY> <IMG src="Interface\Pictures\14679_Tirion_256"/> </BODY> </HTML> */
UPDATE locales_page_text SET text_loc4='OoOoOoO OOoOOoo OOOoOoo OOoOooO OOoOOoO OOooooO Oooooo OooOOOO OOoOOOo OOoOOoo OOoOooO OOoOOOo OOooOoO Oooooo OooOOOo OOooooO OOOoooo OOooooO Oooooo OoOoOOo OOooooO OOoOOoo OOoOOoo OOooOoO OOOOooO Oooooo OooOoOO OOoOOOo OOoOooO OOooOOO OOoOooo OOOoOoo OOOooOO Oooooo OOoOOOO OOooOOo Oooooo OooooOO OOoOooo OOooooO OOoOOOO OOOooOO' WHERE entry=2411; /* text: OoOoOoO OOoOOoo OOOoOoo OOoOooO OOoOOoO OOooooO Oooooo OooOOOO OOoOOOo OOoOOoo OOoOooO OOoOOOo OOooOoO Oooooo OooOOOo OOooooO OOOoooo OOooooO Oooooo OoOoOOo OOooooO OOoOOoo OOoOOoo OOooOoO OOOOooO Oooooo OooOoOO OOoOOOo OOoOooO OOooOOO OOoOooo OOOoOoo OOOooOO Oooooo OOoOOOO OOooOOo Oooooo OooooOO OOoOooo OOooooO OOoOOOO OOOooOO */
UPDATE locales_page_text SET text_loc4='OoOoOoO OOoOOoo OOOoOoo OOoOooO OOoOOoO OOooooO Oooooo OooOOOO OOoOOOo OOoOOoo OOoOooO OOoOOOo OOooOoO Oooooo OooOOOo OOooooO OOOoooo OOooooO Oooooo OoOoOOo OOooooO OOoOOoo OOoOOoo OOooOoO OOOOooO Oooooo OooOoOO OOoOOOo OOoOooO OOooOOO OOoOooo OOOoOoo OOOooOO Oooooo OOoOOOO OOooOOo Oooooo OooooOO OOoOooo OOooooO OOoOOOO OOOooOO' WHERE entry=2412; /* text: OoOoOoO OOoOOoo OOOoOoo OOoOooO OOoOOoO OOooooO Oooooo OooOOOO OOoOOOo OOoOOoo OOoOooO OOoOOOo OOooOoO Oooooo OooOOOo OOooooO OOOoooo OOooooO Oooooo OoOoOOo OOooooO OOoOOoo OOoOOoo OOooOoO OOOOooO Oooooo OooOoOO OOoOOOo OOoOooO OOooOOO OOoOooo OOOoOoo OOOooOO Oooooo OOoOOOO OOooOOo Oooooo OooooOO OOoOooo OOooooO OOoOOOO OOOooOO */
UPDATE locales_page_text SET text_loc4='Credit\'s Main:
Quest scripter\'s:
==============================
Shultz. Thesleby. Rest of !rpg Team.

' WHERE entry=2605; /* text: Credit\'s Main:
Quest scripter\'s:
==============================
Shultz. Thesleby. Rest of !rpg Team. */
UPDATE locales_page_text SET text_loc4='<HTML>
<BODY>
<IMG src="Interface\Pictures\21037_crudemap_256"/>
</BODY>
</HTML>' WHERE entry=2828; /* text: <HTML>
<BODY>
<IMG src="Interface\Pictures\21037_crudemap_256"/>
</BODY>
</HTML> */
UPDATE locales_page_text SET text_loc4='<HTML>
<BODY>
<IMG src="Interface\Pictures\24475_gordawg_256"/>
</BODY>
</HTML>' WHERE entry=2944; /* text: <HTML>
<BODY>
<IMG src="Interface\Pictures\24475_gordawg_256"/>
</BODY>
</HTML> */
UPDATE locales_page_text SET text_loc4='Howdy! You have found a loot bug in UDB. We are terribly sorry about that, and we will try and fix it just as SOON as possible. However, You need to help us a little bit. If you will go to http://www.udbforums.org and fill out a loot bug report, with the location you found this, we will try and get it fixed ASAP. Thanks, the UDB team!' WHERE entry=9999; /* text: Howdy! You have found a loot bug in UDB. We are terribly sorry about that, and we will try and fix it just as SOON as possible. However, You need to help us a little bit. If you will go to http://www.udbforums.org and fill out a loot bug report, with the location you found this, we will try and get it fixed ASAP. Thanks, the UDB team! */

SET NAMES 'latin1';
