-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE locales_points_of_interest SET icon_name_loc1='사자무리 여관' WHERE entry=1; /* icon_name: Lion\'s Pride Inn */
UPDATE locales_points_of_interest SET icon_name_loc1='잘디마르 웨펠트' WHERE entry=2; /* icon_name: Zaldimar Wefhellt */
UPDATE locales_points_of_interest SET icon_name_loc1='수사 빌헬름' WHERE entry=3; /* icon_name: Brother Wilhelm */
UPDATE locales_points_of_interest SET icon_name_loc1='여사제 조세타' WHERE entry=4; /* icon_name: Priestess Josetta */
UPDATE locales_points_of_interest SET icon_name_loc1='케린 실비우스' WHERE entry=5; /* icon_name: Keryn Sylvius */
UPDATE locales_points_of_interest SET icon_name_loc1='맥시밀리언 크로우' WHERE entry=6; /* icon_name: Maximillian Crowe */
UPDATE locales_points_of_interest SET icon_name_loc1='리리아 뒤 라크' WHERE entry=7; /* icon_name: Lyria Du Lac */
UPDATE locales_points_of_interest SET icon_name_loc1='연금술사 말로리' WHERE entry=8; /* icon_name: Alchemist Mallory */
UPDATE locales_points_of_interest SET icon_name_loc1='대장장이 아르거스' WHERE entry=9; /* icon_name: Smith Argus */
UPDATE locales_points_of_interest SET icon_name_loc1='토마스' WHERE entry=10; /* icon_name: Tomas */
UPDATE locales_points_of_interest SET icon_name_loc1='미셸 벨르' WHERE entry=11; /* icon_name: Michelle Belle */
UPDATE locales_points_of_interest SET icon_name_loc1='리 브라운' WHERE entry=12; /* icon_name: Lee Brown */
UPDATE locales_points_of_interest SET icon_name_loc1='아델레 필더' WHERE entry=14; /* icon_name: Adele Fielder */
UPDATE locales_points_of_interest SET icon_name_loc1='헬렌 펠트스키너' WHERE entry=15; /* icon_name: Helene Peltskinner */
UPDATE locales_points_of_interest SET icon_name_loc1='엘드린' WHERE entry=16; /* icon_name: Eldrin */
UPDATE locales_points_of_interest SET icon_name_loc1='엘마' WHERE entry=17; /* icon_name: Erma */
UPDATE locales_points_of_interest SET icon_name_loc1='스톰윈드 경매장' WHERE entry=18; /* icon_name: Stormwind Auction House */
UPDATE locales_points_of_interest SET icon_name_loc1='황금 장미 여관' WHERE entry=22; /* icon_name: The Gilded Rose */
UPDATE locales_points_of_interest SET icon_name_loc1='스톰윈드 사무소' WHERE entry=24; /* icon_name: Stormwind Visitor\'s Center */
UPDATE locales_points_of_interest SET icon_name_loc1='제노바 스톤실드' WHERE entry=26; /* icon_name: Jenova Stoneshield */
UPDATE locales_points_of_interest SET icon_name_loc1='우 핑' WHERE entry=27; /* icon_name: Woo Ping */
UPDATE locales_points_of_interest SET icon_name_loc1='용사의 전당' WHERE entry=28; /* icon_name: Champions\' Hall */
UPDATE locales_points_of_interest SET icon_name_loc1='스톰윈드 공원' WHERE entry=32; /* icon_name: The Park */
UPDATE locales_points_of_interest SET icon_name_loc1='마법사의 성소' WHERE entry=34; /* icon_name: Wizard\'s Sanctum */
UPDATE locales_points_of_interest SET icon_name_loc1='빛의 대성당' WHERE entry=35; /* icon_name: Cathedral Of Light */
UPDATE locales_points_of_interest SET icon_name_loc1='어둠의 희생양 선술집' WHERE entry=38; /* icon_name: The Slaughtered Lamb */
UPDATE locales_points_of_interest SET icon_name_loc1='연금술의 모든 것' WHERE entry=40; /* icon_name: Alchemy Needs */
UPDATE locales_points_of_interest SET icon_name_loc1='테룸 딥포지' WHERE entry=41; /* icon_name: Therum Deepforge */
UPDATE locales_points_of_interest SET icon_name_loc1='돼지와 휘파람 선술집' WHERE entry=42; /* icon_name: Pig and Whistle Tavern */
UPDATE locales_points_of_interest SET icon_name_loc1='루칸 코르델' WHERE entry=43; /* icon_name: Lucan Cordell */
UPDATE locales_points_of_interest SET icon_name_loc1='릴리암 스파크스핀들' WHERE entry=44; /* icon_name: Lilliam Sparkspindle */
UPDATE locales_points_of_interest SET icon_name_loc1='샤이나 풀러' WHERE entry=45; /* icon_name: Shaina Fuller */
UPDATE locales_points_of_interest SET icon_name_loc1='아놀드 리랜드' WHERE entry=46; /* icon_name: Arnold Leland */
UPDATE locales_points_of_interest SET icon_name_loc1='태너의 가죽용품점' WHERE entry=47; /* icon_name: The Protective Hide */
UPDATE locales_points_of_interest SET icon_name_loc1='겔만 스톤핸드' WHERE entry=48; /* icon_name: Gelman Stonehand */
UPDATE locales_points_of_interest SET icon_name_loc1='던컨의 옷가게' WHERE entry=49; /* icon_name: Duncan\'s Textiles */
UPDATE locales_points_of_interest SET icon_name_loc1='아이언포지 경매장' WHERE entry=50; /* icon_name: Ironforge Auction house */
UPDATE locales_points_of_interest SET icon_name_loc1='깊은굴 지하철' WHERE entry=52; /* icon_name: Deeprun Tram */
UPDATE locales_points_of_interest SET icon_name_loc1='아이언포지 길드 사무소' WHERE entry=54; /* icon_name: Ironforge Visitor\'s Center */
UPDATE locales_points_of_interest SET icon_name_loc1='울브렉 파이어핸드' WHERE entry=57; /* icon_name: Ulbrek Firehand */
UPDATE locales_points_of_interest SET icon_name_loc1='전투의 전당' WHERE entry=61; /* icon_name: Hall of Arms */
UPDATE locales_points_of_interest SET icon_name_loc1='신비의 전당' WHERE entry=62; /* icon_name: Hall of Mysteries */
UPDATE locales_points_of_interest SET icon_name_loc1='베리피즈의 물약 상점' WHERE entry=66; /* icon_name: Berryfizz\'s Potions and Mixed Drinks */
UPDATE locales_points_of_interest SET icon_name_loc1='대용광로' WHERE entry=67; /* icon_name: The Great Forge */
UPDATE locales_points_of_interest SET icon_name_loc1='놋쇠단지 제과점' WHERE entry=68; /* icon_name: The Bronze Kettle */
UPDATE locales_points_of_interest SET icon_name_loc1='시슬퍼즈의 신비한 이야기' WHERE entry=69; /* icon_name: Thistlefuzz Arcanery */
UPDATE locales_points_of_interest SET icon_name_loc1='아이언포지 치료소' WHERE entry=70; /* icon_name: Ironforge Physician */
UPDATE locales_points_of_interest SET icon_name_loc1='여행용 낚시용품점' WHERE entry=71; /* icon_name: Traveling Fisherman */
UPDATE locales_points_of_interest SET icon_name_loc1='파인스핀들의 가죽 상점' WHERE entry=73; /* icon_name: Finespindle\'s Leather Goods */
UPDATE locales_points_of_interest SET icon_name_loc1='스톤브라우의 의류점' WHERE entry=75; /* icon_name: Stonebrow\'s Clothier */
UPDATE locales_points_of_interest SET icon_name_loc1='썬더브루 양조장' WHERE entry=76; /* icon_name: Thunderbrew Distillery */
UPDATE locales_points_of_interest SET icon_name_loc1='셸비 스톤플린트' WHERE entry=77; /* icon_name: Shelby Stoneflint */
UPDATE locales_points_of_interest SET icon_name_loc1='그리프 와일드하트' WHERE entry=78; /* icon_name: Grif Wildheart */
UPDATE locales_points_of_interest SET icon_name_loc1='마지스 스파크맨틀' WHERE entry=79; /* icon_name: Magis Sparkmantle */
UPDATE locales_points_of_interest SET icon_name_loc1='아자르 스트롱해머' WHERE entry=80; /* icon_name: Azar Stronghammer */
UPDATE locales_points_of_interest SET icon_name_loc1='막산 앤볼' WHERE entry=81; /* icon_name: Maxan Anvol */
UPDATE locales_points_of_interest SET icon_name_loc1='호그럴 바칸' WHERE entry=82; /* icon_name: Hogral Bakkan */
UPDATE locales_points_of_interest SET icon_name_loc1='김리즈 섀도코그' WHERE entry=83; /* icon_name: Gimrizz Shadowcog */
UPDATE locales_points_of_interest SET icon_name_loc1='그라니스 스위프트액스' WHERE entry=84; /* icon_name: Granis Swiftaxe */
UPDATE locales_points_of_interest SET icon_name_loc1='토그너스 플린트파이어' WHERE entry=85; /* icon_name: Tognus Flintfire */
UPDATE locales_points_of_interest SET icon_name_loc1='그렘록 필스노르' WHERE entry=86; /* icon_name: Gremlock Pilsnor */
UPDATE locales_points_of_interest SET icon_name_loc1='탐네르 폴' WHERE entry=87; /* icon_name: Thamner Pol */
UPDATE locales_points_of_interest SET icon_name_loc1='팩스턴 간터' WHERE entry=88; /* icon_name: Paxton Ganter */
UPDATE locales_points_of_interest SET icon_name_loc1='다르나서스 경매장' WHERE entry=89; /* icon_name: Darnassus Auction House */
UPDATE locales_points_of_interest SET icon_name_loc1='알랏신' WHERE entry=95; /* icon_name: Alassin */
UPDATE locales_points_of_interest SET icon_name_loc1='일예니아 문파이어' WHERE entry=96; /* icon_name: Ilyenia Moonfire */
UPDATE locales_points_of_interest SET icon_name_loc1='전사의 정원' WHERE entry=101; /* icon_name: Warrior\'s Terrace */
UPDATE locales_points_of_interest SET icon_name_loc1='세리아드네' WHERE entry=112; /* icon_name: Seriadne */
UPDATE locales_points_of_interest SET icon_name_loc1='칼' WHERE entry=113; /* icon_name: Kal */
UPDATE locales_points_of_interest SET icon_name_loc1='다잘라' WHERE entry=114; /* icon_name: Dazalar */
UPDATE locales_points_of_interest SET icon_name_loc1='라우르나 모닝라이트' WHERE entry=115; /* icon_name: Laurna Morninglight */
UPDATE locales_points_of_interest SET icon_name_loc1='잔노크 브리즈송' WHERE entry=116; /* icon_name: Jannok Breezesong */
UPDATE locales_points_of_interest SET icon_name_loc1='키라 윈드블레이드' WHERE entry=117; /* icon_name: Kyra Windblade */
UPDATE locales_points_of_interest SET icon_name_loc1='신드라 카인드위스퍼' WHERE entry=118; /* icon_name: Cyndra Kindwhisper */
UPDATE locales_points_of_interest SET icon_name_loc1='자린' WHERE entry=119; /* icon_name: Zarrin */
UPDATE locales_points_of_interest SET icon_name_loc1='알란나 레이븐아이' WHERE entry=120; /* icon_name: Alanna Raveneye */
UPDATE locales_points_of_interest SET icon_name_loc1='비얀시' WHERE entry=121; /* icon_name: Byancie */
UPDATE locales_points_of_interest SET icon_name_loc1='말로른 블레이드리프' WHERE entry=122; /* icon_name: Malorne Bladeleaf */
UPDATE locales_points_of_interest SET icon_name_loc1='나디야 메인위버' WHERE entry=123; /* icon_name: Nadyia Maneweaver */
UPDATE locales_points_of_interest SET icon_name_loc1='래드날 메인위버' WHERE entry=124; /* icon_name: Radnaal Maneweaver */
UPDATE locales_points_of_interest SET icon_name_loc1='나디야 메인위버' WHERE entry=125; /* icon_name: Nadyia Maneweaver */
UPDATE locales_points_of_interest SET icon_name_loc1='오그리마 은행' WHERE entry=176; /* icon_name: Bank of Orgrimmar */
UPDATE locales_points_of_interest SET icon_name_loc1='호드 대사관' WHERE entry=178; /* icon_name: Horde Embassy */
UPDATE locales_points_of_interest SET icon_name_loc1='오그리마 경매장' WHERE entry=181; /* icon_name: Orgrimmar Auction House */
UPDATE locales_points_of_interest SET icon_name_loc1='손차' WHERE entry=185; /* icon_name: Xon\'cha */
UPDATE locales_points_of_interest SET icon_name_loc1='전설의 전당' WHERE entry=186; /* icon_name: Hall of Legends */
UPDATE locales_points_of_interest SET icon_name_loc1='크룬' WHERE entry=238; /* icon_name: Krunn */
UPDATE locales_points_of_interest SET icon_name_loc1='미시키' WHERE entry=239; /* icon_name: Mishiki */
UPDATE locales_points_of_interest SET icon_name_loc1='라우티키' WHERE entry=240; /* icon_name: Lau\'Tiki */
UPDATE locales_points_of_interest SET icon_name_loc1='로울크' WHERE entry=241; /* icon_name: Rawrk */
UPDATE locales_points_of_interest SET icon_name_loc1='머크드락' WHERE entry=242; /* icon_name: Mukdrak */
UPDATE locales_points_of_interest SET icon_name_loc1='드우크' WHERE entry=243; /* icon_name: Dwukk */
UPDATE locales_points_of_interest SET icon_name_loc1='미아오잔' WHERE entry=244; /* icon_name: Miao\'zan */
UPDATE locales_points_of_interest SET icon_name_loc1='타쇼 재기드스카' WHERE entry=245; /* icon_name: Tarshaw Jaggedscar */
UPDATE locales_points_of_interest SET icon_name_loc1='두그루 고어러스트' WHERE entry=246; /* icon_name: Dhugru Gorelust */
UPDATE locales_points_of_interest SET icon_name_loc1='스워트' WHERE entry=247; /* icon_name: Swart */
UPDATE locales_points_of_interest SET icon_name_loc1='카플라크' WHERE entry=248; /* icon_name: Kaplak */
UPDATE locales_points_of_interest SET icon_name_loc1='타이진' WHERE entry=249; /* icon_name: Tai\'jin */
UPDATE locales_points_of_interest SET icon_name_loc1='운투와' WHERE entry=250; /* icon_name: Un\'Thuwa */
UPDATE locales_points_of_interest SET icon_name_loc1='소타르' WHERE entry=251; /* icon_name: Thotar */
UPDATE locales_points_of_interest SET icon_name_loc1='쇼자미' WHERE entry=252; /* icon_name: Shoja\'my */
UPDATE locales_points_of_interest SET icon_name_loc1='연금술 실험실' WHERE entry=266; /* icon_name: The Apothecarium */
UPDATE locales_points_of_interest SET icon_name_loc1='용사 키사 돈로즈' WHERE entry=271; /* icon_name: Champion Cyssa Dawnrose */
UPDATE locales_points_of_interest SET icon_name_loc1='아키발드' WHERE entry=274; /* icon_name: Archibald */
UPDATE locales_points_of_interest SET icon_name_loc1='안야 마울레이' WHERE entry=275; /* icon_name: Anya Maulray */
UPDATE locales_points_of_interest SET icon_name_loc1='언더시티 경매장' WHERE entry=284; /* icon_name: Undercity Auction House */
UPDATE locales_points_of_interest SET icon_name_loc1='보웬 브리스부아즈' WHERE entry=285; /* icon_name: Bowen Brisboise */
UPDATE locales_points_of_interest SET icon_name_loc1='랜드 로바트' WHERE entry=286; /* icon_name: Rand Rhobart */
UPDATE locales_points_of_interest SET icon_name_loc1='셸렌 로바트' WHERE entry=287; /* icon_name: Shelene Rhobart */
UPDATE locales_points_of_interest SET icon_name_loc1='파루자' WHERE entry=288; /* icon_name: Faruza */
UPDATE locales_points_of_interest SET icon_name_loc1='클리데 켈렌' WHERE entry=289; /* icon_name: Clyde Kellen */
UPDATE locales_points_of_interest SET icon_name_loc1='간호사 닐라' WHERE entry=290; /* icon_name: Nurse Neela */
UPDATE locales_points_of_interest SET icon_name_loc1='밴스 언더글룸' WHERE entry=291; /* icon_name: Vance Undergloom */
UPDATE locales_points_of_interest SET icon_name_loc1='캐롤라이 아니즈' WHERE entry=292; /* icon_name: Carolai Anise */
UPDATE locales_points_of_interest SET icon_name_loc1='오스틸 드 몽' WHERE entry=293; /* icon_name: Austil de Mon */
UPDATE locales_points_of_interest SET icon_name_loc1='루퍼트 보흐' WHERE entry=294; /* icon_name: Rupert Boch */
UPDATE locales_points_of_interest SET icon_name_loc1='매리언 콜' WHERE entry=295; /* icon_name: Marion Call */
UPDATE locales_points_of_interest SET icon_name_loc1='모르가누스' WHERE entry=296; /* icon_name: Morganus */
UPDATE locales_points_of_interest SET icon_name_loc1='어둠의 사제 베릴' WHERE entry=297; /* icon_name: Dark Cleric Beryl */
UPDATE locales_points_of_interest SET icon_name_loc1='케인 파이어송' WHERE entry=298; /* icon_name: Cain Firesong */
UPDATE locales_points_of_interest SET icon_name_loc1='교수대끝 선술집' WHERE entry=299; /* icon_name: Gallows\' End Tavern */
UPDATE locales_points_of_interest SET icon_name_loc1='썬더 블러프 갑옷 상점' WHERE entry=301; /* icon_name: Thunder Bluff Armorers */
UPDATE locales_points_of_interest SET icon_name_loc1='무란타' WHERE entry=302; /* icon_name: Mooranta */
UPDATE locales_points_of_interest SET icon_name_loc1='스톤후프 지질연구소' WHERE entry=303; /* icon_name: Stonehoof Geology */
UPDATE locales_points_of_interest SET icon_name_loc1='썬더 블러프 갑옷 상점' WHERE entry=304; /* icon_name: Thunder Bluff Armorers */
UPDATE locales_points_of_interest SET icon_name_loc1='조화의 약초상점' WHERE entry=306; /* icon_name: Holistic Herbalism */
UPDATE locales_points_of_interest SET icon_name_loc1='산꼭대기 낚시용품점' WHERE entry=307; /* icon_name: Mountaintop Bait & Tackle */
UPDATE locales_points_of_interest SET icon_name_loc1='정기의 치료소' WHERE entry=308; /* icon_name: Spiritual Healing */
UPDATE locales_points_of_interest SET icon_name_loc1='돈스트라이더의 마법부여점' WHERE entry=309; /* icon_name: Dawnstrider Enchanters */
UPDATE locales_points_of_interest SET icon_name_loc1='아스카의 주방' WHERE entry=310; /* icon_name: Aska\'s Kitchen */
UPDATE locales_points_of_interest SET icon_name_loc1='카른 대장간' WHERE entry=311; /* icon_name: Karn\'s Smithy */
UPDATE locales_points_of_interest SET icon_name_loc1='베나의 연금술점' WHERE entry=312; /* icon_name: Bena\'s Alchemy */
UPDATE locales_points_of_interest SET icon_name_loc1='사냥꾼의 전당' WHERE entry=313; /* icon_name: Hunter\'s Hall */
UPDATE locales_points_of_interest SET icon_name_loc1='정기의 전당' WHERE entry=314; /* icon_name: Hall of Spirits */
UPDATE locales_points_of_interest SET icon_name_loc1='예언의 웅덩이' WHERE entry=315; /* icon_name: Pools of Vision */
UPDATE locales_points_of_interest SET icon_name_loc1='장로의 전당' WHERE entry=316; /* icon_name: Hall of Elders */
UPDATE locales_points_of_interest SET icon_name_loc1='불루그' WHERE entry=318; /* icon_name: Bulrug */
UPDATE locales_points_of_interest SET icon_name_loc1='안세크화' WHERE entry=319; /* icon_name: Ansekhwa */
UPDATE locales_points_of_interest SET icon_name_loc1='썬더 블러프 길드 사무소' WHERE entry=323; /* icon_name: Thunder Bluff Civic Information */
UPDATE locales_points_of_interest SET icon_name_loc1='썬더 블러프 은행' WHERE entry=325; /* icon_name: Thunder Bluff Bank */
UPDATE locales_points_of_interest SET icon_name_loc1='욘 디프컷' WHERE entry=326; /* icon_name: Yonn Deepcut */
UPDATE locales_points_of_interest SET icon_name_loc1='초우 스트롱하이드' WHERE entry=327; /* icon_name: Chaw Stronghide */
UPDATE locales_points_of_interest SET icon_name_loc1='우탄 스틸워터' WHERE entry=329; /* icon_name: Uthan Stillwater */
UPDATE locales_points_of_interest SET icon_name_loc1='비라 영후프' WHERE entry=330; /* icon_name: Vira Younghoof */
UPDATE locales_points_of_interest SET icon_name_loc1='피알 사일런트스트라이드' WHERE entry=331; /* icon_name: Pyall Silentstride */
UPDATE locales_points_of_interest SET icon_name_loc1='크랑 스톤후프' WHERE entry=332; /* icon_name: Krang Stonehoof */
UPDATE locales_points_of_interest SET icon_name_loc1='나름 스카이체이서' WHERE entry=334; /* icon_name: Narm Skychaser */
UPDATE locales_points_of_interest SET icon_name_loc1='요 샤프메인' WHERE entry=335; /* icon_name: Yaw Sharpmane */
UPDATE locales_points_of_interest SET icon_name_loc1='제니아 룬토템' WHERE entry=336; /* icon_name: Gennia Runetotem */
UPDATE locales_points_of_interest SET icon_name_loc1='세이크와' WHERE entry=337; /* icon_name: Seikwa */
UPDATE locales_points_of_interest SET icon_name_loc1='얄 해머스톤' WHERE entry=339; /* icon_name: Yarr Hammerstone */
UPDATE locales_points_of_interest SET icon_name_loc1='약초상 포메로이' WHERE entry=363; /* icon_name: Herbalist Pomeroy */
UPDATE locales_points_of_interest SET icon_name_loc1='달의 신전' WHERE entry=364; /* icon_name: Temple of the Moon */
UPDATE locales_points_of_interest SET icon_name_loc1='스프링스핀들의 고물상' WHERE entry=419; /* icon_name: Springspindle\'s Gadgets */
UPDATE locales_points_of_interest SET icon_name_loc1='검은장미 오두막' WHERE entry=421; /* icon_name: Darkbriar Lodge */
UPDATE locales_points_of_interest SET icon_name_loc1='정기의 오두막' WHERE entry=422; /* icon_name: Spirit Lodge */
UPDATE locales_points_of_interest SET icon_name_loc1='스랄의 요새' WHERE entry=423; /* icon_name: Thrall\'s Fortress */
UPDATE locales_points_of_interest SET icon_name_loc1='날쌘그림자 결사단' WHERE entry=424; /* icon_name: Shadowswift Brotherhood */
UPDATE locales_points_of_interest SET icon_name_loc1='검은불꽃 비밀집회' WHERE entry=425; /* icon_name: Darkfire Enclave */
UPDATE locales_points_of_interest SET icon_name_loc1='용사의 전당' WHERE entry=426; /* icon_name: Hall of the Brave */
UPDATE locales_points_of_interest SET icon_name_loc1='옐마크의 연금술용품점' WHERE entry=427; /* icon_name: Yelmak\'s Alchemy and Potions */
UPDATE locales_points_of_interest SET icon_name_loc1='불타는 모루' WHERE entry=428; /* icon_name: The Burning Anvil */
UPDATE locales_points_of_interest SET icon_name_loc1='보르스탄의 아궁이' WHERE entry=429; /* icon_name: Borstan\'s Firepit */
UPDATE locales_points_of_interest SET icon_name_loc1='고단의 마법상점' WHERE entry=430; /* icon_name: Godan\'s Runeworks */
UPDATE locales_points_of_interest SET icon_name_loc1='노그의 작업소' WHERE entry=431; /* icon_name: Nogg\'s Machine Shop */
UPDATE locales_points_of_interest SET icon_name_loc1='적자 생존' WHERE entry=432; /* icon_name: Survival of the Fittest */
UPDATE locales_points_of_interest SET icon_name_loc1='루막의 낚시용품점' WHERE entry=433; /* icon_name: Lumak\'s Fishing */
UPDATE locales_points_of_interest SET icon_name_loc1='잔디의 수목원' WHERE entry=434; /* icon_name: Jandi\'s Arboretum */
UPDATE locales_points_of_interest SET icon_name_loc1='붉은협곡 광부조합' WHERE entry=435; /* icon_name: Red Canyon Mining */
UPDATE locales_points_of_interest SET icon_name_loc1='코도 가죽용품점' WHERE entry=436; /* icon_name: Kodohide Leatherworkers */
UPDATE locales_points_of_interest SET icon_name_loc1='마가르의 의류점' WHERE entry=437; /* icon_name: Magar\'s Cloth Goods */

SET NAMES 'latin1';
