-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE script_texts SET content_loc1='항상 조심하라.' WHERE entry=-1000482; /* content: Look out! */
UPDATE script_texts SET content_loc1='왕께 경배를!' WHERE entry=-1230002; /* content: Hail to the king, baby! */

SET NAMES 'latin1';
