-- File generated by Mangos Online Translation Editor (MOTE) v2.10
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc9`='Metal Mace' WHERE `word_id` = 114253; -- locales_gameobject - name : entry=386
UPDATE `trans_words` SET `content_loc9`='Uther the Lightbringer' WHERE `word_id` = 93584; -- locales_gameobject - name : entry=2082
UPDATE `trans_words` SET `content_loc9`='Stranglevine Wine' WHERE `word_id` = 114376; -- locales_gameobject - name : entry=2333
UPDATE `trans_words` SET `content_loc9`='Keystone' WHERE `word_id` = 114399; -- locales_gameobject - name : entry=2688
UPDATE `trans_words` SET `content_loc9`='Stormbull Water Well' WHERE `word_id` = 114440; -- locales_gameobject - name : entry=2911
UPDATE `trans_words` SET `content_loc9`='Longtoo - Teapee' WHERE `word_id` = 114461; -- locales_gameobject - name : entry=3265
UPDATE `trans_words` SET `content_loc9`='Buzzbox 827' WHERE `word_id` = 114554; -- locales_gameobject - name : entry=17182
UPDATE `trans_words` SET `content_loc9`='Buzzbox 411' WHERE `word_id` = 114555; -- locales_gameobject - name : entry=17183
UPDATE `trans_words` SET `content_loc9`='Buzzbox 323' WHERE `word_id` = 114556; -- locales_gameobject - name : entry=17184
UPDATE `trans_words` SET `content_loc9`='Buzzbox 525' WHERE `word_id` = 114557; -- locales_gameobject - name : entry=17185
UPDATE `trans_words` SET `content_loc9`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18047
UPDATE `trans_words` SET `content_loc9`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18048
UPDATE `trans_words` SET `content_loc9`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18049
UPDATE `trans_words` SET `content_loc9`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18050
UPDATE `trans_words` SET `content_loc9`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18051
UPDATE `trans_words` SET `content_loc9`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18052
UPDATE `trans_words` SET `content_loc9`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18053
UPDATE `trans_words` SET `content_loc9`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18054
UPDATE `trans_words` SET `content_loc9`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18055
UPDATE `trans_words` SET `content_loc9`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18056
UPDATE `trans_words` SET `content_loc9`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18057
UPDATE `trans_words` SET `content_loc9`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18058
UPDATE `trans_words` SET `content_loc9`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18059
UPDATE `trans_words` SET `content_loc9`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18060
UPDATE `trans_words` SET `content_loc9`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18061
UPDATE `trans_words` SET `content_loc9`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18062
UPDATE `trans_words` SET `content_loc9`='Arugal\'s Focus' WHERE `word_id` = 114567; -- locales_gameobject - name : entry=18973
UPDATE `trans_words` SET `content_loc9`='Goblin Shredder Suit' WHERE `word_id` = 114603; -- locales_gameobject - name : entry=19582
UPDATE `trans_words` SET `content_loc9`='Night Elf Moon Well' WHERE `word_id` = 114651; -- locales_gameobject - name : entry=20818
UPDATE `trans_words` SET `content_loc9`='Moon Well 2' WHERE `word_id` = 114652; -- locales_gameobject - name : entry=20819
UPDATE `trans_words` SET `content_loc9`='unk' WHERE `word_id` = 114688; -- locales_gameobject - name : entry=21653
UPDATE `trans_words` SET `content_loc9`='unk' WHERE `word_id` = 114688; -- locales_gameobject - name : entry=21654
UPDATE `trans_words` SET `content_loc9`='unk' WHERE `word_id` = 114688; -- locales_gameobject - name : entry=21655
UPDATE `trans_words` SET `content_loc9`='unk' WHERE `word_id` = 114688; -- locales_gameobject - name : entry=21656
UPDATE `trans_words` SET `content_loc9`='Kurdran Wildhammer' WHERE `word_id` = 88473; -- locales_gameobject - name : entry=25329
UPDATE `trans_words` SET `content_loc9`='Danath Trollbane' WHERE `word_id` = 114711; -- locales_gameobject - name : entry=25332
UPDATE `trans_words` SET `content_loc9`='Recombobulator' WHERE `word_id` = 114714; -- locales_gameobject - name : entry=26449
UPDATE `trans_words` SET `content_loc9`='Ironforge Main Gate' WHERE `word_id` = 114748; -- locales_gameobject - name : entry=32355
UPDATE `trans_words` SET `content_loc9`='The Commerce Ward' WHERE `word_id` = 114750; -- locales_gameobject - name : entry=32357
UPDATE `trans_words` SET `content_loc9`='The Commerce Ward' WHERE `word_id` = 114750; -- locales_gameobject - name : entry=32361
UPDATE `trans_words` SET `content_loc9`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32364
UPDATE `trans_words` SET `content_loc9`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32366
UPDATE `trans_words` SET `content_loc9`='Ironforge Main Gate' WHERE `word_id` = 114748; -- locales_gameobject - name : entry=32367
UPDATE `trans_words` SET `content_loc9`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32368
UPDATE `trans_words` SET `content_loc9`='Ironforge Main Gate' WHERE `word_id` = 114748; -- locales_gameobject - name : entry=32370
UPDATE `trans_words` SET `content_loc9`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32376
UPDATE `trans_words` SET `content_loc9`='The Forlorn Caverns' WHERE `word_id` = 114756; -- locales_gameobject - name : entry=32381
UPDATE `trans_words` SET `content_loc9`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32384
UPDATE `trans_words` SET `content_loc9`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32388
UPDATE `trans_words` SET `content_loc9`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32393
UPDATE `trans_words` SET `content_loc9`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32394
UPDATE `trans_words` SET `content_loc9`='Ironforge Main Gate' WHERE `word_id` = 114748; -- locales_gameobject - name : entry=32396
UPDATE `trans_words` SET `content_loc9`='Ironforge Main Gate' WHERE `word_id` = 114748; -- locales_gameobject - name : entry=32397
UPDATE `trans_words` SET `content_loc9`='Ironforge Main Gate' WHERE `word_id` = 114748; -- locales_gameobject - name : entry=32398
UPDATE `trans_words` SET `content_loc9`='Ironforge Main Gate' WHERE `word_id` = 114748; -- locales_gameobject - name : entry=32399
UPDATE `trans_words` SET `content_loc9`='The Commerce Ward' WHERE `word_id` = 114750; -- locales_gameobject - name : entry=32400
UPDATE `trans_words` SET `content_loc9`='The Commerce Ward' WHERE `word_id` = 114750; -- locales_gameobject - name : entry=32401
UPDATE `trans_words` SET `content_loc9`='Ironforge Main Gate' WHERE `word_id` = 114748; -- locales_gameobject - name : entry=32402
UPDATE `trans_words` SET `content_loc9`='The Commerce Ward' WHERE `word_id` = 114750; -- locales_gameobject - name : entry=32403
UPDATE `trans_words` SET `content_loc9`='Ironforge Main Gate' WHERE `word_id` = 114748; -- locales_gameobject - name : entry=32405
UPDATE `trans_words` SET `content_loc9`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32406
UPDATE `trans_words` SET `content_loc9`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32407
UPDATE `trans_words` SET `content_loc9`='The Commerce Ward' WHERE `word_id` = 114750; -- locales_gameobject - name : entry=32409
UPDATE `trans_words` SET `content_loc9`='Ironforge Main Gate' WHERE `word_id` = 114748; -- locales_gameobject - name : entry=32410
UPDATE `trans_words` SET `content_loc9`='Ironforge Main Gate' WHERE `word_id` = 114748; -- locales_gameobject - name : entry=32411
UPDATE `trans_words` SET `content_loc9`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32412
UPDATE `trans_words` SET `content_loc9`='The Commerce Ward' WHERE `word_id` = 114750; -- locales_gameobject - name : entry=32414
UPDATE `trans_words` SET `content_loc9`='The Commerce Ward' WHERE `word_id` = 114750; -- locales_gameobject - name : entry=32417
UPDATE `trans_words` SET `content_loc9`='The Commerce Ward' WHERE `word_id` = 114750; -- locales_gameobject - name : entry=32420
UPDATE `trans_words` SET `content_loc9`='Ironforge Main Gate' WHERE `word_id` = 114748; -- locales_gameobject - name : entry=32430
UPDATE `trans_words` SET `content_loc9`='Ironforge Main Gate' WHERE `word_id` = 114748; -- locales_gameobject - name : entry=32440
UPDATE `trans_words` SET `content_loc9`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32783
UPDATE `trans_words` SET `content_loc9`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32784
UPDATE `trans_words` SET `content_loc9`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32785
UPDATE `trans_words` SET `content_loc9`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32787
UPDATE `trans_words` SET `content_loc9`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32792
UPDATE `trans_words` SET `content_loc9`='Fire on ground' WHERE `word_id` = 114820; -- locales_gameobject - name : entry=56809
UPDATE `trans_words` SET `content_loc9`='Vator' WHERE `word_id` = 114871; -- locales_gameobject - name : entry=80023
UPDATE `trans_words` SET `content_loc9`='Vator2' WHERE `word_id` = 114874; -- locales_gameobject - name : entry=85556
UPDATE `trans_words` SET `content_loc9`='Cathedral Door' WHERE `word_id` = 114902; -- locales_gameobject - name : entry=101850
UPDATE `trans_words` SET `content_loc9`='Fire With Boiling Water' WHERE `word_id` = 114910; -- locales_gameobject - name : entry=103773
UPDATE `trans_words` SET `content_loc9`='Keystone' WHERE `word_id` = 114399; -- locales_gameobject - name : entry=124371
UPDATE `trans_words` SET `content_loc9`='Horatio Montgomery, M.D.' WHERE `word_id` = 114961; -- locales_gameobject - name : entry=124374
UPDATE `trans_words` SET `content_loc9`='Troll Cage' WHERE `word_id` = 114986; -- locales_gameobject - name : entry=141070
UPDATE `trans_words` SET `content_loc9`='Troll Cage' WHERE `word_id` = 114986; -- locales_gameobject - name : entry=141071
UPDATE `trans_words` SET `content_loc9`='Troll Cage' WHERE `word_id` = 114986; -- locales_gameobject - name : entry=141072
UPDATE `trans_words` SET `content_loc9`='Troll Cage' WHERE `word_id` = 114986; -- locales_gameobject - name : entry=141073
UPDATE `trans_words` SET `content_loc9`='Troll Cage' WHERE `word_id` = 114986; -- locales_gameobject - name : entry=141074
UPDATE `trans_words` SET `content_loc9`='Egg-O-Matic' WHERE `word_id` = 114997; -- locales_gameobject - name : entry=142071
UPDATE `trans_words` SET `content_loc9`='Transpolyporter BB' WHERE `word_id` = 115000; -- locales_gameobject - name : entry=142172
UPDATE `trans_words` SET `content_loc9`='Transpolyporter' WHERE `word_id` = 115001; -- locales_gameobject - name : entry=142175
UPDATE `trans_words` SET `content_loc9`='Transpolyporter' WHERE `word_id` = 115001; -- locales_gameobject - name : entry=142176
UPDATE `trans_words` SET `content_loc9`='Matrix Punchograph 3005-A' WHERE `word_id` = 115023; -- locales_gameobject - name : entry=142345
UPDATE `trans_words` SET `content_loc9`='Matrix Punchograph 3005-B' WHERE `word_id` = 115024; -- locales_gameobject - name : entry=142475
UPDATE `trans_words` SET `content_loc9`='Matrix Punchograph 3005-C' WHERE `word_id` = 115025; -- locales_gameobject - name : entry=142476
UPDATE `trans_words` SET `content_loc9`='Matrix Punchograph 3005-D' WHERE `word_id` = 115029; -- locales_gameobject - name : entry=142696
UPDATE `trans_words` SET `content_loc9`='Transpolyporter DRBB' WHERE `word_id` = 115034; -- locales_gameobject - name : entry=143230
UPDATE `trans_words` SET `content_loc9`='Eternal Flame' WHERE `word_id` = 115061; -- locales_gameobject - name : entry=148418
UPDATE `trans_words` SET `content_loc9`='Eternal Flame' WHERE `word_id` = 115061; -- locales_gameobject - name : entry=148419
UPDATE `trans_words` SET `content_loc9`='Eternal Flame' WHERE `word_id` = 115061; -- locales_gameobject - name : entry=148420
UPDATE `trans_words` SET `content_loc9`='Eternal Flame' WHERE `word_id` = 115061; -- locales_gameobject - name : entry=148421
UPDATE `trans_words` SET `content_loc9`='Ani' WHERE `word_id` = 115088; -- locales_gameobject - name : entry=149420
UPDATE `trans_words` SET `content_loc9`='Aura 1 - Linken' WHERE `word_id` = 115160; -- locales_gameobject - name : entry=164826
UPDATE `trans_words` SET `content_loc9`='Aura 2 - Linken' WHERE `word_id` = 115161; -- locales_gameobject - name : entry=164827
UPDATE `trans_words` SET `content_loc9`='Orgrimmar - Undercity' WHERE `word_id` = 115167; -- locales_gameobject - name : entry=164871
UPDATE `trans_words` SET `content_loc9`='Ironforge Main Gate' WHERE `word_id` = 114748; -- locales_gameobject - name : entry=171526
UPDATE `trans_words` SET `content_loc9`='AuctionNode' WHERE `word_id` = 115290; -- locales_gameobject - name : entry=173227
UPDATE `trans_words` SET `content_loc9`='Bed' WHERE `word_id` = 115307; -- locales_gameobject - name : entry=174849
UPDATE `trans_words` SET `content_loc9`='Grom\'Gol Base Camp - Orgrimmar' WHERE `word_id` = 115320; -- locales_gameobject - name : entry=175080
UPDATE `trans_words` SET `content_loc9`='Service Entrance Gate' WHERE `word_id` = 115371; -- locales_gameobject - name : entry=175368
UPDATE `trans_words` SET `content_loc9`='Elders\' Square Service Entrance' WHERE `word_id` = 115372; -- locales_gameobject - name : entry=175369
UPDATE `trans_words` SET `content_loc9`='Geru Strider' WHERE `word_id` = 115453; -- locales_gameobject - name : entry=175682
UPDATE `trans_words` SET `content_loc9`='Arellas Fireleaf' WHERE `word_id` = 115498; -- locales_gameobject - name : entry=175771
UPDATE `trans_words` SET `content_loc9`='Dorgar Stoenbrow' WHERE `word_id` = 115499; -- locales_gameobject - name : entry=175773
UPDATE `trans_words` SET `content_loc9`='Fellari Swiftarrow' WHERE `word_id` = 115500; -- locales_gameobject - name : entry=175774
UPDATE `trans_words` SET `content_loc9`='Ferren Marcus' WHERE `word_id` = 115501; -- locales_gameobject - name : entry=175775
UPDATE `trans_words` SET `content_loc9`='Harthal Truesight' WHERE `word_id` = 115502; -- locales_gameobject - name : entry=175776
UPDATE `trans_words` SET `content_loc9`='Holia Sunshield' WHERE `word_id` = 115503; -- locales_gameobject - name : entry=175777
UPDATE `trans_words` SET `content_loc9`='Invar One-Arm' WHERE `word_id` = 115504; -- locales_gameobject - name : entry=175778
UPDATE `trans_words` SET `content_loc9`='Valea Twinblades' WHERE `word_id` = 115506; -- locales_gameobject - name : entry=175780
UPDATE `trans_words` SET `content_loc9`='Yana Bloodspear' WHERE `word_id` = 115507; -- locales_gameobject - name : entry=175781
UPDATE `trans_words` SET `content_loc9`='Locked Cage' WHERE `word_id` = 115510; -- locales_gameobject - name : entry=175786
UPDATE `trans_words` SET `content_loc9`='Dawn\'s Gambit' WHERE `word_id` = 16603; -- locales_gameobject - name : entry=176110
UPDATE `trans_words` SET `content_loc9`='Musty Tome Trap' WHERE `word_id` = 115555; -- locales_gameobject - name : entry=176152
UPDATE `trans_words` SET `content_loc9`='Bowel with Boobles' WHERE `word_id` = 115556; -- locales_gameobject - name : entry=176157
UPDATE `trans_words` SET `content_loc9`='Moonspray' WHERE `word_id` = 115575; -- locales_gameobject - name : entry=176244
UPDATE `trans_words` SET `content_loc9`='Serenity\'s Shore' WHERE `word_id` = 115580; -- locales_gameobject - name : entry=176310
UPDATE `trans_words` SET `content_loc9`='Grom\'Gol Base Camp - Undercity' WHERE `word_id` = 115596; -- locales_gameobject - name : entry=176495
UPDATE `trans_words` SET `content_loc9`='Plaguebloom' WHERE `word_id` = 17386; -- locales_gameobject - name : entry=176587
UPDATE `trans_words` SET `content_loc9`='Plaguebloom' WHERE `word_id` = 17386; -- locales_gameobject - name : entry=176641
UPDATE `trans_words` SET `content_loc9`='Lady Mara Fordragon' WHERE `word_id` = 115691; -- locales_gameobject - name : entry=177202
UPDATE `trans_words` SET `content_loc9`='Pull rope Bell' WHERE `word_id` = 115726; -- locales_gameobject - name : entry=177271
UPDATE `trans_words` SET `content_loc9`='Dawn\'s Gambit' WHERE `word_id` = 16603; -- locales_gameobject - name : entry=177304
UPDATE `trans_words` SET `content_loc9`='Mercutio Post' WHERE `word_id` = 115781; -- locales_gameobject - name : entry=177905
UPDATE `trans_words` SET `content_loc9`='Resonite Cask' WHERE `word_id` = 115857; -- locales_gameobject - name : entry=178145
UPDATE `trans_words` SET `content_loc9`='Mercutio Post' WHERE `word_id` = 115781; -- locales_gameobject - name : entry=178264
UPDATE `trans_words` SET `content_loc9`='Mercutio Post' WHERE `word_id` = 115781; -- locales_gameobject - name : entry=178265
UPDATE `trans_words` SET `content_loc9`='Larva Spewer' WHERE `word_id` = 115908; -- locales_gameobject - name : entry=178559
UPDATE `trans_words` SET `content_loc9`='Smokywood Pastures' WHERE `word_id` = 80219; -- locales_gameobject - name : entry=178746
UPDATE `trans_words` SET `content_loc9`='Rope Line' WHERE `word_id` = 115923; -- locales_gameobject - name : entry=178764
UPDATE `trans_words` SET `content_loc9`='Rope Line Pole' WHERE `word_id` = 115924; -- locales_gameobject - name : entry=178765
UPDATE `trans_words` SET `content_loc9`='Vylestem Vine' WHERE `word_id` = 115928; -- locales_gameobject - name : entry=178905
UPDATE `trans_words` SET `content_loc9`='Vylestem Vine' WHERE `word_id` = 115928; -- locales_gameobject - name : entry=178908
UPDATE `trans_words` SET `content_loc9`='SmallBrazier31' WHERE `word_id` = 116030; -- locales_gameobject - name : entry=179874
UPDATE `trans_words` SET `content_loc9`='SmallBrazier19' WHERE `word_id` = 116031; -- locales_gameobject - name : entry=179875
UPDATE `trans_words` SET `content_loc9`='SmallBrazier03' WHERE `word_id` = 116032; -- locales_gameobject - name : entry=179876
UPDATE `trans_words` SET `content_loc9`='SmallBrazier04' WHERE `word_id` = 116033; -- locales_gameobject - name : entry=179877
UPDATE `trans_words` SET `content_loc9`='SmallBrazier01' WHERE `word_id` = 116034; -- locales_gameobject - name : entry=179878
UPDATE `trans_words` SET `content_loc9`='Shoutbox' WHERE `word_id` = 116084; -- locales_gameobject - name : entry=180044
UPDATE `trans_words` SET `content_loc9`='Whipweed' WHERE `word_id` = 116105; -- locales_gameobject - name : entry=180216
UPDATE `trans_words` SET `content_loc9`='Candle 02' WHERE `word_id` = 116142; -- locales_gameobject - name : entry=180339
UPDATE `trans_words` SET `content_loc9`='Candle 03' WHERE `word_id` = 116143; -- locales_gameobject - name : entry=180340
UPDATE `trans_words` SET `content_loc9`='Soapbox' WHERE `word_id` = 116174; -- locales_gameobject - name : entry=180403
UPDATE `trans_words` SET `content_loc9`='Wickerman Guardian Ember' WHERE `word_id` = 117017; -- locales_gameobject - name : entry=180574
UPDATE `trans_words` SET `content_loc9`='Cheer Speaker' WHERE `word_id` = 116292; -- locales_gameobject - name : entry=180749
UPDATE `trans_words` SET `content_loc9`='PX-238 Winter Wondervolt' WHERE `word_id` = 116314; -- locales_gameobject - name : entry=180796
UPDATE `trans_words` SET `content_loc9`='War Map' WHERE `word_id` = 116360; -- locales_gameobject - name : entry=180852
UPDATE `trans_words` SET `content_loc9`='Duke\'s Box' WHERE `word_id` = 116361; -- locales_gameobject - name : entry=180853
UPDATE `trans_words` SET `content_loc9`='Kel\'Thuzad Trigger' WHERE `word_id` = 116527; -- locales_gameobject - name : entry=181444
UPDATE `trans_words` SET `content_loc9`='Fel Reaver Cap Pt' WHERE `word_id` = 116695; -- locales_gameobject - name : entry=184081
UPDATE `trans_words` SET `content_loc9`='Scrying Aura' WHERE `word_id` = 116700; -- locales_gameobject - name : entry=184119
UPDATE `trans_words` SET `content_loc9`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184507
UPDATE `trans_words` SET `content_loc9`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184508
UPDATE `trans_words` SET `content_loc9`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184509
UPDATE `trans_words` SET `content_loc9`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184511
UPDATE `trans_words` SET `content_loc9`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184512
UPDATE `trans_words` SET `content_loc9`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184513
UPDATE `trans_words` SET `content_loc9`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184514
UPDATE `trans_words` SET `content_loc9`='Wooden Board' WHERE `word_id` = 116718; -- locales_gameobject - name : entry=184515
UPDATE `trans_words` SET `content_loc9`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184563
UPDATE `trans_words` SET `content_loc9`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184564
UPDATE `trans_words` SET `content_loc9`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184579
UPDATE `trans_words` SET `content_loc9`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184580
UPDATE `trans_words` SET `content_loc9`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184581
UPDATE `trans_words` SET `content_loc9`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184582
UPDATE `trans_words` SET `content_loc9`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184583
UPDATE `trans_words` SET `content_loc9`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184584
UPDATE `trans_words` SET `content_loc9`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184585
UPDATE `trans_words` SET `content_loc9`='Barrel A' WHERE `word_id` = 116738; -- locales_gameobject - name : entry=184863
UPDATE `trans_words` SET `content_loc9`='Don de Mordant' WHERE `word_id` = 116852; -- locales_gameobject - name : entry=186418
UPDATE `trans_words` SET `content_loc9`='Torche en sorbier' WHERE `word_id` = 116853; -- locales_gameobject - name : entry=186425

SET NAMES 'latin1';
