-- File generated by Mangos Online Translation Editor (MOTE) v2.10
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc9`='Zaldimar Wefhellt' WHERE `word_id` = 72463; -- locales_points_of_interest - icon_name : entry=2
UPDATE `trans_words` SET `content_loc9`='Priestess Josetta' WHERE `word_id` = 72497; -- locales_points_of_interest - icon_name : entry=4
UPDATE `trans_words` SET `content_loc9`='Keryn Sylvius' WHERE `word_id` = 72902; -- locales_points_of_interest - icon_name : entry=5
UPDATE `trans_words` SET `content_loc9`='Maximillian Crowe' WHERE `word_id` = 72889; -- locales_points_of_interest - icon_name : entry=6
UPDATE `trans_words` SET `content_loc9`='Lyria Du Lac' WHERE `word_id` = 72897; -- locales_points_of_interest - icon_name : entry=7
UPDATE `trans_words` SET `content_loc9`='Smith Argus' WHERE `word_id` = 72592; -- locales_points_of_interest - icon_name : entry=9
UPDATE `trans_words` SET `content_loc9`='Tomas' WHERE `word_id` = 73402; -- locales_points_of_interest - icon_name : entry=10
UPDATE `trans_words` SET `content_loc9`='Michelle Belle' WHERE `word_id` = 74081; -- locales_points_of_interest - icon_name : entry=11
UPDATE `trans_words` SET `content_loc9`='Lee Brown' WHERE `word_id` = 73545; -- locales_points_of_interest - icon_name : entry=12
UPDATE `trans_words` SET `content_loc9`='Adele Fielder' WHERE `word_id` = 73538; -- locales_points_of_interest - icon_name : entry=14
UPDATE `trans_words` SET `content_loc9`='Helene Peltskinner' WHERE `word_id` = 77268; -- locales_points_of_interest - icon_name : entry=15
UPDATE `trans_words` SET `content_loc9`='Eldrin' WHERE `word_id` = 73064; -- locales_points_of_interest - icon_name : entry=16
UPDATE `trans_words` SET `content_loc9`='Erma' WHERE `word_id` = 77425; -- locales_points_of_interest - icon_name : entry=17
UPDATE `trans_words` SET `content_loc9`='Stormwind Bank' WHERE `word_id` = 127169; -- locales_points_of_interest - icon_name : entry=19
UPDATE `trans_words` SET `content_loc9`='The Deeprun Tram' WHERE `word_id` = 127170; -- locales_points_of_interest - icon_name : entry=21
UPDATE `trans_words` SET `content_loc9`='Stormwind Gryphon Master' WHERE `word_id` = 127171; -- locales_points_of_interest - icon_name : entry=23
UPDATE `trans_words` SET `content_loc9`='Jenova Stoneshield' WHERE `word_id` = 79231; -- locales_points_of_interest - icon_name : entry=26
UPDATE `trans_words` SET `content_loc9`='Woo Ping' WHERE `word_id` = 79677; -- locales_points_of_interest - icon_name : entry=27
UPDATE `trans_words` SET `content_loc9`='Hunter Lodge' WHERE `word_id` = 127173; -- locales_points_of_interest - icon_name : entry=33
UPDATE `trans_words` SET `content_loc9`='Stormwind - Rogue House' WHERE `word_id` = 127176; -- locales_points_of_interest - icon_name : entry=36
UPDATE `trans_words` SET `content_loc9`='Stormwind Barracks' WHERE `word_id` = 127177; -- locales_points_of_interest - icon_name : entry=39
UPDATE `trans_words` SET `content_loc9`='Therum Deepforge' WHERE `word_id` = 76707; -- locales_points_of_interest - icon_name : entry=41
UPDATE `trans_words` SET `content_loc9`='Lucan Cordell' WHERE `word_id` = 73281; -- locales_points_of_interest - icon_name : entry=43
UPDATE `trans_words` SET `content_loc9`='Lilliam Sparkspindle' WHERE `word_id` = 76714; -- locales_points_of_interest - icon_name : entry=44
UPDATE `trans_words` SET `content_loc9`='Shaina Fuller' WHERE `word_id` = 74079; -- locales_points_of_interest - icon_name : entry=45
UPDATE `trans_words` SET `content_loc9`='Arnold Leland' WHERE `word_id` = 76689; -- locales_points_of_interest - icon_name : entry=46
UPDATE `trans_words` SET `content_loc9`='Gelman Stonehand' WHERE `word_id` = 76709; -- locales_points_of_interest - icon_name : entry=48
UPDATE `trans_words` SET `content_loc9`='The Vault' WHERE `word_id` = 127178; -- locales_points_of_interest - icon_name : entry=51
UPDATE `trans_words` SET `content_loc9`='Ironforge Gryphon Master' WHERE `word_id` = 127179; -- locales_points_of_interest - icon_name : entry=53
UPDATE `trans_words` SET `content_loc9`='Stonefire Tavern' WHERE `word_id` = 127180; -- locales_points_of_interest - icon_name : entry=55
UPDATE `trans_words` SET `content_loc9`='Ironforge Mailbox' WHERE `word_id` = 127181; -- locales_points_of_interest - icon_name : entry=56
UPDATE `trans_words` SET `content_loc9`='Ulbrek Firehand' WHERE `word_id` = 78710; -- locales_points_of_interest - icon_name : entry=57
UPDATE `trans_words` SET `content_loc9`='Ironforge Rogue Trainer' WHERE `word_id` = 127184; -- locales_points_of_interest - icon_name : entry=63
UPDATE `trans_words` SET `content_loc9`='Ironforge Warlock Trainer' WHERE `word_id` = 127185; -- locales_points_of_interest - icon_name : entry=64
UPDATE `trans_words` SET `content_loc9`='Shelby Stoneflint' WHERE `word_id` = 78706; -- locales_points_of_interest - icon_name : entry=77
UPDATE `trans_words` SET `content_loc9`='Grif Wildheart' WHERE `word_id` = 73182; -- locales_points_of_interest - icon_name : entry=78
UPDATE `trans_words` SET `content_loc9`='Magis Sparkmantle' WHERE `word_id` = 73180; -- locales_points_of_interest - icon_name : entry=79
UPDATE `trans_words` SET `content_loc9`='Azar Stronghammer' WHERE `word_id` = 73183; -- locales_points_of_interest - icon_name : entry=80
UPDATE `trans_words` SET `content_loc9`='Maxan Anvol' WHERE `word_id` = 73179; -- locales_points_of_interest - icon_name : entry=81
UPDATE `trans_words` SET `content_loc9`='Hogral Bakkan' WHERE `word_id` = 73184; -- locales_points_of_interest - icon_name : entry=82
UPDATE `trans_words` SET `content_loc9`='Gimrizz Shadowcog' WHERE `word_id` = 76748; -- locales_points_of_interest - icon_name : entry=83
UPDATE `trans_words` SET `content_loc9`='Granis Swiftaxe' WHERE `word_id` = 73181; -- locales_points_of_interest - icon_name : entry=84
UPDATE `trans_words` SET `content_loc9`='Tognus Flintfire' WHERE `word_id` = 73191; -- locales_points_of_interest - icon_name : entry=85
UPDATE `trans_words` SET `content_loc9`='Gremlock Pilsnor' WHERE `word_id` = 73601; -- locales_points_of_interest - icon_name : entry=86
UPDATE `trans_words` SET `content_loc9`='Thamner Pol' WHERE `word_id` = 74077; -- locales_points_of_interest - icon_name : entry=87
UPDATE `trans_words` SET `content_loc9`='Paxton Ganter' WHERE `word_id` = 73602; -- locales_points_of_interest - icon_name : entry=88
UPDATE `trans_words` SET `content_loc9`='Darnassus Bank' WHERE `word_id` = 127188; -- locales_points_of_interest - icon_name : entry=90
UPDATE `trans_words` SET `content_loc9`='Darnassus Hippogryph Master' WHERE `word_id` = 127189; -- locales_points_of_interest - icon_name : entry=91
UPDATE `trans_words` SET `content_loc9`='Darnassus Guild Master' WHERE `word_id` = 127190; -- locales_points_of_interest - icon_name : entry=92
UPDATE `trans_words` SET `content_loc9`='Darnassus Inn' WHERE `word_id` = 127191; -- locales_points_of_interest - icon_name : entry=93
UPDATE `trans_words` SET `content_loc9`='Darnassus Mailbox' WHERE `word_id` = 127192; -- locales_points_of_interest - icon_name : entry=94
UPDATE `trans_words` SET `content_loc9`='Alassin' WHERE `word_id` = 78742; -- locales_points_of_interest - icon_name : entry=95
UPDATE `trans_words` SET `content_loc9`='Ilyenia Moonfire' WHERE `word_id` = 79676; -- locales_points_of_interest - icon_name : entry=96
UPDATE `trans_words` SET `content_loc9`='Darnassus Druid Trainer' WHERE `word_id` = 127194; -- locales_points_of_interest - icon_name : entry=98
UPDATE `trans_words` SET `content_loc9`='Darnassus Hunter Trainer' WHERE `word_id` = 127195; -- locales_points_of_interest - icon_name : entry=99
UPDATE `trans_words` SET `content_loc9`='Darnassus Rogue Trainer' WHERE `word_id` = 127196; -- locales_points_of_interest - icon_name : entry=100
UPDATE `trans_words` SET `content_loc9`='Darnassus Alchemy Trainer' WHERE `word_id` = 127198; -- locales_points_of_interest - icon_name : entry=102
UPDATE `trans_words` SET `content_loc9`='Darnassus Cooking Trainer' WHERE `word_id` = 127199; -- locales_points_of_interest - icon_name : entry=103
UPDATE `trans_words` SET `content_loc9`='Darnassus Enchanting Trainer' WHERE `word_id` = 127200; -- locales_points_of_interest - icon_name : entry=104
UPDATE `trans_words` SET `content_loc9`='Darnassus First Aid Trainer' WHERE `word_id` = 127201; -- locales_points_of_interest - icon_name : entry=105
UPDATE `trans_words` SET `content_loc9`='Darnassus Fishing Trainer' WHERE `word_id` = 127202; -- locales_points_of_interest - icon_name : entry=106
UPDATE `trans_words` SET `content_loc9`='Darnassus Leatherworking Trainer' WHERE `word_id` = 127203; -- locales_points_of_interest - icon_name : entry=108
UPDATE `trans_words` SET `content_loc9`='Darnassus Skinning Trainer' WHERE `word_id` = 127204; -- locales_points_of_interest - icon_name : entry=109
UPDATE `trans_words` SET `content_loc9`='Darnassus Tailor' WHERE `word_id` = 127205; -- locales_points_of_interest - icon_name : entry=110
UPDATE `trans_words` SET `content_loc9`='Dolanaar Inn' WHERE `word_id` = 127206; -- locales_points_of_interest - icon_name : entry=111
UPDATE `trans_words` SET `content_loc9`='Seriadne' WHERE `word_id` = 78737; -- locales_points_of_interest - icon_name : entry=112
UPDATE `trans_words` SET `content_loc9`='Kal' WHERE `word_id` = 75285; -- locales_points_of_interest - icon_name : entry=113
UPDATE `trans_words` SET `content_loc9`='Dazalar' WHERE `word_id` = 75284; -- locales_points_of_interest - icon_name : entry=114
UPDATE `trans_words` SET `content_loc9`='Laurna Morninglight' WHERE `word_id` = 75283; -- locales_points_of_interest - icon_name : entry=115
UPDATE `trans_words` SET `content_loc9`='Jannok Breezesong' WHERE `word_id` = 75282; -- locales_points_of_interest - icon_name : entry=116
UPDATE `trans_words` SET `content_loc9`='Kyra Windblade' WHERE `word_id` = 75281; -- locales_points_of_interest - icon_name : entry=117
UPDATE `trans_words` SET `content_loc9`='Cyndra Kindwhisper' WHERE `word_id` = 75286; -- locales_points_of_interest - icon_name : entry=118
UPDATE `trans_words` SET `content_loc9`='Zarrin' WHERE `word_id` = 77253; -- locales_points_of_interest - icon_name : entry=119
UPDATE `trans_words` SET `content_loc9`='Alanna Raveneye' WHERE `word_id` = 75289; -- locales_points_of_interest - icon_name : entry=120
UPDATE `trans_words` SET `content_loc9`='Byancie' WHERE `word_id` = 77126; -- locales_points_of_interest - icon_name : entry=121
UPDATE `trans_words` SET `content_loc9`='Malorne Bladeleaf' WHERE `word_id` = 75287; -- locales_points_of_interest - icon_name : entry=122
UPDATE `trans_words` SET `content_loc9`='Nadyia Maneweaver' WHERE `word_id` = 75288; -- locales_points_of_interest - icon_name : entry=123
UPDATE `trans_words` SET `content_loc9`='Radnaal Maneweaver' WHERE `word_id` = 77254; -- locales_points_of_interest - icon_name : entry=124
UPDATE `trans_words` SET `content_loc9`='Nadyia Maneweaver' WHERE `word_id` = 75288; -- locales_points_of_interest - icon_name : entry=125
UPDATE `trans_words` SET `content_loc9`='Orgrimmar Inn' WHERE `word_id` = 127208; -- locales_points_of_interest - icon_name : entry=179
UPDATE `trans_words` SET `content_loc9`='Orgrimmar Mailbox' WHERE `word_id` = 127209; -- locales_points_of_interest - icon_name : entry=180
UPDATE `trans_words` SET `content_loc9`='Orgrimmar Zeppelin Tower' WHERE `word_id` = 127210; -- locales_points_of_interest - icon_name : entry=182
UPDATE `trans_words` SET `content_loc9`='Sayoc & Hanashi' WHERE `word_id` = 127211; -- locales_points_of_interest - icon_name : entry=184
UPDATE `trans_words` SET `content_loc9`='Xon\'cha' WHERE `word_id` = 78714; -- locales_points_of_interest - icon_name : entry=185
UPDATE `trans_words` SET `content_loc9`='Krunn' WHERE `word_id` = 74864; -- locales_points_of_interest - icon_name : entry=238
UPDATE `trans_words` SET `content_loc9`='Mishiki' WHERE `word_id` = 74875; -- locales_points_of_interest - icon_name : entry=239
UPDATE `trans_words` SET `content_loc9`='Lau\'Tiki' WHERE `word_id` = 77040; -- locales_points_of_interest - icon_name : entry=240
UPDATE `trans_words` SET `content_loc9`='Rawrk' WHERE `word_id` = 77042; -- locales_points_of_interest - icon_name : entry=241
UPDATE `trans_words` SET `content_loc9`='Mukdrak' WHERE `word_id` = 79192; -- locales_points_of_interest - icon_name : entry=242
UPDATE `trans_words` SET `content_loc9`='Dwukk' WHERE `word_id` = 74863; -- locales_points_of_interest - icon_name : entry=243
UPDATE `trans_words` SET `content_loc9`='Miao\'zan' WHERE `word_id` = 74874; -- locales_points_of_interest - icon_name : entry=244
UPDATE `trans_words` SET `content_loc9`='Tarshaw Jaggedscar' WHERE `word_id` = 74858; -- locales_points_of_interest - icon_name : entry=245
UPDATE `trans_words` SET `content_loc9`='Dhugru Gorelust' WHERE `word_id` = 74861; -- locales_points_of_interest - icon_name : entry=246
UPDATE `trans_words` SET `content_loc9`='Swart' WHERE `word_id` = 74862; -- locales_points_of_interest - icon_name : entry=247
UPDATE `trans_words` SET `content_loc9`='Kaplak' WHERE `word_id` = 74859; -- locales_points_of_interest - icon_name : entry=248
UPDATE `trans_words` SET `content_loc9`='Tai\'jin' WHERE `word_id` = 75379; -- locales_points_of_interest - icon_name : entry=249
UPDATE `trans_words` SET `content_loc9`='Un\'Thuwa' WHERE `word_id` = 76982; -- locales_points_of_interest - icon_name : entry=250
UPDATE `trans_words` SET `content_loc9`='Thotar' WHERE `word_id` = 74860; -- locales_points_of_interest - icon_name : entry=251
UPDATE `trans_words` SET `content_loc9`='Shoja\'my' WHERE `word_id` = 78713; -- locales_points_of_interest - icon_name : entry=252
UPDATE `trans_words` SET `content_loc9`='Razor Hill Inn' WHERE `word_id` = 127213; -- locales_points_of_interest - icon_name : entry=253
UPDATE `trans_words` SET `content_loc9`='Undercity Tailoring Trainer' WHERE `word_id` = 127214; -- locales_points_of_interest - icon_name : entry=254
UPDATE `trans_words` SET `content_loc9`='Undercity Skinning Trainer' WHERE `word_id` = 127215; -- locales_points_of_interest - icon_name : entry=255
UPDATE `trans_words` SET `content_loc9`='Undercity Mining Trainer' WHERE `word_id` = 127216; -- locales_points_of_interest - icon_name : entry=256
UPDATE `trans_words` SET `content_loc9`='Undercity Leatherworking Trainer' WHERE `word_id` = 127217; -- locales_points_of_interest - icon_name : entry=257
UPDATE `trans_words` SET `content_loc9`='Undercity Herbalism Trainer' WHERE `word_id` = 127218; -- locales_points_of_interest - icon_name : entry=259
UPDATE `trans_words` SET `content_loc9`='Undercity Fishing Trainer' WHERE `word_id` = 127219; -- locales_points_of_interest - icon_name : entry=260
UPDATE `trans_words` SET `content_loc9`='Undercity First Aid Trainer' WHERE `word_id` = 127220; -- locales_points_of_interest - icon_name : entry=261
UPDATE `trans_words` SET `content_loc9`='Undercity Engineering Trainer' WHERE `word_id` = 127221; -- locales_points_of_interest - icon_name : entry=262
UPDATE `trans_words` SET `content_loc9`='Undercity Enchanting Trainer' WHERE `word_id` = 127222; -- locales_points_of_interest - icon_name : entry=263
UPDATE `trans_words` SET `content_loc9`='Undercity Cooking Trainer' WHERE `word_id` = 127223; -- locales_points_of_interest - icon_name : entry=264
UPDATE `trans_words` SET `content_loc9`='Undercity Blacksmithing Trainer' WHERE `word_id` = 127224; -- locales_points_of_interest - icon_name : entry=265
UPDATE `trans_words` SET `content_loc9`='Undercity Warrior Trainers' WHERE `word_id` = 127225; -- locales_points_of_interest - icon_name : entry=267
UPDATE `trans_words` SET `content_loc9`='Undercity Warlock Trainers' WHERE `word_id` = 127226; -- locales_points_of_interest - icon_name : entry=268
UPDATE `trans_words` SET `content_loc9`='Undercity Rogue Trainers' WHERE `word_id` = 127227; -- locales_points_of_interest - icon_name : entry=269
UPDATE `trans_words` SET `content_loc9`='Undercity Priest Trainers' WHERE `word_id` = 127228; -- locales_points_of_interest - icon_name : entry=270
UPDATE `trans_words` SET `content_loc9`='Undercity Mage Trainers' WHERE `word_id` = 127229; -- locales_points_of_interest - icon_name : entry=272
UPDATE `trans_words` SET `content_loc9`='Undercity Zeppelin' WHERE `word_id` = 127230; -- locales_points_of_interest - icon_name : entry=273
UPDATE `trans_words` SET `content_loc9`='Archibald' WHERE `word_id` = 79680; -- locales_points_of_interest - icon_name : entry=274
UPDATE `trans_words` SET `content_loc9`='Anya Maulray' WHERE `word_id` = 78739; -- locales_points_of_interest - icon_name : entry=275
UPDATE `trans_words` SET `content_loc9`='Undercity Mailbox' WHERE `word_id` = 127231; -- locales_points_of_interest - icon_name : entry=276
UPDATE `trans_words` SET `content_loc9`='Undercity Inn' WHERE `word_id` = 127232; -- locales_points_of_interest - icon_name : entry=278
UPDATE `trans_words` SET `content_loc9`='Undercity Guild Master' WHERE `word_id` = 127233; -- locales_points_of_interest - icon_name : entry=279
UPDATE `trans_words` SET `content_loc9`='Undercity Bat Handler' WHERE `word_id` = 127235; -- locales_points_of_interest - icon_name : entry=281
UPDATE `trans_words` SET `content_loc9`='Undercity Bank' WHERE `word_id` = 127236; -- locales_points_of_interest - icon_name : entry=283
UPDATE `trans_words` SET `content_loc9`='Bowen Brisboise' WHERE `word_id` = 75208; -- locales_points_of_interest - icon_name : entry=285
UPDATE `trans_words` SET `content_loc9`='Rand Rhobart' WHERE `word_id` = 77256; -- locales_points_of_interest - icon_name : entry=286
UPDATE `trans_words` SET `content_loc9`='Shelene Rhobart' WHERE `word_id` = 75240; -- locales_points_of_interest - icon_name : entry=287
UPDATE `trans_words` SET `content_loc9`='Faruza' WHERE `word_id` = 73913; -- locales_points_of_interest - icon_name : entry=288
UPDATE `trans_words` SET `content_loc9`='Clyde Kellen' WHERE `word_id` = 76812; -- locales_points_of_interest - icon_name : entry=289
UPDATE `trans_words` SET `content_loc9`='Nurse Neela' WHERE `word_id` = 76878; -- locales_points_of_interest - icon_name : entry=290
UPDATE `trans_words` SET `content_loc9`='Vance Undergloom' WHERE `word_id` = 76817; -- locales_points_of_interest - icon_name : entry=291
UPDATE `trans_words` SET `content_loc9`='Carolai Anise' WHERE `word_id` = 73931; -- locales_points_of_interest - icon_name : entry=292
UPDATE `trans_words` SET `content_loc9`='Austil de Mon' WHERE `word_id` = 73930; -- locales_points_of_interest - icon_name : entry=293
UPDATE `trans_words` SET `content_loc9`='Rupert Boch' WHERE `word_id` = 73926; -- locales_points_of_interest - icon_name : entry=294
UPDATE `trans_words` SET `content_loc9`='Marion Call' WHERE `word_id` = 73929; -- locales_points_of_interest - icon_name : entry=295
UPDATE `trans_words` SET `content_loc9`='Morganus' WHERE `word_id` = 78741; -- locales_points_of_interest - icon_name : entry=296
UPDATE `trans_words` SET `content_loc9`='Dark Cleric Beryl' WHERE `word_id` = 73928; -- locales_points_of_interest - icon_name : entry=297
UPDATE `trans_words` SET `content_loc9`='Cain Firesong' WHERE `word_id` = 73927; -- locales_points_of_interest - icon_name : entry=298
UPDATE `trans_words` SET `content_loc9`='Mooranta' WHERE `word_id` = 77537; -- locales_points_of_interest - icon_name : entry=302
UPDATE `trans_words` SET `content_loc9`='Bulrug' WHERE `word_id` = 78740; -- locales_points_of_interest - icon_name : entry=318
UPDATE `trans_words` SET `content_loc9`='Ansekhwa' WHERE `word_id` = 79679; -- locales_points_of_interest - icon_name : entry=319
UPDATE `trans_words` SET `content_loc9`='Thunder Bluff Auction house' WHERE `word_id` = 127241; -- locales_points_of_interest - icon_name : entry=320
UPDATE `trans_words` SET `content_loc9`='Thunder Bluff Mailbox' WHERE `word_id` = 127242; -- locales_points_of_interest - icon_name : entry=321
UPDATE `trans_words` SET `content_loc9`='Thunder Bluff Inn' WHERE `word_id` = 127243; -- locales_points_of_interest - icon_name : entry=322
UPDATE `trans_words` SET `content_loc9`='Wind Rider Roost' WHERE `word_id` = 127244; -- locales_points_of_interest - icon_name : entry=324
UPDATE `trans_words` SET `content_loc9`='Yonn Deepcut' WHERE `word_id` = 77257; -- locales_points_of_interest - icon_name : entry=326
UPDATE `trans_words` SET `content_loc9`='Chaw Stronghide' WHERE `word_id` = 74762; -- locales_points_of_interest - icon_name : entry=327
UPDATE `trans_words` SET `content_loc9`='Uthan Stillwater' WHERE `word_id` = 77037; -- locales_points_of_interest - icon_name : entry=329
UPDATE `trans_words` SET `content_loc9`='Vira Younghoof' WHERE `word_id` = 77038; -- locales_points_of_interest - icon_name : entry=330
UPDATE `trans_words` SET `content_loc9`='Pyall Silentstride' WHERE `word_id` = 74760; -- locales_points_of_interest - icon_name : entry=331
UPDATE `trans_words` SET `content_loc9`='Krang Stonehoof' WHERE `word_id` = 74756; -- locales_points_of_interest - icon_name : entry=332
UPDATE `trans_words` SET `content_loc9`='Narm Skychaser' WHERE `word_id` = 74759; -- locales_points_of_interest - icon_name : entry=334
UPDATE `trans_words` SET `content_loc9`='Yaw Sharpmane' WHERE `word_id` = 74758; -- locales_points_of_interest - icon_name : entry=335
UPDATE `trans_words` SET `content_loc9`='Gennia Runetotem' WHERE `word_id` = 74757; -- locales_points_of_interest - icon_name : entry=336
UPDATE `trans_words` SET `content_loc9`='Seikwa' WHERE `word_id` = 78736; -- locales_points_of_interest - icon_name : entry=337
UPDATE `trans_words` SET `content_loc9`='Yarr Hammerstone' WHERE `word_id` = 76615; -- locales_points_of_interest - icon_name : entry=339
UPDATE `trans_words` SET `content_loc9`='Herbalist Pomeroy' WHERE `word_id` = 73175; -- locales_points_of_interest - icon_name : entry=363
UPDATE `trans_words` SET `content_loc9`='Saltheril\'s Haven, Tailor' WHERE `word_id` = 127247; -- locales_points_of_interest - icon_name : entry=418
UPDATE `trans_words` SET `content_loc9`='Orgrimmar Hunter\'s Hall' WHERE `word_id` = 127248; -- locales_points_of_interest - icon_name : entry=420
UPDATE `trans_words` SET `content_loc9`='Darnassus Herbalism Trainer' WHERE `word_id` = 127249; -- locales_points_of_interest - icon_name : entry=440

SET NAMES 'latin1';
