-- File generated by Mangos Online Translation Editor (MOTE) v2.00
SET NAMES 'utf8';
UPDATE locales_gossip_menu_option SET option_text_loc9='Here\'s a gold, buy yourself something nice.',box_text_loc9='Do you really want to bribe Olga?' WHERE menu_id=9014 AND id=0;

SET NAMES 'latin1';
