-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE db_script_string SET content_loc4='小心，$n！看西边！' WHERE entry = 2000000031; -- content_default: Beware, $n! Look to the west!
UPDATE db_script_string SET content_loc4='赶快去,$N。我的命运掌握在你手中。' WHERE entry = 2000005017; -- content_default: Go swiftly $N. My fate is in your hands.
UPDATE db_script_string SET content_loc4='我只是在自言自语罢了，和这里的其它人说话的时候，我总是得不到应有的尊重。' WHERE entry=2000005105; -- content: O\'ourse I\'m talking to myself. Only way to get a decent conversation in this city.
UPDATE db_script_string SET content_loc4='我这么多年来好像都没干过比打水更有意义的事情似的!' WHERE entry=2000005106; -- content: As if I don\'t have better things to do in my old age than carry buckets of water.
UPDATE db_script_string SET content_loc4='我一天要走好多趟到水井那边去打水，现在的年轻人啊...' WHERE entry=2000005107; -- content: Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya.
UPDATE db_script_string SET content_loc4='过敏是什么意思？和我的小猫咪有什么关系吗？' WHERE entry=2000005314; -- content: What does allergic mean anyway? And what does it have to do with either of my kitties?
UPDATE db_script_string SET content_loc4='我不敢相信爸爸不让我留下你妹妹。' WHERE entry=2000005315; -- content: I can\'t believe dad won\'t let me keep your sister.
UPDATE db_script_string SET content_loc4='别担心，我会帮你找到个舒适的家。' WHERE entry=2000005316; -- content: Don\'t worry, I\'ll find a good home for ya.
UPDATE db_script_string SET content_loc4='有人能给我可爱的小猫咪一个家吗？' WHERE entry=2000005317; -- content: Can anyone give my adorable, extra little kitty a home?
UPDATE db_script_string SET content_loc4='有好心人能给我的小猫咪一个舒适的家吗？' WHERE entry=2000005318; -- content: Will someone please give my little kitten a good home?
UPDATE db_script_string SET content_loc4='现在我们来试一下...' WHERE entry = 2000005752; -- content_default: Now let\'s try it...
UPDATE db_script_string SET content_loc4='噢！真是糟透了！' WHERE entry = 2000005753; -- content_default: Ugh! That\'s terrible!

SET NAMES 'latin1';
