-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE script_texts SET content_loc4='%s进入了狂乱状态！' WHERE entry=-1000001; -- content: %s goes into a killing frenzy!
UPDATE script_texts SET content_loc4='%s狂暴了！' WHERE entry=-1000002; -- content: %s goes into a frenzy!
UPDATE script_texts SET content_loc4='%s变得愤怒了！' WHERE entry=-1000003; -- content: %s becomes enraged!
UPDATE script_texts SET content_loc4='%s变得狂怒了！' WHERE entry=-1000004; -- content: %s goes into a berserker rage!
UPDATE script_texts SET content_loc4='%s狂暴了！' WHERE entry=-1000005; -- content: %s goes into a frenzy!
UPDATE script_texts SET content_loc4='%s变得愤怒了！' WHERE entry=-1000006; -- content: %s becomes enraged!
UPDATE script_texts SET content_loc4='快跟上$N！准备战斗！' WHERE entry=-1000104; -- content: $N coming in fast! Prepare to fight!
UPDATE script_texts SET content_loc4='快帮帮我！' WHERE entry=-1000105; -- content: Help!
UPDATE script_texts SET content_loc4='都准备好了吗！' WHERE entry=-1000106; -- content: Everyone ready?
UPDATE script_texts SET content_loc4='在他们发现我逃走之前，我们赶快走吧！' WHERE entry=-1000357; -- content: Let\'s go before they find out I\'m free!
UPDATE script_texts SET content_loc4='当心！我们被攻击了！' WHERE entry=-1000358; -- content: Look out! We\'re under attack!
UPDATE script_texts SET content_loc4='感谢你帮助我。我知道从这里怎么回去。' WHERE entry=-1000359; -- content: Thank you for helping me. I know my way back from here.
UPDATE script_texts SET content_loc4='当心，恐怖图腾在向我们靠近！' WHERE entry=-1000366; -- content: Look out, the Grimtotem are upon us!
UPDATE script_texts SET content_loc4='他们来了。' WHERE entry=-1000367; -- content: Here they come.
UPDATE script_texts SET content_loc4='更多恐怖图腾朝这边来了！' WHERE entry=-1000368; -- content: More Grimtotems are coming this way!
UPDATE script_texts SET content_loc4='终于自由了...我必须走了，谢谢你帮我逃出来！我能自己回到乱风岗。' WHERE entry=-1000369; -- content: Finally, free at last... I must be going now, thanks for helping me escape. I can get back to Freewind Post by myself.
UPDATE script_texts SET content_loc4='跟紧点，$n。我需要一些帮助才能逃出这儿。我们出发吧！' WHERE entry=-1000370; -- content: Stay close, $n. I\'ll need all the help I can get to break out of here. Let\'s go!
UPDATE script_texts SET content_loc4='终于从北方城堡逃出来了！我需要停下来喘口气...' WHERE entry=-1000371; -- content: At last! Free from Northwatch Hold! I need a moment to catch my breath...
UPDATE script_texts SET content_loc4='现在感觉好多了，我们回棘齿城吧。跟上，$n。' WHERE entry=-1000372; -- content: Now i feel better. Let\'s get back to Ratchet. Come on, $n.
UPDATE script_texts SET content_loc4='快帮帮我！我被$C攻击了！' WHERE entry=-1000374; -- content: Help! $C attacking!
UPDATE script_texts SET content_loc4='$C快速的朝这边来了！报仇的时候到了！' WHERE entry=-1000375; -- content: $C heading this way fast! Time for revenge!
UPDATE script_texts SET content_loc4='$C朝我们过来了！' WHERE entry=-1000376; -- content: $C coming right at us!
UPDATE script_texts SET content_loc4='让这个$C离我远点！' WHERE entry=-1000377; -- content: Get this $C off of me!
UPDATE script_texts SET content_loc4='快要到棘齿城了！我们继续前进...' WHERE entry=-1000378; -- content: Almost back to Ratchet! Let\'s keep up the pace...
UPDATE script_texts SET content_loc4='啊~~~棘齿城那带着咸味的空气。' WHERE entry=-1000379; -- content: Ah, the sweet salt air of Ratchet.
UPDATE script_texts SET content_loc4='队长，这位$N帮助我逃了出来！$N,队长一定会嘉奖你的勇气的。' WHERE entry=-1000380; -- content: Captain Brightsun, $N here has freed me! $N, i am certain the Captain will reward your bravery.
UPDATE script_texts SET content_loc4='当心！' WHERE entry=-1000482; -- content: Look out!
UPDATE script_texts SET content_loc4='感觉一下黑铁矮人的力量!' WHERE entry=-1000572; -- content: Feel the power of the Dark Iron Dwarves!
UPDATE script_texts SET content_loc4='他们来了。' WHERE entry=-1000791; -- content: Here they come.
UPDATE script_texts SET content_loc4='不要放弃！一直战斗，直到死去！' WHERE entry=-1000794; -- content: Don\'t give up! Fight, to the death!
UPDATE script_texts SET content_loc4='好的，老板，我马上回去砍树。' WHERE entry=-1000795; -- content: OK boss, I get back to tree hitting.
UPDATE script_texts SET content_loc4='好困...太困了...' WHERE entry=-1000796; -- content: Sleepy... so sleepy...
UPDATE script_texts SET content_loc4='当心$N！你看西边！' WHERE entry=-1000891; -- content: Beware $N! Look to the west!
UPDATE script_texts SET content_loc4='一个保卫者倒下了！' WHERE entry=-1000892; -- content: A defender has fallen!
UPDATE script_texts SET content_loc4='科尔卡入侵者撤退了！' WHERE entry=-1000893; -- content: Kolkar invaders are retreating!
UPDATE script_texts SET content_loc4='科尔卡半人马是最强的！' WHERE entry=-1000894; -- content: Kolkar are the strongest!
UPDATE script_texts SET content_loc4='为了部落！' WHERE entry=-1000895; -- content: For the Horde!
UPDATE script_texts SET content_loc4='保卫地堡工事！' WHERE entry=-1000896; -- content: Defend the bunkers!
UPDATE script_texts SET content_loc4='我们的敌人必将失败！' WHERE entry=-1000897; -- content: Our foes will fall!
UPDATE script_texts SET content_loc4='啊~！现在你让我生气了！' WHERE entry=-1036003; -- content: D\'ah! Now you\'re making me angry!
UPDATE script_texts SET content_loc4='现在可以唤醒纳拉雷克斯了！来协助我，勇敢的冒险者！' WHERE entry=-1043000; -- content: At last! Naralex can be awakened! Come aid me, brave adventurers!
UPDATE script_texts SET content_loc4='唤醒仪式开始之前我必须做一些准备工作，你必须保护我。' WHERE entry=-1043001; -- content: I must make the necessary preparations before the awakening ritual can begin. You must protect me!
UPDATE script_texts SET content_loc4='这些洞穴曾经是一座神庙，是治愈贫瘠之地的希望。现在成了梦魇的栖息之地。' WHERE entry=-1043002; -- content: These caverns were once a temple of promise for regrowth in the Barrens. Now, they are the halls of nightmares.
UPDATE script_texts SET content_loc4='跟上，我们必须继续前进。在我们能把纳拉雷克斯从他的梦魇中唤醒之前还有很多事情需要做。' WHERE entry=-1043003; -- content: Come. We must continue. There is much to be done before we can pull Naralex from his nightmare.
UPDATE script_texts SET content_loc4='我必须在这个法阵中施法来放逐这些被杀的尖牙德鲁伊的灵魂。' WHERE entry=-1043004; -- content: Within this circle of fire I must cast the spell to banish the spirits of the slain Fanglords.
UPDATE script_texts SET content_loc4='这个洞穴被净化了。我们赶快去纳拉雷克斯的房间！' WHERE entry=-1043005; -- content: The caverns have been purified. To Naralex\'s chamber we go!
UPDATE script_texts SET content_loc4='穿过这个通道，纳拉雷克斯正沉睡在他无尽的梦魇中。我们赶快去唤醒他，不然就来不及了。' WHERE entry=-1043006; -- content: Beyond this corridor, Naralex lies in fitful sleep. Let us go awaken him before it is too late.
UPDATE script_texts SET content_loc4='勇士们，当我进入翡翠梦境营救纳拉雷克斯时请保护我，然后我们终结这里的堕落之源！' WHERE entry=-1043007; -- content: Protect me brave souls as I delve into the Emerald Dream to rescue Naralex and put an end to this corruption!
UPDATE script_texts SET content_loc4='%s开始对纳拉雷克斯启动唤醒仪式' WHERE entry=-1043008; -- content: %s begins to perform the awakening ritual on Naralex.
UPDATE script_texts SET content_loc4='%s的梦境渐渐开始崩塌' WHERE entry=-1043009; -- content: %s tosses fitfully in troubled sleep.
UPDATE script_texts SET content_loc4='这个$N毫无疑问是纳拉雷克斯梦魇中的一个小角色！' WHERE entry=-1043012; -- content: This $N is a minion from Naralex\'s nightmare no doubt!.
UPDATE script_texts SET content_loc4='我终于醒了！！' WHERE entry=-1043013; -- content: I AM AWAKE, AT LAST!
UPDATE script_texts SET content_loc4='纳拉雷克斯终于中梦魇中醒过来了！' WHERE entry=-1043014; -- content: At last! Naralex awakes from the nightmare.
UPDATE script_texts SET content_loc4='啊，你们从可怕的梦魇中救了我！谢谢你,我忠诚的信徒,连同你的勇敢的同伴。' WHERE entry=-1043015; -- content: Ah, to be pulled from the dreaded nightmare! I thank you, my loyal Disciple, along with your brave companions.
UPDATE script_texts SET content_loc4='我必须去和其它信徒汇合了。在我尝试用其他方法治愈贫瘠之地之前还有很多工作要做。后会有期，勇士们！' WHERE entry=-1043016; -- content: We must go and gather with the other Disciplies. There is much work to be done before I can make another attempt to restore the Barrens. Farewell, brave souls!
UPDATE script_texts SET content_loc4='我受到攻击！快让这个$N离我远点！' WHERE entry=-1043017; -- content: Attacked! Help get this $N off of me!
UPDATE script_texts SET content_loc4='快帮帮我！' WHERE entry=-1043018; -- content: Help!
UPDATE script_texts SET content_loc4='对付一下这个$N！我要准备唤醒纳拉雷克斯！' WHERE entry=-1043019; -- content: Deal with this $N! I need to prepare to awake Naralex!
UPDATE script_texts SET content_loc4='给我来一次真正的挑战吧！' WHERE entry=-1189000; -- content: Ah, I have been waiting for a real challenge!
UPDATE script_texts SET content_loc4='光明之刃！' WHERE entry=-1189001; -- content: Blades of Light!
UPDATE script_texts SET content_loc4='圣光，赐予我力量吧！' WHERE entry=-1189002; -- content: Light, give me strength!
UPDATE script_texts SET content_loc4='哈，你们就这点本事吗？' WHERE entry=-1189003; -- content: Hah, is that all?
UPDATE script_texts SET content_loc4='异教徒！净化他们！' WHERE entry=-1189005; -- content: Infidels! They must be purified!
UPDATE script_texts SET content_loc4='真可惜！' WHERE entry=-1189006; -- content: Unworthy!
UPDATE script_texts SET content_loc4='为你而战！我的女士！' WHERE entry=-1189007; -- content: At your side, milady!
UPDATE script_texts SET content_loc4='莫格莱尼,你死了吗？你们要为此付出代价！' WHERE entry=-1189008; -- content: What, Mograine has fallen? You shall pay for this treachery!
UPDATE script_texts SET content_loc4='圣光会审判你们的！' WHERE entry=-1189009; -- content: The Light has spoken!
UPDATE script_texts SET content_loc4='复活吧！我的勇士！' WHERE entry=-1189010; -- content: Arise, my champion!
UPDATE script_texts SET content_loc4='你不能玷污这些神迹！' WHERE entry=-1189019; -- content: You will not defile these mysteries!
UPDATE script_texts SET content_loc4='让正义的火焰吞噬你吧！' WHERE entry=-1189020; -- content: Burn in righteous fire!
UPDATE script_texts SET content_loc4='你们怎敢进入我的密室！' WHERE entry=-1209000; -- content: How dare you enter my sanctum!
UPDATE script_texts SET content_loc4='沙漠会将你吞噬！' WHERE entry=-1209001; -- content: Sands consume you!
UPDATE script_texts SET content_loc4='Hail to the king, baby!' WHERE entry=-1230002; -- content: Hail to the king, baby!
UPDATE script_texts SET content_loc4='胆敢破坏神圣的埃德萨拉斯? 面对我吧，懦夫！' WHERE entry=-1429001; -- content: Who dares disrupt the sanctity of Eldre\'Thalas? Face me, cowards!
UPDATE script_texts SET content_loc4='战士们！船长们！继续战斗！' WHERE entry=-1509014; -- content: Warriors! Captains! Continue the fight!
UPDATE script_texts SET content_loc4='你被终结了。' WHERE entry=-1509026; -- content: You are terminated.
UPDATE script_texts SET content_loc4='杀死！' WHERE entry=-1533030; -- content: KILL!

SET NAMES 'latin1';