-- File generated by Mangos Online Translation Editor (MOTE) v2.10
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc7`='Eliza\'s Tombstone' WHERE `word_id` = 114195; -- locales_gameobject - name : entry=37
UPDATE `trans_words` SET `content_loc7`='Captain Sanders Chest' WHERE `word_id` = 114196; -- locales_gameobject - name : entry=38
UPDATE `trans_words` SET `content_loc7`='Mound of loose dirt' WHERE `word_id` = 114200; -- locales_gameobject - name : entry=59
UPDATE `trans_words` SET `content_loc7`='Corpse Laden Boat' WHERE `word_id` = 114268; -- locales_gameobject - name : entry=1593
UPDATE `trans_words` SET `content_loc7`='Stanley\'s Dish' WHERE `word_id` = 114297; -- locales_gameobject - name : entry=1720
UPDATE `trans_words` SET `content_loc7`='Smoldering Fire' WHERE `word_id` = 114328; -- locales_gameobject - name : entry=2004
UPDATE `trans_words` SET `content_loc7`='The Wine Cask' WHERE `word_id` = 114347; -- locales_gameobject - name : entry=2130
UPDATE `trans_words` SET `content_loc7`='The Cheese Cutters' WHERE `word_id` = 114352; -- locales_gameobject - name : entry=2148
UPDATE `trans_words` SET `content_loc7`='The Seven Deadly Venoms' WHERE `word_id` = 114353; -- locales_gameobject - name : entry=2149
UPDATE `trans_words` SET `content_loc7`='Thane\'s Boots and Shoulderpads' WHERE `word_id` = 114355; -- locales_gameobject - name : entry=2151
UPDATE `trans_words` SET `content_loc7`='Mage Quarters' WHERE `word_id` = 114373; -- locales_gameobject - name : entry=2188
UPDATE `trans_words` SET `content_loc7`='Pillar of Diamond' WHERE `word_id` = 114423; -- locales_gameobject - name : entry=2842
UPDATE `trans_words` SET `content_loc7`='Pillar of Opal' WHERE `word_id` = 114425; -- locales_gameobject - name : entry=2848
UPDATE `trans_words` SET `content_loc7`='Pillar of Amethyst' WHERE `word_id` = 114427; -- locales_gameobject - name : entry=2858
UPDATE `trans_words` SET `content_loc7`='Benedict\'s Chest' WHERE `word_id` = 114459; -- locales_gameobject - name : entry=3239
UPDATE `trans_words` SET `content_loc7`='Longtoo - Teapee' WHERE `word_id` = 114461; -- locales_gameobject - name : entry=3265
UPDATE `trans_words` SET `content_loc7`='Drizzlik\'s Emporium' WHERE `word_id` = 114487; -- locales_gameobject - name : entry=3767
UPDATE `trans_words` SET `content_loc7`='Fragile - Do Not Drop' WHERE `word_id` = 114488; -- locales_gameobject - name : entry=3768
UPDATE `trans_words` SET `content_loc7`='Red Raptor Nest' WHERE `word_id` = 114516; -- locales_gameobject - name : entry=6906
UPDATE `trans_words` SET `content_loc7`='Blue Raptor Nest' WHERE `word_id` = 114517; -- locales_gameobject - name : entry=6907
UPDATE `trans_words` SET `content_loc7`='Yellow Raptor Nest' WHERE `word_id` = 114518; -- locales_gameobject - name : entry=6908
UPDATE `trans_words` SET `content_loc7`='Cat Figurine Trap' WHERE `word_id` = 117014; -- locales_gameobject - name : entry=12653
UPDATE `trans_words` SET `content_loc7`='Graveyard Banner' WHERE `word_id` = 114539; -- locales_gameobject - name : entry=13756
UPDATE `trans_words` SET `content_loc7`='Target' WHERE `word_id` = 114541; -- locales_gameobject - name : entry=13952
UPDATE `trans_words` SET `content_loc7`='The Lay of Ameth\'Aran' WHERE `word_id` = 24268; -- locales_gameobject - name : entry=17188
UPDATE `trans_words` SET `content_loc7`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18047
UPDATE `trans_words` SET `content_loc7`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18048
UPDATE `trans_words` SET `content_loc7`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18049
UPDATE `trans_words` SET `content_loc7`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18050
UPDATE `trans_words` SET `content_loc7`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18051
UPDATE `trans_words` SET `content_loc7`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18052
UPDATE `trans_words` SET `content_loc7`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18053
UPDATE `trans_words` SET `content_loc7`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18054
UPDATE `trans_words` SET `content_loc7`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18055
UPDATE `trans_words` SET `content_loc7`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18056
UPDATE `trans_words` SET `content_loc7`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18057
UPDATE `trans_words` SET `content_loc7`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18058
UPDATE `trans_words` SET `content_loc7`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18059
UPDATE `trans_words` SET `content_loc7`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18060
UPDATE `trans_words` SET `content_loc7`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18061
UPDATE `trans_words` SET `content_loc7`='Stand up Torch' WHERE `word_id` = 114559; -- locales_gameobject - name : entry=18062
UPDATE `trans_words` SET `content_loc7`='Goblin Shredder Suit' WHERE `word_id` = 114603; -- locales_gameobject - name : entry=19582
UPDATE `trans_words` SET `content_loc7`='Circle of Imprisonment' WHERE `word_id` = 114630; -- locales_gameobject - name : entry=19901
UPDATE `trans_words` SET `content_loc7`='Circle of Imprisonment' WHERE `word_id` = 114630; -- locales_gameobject - name : entry=20352
UPDATE `trans_words` SET `content_loc7`='Orc Tower' WHERE `word_id` = 114648; -- locales_gameobject - name : entry=20812
UPDATE `trans_words` SET `content_loc7`='Guard Tower' WHERE `word_id` = 114649; -- locales_gameobject - name : entry=20816
UPDATE `trans_words` SET `content_loc7`='Night Elf Moon Well' WHERE `word_id` = 114651; -- locales_gameobject - name : entry=20818
UPDATE `trans_words` SET `content_loc7`='Moon Well 2' WHERE `word_id` = 114652; -- locales_gameobject - name : entry=20819
UPDATE `trans_words` SET `content_loc7`='Giant Sea Turtle' WHERE `word_id` = 114653; -- locales_gameobject - name : entry=20820
UPDATE `trans_words` SET `content_loc7`='Giant Turtle' WHERE `word_id` = 114654; -- locales_gameobject - name : entry=20821
UPDATE `trans_words` SET `content_loc7`='Player Housing' WHERE `word_id` = 114656; -- locales_gameobject - name : entry=20823
UPDATE `trans_words` SET `content_loc7`='Orc Tower' WHERE `word_id` = 114648; -- locales_gameobject - name : entry=20824
UPDATE `trans_words` SET `content_loc7`='Flickering Campfire' WHERE `word_id` = 114657; -- locales_gameobject - name : entry=20881
UPDATE `trans_words` SET `content_loc7`='Flickering Campfire' WHERE `word_id` = 114657; -- locales_gameobject - name : entry=20926
UPDATE `trans_words` SET `content_loc7`='Hoofprints' WHERE `word_id` = 114667; -- locales_gameobject - name : entry=21015
UPDATE `trans_words` SET `content_loc7`='Hoofprints' WHERE `word_id` = 114667; -- locales_gameobject - name : entry=21016
UPDATE `trans_words` SET `content_loc7`='unk' WHERE `word_id` = 114688; -- locales_gameobject - name : entry=21653
UPDATE `trans_words` SET `content_loc7`='unk' WHERE `word_id` = 114688; -- locales_gameobject - name : entry=21654
UPDATE `trans_words` SET `content_loc7`='unk' WHERE `word_id` = 114688; -- locales_gameobject - name : entry=21655
UPDATE `trans_words` SET `content_loc7`='unk' WHERE `word_id` = 114688; -- locales_gameobject - name : entry=21656
UPDATE `trans_words` SET `content_loc7`='Desk Chair' WHERE `word_id` = 114697; -- locales_gameobject - name : entry=22256
UPDATE `trans_words` SET `content_loc7`='Industrial District' WHERE `word_id` = 114713; -- locales_gameobject - name : entry=25334
UPDATE `trans_words` SET `content_loc7`='Thundershot Guns \'n Ammo' WHERE `word_id` = 114718; -- locales_gameobject - name : entry=26485
UPDATE `trans_words` SET `content_loc7`='Pithwick\'s Bags and Supplies' WHERE `word_id` = 114724; -- locales_gameobject - name : entry=26491
UPDATE `trans_words` SET `content_loc7`='Farmountain Maps' WHERE `word_id` = 114725; -- locales_gameobject - name : entry=26492
UPDATE `trans_words` SET `content_loc7`='Stonebranch Herbalist' WHERE `word_id` = 114726; -- locales_gameobject - name : entry=26493
UPDATE `trans_words` SET `content_loc7`='IronForge Elevator' WHERE `word_id` = 114740; -- locales_gameobject - name : entry=32056
UPDATE `trans_words` SET `content_loc7`='IronForge Elevator' WHERE `word_id` = 114740; -- locales_gameobject - name : entry=32057
UPDATE `trans_words` SET `content_loc7`='Flinthammer\'s Armorer and Clothier' WHERE `word_id` = 114741; -- locales_gameobject - name : entry=32348
UPDATE `trans_words` SET `content_loc7`='The Commerce Ward' WHERE `word_id` = 114750; -- locales_gameobject - name : entry=32357
UPDATE `trans_words` SET `content_loc7`='The Commerce Ward' WHERE `word_id` = 114750; -- locales_gameobject - name : entry=32361
UPDATE `trans_words` SET `content_loc7`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32364
UPDATE `trans_words` SET `content_loc7`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32366
UPDATE `trans_words` SET `content_loc7`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32368
UPDATE `trans_words` SET `content_loc7`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32376
UPDATE `trans_words` SET `content_loc7`='The Forlorn Caverns' WHERE `word_id` = 114756; -- locales_gameobject - name : entry=32381
UPDATE `trans_words` SET `content_loc7`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32384
UPDATE `trans_words` SET `content_loc7`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32388
UPDATE `trans_words` SET `content_loc7`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32393
UPDATE `trans_words` SET `content_loc7`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32394
UPDATE `trans_words` SET `content_loc7`='The Commerce Ward' WHERE `word_id` = 114750; -- locales_gameobject - name : entry=32400
UPDATE `trans_words` SET `content_loc7`='The Commerce Ward' WHERE `word_id` = 114750; -- locales_gameobject - name : entry=32401
UPDATE `trans_words` SET `content_loc7`='The Commerce Ward' WHERE `word_id` = 114750; -- locales_gameobject - name : entry=32403
UPDATE `trans_words` SET `content_loc7`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32406
UPDATE `trans_words` SET `content_loc7`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32407
UPDATE `trans_words` SET `content_loc7`='The Commerce Ward' WHERE `word_id` = 114750; -- locales_gameobject - name : entry=32409
UPDATE `trans_words` SET `content_loc7`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32412
UPDATE `trans_words` SET `content_loc7`='The Commerce Ward' WHERE `word_id` = 114750; -- locales_gameobject - name : entry=32414
UPDATE `trans_words` SET `content_loc7`='The Commerce Ward' WHERE `word_id` = 114750; -- locales_gameobject - name : entry=32417
UPDATE `trans_words` SET `content_loc7`='Gnomes' WHERE `word_id` = 114760; -- locales_gameobject - name : entry=32419
UPDATE `trans_words` SET `content_loc7`='The Commerce Ward' WHERE `word_id` = 114750; -- locales_gameobject - name : entry=32420
UPDATE `trans_words` SET `content_loc7`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32783
UPDATE `trans_words` SET `content_loc7`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32784
UPDATE `trans_words` SET `content_loc7`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32785
UPDATE `trans_words` SET `content_loc7`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32787
UPDATE `trans_words` SET `content_loc7`='Market Walk' WHERE `word_id` = 114753; -- locales_gameobject - name : entry=32792
UPDATE `trans_words` SET `content_loc7`='BerryFizz Potions and Mixed Drinks' WHERE `word_id` = 114764; -- locales_gameobject - name : entry=34357
UPDATE `trans_words` SET `content_loc7`='Dining Bench' WHERE `word_id` = 114774; -- locales_gameobject - name : entry=36990
UPDATE `trans_words` SET `content_loc7`='Dining Bench' WHERE `word_id` = 114774; -- locales_gameobject - name : entry=36991
UPDATE `trans_words` SET `content_loc7`='Dining Bench' WHERE `word_id` = 114774; -- locales_gameobject - name : entry=36992
UPDATE `trans_words` SET `content_loc7`='Dining Bench' WHERE `word_id` = 114774; -- locales_gameobject - name : entry=36993
UPDATE `trans_words` SET `content_loc7`='Dining Bench' WHERE `word_id` = 114774; -- locales_gameobject - name : entry=36994
UPDATE `trans_words` SET `content_loc7`='Dining Bench' WHERE `word_id` = 114774; -- locales_gameobject - name : entry=36995
UPDATE `trans_words` SET `content_loc7`='Fire on ground' WHERE `word_id` = 114820; -- locales_gameobject - name : entry=56809
UPDATE `trans_words` SET `content_loc7`='Rail' WHERE `word_id` = 114872; -- locales_gameobject - name : entry=80024
UPDATE `trans_words` SET `content_loc7`='Stolen Books' WHERE `word_id` = 114873; -- locales_gameobject - name : entry=83763
UPDATE `trans_words` SET `content_loc7`='Fire With Boiling Water' WHERE `word_id` = 114910; -- locales_gameobject - name : entry=103773
UPDATE `trans_words` SET `content_loc7`='Brazier of Everfount' WHERE `word_id` = 114939; -- locales_gameobject - name : entry=113791
UPDATE `trans_words` SET `content_loc7`='Smoldering Coals' WHERE `word_id` = 114984; -- locales_gameobject - name : entry=140358
UPDATE `trans_words` SET `content_loc7`='Smoldering Coals' WHERE `word_id` = 114984; -- locales_gameobject - name : entry=140359
UPDATE `trans_words` SET `content_loc7`='Rin\'ji\'s Cage' WHERE `word_id` = 114996; -- locales_gameobject - name : entry=142036
UPDATE `trans_words` SET `content_loc7`='Egg-O-Matic' WHERE `word_id` = 114997; -- locales_gameobject - name : entry=142071
UPDATE `trans_words` SET `content_loc7`='Captain\'s Chest' WHERE `word_id` = 268307; -- locales_gameobject - name : entry=142184
UPDATE `trans_words` SET `content_loc7`='Stone Chair' WHERE `word_id` = 115033; -- locales_gameobject - name : entry=142947
UPDATE `trans_words` SET `content_loc7`='Stone Chair' WHERE `word_id` = 115033; -- locales_gameobject - name : entry=142948
UPDATE `trans_words` SET `content_loc7`='Flinthammer\'s Armorer and Clothier' WHERE `word_id` = 114741; -- locales_gameobject - name : entry=143332
UPDATE `trans_words` SET `content_loc7`='Ani' WHERE `word_id` = 115088; -- locales_gameobject - name : entry=149420
UPDATE `trans_words` SET `content_loc7`='Rune of Jin\'yael' WHERE `word_id` = 115092; -- locales_gameobject - name : entry=149480
UPDATE `trans_words` SET `content_loc7`='Rune of Beth\'Amara' WHERE `word_id` = 115093; -- locales_gameobject - name : entry=149481
UPDATE `trans_words` SET `content_loc7`='Rune of Markri' WHERE `word_id` = 115094; -- locales_gameobject - name : entry=149482
UPDATE `trans_words` SET `content_loc7`='Rune of Sael\'hai' WHERE `word_id` = 115095; -- locales_gameobject - name : entry=149483
UPDATE `trans_words` SET `content_loc7`='Kaldorei Tome of Summoning' WHERE `word_id` = 115100; -- locales_gameobject - name : entry=151286
UPDATE `trans_words` SET `content_loc7`='Magus Rimtori\'s Journal' WHERE `word_id` = 115110; -- locales_gameobject - name : entry=152098
UPDATE `trans_words` SET `content_loc7`='Zeppelin Landing Tower' WHERE `word_id` = 115195; -- locales_gameobject - name : entry=165557
UPDATE `trans_words` SET `content_loc7`='Stone Chair' WHERE `word_id` = 115033; -- locales_gameobject - name : entry=171567
UPDATE `trans_words` SET `content_loc7`='Stone Chair' WHERE `word_id` = 115033; -- locales_gameobject - name : entry=171568
UPDATE `trans_words` SET `content_loc7`='Stone Chair' WHERE `word_id` = 115033; -- locales_gameobject - name : entry=171674
UPDATE `trans_words` SET `content_loc7`='Stone Chair' WHERE `word_id` = 115033; -- locales_gameobject - name : entry=171675
UPDATE `trans_words` SET `content_loc7`='Stone Chair' WHERE `word_id` = 115033; -- locales_gameobject - name : entry=171676
UPDATE `trans_words` SET `content_loc7`='Stone Chair' WHERE `word_id` = 115033; -- locales_gameobject - name : entry=171677
UPDATE `trans_words` SET `content_loc7`='Stone Chair' WHERE `word_id` = 115033; -- locales_gameobject - name : entry=171718
UPDATE `trans_words` SET `content_loc7`='Stone Chair' WHERE `word_id` = 115033; -- locales_gameobject - name : entry=171719
UPDATE `trans_words` SET `content_loc7`='Stone Chair' WHERE `word_id` = 115033; -- locales_gameobject - name : entry=171720
UPDATE `trans_words` SET `content_loc7`='Stone Chair' WHERE `word_id` = 115033; -- locales_gameobject - name : entry=171721
UPDATE `trans_words` SET `content_loc7`='Bed' WHERE `word_id` = 115307; -- locales_gameobject - name : entry=174849
UPDATE `trans_words` SET `content_loc7`='Blackwood Nut Stores' WHERE `word_id` = 115359; -- locales_gameobject - name : entry=175329
UPDATE `trans_words` SET `content_loc7`='Blackwood Fruit Stores' WHERE `word_id` = 115360; -- locales_gameobject - name : entry=175330
UPDATE `trans_words` SET `content_loc7`='Blackwood Grain Stores' WHERE `word_id` = 115361; -- locales_gameobject - name : entry=175331
UPDATE `trans_words` SET `content_loc7`='Postbox' WHERE `word_id` = 115449; -- locales_gameobject - name : entry=175668
UPDATE `trans_words` SET `content_loc7`='Locked Cage' WHERE `word_id` = 115510; -- locales_gameobject - name : entry=175786
UPDATE `trans_words` SET `content_loc7`='Gadgetzan Auction' WHERE `word_id` = 115524; -- locales_gameobject - name : entry=175904
UPDATE `trans_words` SET `content_loc7`='Booty Bay Alarm Bell' WHERE `word_id` = 115533; -- locales_gameobject - name : entry=175948
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176004
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176005
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176006
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176007
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176008
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176009
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176010
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176011
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176012
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176013
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176014
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176015
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176016
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176017
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176018
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176019
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176020
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176021
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176022
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176023
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176024
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176025
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176026
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176027
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176028
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176029
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176030
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176031
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176032
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176033
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176034
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176035
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176036
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176037
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176038
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176039
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176040
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176041
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176042
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176043
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176044
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176045
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176046
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176047
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176048
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176049
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176050
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176051
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176052
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176053
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176054
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176055
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176056
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176057
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176058
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176059
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176060
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176061
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176062
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176063
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176064
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176065
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176066
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176067
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176068
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176069
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176070
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176071
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176072
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176073
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176074
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176075
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176076
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176077
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176078
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176079
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176098
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176099
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176100
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176101
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176102
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176103
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176104
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176105
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176106
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176107
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176108
UPDATE `trans_words` SET `content_loc7`='Subway Bench' WHERE `word_id` = 115538; -- locales_gameobject - name : entry=176109
UPDATE `trans_words` SET `content_loc7`='Bowel with Boobles' WHERE `word_id` = 115556; -- locales_gameobject - name : entry=176157
UPDATE `trans_words` SET `content_loc7`='Command Tent' WHERE `word_id` = 115571; -- locales_gameobject - name : entry=176210
UPDATE `trans_words` SET `content_loc7`='Boat to Menethil' WHERE `word_id` = 115591; -- locales_gameobject - name : entry=176364
UPDATE `trans_words` SET `content_loc7`='Boat to Teldrassil' WHERE `word_id` = 115592; -- locales_gameobject - name : entry=176365
UPDATE `trans_words` SET `content_loc7`='Boat to Theramore' WHERE `word_id` = 115593; -- locales_gameobject - name : entry=176369
UPDATE `trans_words` SET `content_loc7`='CavernDoor01' WHERE `word_id` = 115664; -- locales_gameobject - name : entry=176996
UPDATE `trans_words` SET `content_loc7`='Ahn\'Qiraj Gong' WHERE `word_id` = 115700; -- locales_gameobject - name : entry=177223
UPDATE `trans_words` SET `content_loc7`='Vault Door' WHERE `word_id` = 115704; -- locales_gameobject - name : entry=177237
UPDATE `trans_words` SET `content_loc7`='Vault Door' WHERE `word_id` = 115704; -- locales_gameobject - name : entry=177238
UPDATE `trans_words` SET `content_loc7`='Pull rope Bell' WHERE `word_id` = 115726; -- locales_gameobject - name : entry=177271
UPDATE `trans_words` SET `content_loc7`='CavernDoor01' WHERE `word_id` = 115664; -- locales_gameobject - name : entry=179588
UPDATE `trans_words` SET `content_loc7`='Meetingstone01' WHERE `word_id` = 115997; -- locales_gameobject - name : entry=179597
UPDATE `trans_words` SET `content_loc7`='SmallBrazier31' WHERE `word_id` = 116030; -- locales_gameobject - name : entry=179874
UPDATE `trans_words` SET `content_loc7`='SmallBrazier19' WHERE `word_id` = 116031; -- locales_gameobject - name : entry=179875
UPDATE `trans_words` SET `content_loc7`='SmallBrazier03' WHERE `word_id` = 116032; -- locales_gameobject - name : entry=179876
UPDATE `trans_words` SET `content_loc7`='SmallBrazier04' WHERE `word_id` = 116033; -- locales_gameobject - name : entry=179877
UPDATE `trans_words` SET `content_loc7`='SmallBrazier01' WHERE `word_id` = 116034; -- locales_gameobject - name : entry=179878
UPDATE `trans_words` SET `content_loc7`='OUT OF ORDER! Use Postman instead - your GM\'s' WHERE `word_id` = 116053; -- locales_gameobject - name : entry=179963
UPDATE `trans_words` SET `content_loc7`='Mysterious Wailing Caverns Chest' WHERE `word_id` = 116598; -- locales_gameobject - name : entry=180055
UPDATE `trans_words` SET `content_loc7`='Gates of Zul\'Gurub' WHERE `word_id` = 116128; -- locales_gameobject - name : entry=180323
UPDATE `trans_words` SET `content_loc7`='Gong of Bethekk' WHERE `word_id` = 116216; -- locales_gameobject - name : entry=180526
UPDATE `trans_words` SET `content_loc7`='Wickerman Guardian Ember' WHERE `word_id` = 117017; -- locales_gameobject - name : entry=180574
UPDATE `trans_words` SET `content_loc7`='Hanging, Streamers, x3' WHERE `word_id` = 116404; -- locales_gameobject - name : entry=181055
UPDATE `trans_words` SET `content_loc7`='Arena Spoils' WHERE `word_id` = 116413; -- locales_gameobject - name : entry=181074
UPDATE `trans_words` SET `content_loc7`='Grand Widow Faerlina Door' WHERE `word_id` = 116442; -- locales_gameobject - name : entry=181167
UPDATE `trans_words` SET `content_loc7`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184507
UPDATE `trans_words` SET `content_loc7`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184508
UPDATE `trans_words` SET `content_loc7`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184509
UPDATE `trans_words` SET `content_loc7`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184511
UPDATE `trans_words` SET `content_loc7`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184512
UPDATE `trans_words` SET `content_loc7`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184513
UPDATE `trans_words` SET `content_loc7`='Logs on fire' WHERE `word_id` = 116717; -- locales_gameobject - name : entry=184514
UPDATE `trans_words` SET `content_loc7`='Wooden Board' WHERE `word_id` = 116718; -- locales_gameobject - name : entry=184515
UPDATE `trans_words` SET `content_loc7`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184563
UPDATE `trans_words` SET `content_loc7`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184564
UPDATE `trans_words` SET `content_loc7`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184579
UPDATE `trans_words` SET `content_loc7`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184580
UPDATE `trans_words` SET `content_loc7`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184581
UPDATE `trans_words` SET `content_loc7`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184582
UPDATE `trans_words` SET `content_loc7`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184583
UPDATE `trans_words` SET `content_loc7`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184584
UPDATE `trans_words` SET `content_loc7`='Large x2 Fire' WHERE `word_id` = 116720; -- locales_gameobject - name : entry=184585
UPDATE `trans_words` SET `content_loc7`='Fel Orc Encampment Custom Area' WHERE `word_id` = 116892; -- locales_gameobject - name : entry=200000
UPDATE `trans_words` SET `content_loc7`='Shopping Centre' WHERE `word_id` = 116893; -- locales_gameobject - name : entry=200001
UPDATE `trans_words` SET `content_loc7`='New Year Alliance Hanging Banner' WHERE `word_id` = 116894; -- locales_gameobject - name : entry=210210
UPDATE `trans_words` SET `content_loc7`='New Year Alliance Hanging Banner 02' WHERE `word_id` = 116895; -- locales_gameobject - name : entry=210211
UPDATE `trans_words` SET `content_loc7`='New Year Horde Hanging Banner' WHERE `word_id` = 116896; -- locales_gameobject - name : entry=210212
UPDATE `trans_words` SET `content_loc7`='New Year Horde Hanging Banner 02' WHERE `word_id` = 116897; -- locales_gameobject - name : entry=210213
UPDATE `trans_words` SET `content_loc7`='New Year Alliance Standing Banner' WHERE `word_id` = 116898; -- locales_gameobject - name : entry=210214
UPDATE `trans_words` SET `content_loc7`='New Year Horde Standing Banner' WHERE `word_id` = 116899; -- locales_gameobject - name : entry=210215
UPDATE `trans_words` SET `content_loc7`='Excavation Tent Pavillion' WHERE `word_id` = 116900; -- locales_gameobject - name : entry=210286
UPDATE `trans_words` SET `content_loc7`='Ahn\'Qiraj Ossirian Crystal' WHERE `word_id` = 116901; -- locales_gameobject - name : entry=210312
UPDATE `trans_words` SET `content_loc7`='Ahn\'Qiraj Ossirian Crystal' WHERE `word_id` = 116901; -- locales_gameobject - name : entry=210313
UPDATE `trans_words` SET `content_loc7`='Communication Crystal' WHERE `word_id` = 116902; -- locales_gameobject - name : entry=210327
UPDATE `trans_words` SET `content_loc7`='Communication Crystal' WHERE `word_id` = 116902; -- locales_gameobject - name : entry=210328
UPDATE `trans_words` SET `content_loc7`='Communication Crystal' WHERE `word_id` = 116902; -- locales_gameobject - name : entry=210329
UPDATE `trans_words` SET `content_loc7`='Communication Crystal' WHERE `word_id` = 116902; -- locales_gameobject - name : entry=210330
UPDATE `trans_words` SET `content_loc7`='Communication Crystal' WHERE `word_id` = 116902; -- locales_gameobject - name : entry=210331
UPDATE `trans_words` SET `content_loc7`='Communication Crystal' WHERE `word_id` = 116902; -- locales_gameobject - name : entry=210332
UPDATE `trans_words` SET `content_loc7`='Ahn\'Qiraj Gong' WHERE `word_id` = 115700; -- locales_gameobject - name : entry=210334
UPDATE `trans_words` SET `content_loc7`='Twilight Tablet' WHERE `word_id` = 116903; -- locales_gameobject - name : entry=210335
UPDATE `trans_words` SET `content_loc7`='Twilight Tablet' WHERE `word_id` = 116903; -- locales_gameobject - name : entry=210336
UPDATE `trans_words` SET `content_loc7`='Glyphed Crystal' WHERE `word_id` = 116904; -- locales_gameobject - name : entry=210337
UPDATE `trans_words` SET `content_loc7`='Ahn\'Qiraj Sand Trap' WHERE `word_id` = 116905; -- locales_gameobject - name : entry=210339
UPDATE `trans_words` SET `content_loc7`='Hive Fireflies 01' WHERE `word_id` = 116906; -- locales_gameobject - name : entry=210341
UPDATE `trans_words` SET `content_loc7`='Glyphed Crystal' WHERE `word_id` = 116904; -- locales_gameobject - name : entry=210342
UPDATE `trans_words` SET `content_loc7`='Sand Worm Rock Base' WHERE `word_id` = 116907; -- locales_gameobject - name : entry=210343
UPDATE `trans_words` SET `content_loc7`='Silithus Crystal Formation 03' WHERE `word_id` = 116908; -- locales_gameobject - name : entry=210344
UPDATE `trans_words` SET `content_loc7`='Floating Red Crystal Broken 03' WHERE `word_id` = 116909; -- locales_gameobject - name : entry=210345
UPDATE `trans_words` SET `content_loc7`='Floating Red Crystal Broken 01' WHERE `word_id` = 116910; -- locales_gameobject - name : entry=210346
UPDATE `trans_words` SET `content_loc7`='Ahn\'Qiraj Door 01' WHERE `word_id` = 116911; -- locales_gameobject - name : entry=210347
UPDATE `trans_words` SET `content_loc7`='Floating Purple Crystal Broken 01' WHERE `word_id` = 116912; -- locales_gameobject - name : entry=210348
UPDATE `trans_words` SET `content_loc7`='Gastric Exit' WHERE `word_id` = 116913; -- locales_gameobject - name : entry=210349
UPDATE `trans_words` SET `content_loc7`='Kre\'tal\'s Wagon' WHERE `word_id` = 116914; -- locales_gameobject - name : entry=211017
UPDATE `trans_words` SET `content_loc7`='Asheron\'s Tome of Summoning' WHERE `word_id` = 116915; -- locales_gameobject - name : entry=211018
UPDATE `trans_words` SET `content_loc7`='Altar of Hyjal' WHERE `word_id` = 116916; -- locales_gameobject - name : entry=211019
UPDATE `trans_words` SET `content_loc7`='Eye of Asheron' WHERE `word_id` = 116917; -- locales_gameobject - name : entry=211021
UPDATE `trans_words` SET `content_loc7`='Commander\'s Tent' WHERE `word_id` = 116918; -- locales_gameobject - name : entry=211022
UPDATE `trans_words` SET `content_loc7`='Black Portal' WHERE `word_id` = 116919; -- locales_gameobject - name : entry=211023
UPDATE `trans_words` SET `content_loc7`='Black Portal' WHERE `word_id` = 116919; -- locales_gameobject - name : entry=211024
UPDATE `trans_words` SET `content_loc7`='Lair Exit' WHERE `word_id` = 116921; -- locales_gameobject - name : entry=211035
UPDATE `trans_words` SET `content_loc7`='Teleport-Stone to Hyjal' WHERE `word_id` = 116922; -- locales_gameobject - name : entry=211050
UPDATE `trans_words` SET `content_loc7`='Tree Stump' WHERE `word_id` = 116923; -- locales_gameobject - name : entry=211052
UPDATE `trans_words` SET `content_loc7`='Mysterious Monument' WHERE `word_id` = 116924; -- locales_gameobject - name : entry=211053
UPDATE `trans_words` SET `content_loc7`='Elwynn Fence' WHERE `word_id` = 116925; -- locales_gameobject - name : entry=211062
UPDATE `trans_words` SET `content_loc7`='Elwynn Fence' WHERE `word_id` = 116925; -- locales_gameobject - name : entry=211063
UPDATE `trans_words` SET `content_loc7`='Rockwall Fence' WHERE `word_id` = 116926; -- locales_gameobject - name : entry=211064
UPDATE `trans_words` SET `content_loc7`='Grave' WHERE `word_id` = 116927; -- locales_gameobject - name : entry=211065
UPDATE `trans_words` SET `content_loc7`='Sarcophag' WHERE `word_id` = 116928; -- locales_gameobject - name : entry=211067
UPDATE `trans_words` SET `content_loc7`='Mephistroph\'s HellFire' WHERE `word_id` = 116929; -- locales_gameobject - name : entry=211084

SET NAMES 'latin1';
