-- File generated by Mangos Online Translation Editor (MOTE) v2.10
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc7`='Waypoint' WHERE `word_id`=4588; -- locales_creature - name : entry=1
UPDATE `trans_words` SET `content_loc7`='GM Visual' WHERE `word_id`=72308; -- locales_creature - subname : entry=1
UPDATE `trans_words` SET `content_loc7`='Spawnpoint' WHERE `word_id`=72309; -- locales_creature - name : entry=2
UPDATE `trans_words` SET `content_loc7`='GM Visual' WHERE `word_id`=72308; -- locales_creature - subname : entry=2
UPDATE `trans_words` SET `content_loc7`='Enraged Form' WHERE `word_id`=74198; -- locales_creature - subname : entry=2454
UPDATE `trans_words` SET `content_loc7`='PH MODEL WIP' WHERE `word_id`=74421; -- locales_creature - subname : entry=2694
UPDATE `trans_words` SET `content_loc7`='Crocilisk Trainer' WHERE `word_id`=74578; -- locales_creature - subname : entry=2876
UPDATE `trans_words` SET `content_loc7`='Cottontail Rabbit' WHERE `word_id`=77780; -- locales_creature - name : entry=7558
UPDATE `trans_words` SET `content_loc7`='Spotted Rabbit' WHERE `word_id`=77781; -- locales_creature - name : entry=7559
UPDATE `trans_words` SET `content_loc7`='Auctioneer Wabang' WHERE `word_id`=78313; -- locales_creature - name : entry=8724
UPDATE `trans_words` SET `content_loc7`='Auctioneer Grimful' WHERE `word_id`=78686; -- locales_creature - name : entry=9856
UPDATE `trans_words` SET `content_loc7`='Spell Visual' WHERE `word_id`=78969; -- locales_creature - subname : entry=10579
UPDATE `trans_words` SET `content_loc7`='Orc Female' WHERE `word_id`=79065; -- locales_creature - subname : entry=10784
UPDATE `trans_words` SET `content_loc7`='Tauren Male' WHERE `word_id`=79066; -- locales_creature - subname : entry=10785
UPDATE `trans_words` SET `content_loc7`='Tauren Female' WHERE `word_id`=79067; -- locales_creature - subname : entry=10786
UPDATE `trans_words` SET `content_loc7`='Troll Male' WHERE `word_id`=79068; -- locales_creature - subname : entry=10787
UPDATE `trans_words` SET `content_loc7`='Troll Female' WHERE `word_id`=79069; -- locales_creature - subname : entry=10788
UPDATE `trans_words` SET `content_loc7`='Undead Male' WHERE `word_id`=79070; -- locales_creature - subname : entry=10789
UPDATE `trans_words` SET `content_loc7`='Undead Female' WHERE `word_id`=79071; -- locales_creature - subname : entry=10790
UPDATE `trans_words` SET `content_loc7`='Dwarf Male' WHERE `word_id`=79072; -- locales_creature - subname : entry=10791
UPDATE `trans_words` SET `content_loc7`='Dwarf Female' WHERE `word_id`=79073; -- locales_creature - subname : entry=10792
UPDATE `trans_words` SET `content_loc7`='Gnome Male' WHERE `word_id`=79074; -- locales_creature - subname : entry=10793
UPDATE `trans_words` SET `content_loc7`='Gnome Female' WHERE `word_id`=79075; -- locales_creature - subname : entry=10794
UPDATE `trans_words` SET `content_loc7`='Human Male' WHERE `word_id`=79076; -- locales_creature - subname : entry=10795
UPDATE `trans_words` SET `content_loc7`='Human Female' WHERE `word_id`=79077; -- locales_creature - subname : entry=10796
UPDATE `trans_words` SET `content_loc7`='Night Elf Male' WHERE `word_id`=79078; -- locales_creature - subname : entry=10797
UPDATE `trans_words` SET `content_loc7`='(Night Elf Female)' WHERE `word_id`=79079; -- locales_creature - subname : entry=10798
UPDATE `trans_words` SET `content_loc7`='The Head of The Black Flight' WHERE `word_id`=79478; -- locales_creature - subname : entry=11583
UPDATE `trans_words` SET `content_loc7`='Ghost Visual' WHERE `word_id`=80045; -- locales_creature - subname : entry=12861
UPDATE `trans_words` SET `content_loc7`='Mount Visual' WHERE `word_id`=81392; -- locales_creature - subname : entry=15778
UPDATE `trans_words` SET `content_loc7`='Ghost/Ghoul spawner' WHERE `word_id`=81712; -- locales_creature - subname : entry=16306
UPDATE `trans_words` SET `content_loc7`='Ghost/Skeleton spawner' WHERE `word_id`=81713; -- locales_creature - subname : entry=16336
UPDATE `trans_words` SET `content_loc7`='Ghoul/Skeleton spawner' WHERE `word_id`=81714; -- locales_creature - subname : entry=16338
UPDATE `trans_words` SET `content_loc7`='Ammunition Vendor' WHERE `word_id`=81854; -- locales_creature - subname : entry=17598

SET NAMES 'latin1';
