-- File generated by Mangos Online Translation Editor (MOTE) v2.00
SET NAMES 'utf8';
UPDATE locales_item SET description_loc1='Engraved with the words \'For years of service: -EVC.\'' WHERE entry=2239;
UPDATE locales_item SET description_loc1='A reagent for mage spells.' WHERE entry=5517;
UPDATE locales_item SET description_loc1='A reagent for mage spells.' WHERE entry=5518;
UPDATE locales_item SET name_loc1='Codex of Flash Heal',description_loc1='Teaches Inner Fire (Rank 2).' WHERE entry=8964;
UPDATE locales_item SET description_loc1='The completed amulet of Rakh\'likh.' WHERE entry=10757;
UPDATE locales_item SET name_loc1='Shadowforge Key',description_loc1='Master Key to the Depths, Courtesy of F.F.F.' WHERE entry=11000;
UPDATE locales_item SET description_loc1='Gor\'tesh\'s severed head, propped up on a pike.' WHERE entry=11079;
UPDATE locales_item SET name_loc1='Alex\'s Ring of Audacity',description_loc1='Looks great. Less filling.' WHERE entry=12947;
UPDATE locales_item SET description_loc1='Teaches you how to make Thorium Shells.' WHERE entry=16051;
UPDATE locales_item SET name_loc1='Key to Salem\'s Chest',description_loc1='Opens Dark Cleric Salem\'s Chest' WHERE entry=17242;
UPDATE locales_item SET name_loc1='James\' Key',description_loc1='Opens the stolen chest from the Cathedral of Light' WHERE entry=17262;
UPDATE locales_item SET description_loc1='Only ONE May Rise... (and consequently, only ONE may loot this head)' WHERE entry=20383;
UPDATE locales_item SET description_loc1='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=22345;
UPDATE locales_item SET description_loc1='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=22395;
UPDATE locales_item SET description_loc1='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=22396;
UPDATE locales_item SET description_loc1='This blade is dimensional. It appears to be fading from this plane of existence.' WHERE entry=22736;
UPDATE locales_item SET description_loc1='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=23005;
UPDATE locales_item SET description_loc1='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=23199;
UPDATE locales_item SET description_loc1='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=23200;
UPDATE locales_item SET name_loc1='Diet McWeaksauce',description_loc1='Food for the Mind' WHERE entry=23578;
UPDATE locales_item SET name_loc1='The McWeaksauce Classic',description_loc1='The Original.' WHERE entry=23579;

SET NAMES 'latin1';
