-- File generated by Mangos Online Translation Editor (MOTE) v0.8
SET NAMES 'utf8';
UPDATE creature_ai_texts SET content_loc2='Je vois que ces idiots de l\'Abbaye nous ont envoyé de la chair fraîche.' WHERE entry=-1; /* content: I see those fools at the Abbey sent some fresh meat for us. */
UPDATE creature_ai_texts SET content_loc2='La Confrérie ne tolérera pas vos actions.' WHERE entry=-2; /* content: The Brotherhood will not tolerate your actions. */
UPDATE creature_ai_texts SET content_loc2='Ah, une occasion d\'utiliser cette lame fraîchement aiguisée.' WHERE entry=-3; /* content: Ah, a chance to use this freshly sharpened blade. */
UPDATE creature_ai_texts SET content_loc2='Sentez le pouvoir de la Confrérie !' WHERE entry=-4; /* content: Feel the power of the Brotherhood! */
UPDATE creature_ai_texts SET content_loc2='Plus d\'os à ronger…' WHERE entry=-5; /* content: More bones to gnaw on... */
UPDATE creature_ai_texts SET content_loc2='Grrrr... de la viande fraîche !' WHERE entry=-6; /* content: Grrrr... fresh meat! */
UPDATE creature_ai_texts SET content_loc2='Vous pas prendre bougie !' WHERE entry=-7; /* content: You no take candle! */
UPDATE creature_ai_texts SET content_loc2='Yiieeeee ! À moi !' WHERE entry=-8; /* content: Yiieeeee! Me run! */
UPDATE creature_ai_texts SET content_loc2='VanCleef paie bien pour vos têtes !' WHERE entry=-22; /* content: VanCleef pay big for you heads! */
UPDATE creature_ai_texts SET content_loc2='Votre place n\'est pas ici ! Anciens, affrontez les intrus !' WHERE entry=-28; /* content: You do not belong here!  Ancients, rise against these intruders! */
UPDATE creature_ai_texts SET content_loc2='Le sang |2 %s jaillit !' WHERE entry=-30; /* content: %s blood sprays into the air! */
UPDATE creature_ai_texts SET content_loc2='%s est éclaboussée de sang et devient irradiée !' WHERE entry=-31; /* content: %s is splashed by the blood and becomes irradiated! */
UPDATE creature_ai_texts SET content_loc2='Justice électrique !' WHERE entry=-32; /* content: Electric justice! */
UPDATE creature_ai_texts SET content_loc2='Attention ! Attention ! Alerte intrus !' WHERE entry=-33; /* content: Warning! Warning! Intruder alert! Intruder alert! */
UPDATE creature_ai_texts SET content_loc2='Il est temps de nous rejoindre, $c.' WHERE entry=-42; /* content: Time to join us, $c. */
UPDATE creature_ai_texts SET content_loc2='%s est pris de frénésie  !' WHERE entry=-46; /* content: %s becomes enraged! */
UPDATE creature_ai_texts SET content_loc2='%s essaie de s\'enfuir dans un moment de panique !' WHERE entry=-47; /* content: %s attempts to run away in fear! */
UPDATE creature_ai_texts SET content_loc2='Tellement sombre...' WHERE entry=-73; /* content: So dark... */
UPDATE creature_ai_texts SET content_loc2='Aaaaahhh ! Si près de la liberté.' WHERE entry=-74; /* content: Aaaaahhh! So close to escaping. */
UPDATE creature_ai_texts SET content_loc2='Vous n\'éveillerez pas le rêveur !' WHERE entry=-99; /* content: You will never wake the dreamer! */
UPDATE creature_ai_texts SET content_loc2='%s pousse un cri strident pour appeler à l’aide !' WHERE entry=-100; /* content: %s lets out a high pitched screech, calling for help! */
UPDATE creature_ai_texts SET content_loc2='Pour les Gueules-de-dragon !' WHERE entry=-101; /* content: For the Dragonmaw! */
UPDATE creature_ai_texts SET content_loc2='Longue vie aux Gueules-de-dragon ! Meurs, sale $r !' WHERE entry=-102; /* content: Long live the Dragonmaw! Die you worthless $r! */
UPDATE creature_ai_texts SET content_loc2='Cerveaux...' WHERE entry=-103; /* content: Brains... */
UPDATE creature_ai_texts SET content_loc2='Vos os se briseront sous ma botte, $r !' WHERE entry=-105; /* content: Your bones will break under my boot, $r! */
UPDATE creature_ai_texts SET content_loc2='%s est pris de frénésie !' WHERE entry=-106; /* content: %s goes into a frenzy! */
UPDATE creature_ai_texts SET content_loc2='Satanés curieux ! Je vous apprendrai à vous mêler de mes affaires !' WHERE entry=-133; /* content: Troublesome whelps. I\'ll teach you to interfere! */
UPDATE creature_ai_texts SET content_loc2='Vous, les intrus, allez payer pour avoir empiété sur nos terres !' WHERE entry=-135; /* content: You outsiders will pay for encroaching on our land! */
UPDATE creature_ai_texts SET content_loc2='Bah ! Ma puissance est maîtresse, ici !' WHERE entry=-136; /* content: Bah! My power rules here! */
UPDATE creature_ai_texts SET content_loc2='Je renaîtrai, mortels ! Incendius rendra la vie à mes cendres !' WHERE entry=-137; /* content: I will be reborn, mortals! Incendius shall raise me from these ashes! */
UPDATE creature_ai_texts SET content_loc2='Les Défias vaincront ! Jamais un aventurier de pacotille ne nous arrêtera !' WHERE entry=-143; /* content: The Defias shall succeed! No meek adventurer will stop us! */
UPDATE creature_ai_texts SET content_loc2='$gUn:Une:r; $r $gvivant:vivante:r;... $gil:elle; sera bientôt $gmort:morte; comme moi.' WHERE entry=-161; /* content: A living $r... soon to be a dead like me. */
UPDATE creature_ai_texts SET content_loc2='Humm... J’adore la bière brune d’Austrivage.' WHERE entry=-162; /* content: Mmm... I love my delicious Southshore stout. */
UPDATE creature_ai_texts SET content_loc2='Tuez-les, mes frères ! Pour le Fléau !' WHERE entry=-163; /* content: Slay them, my brethren! For the Scourge! */
UPDATE creature_ai_texts SET content_loc2='Nous réduirons les hurans en esclavage !' WHERE entry=-164; /* content: We will enslave the quilboar! */
UPDATE creature_ai_texts SET content_loc2='Nous nous répandrons sur ces terres désolées !' WHERE entry=-165; /* content: We will spread across this barren land! */
UPDATE creature_ai_texts SET content_loc2='Bientôt, le Fléau régnera sur le monde !' WHERE entry=-166; /* content: Soon, the Scourge will rule the world! */
UPDATE creature_ai_texts SET content_loc2='Tuez !!' WHERE entry=-167; /* content: KILL!!! */
UPDATE creature_ai_texts SET content_loc2='Qui ose me déranger ? Meurs, $n !' WHERE entry=-168; /* content: Who dares disturb me?  Die $N! */
UPDATE creature_ai_texts SET content_loc2='Personne ne peut défier la Confrérie !' WHERE entry=-169; /* content: None may challenge the Brotherhood! */
UPDATE creature_ai_texts SET content_loc2='Et restez au sol !' WHERE entry=-170; /* content: And stay down! */
UPDATE creature_ai_texts SET content_loc2='Chiens ! Tous autant que vous êtes.' WHERE entry=-171; /* content: Lapdogs, all of you! */
UPDATE creature_ai_texts SET content_loc2='Imbéciles ! Notre cause est juste !' WHERE entry=-172; /* content: Fools! Our cause is righteous! */
UPDATE creature_ai_texts SET content_loc2='La Confrérie prévaudra !' WHERE entry=-173; /* content: The Brotherhood shall prevail! */
UPDATE creature_ai_texts SET content_loc2='Rah ! Vous commencez sérieusement à m\'échauffer !' WHERE entry=-176; /* content: D\'ah! Now you\'re making me angry! */
UPDATE creature_ai_texts SET content_loc2='Je vais transformer votre peau en veston pour le fumoir ! Les cigares ? Vous devrez les prendre sur mon corps... heu... RAWR !!!!' WHERE entry=-177; /* content: I\'m going to wear your skin as a smoking jacket! The stogies? You\'ll have to pry them from my cold dead... er... RAWR!!!! */
UPDATE creature_ai_texts SET content_loc2='C\'est ça que vous cherchez ??? Vous ne les aurez jamais !' WHERE entry=-178; /* content: Looking for these???? You\'ll never have em! */
UPDATE creature_ai_texts SET content_loc2='Avouez et nous vous libérerons.' WHERE entry=-185; /* content: Confess and we shall set you free. */
UPDATE creature_ai_texts SET content_loc2='Les vivants sont là !' WHERE entry=-186; /* content: The living are here! */
UPDATE creature_ai_texts SET content_loc2='Un infâme trogg. Meurs !' WHERE entry=-188; /* content: A foul trogg if ever I saw one.  Die! */
UPDATE creature_ai_texts SET content_loc2='Cette maladie trouble ma vision mais, à mon avis, vous devez être un trogg. Meurs, infâme envahisseur !' WHERE entry=-189; /* content: This sickness clouds my vision, but I know you must be a trogg.  Die foul invader! */
UPDATE creature_ai_texts SET content_loc2='Aucun gnome ne sera abandonné.' WHERE entry=-190; /* content: No gnome will be left behind. */
UPDATE creature_ai_texts SET content_loc2='Les troggs... ils ne cessent de nous envahir. Qu’ils meurent ! Qu’ils meurent !' WHERE entry=-191; /* content: The troggs...they never stop coming.  Die trogg!  Die! */
UPDATE creature_ai_texts SET content_loc2='Il peut faire vraiment chaud ici, dans les Terres ingrates. Mais au moins c’est une chaleur sèche.' WHERE entry=-192; /* content: It can get really hot here in the Badlands. But at least it\'s a dry heat. */
UPDATE creature_ai_texts SET content_loc2='Bidules... c’est bon. Machins... c’est bon. Trucs... c’est bon.' WHERE entry=-193; /* content: Gizmos... check. Doothingies... check. Wizzers... check. */
UPDATE creature_ai_texts SET content_loc2='Un jour, je serai un vrai garçon.' WHERE entry=-194; /* content: One day I\'ll be a real boy. */
UPDATE creature_ai_texts SET content_loc2='Brzt... click... whir...' WHERE entry=-195; /* content: Brzt... click... whir... */
UPDATE creature_ai_texts SET content_loc2='C’est dangereux ici, maître. Mais j’aiderai à monter la garde.' WHERE entry=-196; /* content: It is dangerous here, master. But I shall help stand guard. */
UPDATE creature_ai_texts SET content_loc2='Nous pouvons l’améliorer, le rendre plus solide et plus rapide. Nous avons la technologie. Nous avons le pouvoir magique.' WHERE entry=-197; /* content: We can make it better, stronger, faster. We have the technology. We have the magic. */
UPDATE creature_ai_texts SET content_loc2='Vous n\'avez rien à faire ici ! Tuez-les !' WHERE entry=-198; /* content: You should not be here! Slay them! */
UPDATE creature_ai_texts SET content_loc2='Vous serez une proie facile, $c.' WHERE entry=-200; /* content: You will be easy prey, $c. */
UPDATE creature_ai_texts SET content_loc2='Mes griffes déchiquetteront votre corps chétif, $r.' WHERE entry=-201; /* content: My talons will shred your puny body, $r. */
UPDATE creature_ai_texts SET content_loc2='Votre tête fera un beau trophée, $r.' WHERE entry=-202; /* content: A fine trophy your head will make, $r. */
UPDATE creature_ai_texts SET content_loc2='NON ! Ça met le tanin dans le panier, ou ça tâte encore du maillet !' WHERE entry=-203; /* content: NO!!!  It puts the tannin in the basket, or it gets the mallet again! */
UPDATE creature_ai_texts SET content_loc2='Pain frais !' WHERE entry=-204; /* content: Fresh bread for sale! */
UPDATE creature_ai_texts SET content_loc2='Pain frais, tout juste sorti du four !' WHERE entry=-205; /* content: Freshly baked bread for sale! */
UPDATE creature_ai_texts SET content_loc2='Un coup de main à une pauvre malheureuse ?' WHERE entry=-207; /* content: Help a poor bloke out? */
UPDATE creature_ai_texts SET content_loc2='Misérable $c, je te ferai rejoindre l\'au-delà !' WHERE entry=-210; /* content: I\'ll deliver you, weak $c, to the afterlife! */
UPDATE creature_ai_texts SET content_loc2='Meurs au nom d’Edwin Van Cleef !' WHERE entry=-211; /* content: Die in the name of Edwin van Cleef! */
UPDATE creature_ai_texts SET content_loc2='ÉCRASE !' WHERE entry=-213; /* content: Crush! */
UPDATE creature_ai_texts SET content_loc2='TUER !' WHERE entry=-214; /* content: KILL! */
UPDATE creature_ai_texts SET content_loc2='DÉTRUIRE !' WHERE entry=-215; /* content: Destroy! */
UPDATE creature_ai_texts SET content_loc2='Moi transformer vous en mojo !' WHERE entry=-228; /* content: I gonna make you into mojo! */
UPDATE creature_ai_texts SET content_loc2='Tuer vous être facile.' WHERE entry=-229; /* content: Killing you be easy. */
UPDATE creature_ai_texts SET content_loc2='Vous mourrez bientôt !' WHERE entry=-230; /* content: You be dead soon! */
UPDATE creature_ai_texts SET content_loc2='Je vous découperai !' WHERE entry=-231; /* content: I\'ll cut you! */
UPDATE creature_ai_texts SET content_loc2='La Confrérie ne sera pas entravée par des insectes.' WHERE entry=-232; /* content: The Brotherhood will not be hampered by insects. */
UPDATE creature_ai_texts SET content_loc2='Celui-ci est un peu mieux que le dernier. Mais il souffre de la même fragilité osseuse que les autres. Si vous arrivez à en invoquer un, vous êtes sur la bonne voie.' WHERE entry=-311; /* content: This one is slightly better than the last. However, it still suffers from the same flimsy bone structure as the others. When you summon one of these, you are on the right path. */
UPDATE creature_ai_texts SET content_loc2='Que les sables vous engloutissent !' WHERE entry=-320; /* content: Sands consume you! */
UPDATE creature_ai_texts SET content_loc2='Il est temps de frapper !' WHERE entry=-324; /* content: Time to bash! */
UPDATE creature_ai_texts SET content_loc2='%s surgit des ténèbres !' WHERE entry=-341; /* content: %s jumps out of the shadows! */
UPDATE creature_ai_texts SET content_loc2='%s appelle d’autres alliés à quitter les ténèbres.' WHERE entry=-342; /* content: %s calls more of his allies out of the shadows. */
UPDATE creature_ai_texts SET content_loc2='%s grogne dans votre direction avant de prendre le temps de vous renifler.' WHERE entry=-343; /* content: %s growls in your direction before taking time to sniff you. */
UPDATE creature_ai_texts SET content_loc2='%s commence à appeler du renfort !' WHERE entry=-346; /* content: %s begins to summon in reinforcements! */
UPDATE creature_ai_texts SET content_loc2='Moi pas fuir $c comme vous !' WHERE entry=-353; /* content: Me no run from $c like you! */
UPDATE creature_ai_texts SET content_loc2='Yip ! Moi tuer !' WHERE entry=-354; /* content: Yip! Me kill! */
UPDATE creature_ai_texts SET content_loc2='$gUn bon:Une bonne:r; $r est $gun:une:r; $r $gmort:morte:r; !' WHERE entry=-355; /* content: The only good $r is a dead $r! */
UPDATE creature_ai_texts SET content_loc2='Misérable $c ! Tu n’es pas de taille à combattre la tribu Brisepierre !' WHERE entry=-356; /* content: Weak $c! You are no match for the Stonesplinter Tribe! */
UPDATE creature_ai_texts SET content_loc2='Sentez le pouvoir des nains sombrefers !' WHERE entry=-357; /* content: Feel the power of the Dark Iron Dwarves! */
UPDATE creature_ai_texts SET content_loc2='Je vais vous écraser !' WHERE entry=-359; /* content: I will crush you! */
UPDATE creature_ai_texts SET content_loc2='Moi détruire ! Vous mourir !' WHERE entry=-360; /* content: Me smash! You die! */
UPDATE creature_ai_texts SET content_loc2='Raaaaaaaaaaaaar !!! Moi détruire $r !' WHERE entry=-361; /* content: Raaar!!! Me smash $r! */
UPDATE creature_ai_texts SET content_loc2='Le roi Magni Barbe-de-bronze est un imbécile et un charlatan !' WHERE entry=-362; /* content: King Magni Bronzebeard is a fool and a charlatan! */
UPDATE creature_ai_texts SET content_loc2='Héhéhé ! Je vous emporte avec moi !' WHERE entry=-364; /* content: Wahehe! I\'m taking you down with me! */
UPDATE creature_ai_texts SET content_loc2='J’en ai assez de ces idioties ! Prépare-toi à mourir !' WHERE entry=-365; /* content: I tire of this nonsense! Prepare to die! */
UPDATE creature_ai_texts SET content_loc2='Hein ? Quoi ?' WHERE entry=-367; /* content: Huh? What dat? */
UPDATE creature_ai_texts SET content_loc2='$gCe:Cette:r; $r a l\'air bon à manger !' WHERE entry=-368; /* content: Dat $r look gud to eat! */
UPDATE creature_ai_texts SET content_loc2='Frappez-le !' WHERE entry=-369; /* content: Bash it! */
UPDATE creature_ai_texts SET content_loc2='$gUn:Une:c; $c $gappelé:appelée:c; $n ? Vous ferez un bon petit-déjeuner !' WHERE entry=-370; /* content: A $c called $N? You\'ll make a fine breakfast! */
UPDATE creature_ai_texts SET content_loc2='Meurs au nom de Ragnaros !' WHERE entry=-373; /* content: Die in the name of Ragnaros! */
UPDATE creature_ai_texts SET content_loc2='Les yeux rougis |2 %s brillent tandis qu\'il allume sa dynamite et se met à caqueter comme un fou !' WHERE entry=-375; /* content: %s\'s eyes glow red as he lights his dynamite and begins to cackle madly! */
UPDATE creature_ai_texts SET content_loc2='%s paraît beaucoup plus calme après avoir mangé les restes |2 $n.' WHERE entry=-405; /* content: %s seems much calmer now that it has eaten the remains of $N. */
UPDATE creature_ai_texts SET content_loc2='Ne contrariez jamais un Sombrefer, $c.' WHERE entry=-406; /* content: Never cross a Dark Iron, $c. */
UPDATE creature_ai_texts SET content_loc2='Ton sang va couler, $c !' WHERE entry=-407; /* content: I shall spill your blood, $c! */
UPDATE creature_ai_texts SET content_loc2='Quelqu’un veut faire une pause ? Eh bien c’est dommage ! Au travail, bande de gros balourds !' WHERE entry=-408; /* content: Anyone want to take a break?  Well too bad!  Get to work you oafs! */
UPDATE creature_ai_texts SET content_loc2='Dépêchez-vous d’acheminer ces pièces au bateau !' WHERE entry=-409; /* content: Get those parts moving down to the ship! */
UPDATE creature_ai_texts SET content_loc2='Hmmm, celui-ci ferait à peine un xylophone. Prenez des notes ! Ce n\'est PAS ce que vous voulez invoquer au cœur des combats.' WHERE entry=-410; /* content: Hmmm, this one looks like something that would be better off as a windchime. Take notes class... This is NOT what you want to summon in the heat of battle. */
UPDATE creature_ai_texts SET content_loc2='Je te paierai volontiers mardi pour avoir un bon steak aujourd’hui.' WHERE entry=-411; /* content: I will gladly pay you Tuesday for a hamburger today. */
UPDATE creature_ai_texts SET content_loc2='C’est entièrement leur faute à ces imbéciles de soldats de l’Alliance. Il fallait qu\'ils aillent construire leurs tours juste derrière ma ferme.' WHERE entry=-413; /* content: It\'s all their fault, stupid Alliance army. Just had to build their towers right behind my farm. */
UPDATE creature_ai_texts SET content_loc2='Si le capitaine me démasque, ce sera la fin pour moi.' WHERE entry=-414; /* content: If the Captain finds out, it\'ll be the end of me. */
UPDATE creature_ai_texts SET content_loc2='Quelqu\'un a dû les aider.' WHERE entry=-415; /* content: They must have had someone helping them. */
UPDATE creature_ai_texts SET content_loc2='Tout à coup, ils étaient partout.' WHERE entry=-416; /* content: All of a sudden they were everywhere. */
UPDATE creature_ai_texts SET content_loc2='J’ai l’impression de m’enraciner dans les pavés.' WHERE entry=-423; /* content: Think I\'m starting to wear a rut in the paving stones. */
UPDATE creature_ai_texts SET content_loc2='C’est moi qui transporte toute l’eau par ici.' WHERE entry=-424; /* content: Jack and Jill my wrinkled patoot! I do all the water luggin\' \'round here. */
UPDATE creature_ai_texts SET content_loc2='Comme si, à mon grand âge, je n’avais pas mieux à faire que de porter des seaux d’eau.' WHERE entry=-427; /* content: As if I don\'t have better things to do in my old age than carry buckets of water. */
UPDATE creature_ai_texts SET content_loc2='On est arrivés ?' WHERE entry=-429; /* content: Are we there yet? */
UPDATE creature_ai_texts SET content_loc2='J\'ai mal aux pieds.' WHERE entry=-430; /* content: My feet hurt. */
UPDATE creature_ai_texts SET content_loc2='Pourquoi passons-nous toujours par le même chemin ?' WHERE entry=-432; /* content: Why do we always go the same way? */
UPDATE creature_ai_texts SET content_loc2='Où on va ?' WHERE entry=-433; /* content: Where we goin\'? */
UPDATE creature_ai_texts SET content_loc2='J’veux voir la tour des Mages.' WHERE entry=-434; /* content: I wanna see the Mage Tower. */
UPDATE creature_ai_texts SET content_loc2='Voici un exemple de ce qu’il ne faut pas invoquer. Regardez cette silhouette rachitique, cette ossature fragile. Un bon coup de masse projetterait des éclats d’os un peu partout.' WHERE entry=-435; /* content: Now this is an example of what not to summon. Look, it\'s frail and brittle. One good whack from a mace will send bone shards flying. */
UPDATE creature_ai_texts SET content_loc2='Nous avons été trahis !' WHERE entry=-438; /* content: We are betrayed! */
UPDATE creature_ai_texts SET content_loc2='%s pousse un cri strident.' WHERE entry=-448; /* content: %s lets out a shrill cry. */
UPDATE creature_ai_texts SET content_loc2='$gQuel est ce simple:Quelle est cette simple:r; $r qui vient se mêler de ce qui appartient au passé ? Que la légende de Stalvan périsse avec toi !' WHERE entry=-449; /* content: Who is this mere $r that meddles with that which is past?  May the legend of Stalvan die along with you! */
UPDATE creature_ai_texts SET content_loc2='Ne remuez pas les choses qui appartiennent au passé, $n !' WHERE entry=-450; /* content: Toil not in matters of the past, $N! */
UPDATE creature_ai_texts SET content_loc2='Pourquoi les gardes de Hurlevent ne sont-ils pas venus ?' WHERE entry=-451; /* content: Why haven\'t the Stormwind guards come? */
UPDATE creature_ai_texts SET content_loc2='La Lumière semble nous avoir abandonnés.' WHERE entry=-452; /* content: The light appears to have forsaken us. */
UPDATE creature_ai_texts SET content_loc2='Les nouvelles en provenance de Hurlevent n’augurent rien de bon...' WHERE entry=-453; /* content: The news from Stormwind does not bode well. . . . */
UPDATE creature_ai_texts SET content_loc2='Nos querelles incessantes ne nous mèneront à rien. Nous devons agir.' WHERE entry=-454; /* content: Constant bickering will get us nowhere.  We need to take action. */
UPDATE creature_ai_texts SET content_loc2='Je crains l’arrivée de quelque chose de sombre.' WHERE entry=-456; /* content: I fear something dark is coming. */
UPDATE creature_ai_texts SET content_loc2='De l’autre côté des épaisses murailles de pierre de Hurlevent, nul ne prête l’oreille à notre cause.' WHERE entry=-457; /* content: Our cause falls on deaf ears beyond the thick, stone walls of Stormwind. */
UPDATE creature_ai_texts SET content_loc2='Le peuple de Sombre-Comté en attend plus du Conseil. Nous ne pouvons pas les laisser subir cette colère impie qui nous tourmente.' WHERE entry=-458; /* content: The people of Darkshire expect more from the Council.  We cannot let them suffer from this unholy wrath which plagues us. */
UPDATE creature_ai_texts SET content_loc2='Les terres fourmillent de morts-vivants. Où est l’Armée de Hurlevent ?' WHERE entry=-459; /* content: Undead are crawling all over the land.  Where is the Stormwind Army? */
UPDATE creature_ai_texts SET content_loc2='Attendez… Vous n’êtes pas mon mari. Mais il doit vous avoir envoyé. Et vous avez l’air… délicieux !' WHERE entry=-460; /* content: Wait...you are not my husband.  But he must have sent you.  And you...look..delicious! */
UPDATE creature_ai_texts SET content_loc2='Aber ? C’est toi ? Oh… J’ai tellement faim, Aber ! TELLEMENT FAIM !!' WHERE entry=-461; /* content: Aber?  Is that you...?  Oh...I\'m so hungry, Aber!  SO HUNGRY!! */
UPDATE creature_ai_texts SET content_loc2='Le Conseil du bois de la Pénombre doit agir. Le mal imprègne l\'air.' WHERE entry=-462; /* content: The Council of Duskwood must take action.  Evil lingers in the air. */
UPDATE creature_ai_texts SET content_loc2='Vous n\'arrêterez jamais les Réprouvés, $r. La Dame noire vous fera souffrir.' WHERE entry=-469; /* content: You will never stop the Forsaken, $r. The Dark Lady shall make you suffer. */
UPDATE creature_ai_texts SET content_loc2='Je vous jure que je trouverai un emploi pour votre corps une fois que je vous aurai tué, $r.' WHERE entry=-470; /* content: You have my word that I shall find a use for your body after I\'ve killed you, $r. */
UPDATE creature_ai_texts SET content_loc2='%s commence à se crevasser et à se briser.' WHERE entry=-471; /* content: %s begins to crack and break apart. */
UPDATE creature_ai_texts SET content_loc2='La force |2 %s diminue à mesure que des morceaux de roche se détachent.' WHERE entry=-472; /* content: %s\'s strength dwindles as chunks of rock break off. */
UPDATE creature_ai_texts SET content_loc2='%s n\'est plus qu\'un tas de décombres mais continue à se battre.' WHERE entry=-473; /* content: %s is reduced to rubble, but still continues to fight. */
UPDATE creature_ai_texts SET content_loc2='J\'ai un lumbago horrible !' WHERE entry=-490; /* content: My back is killing me. */
UPDATE creature_ai_texts SET content_loc2='Si j\'échoue, prenez ma sacoche. Il faut à tout prix qu\'elle arrive jusqu\'au Grand général.' WHERE entry=-491; /* content: If I should fall, take my pouch. Make certain that it gets to the High General. */
UPDATE creature_ai_texts SET content_loc2='Je sens un danger proche...' WHERE entry=-492; /* content: I sense danger up ahead. */
UPDATE creature_ai_texts SET content_loc2='Mes griffes déchiquetteront votre corps chétif, $r.' WHERE entry=-494; /* content: My talons will shred your puny body, $r. */
UPDATE creature_ai_texts SET content_loc2='Je présume que vous m\'apportez de bonnes nouvelles ?' WHERE entry=-502; /* content: I presume you come with good news? */
UPDATE creature_ai_texts SET content_loc2='Tout se passe comme prévu, seigneur Lépervier. Je vous assure que ce n\'est qu\'une question de temps.' WHERE entry=-503; /* content: Things are going as planned, Lord Falconcrest. I assure you, it is only a matter of time. */
UPDATE creature_ai_texts SET content_loc2='%s commence à invoquer un Tisseur d\'effroi Main-noire !' WHERE entry=-523; /* content: %s begins to summon in a Blackhand Dreadweaver! */
UPDATE creature_ai_texts SET content_loc2='%s commence à invoquer un vétéran Main-noire !' WHERE entry=-524; /* content: %s begins to summon in a Blackhand Veteran! */
UPDATE creature_ai_texts SET content_loc2='%s invoque un Tisseur d\'effroi Main-noire pour qu\'il vienne l\'aider !' WHERE entry=-525; /* content: %s summons a Blackhand Dreadweaver to his aid! */
UPDATE creature_ai_texts SET content_loc2='%s invoque un vétéran Main-noire pour qu\'il vienne l\'aider !' WHERE entry=-526; /* content: %s summons a Blackhand Veteran to his aid! */
UPDATE creature_ai_texts SET content_loc2='Le Tout-puissant t\'écrasera !' WHERE entry=-527; /* content: The Great One will smash you! */
UPDATE creature_ai_texts SET content_loc2='Meurs ! Tu ne libéreras pas Myzrael !' WHERE entry=-528; /* content: Die!  You will not free Myzrael! */
UPDATE creature_ai_texts SET content_loc2='Tenez bon, mes frères, et ne craignez rien ! La taille joue en notre faveur !' WHERE entry=-529; /* content: Stand firm, brothers.  And don\'t worry!  Size is on our side! */
UPDATE creature_ai_texts SET content_loc2='Non ! Laissez-nous ! Nous ne devons pas faillir à notre tâche !' WHERE entry=-530; /* content: No!  Leave us!  We must not fail our task! */
UPDATE creature_ai_texts SET content_loc2='Prends ça ! Les Sèches-moustaches vaincront !' WHERE entry=-531; /* content: Take that!  The Drywhiskers will prevail! */
UPDATE creature_ai_texts SET content_loc2='Stop ! Pauvre $c, nous ne pouvons pas vous laisser invoquer la créature Myzrael !' WHERE entry=-532; /* content: Stop!  Foolish $c, we cannot let you summon the creature Myzrael! */
UPDATE creature_ai_texts SET content_loc2='Recherche de formes de vie… cible non trouvée' WHERE entry=-545; /* content: Scanning life forms....target not found */
UPDATE creature_ai_texts SET content_loc2='Cible perdue… reprise de la configuration de recherche Delta' WHERE entry=-546; /* content: Target lost....resuming search patterns Delta */
UPDATE creature_ai_texts SET content_loc2='Formes de vie inconnues détectées… évaluation…' WHERE entry=-547; /* content: Unknown life forms detected....assessing... */
UPDATE creature_ai_texts SET content_loc2='Gardes !' WHERE entry=-549; /* content: Guards! */
UPDATE creature_ai_texts SET content_loc2='%s se met en rage après avoir vu un ami tomber au combat !' WHERE entry=-550; /* content: %s goes into a rage after seeing a friend fall in battle! */
UPDATE creature_ai_texts SET content_loc2='%s appelle à l’aide !' WHERE entry=-551; /* content: %s calls for help! */
UPDATE creature_ai_texts SET content_loc2='Qui ose violer le sanctuaire d’Eldre’Thalas ? Affrontez-moi, lâches !' WHERE entry=-553; /* content: Who dares disrupt the sanctity of Eldre\'Thalas? Face me, cowards! */
UPDATE creature_ai_texts SET content_loc2='Enfin, mon âme va pouvoir reposer en paix... Oh, très cher Cerellean...' WHERE entry=-554; /* content: Finally, my soul may rest... Oh, dearest Cerellean... */
UPDATE creature_ai_texts SET content_loc2='Par la barbe de Thaurissan ! Tuez-les !' WHERE entry=-576; /* content: By Thaurissan\'s beard! Slay them! */
UPDATE creature_ai_texts SET content_loc2='Moi Grimelok, roi !' WHERE entry=-577; /* content: Me Grimlok, king! */
UPDATE creature_ai_texts SET content_loc2='À mort ! À mort !' WHERE entry=-578; /* content: Die! Die! */
UPDATE creature_ai_texts SET content_loc2='MOUREZ, MORTELS !' WHERE entry=-580; /* content: DIE, MORTALS! */
UPDATE creature_ai_texts SET content_loc2='Bijou sait où les trésors sont cachés.' WHERE entry=-582; /* content: Bijou knows where treasures are hidden. */
UPDATE creature_ai_texts SET content_loc2='GROA !! *tousse* *tousse* Faut que j\'arrête de fumer.' WHERE entry=-583; /* content: SQUAWK!! *cough* *cough* I need to quit smoking! */
UPDATE creature_ai_texts SET content_loc2='Demandez à Kibler pour le trésor ! GROA !' WHERE entry=-584; /* content: Ask Kibler about the treasure! SQUAWK! */
UPDATE creature_ai_texts SET content_loc2='Opus veut l\'or de Cuergo... avec des vers.' WHERE entry=-586; /* content: Opus wants some Cuergo\'s Gold... with worm. */
UPDATE creature_ai_texts SET content_loc2='La SgPA mène une enquête sur Kibler.' WHERE entry=-587; /* content: Kibler is being investigated by G.E.T.A. */
UPDATE creature_ai_texts SET content_loc2='%s pousse un rugissement qui alerte ses alliés proches, et devient enragé !' WHERE entry=-648; /* content: %s lets out a deep roar, alerting nearby allies and becoming enraged! */
UPDATE creature_ai_texts SET content_loc2='%s pique une colère d’ivrogne !' WHERE entry=-649; /* content: %s goes into a drunken rage! */
UPDATE creature_ai_texts SET content_loc2='Lorsque je trébuchai sur les pierres de Suntara, sur le site de fouilles de Crasseboue, la puissance de Ragnaros afflua dans mon corps. Ragnaros m\'avait donné un but.' WHERE entry=-660; /* content: When I stumbled upon the Suntara stones at the Grimesilt Digsite, the power of Ragnaros surged through my being. It was Ragnaros that gave me a purpose. */
UPDATE creature_ai_texts SET content_loc2='C\'est Ragnaros qui a voulu construire l\'Obsidion. L\'Obsidion détruira les orcs du pic Rochenoire, en nous unissant à nos frères des profondeurs flamboyantes.' WHERE entry=-661; /* content: It was the will of Ragnaros that Obsidion be built. Obsidion will destroy the Blackrock orcs of Blackrock Spire, uniting us with our bretheren in the fiery depths. */
UPDATE creature_ai_texts SET content_loc2='Et finalement, ce fut Ragnaros qui me donna un nom quand je naquis de nouveau sous la forme d\'un acolyte de feu : Lathoric... Lathoric le Noir.' WHERE entry=-662; /* content: And ultimately, it was Ragnaros that named me when I was reborn as an acolyte of fire: Lathoric... Lathoric the Black. */
UPDATE creature_ai_texts SET content_loc2='Votre tâche est accomplie. Préparez-vous à affronter votre destin.' WHERE entry=-664; /* content: Your task is complete. Prepare to meet your doom. */
UPDATE creature_ai_texts SET content_loc2='Écoutez attentivement, car le seigneur de Rochenoire va sûrement vous détruire si vous n\'êtes pas correctement préparés.' WHERE entry=-667; /* content: Listen carefully, for the lord of Blackrock will surely destroy you, should you not be prepared. */
UPDATE creature_ai_texts SET content_loc2='%s tombe en morceaux !' WHERE entry=-694; /* content: %s chips and splinters! */
UPDATE creature_ai_texts SET content_loc2='Personne n’a le droit de voler le secret des Faiseurs !' WHERE entry=-695; /* content: None may steal the secrets of the Makers! */
UPDATE creature_ai_texts SET content_loc2='Sables du désert, à moi ! Cachez le soleil !' WHERE entry=-698; /* content: Sands of the desert, rise and block out the sun! */
UPDATE creature_ai_texts SET content_loc2='Vous avez été liquidés.' WHERE entry=-699; /* content: You are terminated. */
UPDATE creature_ai_texts SET content_loc2='Guerriers ! Capitaines ! Continuez le combat !' WHERE entry=-702; /* content: Warriors! Captains! Continue the fight! */
UPDATE creature_ai_texts SET content_loc2='%s supplie qu\'on le libère de ses souffrances.' WHERE entry=-704; /* content: %s begs to be put out of his misery. */
UPDATE creature_ai_texts SET content_loc2='%s grogne.' WHERE entry=-705; /* content: %s groans. */
UPDATE creature_ai_texts SET content_loc2='%s pleurniche pitoyablement.' WHERE entry=-706; /* content: %s weeps pitifully. */
UPDATE creature_ai_texts SET content_loc2='Le déjeuner est servi, mes chers enfants. Écorchez-les vifs !' WHERE entry=-710; /* content: Lunch has arrived, my beautiful children. Tear them to pieces! */
UPDATE creature_ai_texts SET content_loc2='Levez-vous et défendez votre maître !' WHERE entry=-711; /* content: Rise and defend your master! */
UPDATE creature_ai_texts SET content_loc2='Les enfants de Sul protègeront leur maître. Vive Sul\'lithuz !' WHERE entry=-712; /* content: The children of Sul will protect their master. Rise once more Sul\'lithuz! */
UPDATE creature_ai_texts SET content_loc2='Ilifar, votre maître vous attend !' WHERE entry=-713; /* content: Ilifar, your master calls! */
UPDATE creature_ai_texts SET content_loc2='Que les flammes du chaos vous engloutissent !' WHERE entry=-714; /* content: Let the flames of chaos engulf you! */
UPDATE creature_ai_texts SET content_loc2='Affrontez mon champion, mortels !' WHERE entry=-715; /* content: Face my champion, mortals! */
UPDATE creature_ai_texts SET content_loc2='Préparez-vous à subir une éternité d\'angoisses et de tortures. Vengeance !' WHERE entry=-716; /* content: Prepare yourselves for an eternity of anguish and torture - vengeance shall be mine... */
UPDATE creature_ai_texts SET content_loc2='QUITTEZ CES LIEUX !' WHERE entry=-764; /* content: Leave this place! */
UPDATE creature_ai_texts SET content_loc2='%s lâche sa massue et commence à cogner frénétiquement !' WHERE entry=-797; /* content: %s puts his club away and begins swinging wildly! */
UPDATE creature_ai_texts SET content_loc2='%s commence à répliquer à toutes les attaques !' WHERE entry=-807; /* content: %s begins to retaliate all attacks against him! */
UPDATE creature_ai_texts SET content_loc2='Personne ne menace l\'roi d\'vant moi ! Ungh, prends ça !' WHERE entry=-808; /* content: No one get past me and threaten da king!  Ungh, take it!! */
UPDATE creature_ai_texts SET content_loc2='Aidez-moi à écraser ces larves !' WHERE entry=-809; /* content: Help me crush these punys! */
UPDATE creature_ai_texts SET content_loc2='Partez ! Ne réveillez pas le rêveur !' WHERE entry=-819; /* content: Turn back! Do not wake the dreamer! */
UPDATE creature_ai_texts SET content_loc2='Vient l\'Écorcheur d\'âmes !' WHERE entry=-822; /* content: The Soulflayer comes! */
UPDATE creature_ai_texts SET content_loc2='Rejoignez-nous !' WHERE entry=-823; /* content: Join us! */
UPDATE creature_ai_texts SET content_loc2='Hakkar vivra de nouveau !' WHERE entry=-824; /* content: Hakkar shall live again! */
UPDATE creature_ai_texts SET content_loc2='Ce mal ne peut s\'étendre au monde entier ! Venez, mes enfants !' WHERE entry=-825; /* content: This evil cannot be allowed to enter this world!  Come my children! */
UPDATE creature_ai_texts SET content_loc2='Vous n\'êtes qu\'un moucheron pour les Vile-sylve ! À mort !' WHERE entry=-826; /* content: You are a little gnat to the Foulweald!  Die! */
UPDATE creature_ai_texts SET content_loc2='Non ! Vous ne pouvez surpasser les Vile-sylve ! Non !' WHERE entry=-827; /* content: No!  You cannot be stronger than the Foulweald!  No!! */
UPDATE creature_ai_texts SET content_loc2='%s charge !' WHERE entry=-829; /* content: %s charges! */
UPDATE creature_ai_texts SET content_loc2='D’autres agents du Syndicat, je parie ! Vous ne reprendrez jamais Alterac... ni Austrivage !' WHERE entry=-924; /* content: More agents of the Syndicate I\'ll wager! You\'ll never take back Alterac... Or Southshore! */
UPDATE creature_ai_texts SET content_loc2='Ce verger est maintenant aussi nu et désolé que ma carcasse est pourrie. Ces arbres ont naguère donné des fruits, mais maintenant il ne reste que de la pourriture.' WHERE entry=-925; /* content: This orchard is now as barren and lifeless as my rotting shell. Once these trees bloomed with fruit but now there is only rot. */
UPDATE creature_ai_texts SET content_loc2='J’ai passé ma vie entière à soigner ces arbres. je les ai taillés et je leur ai mis de l’engrais... Ce n’est que justice qu’ils m’aient rejoint dans la mort.' WHERE entry=-926; /* content: I spent my whole life caring for these trees. Pruning and nurturing them... only fitting that they have joined me in death. */
UPDATE creature_ai_texts SET content_loc2='Des intrus ! Attaquez les intrus !' WHERE entry=-927; /* content: Intruders! Attack the intruders! */
UPDATE creature_ai_texts SET content_loc2='Austrivage va payer de son sang !' WHERE entry=-928; /* content: Southshore shall pay in blood! */
UPDATE creature_ai_texts SET content_loc2='Je suis ressuscité !' WHERE entry=-929; /* content: I have risen! */
UPDATE creature_ai_texts SET content_loc2='Enfin, je tiens ma vengeance !' WHERE entry=-930; /* content: Revenge shall be mine at last! */
UPDATE creature_ai_texts SET content_loc2='Les morts-vivants se repaîtront de ton âme, $n.' WHERE entry=-931; /* content: The undead shall feast on your soul, $N. */
UPDATE creature_ai_texts SET content_loc2='Au secours ! À l’aide ! Des assassins ont été repérés dans les collines ! Aux armes ! Aux armes !' WHERE entry=-932; /* content: Help me! Help! Assassins in the hills! To arms! To arms! */
UPDATE creature_ai_texts SET content_loc2='Gardes ! À vos postes ! Ils doivent encore poursuivre le Magistrat. Il faut le protéger ! Ils peuvent venir de n\'importe où !' WHERE entry=-933; /* content: Guards to your posts! They must be after the Magistrate again. He must be protected! They could come from any direction! */
UPDATE creature_ai_texts SET content_loc2='Assassins... sauvez... le... Magistraaa...' WHERE entry=-935; /* content: Assassins... save... th... Magistraaa... */
UPDATE creature_ai_texts SET content_loc2='Voleurs ! Malandrins ! Malfaisants ! Venez affronter mes oreillers géants !' WHERE entry=-974; /* content: Thieves! Scallywags! Rapscallions! Come face me gigantic pillas! */
UPDATE creature_ai_texts SET content_loc2='Il y a quelqu’un ? Tirion, mon vieil ami, est-ce que c’est vous ? Êtes-vous venu pour nous sauver ?' WHERE entry=-982; /* content: Is someone there? Tirion my old friend, is that you? Have you come to save us? */
UPDATE creature_ai_texts SET content_loc2='Vous osez ! Maintenant, encourez ma colère !' WHERE entry=-983; /* content: You dare! Now feel my wrath! */
UPDATE creature_ai_texts SET content_loc2='Qui ose... Je vais vous détruire !' WHERE entry=-984; /* content: Who dares?! I will destroy you! */
UPDATE creature_ai_texts SET content_loc2='Maman !' WHERE entry=-990; /* content: Mommy! */
UPDATE creature_ai_texts SET content_loc2='Les grenouilles croustillantes sont en vente exclusivement dans notre foire ! Pour un temps limité seulement !' WHERE entry=-1027; /* content: For a limited time only, Crunchy Frog available exclusively here at the Darkmoon Faire. */
UPDATE creature_ai_texts SET content_loc2='La Croisade écarlate anéantira les méchants et chassera le mal de ces terres !' WHERE entry=-1028; /* content: The Scarlet Crusade shall smite the wicked and drive evil from these lands! */
UPDATE creature_ai_texts SET content_loc2='Vous portez la souillure du Fléau. Préparez-vous à entrer dans le Néant distordu.' WHERE entry=-1029; /* content: You carry the taint of the scourge.  Prepare to enter the twisting nether. */
UPDATE creature_ai_texts SET content_loc2='Ces atroces morts-vivants seront détruits !' WHERE entry=-1031; /* content: These undead atrocities will be destroyed! */
UPDATE creature_ai_texts SET content_loc2='Ces terres seront purifiées !' WHERE entry=-1032; /* content: These lands shall be cleansed! */
UPDATE creature_ai_texts SET content_loc2='Ce désert m\'appartient !' WHERE entry=-1035; /* content: This desert be mine! */
UPDATE creature_ai_texts SET content_loc2='Les Furie-des-sables sont les maîtres !' WHERE entry=-1036; /* content: The Sandfury reign supreme! */
UPDATE creature_ai_texts SET content_loc2='Par la fureur du désert !' WHERE entry=-1037; /* content: Feel the fury of the sands! */
UPDATE creature_ai_texts SET content_loc2='Meurs, étranger !' WHERE entry=-1038; /* content: Die, outlander! */
UPDATE creature_ai_texts SET content_loc2='Que l\'exécution commence !' WHERE entry=-1039; /* content: Let the executions begin! */
UPDATE creature_ai_texts SET content_loc2='Justice est faite !' WHERE entry=-1040; /* content: Justice is done! */
UPDATE creature_ai_texts SET content_loc2='Dites au Gardien que la prison est à nous maintenant !' WHERE entry=-1041; /* content: Tell the Warden this prison is ours now! */
UPDATE creature_ai_texts SET content_loc2='J\'écraserai ton crâne sous ma botte !' WHERE entry=-1042; /* content: I\'ll crush your skull beneath my boot! */
UPDATE creature_ai_texts SET content_loc2='Mort aux hommes de la Gardienne !' WHERE entry=-1043; /* content: Death to the Warden\'s men! */
UPDATE creature_ai_texts SET content_loc2='De la viande fraîche !' WHERE entry=-1044; /* content: Fresh meat! */
UPDATE creature_ai_texts SET content_loc2='Il faut plus de coursiers du Gardien !' WHERE entry=-1045; /* content: More of the Warden\'s errand boys! */
UPDATE creature_ai_texts SET content_loc2='Comment osez-vous entrer dans mon sanctuaire !' WHERE entry=-1047; /* content: How dare you enter my sanctum! */
UPDATE creature_ai_texts SET content_loc2='%s s\'écroule, mais le cadavre brisé se relève de nouveau !' WHERE entry=-1054; /* content: %s collapses but the broken body rises again! */
UPDATE creature_ai_texts SET content_loc2='On ne joue pas avec le courrier !' WHERE entry=-1055; /* content: No tampering with the mail! */
UPDATE creature_ai_texts SET content_loc2='C\'est notre trésor, espèce de minable !' WHERE entry=-1056; /* content: That\'s our treasure, you lubber! */
UPDATE creature_ai_texts SET content_loc2='Hé ! Éloignez-vous de notre trésor !' WHERE entry=-1057; /* content: Hey!  Get away from our treasure! */
UPDATE creature_ai_texts SET content_loc2='Tuez $n !' WHERE entry=-1119; /* content: Kill $N! */
UPDATE creature_ai_texts SET content_loc2='Pour Kalimdor !' WHERE entry=-1133; /* content: For Kalimdor! */
UPDATE creature_ai_texts SET content_loc2='Nul ne peut s\'opposer aux seigneurs-serpents !' WHERE entry=-1135; /* content: None can stand against the serpent lords! */
UPDATE creature_ai_texts SET content_loc2='Venez, $n. Voyons ce qu’apporte le Cauchemar…' WHERE entry=-1139; /* content: Come, $n. See what the Nightmare brings... */
UPDATE creature_ai_texts SET content_loc2='Le Cauchemar ne peut pas être arrêté !' WHERE entry=-1140; /* content: The Nightmare cannot be stopped! */
UPDATE creature_ai_texts SET content_loc2='%s arrache les dernières bribes de vie à $n et dévore son âme.' WHERE entry=-1141; /* content: %s squeezes the last bit of life out of $n and swallows their soul. */
UPDATE creature_ai_texts SET content_loc2='Vous l’avez cherché.' WHERE entry=-1148; /* content: You asked for it. */
UPDATE creature_ai_texts SET content_loc2='Goûte à ma lame, bâtard !' WHERE entry=-1156; /* content: Taste blade, mongrel! */
UPDATE creature_ai_texts SET content_loc2='Pitié, dites-moi que vous n\'avez pas fait ce que je crois que vous avez fait. Dites-moi que je ne vais pas devoir vous faire de mal...' WHERE entry=-1157; /* content: Please tell me that you didn\'t just do what I think you just did. Please tell me that I\'m not going to have to hurt you... */
UPDATE creature_ai_texts SET content_loc2='Comme si nous n\'avons pas assez de problèmes, vous allez en créer encore plus !' WHERE entry=-1158; /* content: As if we don\'t have enough problems, you go and create more! */
UPDATE creature_ai_texts SET content_loc2='C\'est ce que tu peux faire de mieux ?' WHERE entry=-1159; /* content: Is that the best you can do? */
UPDATE creature_ai_texts SET content_loc2='L\'empereur Thaurissan ne veut pas être dérangé ! Faites demi-tour ou affrontez votre fin, puérils mortels !' WHERE entry=-1194; /* content: Emperor Thaurissan does not wish to be disturbed! Turn back now or face your doom, weak mortals! */
UPDATE creature_ai_texts SET content_loc2='Préparez-vous au Malownage !' WHERE entry=-1195; /* content: Prepare to be Malowned! */
UPDATE creature_ai_texts SET content_loc2='TIMMY !' WHERE entry=-1197; /* content: TIMMY! */
UPDATE creature_ai_texts SET content_loc2='Dites-moi... Dites-moi tout !' WHERE entry=-1198; /* content: Tell me... tell me everything! */
UPDATE creature_ai_texts SET content_loc2='Vilains secrets...' WHERE entry=-1199; /* content: Naughty secrets! */
UPDATE creature_ai_texts SET content_loc2='J\'arracherai les secrets de votre chair !' WHERE entry=-1200; /* content: I\'ll rip the secrets from your flesh! */
UPDATE creature_ai_texts SET content_loc2='Purifié par la douleur !' WHERE entry=-1201; /* content: Purged by pain! */
UPDATE creature_ai_texts SET content_loc2='Nous avons soif de vengeance.' WHERE entry=-1202; /* content: We hunger for vengeance. */
UPDATE creature_ai_texts SET content_loc2='Lâchez les chiens !' WHERE entry=-1205; /* content: Release the hounds! */
UPDATE creature_ai_texts SET content_loc2='TU AS ÉTÉ TELLEMENT BON JOUEUR LA DERNIÈRE FOIS… SORS DONC !' WHERE entry=-1212; /* content: YOU WERE SUCH GOOD SPORT THE LAST TIME...COME OUT! */
UPDATE creature_ai_texts SET content_loc2='À moi, serviteurs !' WHERE entry=-1222; /* content: To me, my servants! */
UPDATE creature_ai_texts SET content_loc2='Je suis la main du roi-liche !' WHERE entry=-1224; /* content: I am the hand of the Lich King! */
UPDATE creature_ai_texts SET content_loc2='Oh maintenant je suis furieux ! Le moment est venu de voir la véritable force de la Pierre des Marées !' WHERE entry=-1226; /* content: Oh now you\'ve gone and angered me! Time to see the true force of the Stone of Tides! */
UPDATE creature_ai_texts SET content_loc2='En vérité, le pouvoir de la Lumière est grand et miséricordieux.' WHERE entry=-1296; /* content: The power of the light is truly great and merciful. */
UPDATE creature_ai_texts SET content_loc2='Nous serons à nouveau réunis, mon amour…' WHERE entry=-1297; /* content: We shall be reunited once more, my love... */
UPDATE creature_ai_texts SET content_loc2='$gÉtranger:Étrangère;, trouvez le prince déchu Menethil et mettez un terme à son règne de terreur.' WHERE entry=-1299; /* content: Stranger, find the fallen Prince Menethil and end his reign of terror. */
UPDATE creature_ai_texts SET content_loc2='Si je survis, l\'unique ambition du reste de ma vie sera de détruire Arthas…' WHERE entry=-1300; /* content: Should I live through this, I shall make it my life\'s sole ambition to destroy Arthas... */
UPDATE creature_ai_texts SET content_loc2='Je n’y arriverai pas… partez… continuez sans moi…' WHERE entry=-1301; /* content: I won\'t make it... go... go on without me... */
UPDATE creature_ai_texts SET content_loc2='Que la Mort me prenne ! Je ne peux pas continuer ! Il ne me reste rien…' WHERE entry=-1302; /* content: Death take me! I cannot go on! I have nothing left... */
UPDATE creature_ai_texts SET content_loc2='La Lumière condamne quiconque abrite le mal. Maintenant, vous allez mourir !' WHERE entry=-1305; /* content: The light condemns all who harbor evil.  Now you will die! */
UPDATE creature_ai_texts SET content_loc2='Vous portez la souillure du Fléau. Préparez-vous à entrer dans le Néant distordu.' WHERE entry=-1306; /* content: You carry the taint of the scourge.  Prepare to enter the twisting nether. */
UPDATE creature_ai_texts SET content_loc2='Vous ne pouvez vous échapper. La Croisade détruira quiconque porte la souillure du Fléau.' WHERE entry=-1307; /* content: There is no escape for you.  The Crusade shall destroy all who carry the scourge\'s taint. */
UPDATE creature_ai_texts SET content_loc2='La Croisade écarlate anéantira les méchants et chassera le mal de ces terres !' WHERE entry=-1308; /* content: The Scarlet Crusade shall smite the wicked and drive evil from these lands! */
UPDATE creature_ai_texts SET content_loc2='Bienvenue au pays du goût !' WHERE entry=-1310; /* content: Welcome to flavor country! */
UPDATE creature_ai_texts SET content_loc2='Je n\'arrive pas à croire que papa m\'interdise de garder ta sœur.' WHERE entry=-1312; /* content: I can\'t believe dad won\'t let me keep your sister. */
UPDATE creature_ai_texts SET content_loc2='Il n\'y a personne pour offrir un foyer à mon adorable petit chaton ?' WHERE entry=-1313; /* content: Can anyone give my adorable, extra little kitty a home? */
UPDATE creature_ai_texts SET content_loc2='Allergique ? Ça veut dire quoi ? Et quel rapport avec mes minous ?' WHERE entry=-1314; /* content: What does allergic mean anyway? And what does it have to do with either of my kitties? */
UPDATE creature_ai_texts SET content_loc2='Est-ce que quelqu\'un pourrait donner un bon foyer à mon chaton ?' WHERE entry=-1315; /* content: Will someone please give my little kitten a good home? */
UPDATE creature_ai_texts SET content_loc2='Pas d\'inquiétude, nous allons te trouver un bon foyer.' WHERE entry=-1316; /* content: Don\'t worry, I\'ll find a good home for ya. */
UPDATE creature_ai_texts SET content_loc2='%s se scinde en deux nouveaux rejetons de lave !' WHERE entry=-1320; /* content: %s splits into two new Lava Spawns! */
UPDATE creature_ai_texts SET content_loc2='Si vous êtes ici, cela signifie que vous êtes $gprêt:prête; à entamer une étude sur l’invocation des cohortes démoniaques en vue de réaliser votre union. Nous commencerons par les créatures les plus humbles que vous serez en mesure d’invoquer puis nous continuerons. Commençons.' WHERE entry=-1411; /* content: If you\'re here, then it means you are prepared to begin the study of summoning demonic cohorts to do your bidding. We will start with the lowliest creatures you will be able to call and continue from there. Let us begin. */
UPDATE creature_ai_texts SET content_loc2='La créature que vous pourrez invoquer sans aucune difficulté est le diablotin. Vous devriez déjà être en mesure de créer ce serviteur, mais afin de vous délivrer un enseignement complet je vais commencer par lui.' WHERE entry=-1412; /* content: The easiest creature for you to summon is the imp. You should already be able to bring forth this minion but for completeness\' sake I will start with him. */
UPDATE creature_ai_texts SET content_loc2='Cette ignoble petite créature est le diablotin. Il est petit et faible, et donc quasiment inutile en tant que bouclier de chair, et sa capacité à infliger des dégâts est au mieux médiocre. Il vaut mieux utiliser cette créature pour soutenir un groupe assez grand.' WHERE entry=-1413; /* content: This foul little beast is the imp. It is small and weak, making it almost useless as a meatshield, and its damage output is mediocre at best. This creature is best used for support of a larger group. */
UPDATE creature_ai_texts SET content_loc2='Cette entité démoniaque est connue sous le nom de "marcheur du Vide". Sa force et son endurance, qui ne sont pas à négliger, sont parfaitement adaptées à la défense. Envoyez-la attaquer vos ennemis, puis utilisez-la comme un bouclier pendant que vous employez vos sorts et vos techniques pour drainer la vie hors du corps de votre adversaire.' WHERE entry=-1415; /* content: This demonic entity is known as the Voidwalker. Its strength and endurance are significant, making it ideal for defense. Send it to attack your enemy, then use it as a shield while you use your spells and abilities to drain away your opponent\'s life. */
UPDATE creature_ai_texts SET content_loc2='Si vous n’en avez jamais vu, c’est un spectacle à voir. Une créature très impressionnante, à la fois sur le champ de bataille et en dehors. À présent, jetons un œil à celle que tous les étudiants mâles attendent. La succube.' WHERE entry=-1416; /* content: If you\'ve never seen one, it is a sight to behold. A very impressive creature both on and off the field of battle. Next, let us take a look at what I am sure all you male students have been waiting for. The succubus. */
UPDATE creature_ai_texts SET content_loc2='Voyons. Mis à part les diversions évidentes qu\'une telle servante occasionnera envers vos ennemis mâles, elle est également capable de causer des dommages d’une ampleur impressionnante. Cependant, sa faible résistance la rend quasiment inutile en tant que bouclier.' WHERE entry=-1417; /* content: All right now. Aside from the obvious distractions a minion like this will provide against your more masculine foes, she is also capable of dealing out impressive amounts of damage. However, her fragile endurance makes her almost useless as a shield. */
UPDATE creature_ai_texts SET content_loc2='Étudiez assidûment, et un jour vous pourriez être capable d’en invoquer une par vous-même. Mais pour le moment, passons au chasseur corrompu.' WHERE entry=-1418; /* content: Study hard and you might one day be able to summon one on your own, but for now it\'s time to move on to the felhunter. */
UPDATE creature_ai_texts SET content_loc2='Ce que vous voyez devant vous est un chasseur corrompu. Les talents naturels de cette créature lui permettent de neutraliser des sorts. Ce talent, ainsi que d’autres capacités, la rendent sans égale face à un adversaires doté de pouvoirs magiques.' WHERE entry=-1419; /* content: What you see before you is a felhunter. This creature\'s natural talents include spell lock and other abilities which make it unequalled when facing a magically attuned opponent. */
UPDATE creature_ai_texts SET content_loc2='Lorsque vous êtes face à un lanceur de sorts quelconque, cette bête sauvage est votre meilleur ami. Maintenant, intéressons-nous à quelque chose d\'un peu différent. La créature suivante vous aidera à voyager et facilitera grandement vos futurs déplacements. Jetons un coup d\'œil sur un palefroi corrompu.' WHERE entry=-1420; /* content: When facing a spellcaster of any kind, this feral beast will be your best friend. Now, let us take a look at something a bit different. This next creature will aid your travels and make your future journeys much easier. Let\'s take a look at a felsteed. */
UPDATE creature_ai_texts SET content_loc2='Voilà. Votre leçon sur l’invocation est terminée. Un nouveau cours est sur le point de commencer, alors si vous souhaitez réviser, n\'hésitez pas à rester.' WHERE entry=-1422; /* content: There you have it. Our lesson on summoning has come to an end. A new class will begin shortly, so if you wish to brush up, feel free to stay around. */

SET NAMES 'latin1';
