-- File generated by Mangos Online Translation Editor (MOTE) v0.10
SET NAMES 'utf8';
UPDATE gossip_texts SET content_loc2='Ezekiel m\'a dit que vous pourriez être en possession d\'un certain livre…' WHERE entry=-3000105; /* content: Ezekiel said that you might have a certain book... */
UPDATE gossip_texts SET content_loc2='Faites savoir au maréchal Windsor que je suis prête.' WHERE entry=-3000106; /* content: Let Marshal Windsor know that I am ready. */
UPDATE gossip_texts SET content_loc2='Mes forces sont prêtes, tout comme moi. Mettons fin à cette plaisanterie !' WHERE entry=-3000107; /* content: I am ready, as are my forces. Let us end this masquerade! */
UPDATE gossip_texts SET content_loc2='Pourriez-vous me consacrer un moment, monsieur ?' WHERE entry=-3000108; /* content: I need a moment of your time, sir. */
UPDATE gossip_texts SET content_loc2='Je suis prête, Oronok. Détruisons Cyrukh et libérons les éléments !' WHERE entry=-3000109; /* content: I am ready, Oronok. Let us destroy Cyrukh and free the elements! */
UPDATE gossip_texts SET content_loc2='Tournez la clé afin de démarrer la machine.' WHERE entry=-3000111; /* content: Turn the key to start the machine. */
UPDATE gossip_texts SET content_loc2='Veuillez déverrouiller la porte de la cour.' WHERE entry=-3033000; /* content: Please unlock the courtyard door. */
UPDATE gossip_texts SET content_loc2='Que la cérémonie commence !' WHERE entry=-3043000; /* content: Let the event begin! */
UPDATE gossip_texts SET content_loc2='Je peux commencer.' WHERE entry=-3090000; /* content: I am ready to begin. */
UPDATE gossip_texts SET content_loc2='Vous êtes libre, Dughal ! Sortez d\'ici !' WHERE entry=-3230000; /* content: You\'re free, Dughal! Get out of here! */
UPDATE gossip_texts SET content_loc2='Hors d\'ici, Tobias, vous êtes libre !' WHERE entry=-3230001; /* content: Get out of here, Tobias, you\'re free! */
UPDATE gossip_texts SET content_loc2='Pourquoi Rochenœud et vous n\'allez pas dans un endroit privé...' WHERE entry=-3230003; /* content: Why don\'t you and Rocknot go find somewhere private... */
UPDATE gossip_texts SET content_loc2='Dites-m\'en plus.' WHERE entry=-3409000; /* content: Tell me more. */
UPDATE gossip_texts SET content_loc2='Qu\'avez-vous d\'autre à dire ?' WHERE entry=-3409001; /* content: What else do you have to say? */
UPDATE gossip_texts SET content_loc2='Je n\'ai commis aucune faute.' WHERE entry=-3469000; /* content: I\'ve made no mistakes. */
UPDATE gossip_texts SET content_loc2='Vous avez perdu la tête, Nefarius. Vous parlez en énigmes.' WHERE entry=-3469001; /* content: You have lost your mind, Nefarius. You speak in riddles. */
UPDATE gossip_texts SET content_loc2='Faites.' WHERE entry=-3469002; /* content: Please do. */
UPDATE gossip_texts SET content_loc2='Je ne peux pas, Vaelastrasz ! Il doit sûrement y avoir un moyen de vous guérir !' WHERE entry=-3469003; /* content: I cannot, Vaelastrasz! Surely something can be done to heal you! */
UPDATE gossip_texts SET content_loc2='Vaelastrasz, non !!!' WHERE entry=-3469004; /* content: Vaelastrasz, no!!! */
UPDATE gossip_texts SET content_loc2='Allons voir.' WHERE entry=-3509000; /* content: Let\'s find out. */
UPDATE gossip_texts SET content_loc2='Voyons voir ce que vous avez là.' WHERE entry=-3509001; /* content: Let\'s see what you have. */

SET NAMES 'latin1';
