-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE locales_item SET description_loc5='Engraved with the words \'For years of service: -EVC.\'' WHERE entry=2239; /* name: The Collector\'s Ring */ /* description: Engraved with the words \'For years of service: -EVC.\' */
UPDATE locales_item SET name_loc5='Tiny Bronze Key',description_loc5='A reagent for mage spells.' WHERE entry=5517; /* name: Tiny Bronze Key */ /* description: A reagent for mage spells. */
UPDATE locales_item SET name_loc5='Tiny Iron Key',description_loc5='A reagent for mage spells.' WHERE entry=5518; /* name: Tiny Iron Key */ /* description: A reagent for mage spells. */
UPDATE locales_item SET name_loc5='Codex of Flash Heal',description_loc5='Teaches Inner Fire (Rank 2).' WHERE entry=8964; /* name: Codex of Flash Heal */ /* description: Teaches Inner Fire (Rank 2). */
UPDATE locales_item SET name_loc5='Ward of the Defiler',description_loc5='The completed amulet of Rakh\'likh.' WHERE entry=10757; /* name: Ward of the Defiler */ /* description: The completed amulet of Rakh\'likh. */
UPDATE locales_item SET name_loc5='Shadowforge Key',description_loc5='Master Key to the Depths, Courtesy of F.F.F.' WHERE entry=11000; /* name: Shadowforge Key */ /* description: Master Key to the Depths, Courtesy of F.F.F. */
UPDATE locales_item SET description_loc5='Gor\'tesh\'s severed head, propped up on a pike.' WHERE entry=11079; /* name: Gor\'tesh\'s Lopped Off Head */ /* description: Gor\'tesh\'s severed head, propped up on a pike. */
UPDATE locales_item SET name_loc5='Alex\'s Ring of Audacity',description_loc5='Looks great. Less filling.' WHERE entry=12947; /* name: Alex\'s Ring of Audacity */ /* description: Looks great. Less filling. */
UPDATE locales_item SET description_loc5='Teaches you how to make Thorium Shells.' WHERE entry=16051; /* name: Schematic: Thorium Shells */ /* description: Teaches you how to make Thorium Shells. */
UPDATE locales_item SET name_loc5='Key to Salem\'s Chest',description_loc5='Opens Dark Cleric Salem\'s Chest' WHERE entry=17242; /* name: Key to Salem\'s Chest */ /* description: Opens Dark Cleric Salem\'s Chest */
UPDATE locales_item SET name_loc5='James\' Key',description_loc5='Opens the stolen chest from the Cathedral of Light' WHERE entry=17262; /* name: James\' Key */ /* description: Opens the stolen chest from the Cathedral of Light */
UPDATE locales_item SET description_loc5='Only ONE May Rise... (and consequently, only ONE may loot this head)' WHERE entry=20383; /* name: Head of the Broodlord Lashlayer */ /* description: Only ONE May Rise... (and consequently, only ONE may loot this head) */
UPDATE locales_item SET description_loc5='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=22345; /* name: Totem of Rebirth */ /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc5='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=22395; /* name: Totem of Rage */ /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc5='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=22396; /* name: Totem of Life */ /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET name_loc5='Andonisus, Reaper of Souls',description_loc5='This blade is dimensional. It appears to be fading from this plane of existence.' WHERE entry=22736; /* name: Andonisus, Reaper of Souls */ /* description: This blade is dimensional. It appears to be fading from this plane of existence. */
UPDATE locales_item SET description_loc5='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=23005; /* name: Totem of Flowing Water */ /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc5='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=23199; /* name: Totem of the Storm */ /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc5='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=23200; /* name: Totem of Sustaining */ /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET name_loc5='Diet McWeaksauce',description_loc5='Food for the Mind' WHERE entry=23578; /* name: Diet McWeaksauce */ /* description: Food for the Mind */
UPDATE locales_item SET name_loc5='The McWeaksauce Classic',description_loc5='The Original.' WHERE entry=23579; /* name: The McWeaksauce Classic */ /* description: The Original. */

SET NAMES 'latin1';
